### ISSUE TITLE
Entrez parser fails on Jython - XMLParser lacks SetParamEntityParsing

### ISSUE THREAD

**Issue by peterjc** [biopython/biopython#1041]
Originally filed as http://bugzilla.open-bio.org/show_bug.cgi?id=2918 later https://redmine.open-bio.org/issues/2918

> I'm filing this as a bug report so we can track it, but the underlying issue is a known Jython bug, http://bugs.jython.org/issue1447 (thanks Kyle for reporting this already).
>
> It can be shown just by running our unit test:
>
> ```
> ======================================================================
> ERROR: Test parsing XML returned by EFetch, Journals database
> ----------------------------------------------------------------------
> Traceback (most recent call last):
> File "/Users/pjcock/repositories/biopython/Tests/test_Entrez.py", line 3443, in test_journals
> record = Entrez.read(input)
> File "/Users/pjcock/repositories/biopython/Bio/Entrez/__init__.py", line 259, in read
> record = handler.run(handle)
> File "/Users/pjcock/repositories/biopython/Bio/Entrez/Parser.py", line 85, in run
> self.parser.SetParamEntityParsing(expat.XML_PARAM_ENTITY_PARSING_ALWAYS)
> AttributeError: 'XMLParser' object has no attribute 'SetParamEntityParsing'
> ~/jython2.5.0/jython run_tests.py test_Entrez.py
> test_Entrez ... FAIL
> ...
> ```

**Comment by peterjc** [comment]
We dropped support for Jython (and Python 2 in general).
