### ISSUE TITLE
Bio.Nexus.StandardData Python 3 non-iterator of type

### ISSUE THREAD

**Issue by peterjc** [biopython/biopython#1058]
While working on moving the Nexus self-tests into ``test_Nexus.py`` (see #820), I found that ``Bio/Nexus/StandardData.py`` is broken under Python 3. This was new in pull request #562, contributed by @JoeCora:

```
>>> from Bio.Nexus.Nexus import Nexus
>>> nexus = Nexus()
>>> data = nexus.read('vSysLab_Ganaspidium_multistate.nex')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/peterjc/lib/python3.4/site-packages/Bio/Nexus/Nexus.py", line 655, in read
    self._parse_nexus_block(title, contents)
  File "/Users/peterjc/lib/python3.4/site-packages/Bio/Nexus/Nexus.py", line 696, in _parse_nexus_block
    getattr(self, '_' + line.command)(line.options)
  File "/Users/peterjc/lib/python3.4/site-packages/Bio/Nexus/Nexus.py", line 997, in _matrix
    for i, c in enumerate(iupac_seq):
TypeError: iter() returned non-iterator of type 'StandardData'
```

Unless using a very recent checkout, you'd first get a ``basestring`` error, which by chance I recently fixed having found that by running ``flake8`` under Python 3 - see 5c974988100148842c80d9f81576cf308b845494

**Comment by peterjc** [comment]
We just need to define ``__next__``, see also bf6445d9de00c739825eb6cf1b649b919c02c19d

**Comment by peterjc** [comment]
I think I've fixed this, I filed the bug primarily as I wasn't sure I'd have time to finish debugging this right now...

**Comment by peterjc** [comment]
Fixed in https://github.com/biopython/biopython/commit/02e208abba77620cbde05de2ba46a80906620204
