### ISSUE TITLE
PyPy NEXUS Character states exceed number of available symbols in line 

### ISSUE THREAD

**Issue by peterjc** [biopython/biopython#1059]
Having recently moved some NEXUS self-tests into the main test suite, db8a3f7da6a0f6fa660932e591730b88fbf8f39a, this has revealed a problem under PyPy 2.5.0 run on TravisCI (i.e. the PyPy implementation of Python 2),

https://travis-ci.org/biopython/biopython/jobs/200919990
and
https://travis-ci.org/biopython/biopython/jobs/200922141

```
======================================================================
ERROR: test_taxa_and_characters_block (test_Nexus.OldSelfTests)
Taxa and characters multi-state block
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/biopython/biopython/Tests/test_Nexus.py", line 47, in test_taxa_and_characters_block
    nexus4.read('Nexus/vSysLab_Ganaspidium_multistate.nex')
  File "/home/travis/build/biopython/biopython/Bio/Nexus/Nexus.py", line 655, in read
    self._parse_nexus_block(title, contents)
  File "/home/travis/build/biopython/biopython/Bio/Nexus/Nexus.py", line 696, in _parse_nexus_block
    getattr(self, '_' + line.command)(line.options)
  File "/home/travis/build/biopython/biopython/Bio/Nexus/Nexus.py", line 906, in _charstatelabels
    'Character states exceed number of available symbols in line %s.' % options)
NexusError: Character states exceed number of available symbols in line 1 'Malar sulcus'/'simple' 'compound', 2 'Malar space'/'smooth' 'partially striate, striations extending 1/2 to 2/3 distance from ventral margin of malar space to base of compound eye' 'completely striate from ventral margin of malar space to base of compound eye' 'partially striate, striations extending to 1/4 distance from ventral margin of malar space to base of compound eye', 3 'Malar protuberance'/'smooth, elongate, extending beyond length of ventral margin of malar space' 'striate, elongate, extending beyond length of ventral margin of malar space' 'smooth, short, not extending beyond length of ventral margin of malar space' 'striate, short, not extending beyond length of ventral margin of malar space', 4 'Clypeal protuberance'/'elongate, overhanging anterior margin of clypeus' 'short, not overhanging anterior margin of clypeus', 5 'Tubercles of scutellar plate'/'present, extremely reduced, hardly distinguishable' 'present, distinct, small, length of tuber less than 1/2 width of tubercle base' 'present, distinct, large, length of tubercle equal to or greater than width of tubercle base' 'absent', 6 'Dorsal surface of scutellar plate'/'flat, smooth, setal bearing pits present surrounding midpit' 'flat, horizontally striate, setal bearing pits present surrounding midpit' 'gently convex, smooth, setal bearing pits surrounding midpit' 'concave, smooth, setal bearing pits surrounding midpit' 'concave around midpit, two setal bearing pits at base of each tubercle' 'concave, radially striate, setal bearing pits surrounding midpit', 7 'Carina along posterior margin of scutellum'/'absent' 'present, delicate, defining transition from dorsal surface of scutellum from posterior surface' 'present, distinctly cleft, defining transition from dorsal surface of scutellum from posterior surface', 8 'Dorsal surface of scutellum'/'entirely smooth' 'smooth except for faint wrinkles along posterior carina' 'smooth anteriorly, reticular/strigate posteriorly' 'smooth anteriorly, longitudinally striate posteriorly' 'entirely rugulose/wrinkled' 'smooth anteriorly, gently striate posteriorly', 9 'Midpit of scutellar plate'/'in center of plate; plate large, obscuring dorsal surface of scutellum when viewed dorsally' 'in center of plate; plate small, revealing dorsal surface of scutellum when viewed dorsally' 'in posterior half of plate; plate small, revealing dorsal surface of scutellum when viewed dorsally', 10 'Mesopopleura setal patch'/'present' 'absent', 11 'Mesopleuron'/'entirely smooth' 'smooth anteriorly, striate along the postero-dorsal margin' 'distinctly striate along the anterior, posterior margins; often entire sclerite striate' 'striate within confines of mesopleural triangle, remainder of sclerite smooth', 12 'Lateral aspect of pronotum'/'covered in long, thin, white setae' 'anteriorly with some short setae, remainder glabrous', 13 'Marginal cell of forewing'/'as deep as long' 'distinctly deeper than long', 14 'Size of metasoma (in lateral view)'/'sub-equal in size to mesosoma' 'distinctly larger than mesosoma (longer and deeper)'.
======================================================================
ERROR: test_taxa_and_characters_with_many_codings_one_without_state (test_Nexus.OldSelfTests)
Taxa and chr blocks, over 9 codings, 1 character without states
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/biopython/biopython/Tests/test_Nexus.py", line 52, in test_taxa_and_characters_with_many_codings_one_without_state
    nexus5.read('Nexus/vSysLab_Heptascelio_no-states_10+chars.nex')
  File "/home/travis/build/biopython/biopython/Bio/Nexus/Nexus.py", line 655, in read
    self._parse_nexus_block(title, contents)
  File "/home/travis/build/biopython/biopython/Bio/Nexus/Nexus.py", line 696, in _parse_nexus_block
    getattr(self, '_' + line.command)(line.options)
  File "/home/travis/build/biopython/biopython/Bio/Nexus/Nexus.py", line 906, in _charstatelabels
    'Character states exceed number of available symbols in line %s.' % options)
NexusError: Character states exceed number of available symbols in line 1 'body color of female'/'entirely dark, dark brown to black' 'bicolored: head and mesosoma dark brown, metasoma yellow', 2 'body color of male'/'entirely black' 'entirely dark brown' 'head and metasoma black, mesosoma reddish brown' 'head and mesosoma black, metasoma dark brown', 3 'sculpture of occiput and posterior vertex'/'areolate-rugose' 'with strong transverse rugae' 'coarsely punctate' 'irregularly rugulose' 'areolate rugose, with distinct transverse tendency' 'with strong arched rugae', 4 'sculpture of frons below ocellus in female'/'transversely striate' 'areolate rugose' 'coarsely punctate' 'dorsoventrally striate', 5 'shape of dorsal margin of frontal scrobe'/'evenly arcuate, weakly produced' 'distinctly incised medially, strongly produced anteriorly' 'ecarinate, rounded onto dorsal portion of frons', 6 'sculpture of frontal depression in female'/'transversely striate ventrally, with smooth field dorsomedially' 'entirely smooth' 'with short transverse striae on sides, medially entirely smooth' 'irregularly areolate ventrally, smooth dorsally and medially' 'coarsely punctate ventrally and laterally, otherwise smooth' 'transversely rugose throughout' 'diagonally striate laterally, smooth medially' 'coarsely punctate' 'punctate, with broad smooth spaces between punctures', 7 'sculpture of gena'/'with irregular dorsoventral rugae' 'with irregular, nearly longitudinal rugulae' 'coarsely punctate' 'areolate rugose, with distinct dorsoventral tendency', 8 'setation of gena'/'with short, uniform setae, with few short bristles interspersed' 'with numerous strong, erect, dark bristles amid shorter setation' 'with short, uniform setae, without bristles', 9 'shape of mandibles'/'normal length, crossed transversely below head when closed, tips overlapping' 'elongate, extending ventrally below head, tips meeting apically', 10 'sculpture of male mesoscutellum'/'coarsely reticulate' 'coarsely reticulate, with distinct longitudinal elements' 'areolate rugose' 'coarsely longitudinally areolate rugose' 'longitudinally strigose', 11 'color of female antenna'/'A1-A2 pale brown, A3-A6 brown, A7-A12 dark brown' 'A1 brown, A2-A5 light brown, A6-A12 dark brown' 'dark brown to black throughout' 'dark brown to black throughout, extremities of A1, A2 lighter in color' 'brown to dark brown throughout' 'A1 brownish yellow, A2-A5 yellow, A6-A12 dark brown to black' 'A1 dark brown, A2-A5 off-white, A6-A12 dark brown to black' 'A1 dark brown, A2-A4 brownish yellow, A5-A12 dark brown to black' 'A1 brown, A2-A5 yellow, A6-A12 generally brown to dark brown, A12 lighter' 'A1 brown, A2-A5 yellow, A6-A12 dark brown', 12 'color of male antenna'/'light brown throughout' 'brown to dark brown throughout' 'brown' 'A1-A5 brown, A6-A12 pale brown', 13 'sculpture of dorsal pronotum'/'longitudinally aciculate, with smooth interspaces' 'areolate rugose' 'coarsely reticulate' 'coarsely punctate' 'areolate rugose, with distinct longitudinal tendency' 'longitudinally strigose', 14 'notaulus', 15 'sculpture of mesoscutum in female'/'coarsely areolate-rugose' 'finely longitudinally aciculate with smooth interspaces' 'coarsely longitudinally strigose with smooth interspaces' 'longitudinally strigose, with strong transverse sculpture in interspaces' 'sparsely punctate, with broad smooth areas between punctures' 'longitudinally strigose with fine sculpture in interspaces' 'sparsely punctate, with broad smooth areas between punctures, with weak indications of longitudinal rugulae' 'midlobe coarsely punctate, lateral lobes with punctures sparser, separated by smooth areas', 16 'sculpture of mesoscutum in male'/'with dense umbilicate punctures' 'finely longitudinally aciculate' 'coarsely areolate rugose' 'sparsely punctate, largely smooth' 'longitudinally strigose, with strong transverse sculpture in interspaces' 'sparsely punctate, with broad smooth areas between punctures, with weak indications of longitudinal rugulae' 'coarsely areolate rugose with distinct longitudinal tendency' 'coarsely longitudinally areolate rugose', 17 'parapsidal line'/'present, clearly impressed' 'absent' 'present, evanescent', 18 'mesoscutellum shape'/'distinctly narrowed apically, with median longitudinal depression' 'broad, weakly convex, apex broadly rounded' 'nearly parallel-sided, apex weakly excavate, with weak median longitudinal impression' 'semicircular, posteriorly distinctly sloping ventrad, without distinct median longitudinal furrow' 'roughly trapezoidal, sides weakly converging apically, apex excavate, with distinct median longitudinal furrow' 'roughly semicircular, with distinct median longitudinal impression in apical half' 'roughly trapezoidal, sides converging apically, apex weakly excavate, without distinct median longitudinal impression', 19 'sculpture of female mesoscutellum'/'coarsely reticulate, with distinct longitudinal elements' 'areolate rugose' 'longitudinally strigate' 'coarsely punctate', 20 'mesoscutellar points of female'/'absent, scutellum with rounded lobes laterally' 'broad, short, acute' 'narrow, elongate, acute' 'forming short, acute teeth' 'forming short, sharp angles, not protruding' 'flattened, broadly rounded apically' 'moderately elongate, narrow, acute, curving medially', 21 'mesoscutellar points of male'/'apex of scutellum transverse, posterolateral corners very weakly produced' 'apex of scutellum rounded, points entirely absent' 'narrow, short, acute' 'flattened, broadly rounded apically' 'broad, short, acute', 22 'posterior surface of propodeum'/'with distinct straight longitudinal paramedian keel arising from apex of inner propodeal projection' 'with medial area covered by elongate areolae, bounded laterally by irregular carinae' 'with central row of quadrate areolae above large smooth central area, bounded laterally by carinae' 'irregularly areolate, without distinct paramedian keel' 'with medial area with elongate areolae, bounded laterally by distinct paramedial carinae' 'with sinuous paramedian keel arising from apex of inner propodeal projection' 'longitudinally carinate, without distinct paramedian keel' 'longitudinally carinate with well-developed transverse striae, without distinct paramedian keel', 23 'length of outer propodeal projection in female'/'extending beyond apex of T1' 'extending at most to midlength of T1' 'rather short, extending at most to midlength of T1, distinctly longer than inner propodeal projection' 'moderately elongate, not reaching midpoint of length of T1, subequal in length to inner propodeal projection' 'elongate, extending near or beyond apex of T1, distinctly longer than inner propodeal projection' 'moderately elongate, extending to midpoint of length of T1, distinctly longer than inner propodeal projection' 'rather short, extending at most to midlength of T1, slightly longer than inner propodeal projection', 24 'sculpture of propodeum between inner and outer propodeal projections'/'areolate rugose' 'coarsely punctate' 'largely smooth, with variably developed diagonal carinae' 'longitudinally carinate with punctures in interspaces' 'areolate rugose, with distinct longitudinal tendency', 25 'netrion shape'/'moderately wide, parallel-sided in ventral half, open' 'strongly narrowed, nearly linear, foveae on surface nearly as high as wide' 'narrow, gradually widened ventrally, foveae on surface distinctly wider than high' 'moderately wide, nearly parallel-sided, with two columns of large punctures' 'moderately wide, nearly parallel-sided, weakly widened ventrally, with single column of large foveae' 'moderately wide, weakly fusiform, with column of elongate foveae' 'moderately wide, weakly fusiform, anterior margin foveate', 26 'netrion setation'/'glabrous' 'densely setose', 27 'sculpture of lateral pronotum posterior to epomial carina'/'smooth' 'coarsely sculptured' 'with large smooth field dorsally, elsewhere finely rugulose' 'with smooth field dorsally, elsewhere areolate rugose' 'with small smooth field near posterior margin, elsewhere finely rugulose' 'coarsely punctate' 'coarsely rugulose throughout' 'coarsely foveolate immediately behind epomial carina, elsewhere sparsely punctate', 28 'setation of posterior half of lateral pronotum'/'largely glabrous, setae limited to small patch near spiracle' 'with numerous scattered setae, densest near spiracle', 29 'sculpture of mesopleural scrobe'/'smooth' 'coarsely areolate to rugose' 'finely microreticulate to smooth' 'coarsely punctate' 'with narrow smooth field medially, elsewhere diagonally striate' 'smooth medially, elsewhere rugose', 30 'sculpture of lower mesepisternum'/'smooth' 'rugulose to punctate' 'finely microreticulate, nearly smooth, sparsely punctate' 'with distinctly separated, coarse punctures' 'largely smooth, with 2-3 longitudinal lines of punctures', 31 'sculpture of metapleuron'/'areolate rugose' 'irregularly longitudinally rugose, with smooth field medially' 'largely smooth' 'areolate rugose above, with smooth or finely sculptured field ventrally' 'coarsely punctate' 'with smooth field in posteroventral quadrant, elsewhere areolate rugose' 'coarsely areolate to rugose throughout' 'with smooth field medially, elsewhere coarsely punctate', 32 'color of legs'/'coxae and femora dark brown, tibiae and tarsi yellow' 'coxae dark brown, femora largely brown, legs otherwise brownish yellow' 'tarsi light brown, otherwise brown to dark brown throughout' 'coxae dark brown to black, legs otherwise brown to dark brown' 'coxae, femora dark brown, tarsi brown, tibiae pale, contrasting with femora and tibiae' 'coxae and femora dark brown, otherwise brown' 'coxae dark brown, otherwise yellowish brown throughout' 'coxae dark brown to black, femora dark brown, legs otherwise very pale brown, nearly white' 'coxae and femora brown, elsewhere light brown' 'coxae, femora, tibiae dark brown, otherwise brown' 'entirely yellow', 33 'long dark bristles on legs'/'present on all femora, tibiae' 'absent' 'present on hind femur only', 34 'color of wing membrane'/'generally hyaline throughout' 'with faint brown infuscation throughout, with strong dark streak below submarginal vein' 'hyaline basally, infuscate in apical two-thirds, streak below submarginal vein weak' 'with weak general brown infuscation, longitudinal dark streak below submarginal vein moderately developed' 'with weak general brown infuscation, longitudinal streak below submarginal vein weak' 'moderately infuscate throughout, streak below submarginal vein darkly pigmented' 'infuscate in apical two thirds, streak below submarginal vein strongly pigmented', 35 'fore wing venation'/'well-developed, with R, r-rs clearly visible' 'reduced to basal stub of R, with pale pseudostigma in wing disk', 36 'submarginal vein bristles'/'with 1-2 dark bristles near base of fore wing' 'with dark bristles extending length of submarginal vein' 'with dark bristles in basal half of submarginal vein' 'absent', 37 'T1 depression'/'glabrous or sparsely setose' 'moderately to densely setose', 38 'sublateral lamella on T1'/'distinctly raised more or less perpendicular to T1' 'indicated as low carina' 'absent', 39 'sculpture of T2-T4'/'longitudinally striate, with fine cross striae, punctures, smooth or finely punctulate transverse band apically' 'longitudinally striate with cross striae laterally, sculpture effaced medially', 40 'setation of laterotergites'/'glabrous' 'setose' 'very sparsely setose', 41 'sculpture of S2, S3 of female'/'strongly longitudinally rugose' 'nearly smooth, with scattered small punctures' 'irregularly longitudinally rugulose, apex of S3 nearly smooth' 'longitudinally rugulose laterally, nearly smooth medially, with scattered small punctures', 42 'sculpture of S2, S3 of male'/'longitudinal rugulae largely effaced, strongest laterally, otherwise smooth with scattered setigerous punctures' 'strongly longitudinally rugose' 'nearly smooth, with scattered setigerous punctures', 43 'distribution of felt fields'/'present on S2-S3' 'present on S3-S4' 'present on S3 only'.
----------------------------------------------------------------------
```

There is apparently something subtly different about PyPy which breaks the assumptions in ``Bio/Nexus/StandardData.py``

**Comment by peterjc** [comment]
Bad news: Also fails locally using PyPy v5.1.1 on Linux

```
$ pypy --version
Python 2.7.10 (b0a649e90b6642251fb4a765fe5b27a97b1319a9, May 05 2016, 17:21:19)
[PyPy 5.1.1 with GCC 4.9.2]
```

Good news: Seems to work using PyPy v5.6

```
$ pypy --version
Python 2.7.12 (aff251e543859ce4508159dd9f1a82a2f553de00, Nov 12 2016, 08:50:18)
[PyPy 5.6.0 with GCC 6.2.0]
```

That is currently the newest (Python 2 compatible) release of PyPy, specifically I used the portable package as I'm running this on an older version of Linux, https://bitbucket.org/squeaky/portable-pypy/downloads/pypy-5.6-linux_x86_64-portable.tar.bz2

I think that means we don't need to worry about this too much, I just need to tweak the unit test so this doesn't fail the TravisCI builds...
