### ISSUE TITLE
GFF parser fails to parse comment

### ISSUE THREAD

**Issue by agrippaAT** [biopython/biopython#1146]
The GFF (BCBio.GFF.Parser) parser fails to parse the following file:
```
##gff-version 3
#!gff-spec-version 1.20
##sequence-region cloning vector 1 4609
##region          source  type   from  to       score   strand  phase   comment
cv_00001	DB	region	1	4609	.	+	.
cv_00001	DB	gene	2202	3059	.	-	.	ID=gene1;Name=Amp
cv_00001	DB	CDS	1850	2259	.	-	0	ID=cds1;Name=Amp
cv_00001	DB	CDS	2502	4059	.	-	0	ID=cds1;Name=Amp
cv_00001	DB	promoter	578	645	.	+	0	Name=T7
cv_00001	DB	terminator	4209	4326	.	-	0	Name=T3
cv_00001	DB	promoter	752	896	.	-	0	Name=T3
cv_00001	DB	rep_origin	6	462	.	+	0	Name= "f1(-) origin of replication"
cv_00001	DB	rep_origin	1258	1738	.	-	0	Name= "ColE1ori"
cv_00001	DB	promoter	1042	1164	.	-	0	Name="lac promoter"
###
```

The problem seems to be line 3, where the library assumes that "vector" is an integer:

```
Traceback (most recent call last):
  File "<pyshell#19>", line 1, in <module>
    for item in pars.parse("cloningvector 2.gff"):
  File "C:\Users\matthias\AppData\Local\Programs\Python\Python35-32\lib\site-packages\BCBio\GFF\GFFParser.py", line 311, in parse
    for rec in self.parse_in_parts(gff_files, base_dict, limit_info):
  File "C:\Users\matthias\AppData\Local\Programs\Python\Python35-32\lib\site-packages\BCBio\GFF\GFFParser.py", line 327, in parse_in_parts
    cur_dict = self._results_to_features(cur_dict, results)
  File "C:\Users\matthias\AppData\Local\Programs\Python\Python35-32\lib\site-packages\BCBio\GFF\GFFParser.py", line 369, in _results_to_features
    base = self._add_directives(base, results.get('directive', []))
  File "C:\Users\matthias\AppData\Local\Programs\Python\Python35-32\lib\site-packages\BCBio\GFF\GFFParser.py", line 388, in _add_directives
    val = (val[0], int(val[1]) - 1, int(val[2]))
ValueError: invalid literal for int() with base 10: 'vector'
```

I'm not sure the file is valid, but wouldn't it be best to ignore malformed comment lines in case the library can't use them?

**Comment by peterjc** [comment]
I would say you'd best file this at @chapmanb's repository https://github.com/chapmanb/bcbb/issues

However, in this case the file is clearly invalid, there should not be a plain space in the sequence identifier on the ``##sequence-region`` line. See https://github.com/The-Sequence-Ontology/Specifications/blob/master/gff3.md which defines the  ``##sequence-region seqid start end`` line.

Also the sequence identifier in the ``##sequence-region`` pragma does not match column one in the tab-separated section. Try using this instead:

```
##sequence-region cv_00001 1 4609
```
