### ISSUE TITLE
codonalign.build not recognizing ambiguous DNA

### ISSUE THREAD

**Issue by universvm** [biopython/biopython#1160]
I am parsing my sequences with SeqIO and I have ambiguous DNA specified in my alphabet. I successfully translate the sequence and store in a list called "protein". When I build the alignment however:
`aln = MultipleSeqAlignment(protein)`
`codon_aln = codonalign.build(aln, sequence)`

it gives me the error:

> ValueError: Sequence contain undefined letters from alphabet (CCR)! 

would it be possible to just ignore the Ambiguous letters in the alignment? 

OS: MacOS
Biopython: 1.68
Python: 2.7

**Comment by peterjc** [comment]
This is coming from the ``CodonSeq`` class ``__init__`` in ``Bio/codonalign/codonseq.py``.

It is not clear from your report what you are asking the code to do, but I suspect you have calling it with unexpected arguments. Can you provide more of your code, and the full error message (traceback)?

Here is ``CCR`` an ambiguous codon (``CCA`` or ``CCG`` since ``R`` is ``A`` or ``G``)?

In particular how are you specifying the ambiguous DNA alphabet?

CC @zruan

**Comment by universvm** [comment]
Hi, see the attached zip file.

The code is exactly the same as last time, however I specified the alphabet in seq.IO with:

`alphabet=Gapped(IUPAC.ambiguous_dna)`

My sequence contains CCR which is successfully translated into Proline. However the alignment fails. Here is the error:

`Traceback (most recent call last):
  File "X/mainmatrix.py", line 34, in <module>
    codon_aln = codonalign.build(aln, sequence, )
  File "/usr/local/lib/python2.7/site-packages/Bio/codonalign/__init__.py", line 180, in build
    max_score=max_score)
  File "/usr/local/lib/python2.7/site-packages/Bio/codonalign/__init__.py", line 592, in _get_codon_rec
    return SeqRecord(CodonSeq(codon_seq, alphabet=alphabet), id=nucl.id)
  File "/usr/local/lib/python2.7/site-packages/Bio/codonalign/codonseq.py", line 86, in __init__
    "({0})! ".format(self._data[i:i + 3]))
ValueError: Sequence contain undefined letters from alphabet (CCR)! `

You could try yourself with the attachment.
[Archive.zip](https://github.com/biopython/biopython/files/925338/Archive.zip)

**Comment by peterjc** [comment]
OK, the problem is the default alphabet here is only unambiguous codons:

```
$ python3 -c "from Bio.codonalign.codonalphabet import default_codon_alphabet; print(default_codon_alphabet.letters)"
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/Bio/codonalign/__init__.py:28: BiopythonExperimentalWarning: Bio.codonalign is an experimental module which may undergo significant changes prior to its future official release.
  BiopythonExperimentalWarning)
['TTT', 'UUU', 'TTC', 'UUC', 'TTA', 'UUA', 'TTG', 'UUG', 'TCT', 'UCU', 'TCC', 'UCC', 'TCA', 'UCA', 'TCG', 'UCG', 'TAT', 'UAU', 'TAC', 'UAC', 'TGT', 'UGU', 'TGC', 'UGC', 'TGG', 'UGG', 'CTT', 'CUU', 'CTC', 'CUC', 'CTA', 'CUA', 'CTG', 'CUG', 'CCT', 'CCU', 'CCC', 'CCA', 'CCG', 'CAT', 'CAU', 'CAC', 'CAA', 'CAG', 'CGT', 'CGU', 'CGC', 'CGA', 'CGG', 'ATT', 'AUU', 'ATC', 'AUC', 'ATA', 'AUA', 'ATG', 'AUG', 'ACT', 'ACU', 'ACC', 'ACA', 'ACG', 'AAT', 'AAU', 'AAC', 'AAA', 'AAG', 'AGT', 'AGU', 'AGC', 'AGA', 'AGG', 'GTT', 'GUU', 'GTC', 'GUC', 'GTA', 'GUA', 'GTG', 'GUG', 'GCT', 'GCU', 'GCC', 'GCA', 'GCG', 'GAT', 'GAU', 'GAC', 'GAA', 'GAG', 'GGT', 'GGU', 'GGC', 'GGA', 'GGG', 'TAA', 'UAA', 'TAG', 'UAG', 'TGA', 'UGA', 'TTG', 'UUG', 'CTG', 'CUG', 'ATG', 'AUG', '---']
```

I'm not sure how @zruan would expect the user to deal with this - see also #1162.

**Comment by zruan** [comment]
The `default_codon_table` do not contain the information for translating ambiguous codons. You can manually add such piece of information to the  `default_codon_table` by specifying the following code.
```
default_codon_table.forward_table['CCR'] = "P"
codon_aln = codonalign.build(aln, sequence, codon_table=default_codon_table)
```

**Comment by universvm** [comment]
Wouldn't it be easier to just add the alphabet from the ambiguos dna to codonalphabet.py at line 41?

I could try specifying there that the alphabet is ambiguos. However, shouldn't it load the ambiguos by default since the ambiguos alphabet also contains the unambiguos alphabet?

**Comment by zruan** [comment]
The `codonalign.build` function doesn't support ambiguous dna right now. Internally, it maps each amino acid to its codon using a re expression dictionary based on user specified codon table. Since there is no ambiguous alphabet in the available codon table, such a dictionary will not be able to map amino acid to ambigous dna sequences.

**Comment by universvm** [comment]
I was thinking that since Ambiguous Alphabet contains the unambiguous alphabet, it could have been used by default. In the meantime, should I just use the:
`default_codon_table.forward_table['CCR'] = "P"`
method to define my Ambiguous codons?

**Comment by zruan** [comment]
Yes, you can modify the codon table by adding all desired ambiguous codon to amino acid mapping.

**Comment by universvm** [comment]
Ok, perfect thanks! Will there be any option to specify the codon alphabet in future releases of Biopython?

**Comment by zruan** [comment]
I have an idea to incorporate ambiguous codon alphabet into the current code set. This could be a user specified option in future release. I will see if I can write it up over next month or so. Once this is done, do you mind if I use your dataset as one of the test case?

**Comment by universvm** [comment]
Oh yes sure! I removed it from the post as I wasn't sure it was useful. This is my code with the sequences I'm using. One of the sequences contains "CCR":
[Archive 2.zip](https://github.com/biopython/biopython/files/957556/Archive.2.zip)

**Comment by universvm** [comment]
Hi @zruan . Today I implemented my code since I had some extra time, however I noticed that the method you specified had some weird behaviour.
 

Basically one of my sequences contains "NAA" and I therefore added:
`default_codon_table.forward_table['NAA'] = "X"`


However after this, I received another error:
```Traceback (most recent call last):
  File "X", line 36, in <module>
    dn_matrix, ds_matrix = codon_aln.get_dn_ds_matrix(method='NG86')
  File "/usr/local/lib/python2.7/site-packages/Bio/codonalign/codonalignment.py", line 127, in get_dn_ds_matrix
    method=method)
  File "/usr/local/lib/python2.7/site-packages/Bio/codonalign/codonseq.py", line 356, in cal_dn_ds
    return dnds_func[method](seq1, seq2, k, codon_table)
  File "/usr/local/lib/python2.7/site-packages/Bio/codonalign/codonseq.py", line 368, in _ng86
    codon_table=codon_table, k=k)
  File "/usr/local/lib/python2.7/site-packages/Bio/codonalign/codonseq.py", line 433, in _count_site_NG86
    elif codon_table.forward_table[neighbor] == aa:
KeyError: 'NGA'````


The game continues like this for a while, with me adding exceptions that don't exist, until this occurs:

```Traceback (most recent call last):
  File "/Users/Leo/Projects/1 - Current/Biopython/mainmatrix.py", line 36, in <module>
    dn_matrix, ds_matrix = codon_aln.get_dn_ds_matrix(method='NG86')
  File "/usr/local/lib/python2.7/site-packages/Bio/codonalign/codonalignment.py", line 127, in get_dn_ds_matrix
    method=method)
  File "/usr/local/lib/python2.7/site-packages/Bio/codonalign/codonseq.py", line 356, in cal_dn_ds
    return dnds_func[method](seq1, seq2, k, codon_table)
  File "/usr/local/lib/python2.7/site-packages/Bio/codonalign/codonseq.py", line 374, in _ng86
    codon_table=codon_table))]
  File "/usr/local/lib/python2.7/site-packages/Bio/codonalign/codonseq.py", line 474, in _count_diff_NG86
    "A, T, C or G)".format(codon2))
RuntimeError: Unrecognized character detected in codon2 NAA (Codons consist of A, T, C or G)````


I thought it could be the "get_dn_ds_matrix" without the codon table, which I specifiedas follows:
`dn_matrix, ds_matrix = codon_aln.get_dn_ds_matrix(method='NG86',codon_table=default_codon_table)
`

This gave the error "TypeError: get_dn_ds_matrix() got an unexpected keyword argument 'codon_table'".


Do you have any ideas on what is the problem here? My major concern is the second error message after adding the first exception.
[biopython.zip](https://github.com/biopython/biopython/files/998991/biopython.zip)
[biopython.zip](https://github.com/biopython/biopython/files/998992/biopython.zip)

**Comment by zruan** [comment]
Hi @universvm,

If you update your biopython to the latest version in github, the the unexpected keyword argument `codon_table` error should not occur [(see here)](https://github.com/biopython/biopython/blob/master/Bio/codonalign/codonalignment.py). `get_dn_ds_matrix()` now accepts `codon_table` argument.

The problem of your second error on unrecognized codon is during the counting step. And the program is checking if your codon character is A, T, C, G. This should be updated when we support user defined degenerated codon characters. 

Right now, an easy fix to this problem is to add character N into the `base_tuple` in line 467 of codonseq.py. You can replace `base_tuple = ('A', 'C', 'G', 'T')` to `base_tuple = ('A', 'C', 'G', 'T', 'N')`. However, since the algorithm are counting how many of the codon pairs are synonymous/nonsynonymous based on codon translation. The degenerated codon position will be counted as nonsynonymous no matter what codon it is aligned with, as you are assigning `X` to its translation.

Ruan

**Comment by zruan** [comment]
The `codonalign.build` used to be able to handle ambiguous nucleotide. But since we dropped the Alphabet class altogether in biopython recently, this is not functional again.

One solution might be to specify the `codon_table` argument of the `build` method to an `AmbiguousCodonTable`. However, I noticed that the forward_table seems to be accessed different between the `CodonTable` and `AmbiguousCodonTable`, which causes problem for the `build` function internally. Is this intended to be the case? @peterjc 

```
from Bio.Data import CodonTable
codon_table = CodonTable.generic_by_id[1]
print(codon_table.forward_table)
ambiguous_codon_table = CodonTable.ambiguous_generic_by_id[1]
#print(codon_table.forward_table) ## This will throw a error.
print(ambiguous_codon_table.forward_table.forward_table)
```

**Comment by peterjc** [comment]
The codon tables are some of the oldest bits of Biopython and (perhaps due to language limitations of the time) are confusing to me too. I would focus on the methods/attributes used in `Bio/Seq.py` and treat the rest as an internal implementation detail if possible.

**Comment by mdehoon** [comment]
Does this bug also occur with the newer `CodonAligner` class in `Bio.Align`?
