### ISSUE TITLE
DSSP failing on new mmCIF tests

### ISSUE THREAD

**Issue by peterjc** [biopython/biopython#1200]
According to the buildbot http://testing.open-bio.org/biopython/tgrid a recent change on the master has broken DSSP testing, 7a42665d5fce fails while a172cb930029 passed.

e.g. http://testing.open-bio.org/biopython/builders/Linux%2064%20-%20Python%203.4/builds/832/steps/shell/logs/stdio

```
======================================================================
ERROR: test_dssp_with_mmcif_file (test_DSSP_tool.DSSP_test)
Test DSSP generationg from MMCIF
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home_local/buildslave/BuildBot_Biopython/lin3464/build/Tests/test_DSSP_tool.py", line 53, in test_dssp_with_mmcif_file
    dssp = DSSP(model, pdbfile)
  File "/home_local/buildslave/BuildBot_Biopython/lin3464/build/build/lib.linux-x86_64-3.4/Bio/PDB/DSSP.py", line 356, in __init__
    dssp_dict, dssp_keys = dssp_dict_from_pdb_file(in_file, dssp)
  File "/home_local/buildslave/BuildBot_Biopython/lin3464/build/build/lib.linux-x86_64-3.4/Bio/PDB/DSSP.py", line 196, in dssp_dict_from_pdb_file
    raise Exception('DSSP failed to produce an output')
Exception: DSSP failed to produce an output

======================================================================
ERROR: test_dssp_with_mmcif_file_and_nonstandard_residues (test_DSSP_tool.DSSP_test)
Test DSSP generationg from MMCIF
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home_local/buildslave/BuildBot_Biopython/lin3464/build/Tests/test_DSSP_tool.py", line 61, in test_dssp_with_mmcif_file_and_nonstandard_residues
    dssp = DSSP(model, pdbfile)
  File "/home_local/buildslave/BuildBot_Biopython/lin3464/build/build/lib.linux-x86_64-3.4/Bio/PDB/DSSP.py", line 356, in __init__
    dssp_dict, dssp_keys = dssp_dict_from_pdb_file(in_file, dssp)
  File "/home_local/buildslave/BuildBot_Biopython/lin3464/build/build/lib.linux-x86_64-3.4/Bio/PDB/DSSP.py", line 196, in dssp_dict_from_pdb_file
    raise Exception('DSSP failed to produce an output')
Exception: DSSP failed to produce an output

----------------------------------------------------------------------
```

Given the timing and failure 67bc849e77688e4be13f69e8477920122389d64d seems likely the cause from #1194, CC @andrewguy 

Might this test machine have too old a version of DSSP?

**Comment by andrewguy** [comment]
That would seem like the most likely culprit. It seems that only DSSP 2.2.0 onwards supports mmCIF files.

What do you think the best approach is for this? I'm happy to do a version check on DSSP in the tests and skip these tests if DSSP is <2.2.0. I'll see if I can get that into a PR tonight.

**Comment by andrewguy** [comment]
#1201 should resolve this, although I'm more than happy if you've got other suggestions.

Do we need to add a warning somewhere that DSSP <2.2.0 won't handle mmCIF files?
