### ISSUE TITLE
mmCIF parser - missing atom serial numbers?

### ISSUE THREAD

**Issue by andrewguy** [biopython/biopython#1206]
Been playing around with the mmCIF parser a bit more (`Bio.PDB.MMCIFParser.py`), noticed that it doesn't record atom serial numbers (`_atom_site.id` in mmCIF files).

Was there a reason that this was excluded from the mmCIF parser? It seems like a deliberate omission (line 425):

```
structure_builder.init_atom(name, coord, tempfactor, occupancy,
    altloc, name, element=element)
```

Compare to PDBParser (line 226):

```
structure_builder.init_atom(name, coord, bfactor, occupancy,
    altloc, fullname, serial_number, element)
```

Was this due to issues with lack of correspondence between atom serial numbers in PDB files and _atom_site.id in mmCIF? If so, perhaps we need to document this.

@JoaoRodrigues - maybe you would know?

**Comment by andrewguy** [comment]
Note that this also breaks writing to a PDB output file when `preserve_atom_numbering=True`:

```
from Bio.PDB import PDBIO, MMCIFParser
parser = MMCIFParser()
s = parser.get_structure('PHA-L', '1FAT.cif')
io = PDBIO()
io.set_structure(s)
io.save('out.pdb', preserve_atom_numbering=True)
```
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/andrew/programs/anaconda3/lib/python3.5/site-packages/Bio/PDB/PDBIO.py", line 218, in save
    resseq, icode, chain_id)
  File "/home/andrew/programs/anaconda3/lib/python3.5/site-packages/Bio/PDB/PDBIO.py", line 109, in _get_atom_line
    return _ATOM_FORMAT_STRING % args
TypeError: %i format: a number is required, not NoneType
```

My inclination would be to record `_atom_site.id` as the atom `serial_number`, and make a note of this in the documentation. Happy to do the work on this if there are no objections to the change.

**Comment by peterjc** [comment]
It is almost certainly due to forcing the mmCIF data into an object structure designed for the PDB files. CC @lennax @etal etc as well.

**Comment by harryjubb** [comment]
Hi all, is there any progress on this? I've been asked to update an older program (using latest Biopython but Python 2.7.15, to be ported to Python 3.6+) to use MMCIF, but my program depends on knowing atom serial numbers.

Is it simply a case of recording the `_atom_site.id` as the atom `serial_number` as @andrewguy says? If so, I can have a go at a PR if that's useful? 🙂

**Comment by andrewguy** [comment]
I haven't done any work on this recently.

You should be able to use the `MMCIF2Dict` class to extract atom serial numbers, as well as all sorts of other useful information. Just as an example:

```
from Bio.PDB.MMCIF2Dict import MMCIF2Dict

mmcif_dict = MMCIF2Dict('my_pdb_file.cif')
atom_id_list = mmcif_dict['_atom_site.id']
```
I'm not 100% sure that the `_atom_site.id` is _always_ the same as the atom serial number in the `.pdb` file - that is something you would have to check yourself.

As Peter pointed out above, the structure of the PDB object in Biopython doesn't really suit the mmCIF format very well, and I suspect that rather than trying to patch bits and pieces when needed, we would be better off building a separate class to handle the newer mmCIF files. But that is likely to be a fair bit of work.

**Comment by harryjubb** [comment]
Thanks Andrew, I'll give that a go. It's definitely nice to have the same interface for structures from whichever format they come from, though I can appreciate that there'll be a big difference between PDB and mmCIF.

**Comment by lpravda** [comment]
Hey guys, in one of the side projects I used our PDBeCIF parser (https://github.com/glenveegee/PDBeCIF) to read in mmcif files to biopython structure. If you would like to help with designing and writing a bit more complex mmcif module, I'm happy to help.

**Comment by andrewguy** [comment]
A quick follow up on this one. There is indeed a lack of correspondence between atom serial numbers in PDB files and `_atom_site.id` numbering in mmCIF files. See 1LCD (in `./Tests/PDB/`) for an example.

I see two options here. 

1. We parse `_atom_site.id` as an atom serial number. Maybe add a warning that there may not be a direct correspondence to the `.pdb` file for the same structure. Maybe add an optional kwarg to `MMCIFParser.get_structure` so that users have to actively request parsing of `_atom_site.id` as serial numbers.

2. Leave it be and close this issue.

@harryjubb Harry, does option number 1 work for the `arpeggio` issue you're working on? Or do you need direct correspondence to the old PDB serial numbers? I've made the relevant changes to the code, and can make a pull request if this is the way people think we should go.

**Comment by lpravda** [comment]
Don't know how what @harryjubb plans with arpeggio are, but I took over to integrating that into PDBe and eventually I had to come up with my own parsing. Like I said before, own own internal parser has been used (pip installable these days). the code is here: https://github.com/lpravda/arpeggio/blob/refactored/arpeggio/core/protein_reader.py

**Comment by harryjubb** [comment]
Hi both, I haven't been working on Arpeggio recently, but great to hear it's gone well to integrate the PDBe parser. @andrewguy I would think option 1 works as a general solution, it doesn't sound like there's a perfect solution. Thanks for your replies.
