### ISSUE TITLE
problem importing SeqIO

### ISSUE THREAD

**Issue by iriet** [biopython/biopython#1248]
I am trying to import SeqIO using:

from Bio import SeqIO

My biopython installation (1.68) is through anaconda (conda 4.3.18), on a mac running Sierra (10.12.5). Somehow, depending on which directory I run python from, I am finding that there are some directories where I am getting this error :

#####
```
>>> import Bio
>>> from Bio import SeqIO
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/iriet/Documents/science/bioinformatics/anaconda/lib/python3.6/site-packages/Bio/SeqIO/__init__.py", line 317, in <module>
    from Bio._py3k import basestring
  File "/Users/iriet/Documents/science/bioinformatics/anaconda/lib/python3.6/site-packages/Bio/_py3k/__init__.py", line 168, in <module>
    from urllib.request import urlopen, Request, urlretrieve, urlparse
  File "/Users/iriet/Documents/science/bioinformatics/anaconda/lib/python3.6/urllib/request.py", line 98, in <module>
    import tempfile
  File "/Users/iriet/Documents/science/bioinformatics/anaconda/lib/python3.6/tempfile.py", line 43, in <module>
    import shutil as _shutil
  File "/Users/iriet/Documents/science/bioinformatics/anaconda/lib/python3.6/shutil.py", line 16, in <module>
    import bz2
  File "/Users/iriet/Documents/science/bioinformatics/anaconda/lib/python3.6/bz2.py", line 19, in <module>
    from threading import RLock
  File "/Users/iriet/Documents/science/bioinformatics/anaconda/lib/python3.6/threading.py", line 7, in <module>
    from traceback import format_exc as _format_exc
  File "/Users/iriet/Documents/science/bioinformatics/anaconda/lib/python3.6/traceback.py", line 5, in <module>
    import linecache
  File "/Users/iriet/Documents/science/bioinformatics/anaconda/lib/python3.6/linecache.py", line 11, in <module>
    import tokenize
  File "/Users/iriet/Documents/science/bioinformatics/anaconda/lib/python3.6/tokenize.py", line 41, in <module>
    __all__ = token.__all__ + ["COMMENT", "tokenize", "detect_encoding",
AttributeError: module 'token' has no attribute '__all__'
>>> 
```
#####
I have managed a workaround by invoking python from a different directory, doing the import call, and then using os.chdir() to traverse to the desired location. That works, but I don't know why the above is happening and it seems to be happening with other imports too though not of the main Bio. Thanks for any help!

**Comment by peterjc** [comment]
Could you give more details about where (which directory) you have been trying to run Python from?

As general advise, you should not run Python from within the Biopython source code (or any installed library's source code), as it will generally mess up the imports. Are you running Python from within the anaconda folder? If so, don't.

**Comment by iriet** [comment]
I can run the conda python from any directory, but when I import Biopython features such as SeqIO (as shown in the example I clipped), I get the error. If I import all of Bio, I don't get the error, but if I import SeqIO, I get the error. I have not been running these scripts from inside the anaconda folder. In the past, when I installed Biopython manually per the instructions, I was able to invoke Biopython scripts from within the same directory as the test script, but now, I am not able. I am wondering if I am encountering this problem either due to the anaconda installation of Bio, or due to a python3.6 property that I don't understand or know about.

I have not been trying to invoke python from within the Biopython code, nor have I been running python from within the anaconda folder. 

Thanks for any further help.

**Comment by peterjc** [comment]
With Google I found some similar issues, e.g. https://lists.gt.net/python/python/1180947

My guess is you have a file named ``token.py`` which is over-riding the Python standard library file of the same name.

**Comment by iriet** [comment]
Yes! That was the problem.
Thank you. My student had created a script called token.py and I didn't
think to check for namespace conflicts.
Much appreciated!

**Comment by peterjc** [comment]
Its an easy mistake to make as Python gives a very cryptic error. Thanks for confirming, I'll close this issue.

**Comment by kalilamali** [comment]
What worked for me was: :)
1. dowload biopython-1.74.tar.gz 16Mb – Source Tarball manually from https://biopython.org/wiki/Download
2. decompress/unzip/tar biopython-1.74.tar.gz
3. in the terminal:
python setup.py build
python setup.py test
sudo python setup.py install
4. DONE! https://pypi.org/project/biopython/
