### ISSUE TITLE
Bio.Phylo.PAML tests failing on 64-bit Windows Python 3.6.0

### ISSUE THREAD

**Issue by peterjc** [biopython/biopython#1257]
See https://ci.appveyor.com/project/peterjc/biopython/build/0.0.5 where using AppVeyor to run the test suite, under 64-bit Python 3.6 these fail (while 32-bit Python 3.6 and 2.7 are fine):

(*Update:* Correction, 32-bit Python 2.7 is fine. Both 32-bit and 64-bit Python 3.6 fail)

```
$ python --version
Python 3.6.0 :: Continuum Analytics, Inc.
$ python -c "import sys; print(sys.version)"
3.6.0 |Continuum Analytics, Inc.| (default, Dec 23 2016, 11:57:41) [MSC v.1900 64 bit (AMD64)]
cd Tests
$ python run_tests.py --offline
...
======================================================================
ERROR: testOutputFileValid (test_PAML_baseml.ModTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\projects\biopython\Tests\test_PAML_baseml.py", line 95, in testOutputFileValid
    self.bml.run)
  File "C:\Py\lib\unittest\case.py", line 728, in assertRaises
    return context.handle('assertRaises', args, kwargs)
  File "C:\Py\lib\unittest\case.py", line 177, in handle
    callable_obj(*args, **kwargs)
  File "C:\projects\biopython\Bio\Phylo\PAML\baseml.py", line 171, in run
    Paml.run(self, ctl_file, verbose, command)
  File "C:\projects\biopython\Bio\Phylo\PAML\_paml.py", line 141, in run
    self.write_ctl_file()
  File "C:\projects\biopython\Bio\Phylo\PAML\baseml.py", line 66, in write_ctl_file
    self._set_rel_paths()
  File "C:\projects\biopython\Bio\Phylo\PAML\baseml.py", line 153, in _set_rel_paths
    Paml._set_rel_paths(self)
  File "C:\projects\biopython\Bio\Phylo\PAML\_paml.py", line 113, in _set_rel_paths
    self._rel_out_file = _relpath(self.out_file, self.working_dir)
  File "C:\Py\lib\ntpath.py", line 561, in relpath
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not list
======================================================================
ERROR: testOutputFileValid (test_PAML_codeml.ModTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\projects\biopython\Tests\test_PAML_codeml.py", line 105, in testOutputFileValid
    self.cml.run)
  File "C:\Py\lib\unittest\case.py", line 728, in assertRaises
    return context.handle('assertRaises', args, kwargs)
  File "C:\Py\lib\unittest\case.py", line 177, in handle
    callable_obj(*args, **kwargs)
  File "C:\projects\biopython\Bio\Phylo\PAML\codeml.py", line 184, in run
    Paml.run(self, ctl_file, verbose, command)
  File "C:\projects\biopython\Bio\Phylo\PAML\_paml.py", line 141, in run
    self.write_ctl_file()
  File "C:\projects\biopython\Bio\Phylo\PAML\codeml.py", line 74, in write_ctl_file
    self._set_rel_paths()
  File "C:\projects\biopython\Bio\Phylo\PAML\codeml.py", line 167, in _set_rel_paths
    Paml._set_rel_paths(self)
  File "C:\projects\biopython\Bio\Phylo\PAML\_paml.py", line 113, in _set_rel_paths
    self._rel_out_file = _relpath(self.out_file, self.working_dir)
  File "C:\Py\lib\ntpath.py", line 561, in relpath
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not list
======================================================================
ERROR: testOutputFileValid (test_PAML_yn00.ModTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\projects\biopython\Tests\test_PAML_yn00.py", line 71, in testOutputFileValid
    self.yn00.run)
  File "C:\Py\lib\unittest\case.py", line 728, in assertRaises
    return context.handle('assertRaises', args, kwargs)
  File "C:\Py\lib\unittest\case.py", line 177, in handle
    callable_obj(*args, **kwargs)
  File "C:\projects\biopython\Bio\Phylo\PAML\yn00.py", line 98, in run
    Paml.run(self, ctl_file, verbose, command)
  File "C:\projects\biopython\Bio\Phylo\PAML\_paml.py", line 141, in run
    self.write_ctl_file()
  File "C:\projects\biopython\Bio\Phylo\PAML\yn00.py", line 44, in write_ctl_file
    self._set_rel_paths()
  File "C:\projects\biopython\Bio\Phylo\PAML\_paml.py", line 113, in _set_rel_paths
    self._rel_out_file = _relpath(self.out_file, self.working_dir)
  File "C:\Py\lib\ntpath.py", line 561, in relpath
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not list
----------------------------------------------------------------------
Ran 272 tests in 578.695 seconds
FAILED (failures = 3)
```

**Comment by peterjc** [comment]
This commit may help - and at very least avoids the confusion about which ``relpath`` is being used: https://github.com/biopython/biopython/commit/d8db6c4cbfcd6cffaffdc0085eccc5495ad09f27

**Comment by peterjc** [comment]
@brandoninvergo do you have any idea what's going on here?

If you have access to a 64-bit Windows machine with Python 3 that would be handy...

**Comment by brandoninvergo** [comment]
It looks like `os.path.relpath` works differently on NT systems compared to POSIX systems.  The test in question tries setting one of the configured files to a list rather than a string or path-like object. On my POSIX machine:

    > os.path.relpath(list())
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/usr/lib/python3.6/posixpath.py", line 448, in relpath
        raise ValueError("no path specified")
    ValueError: no path specified

Whereas apparently on NT systems, it raises a `TypeError`. The simplest solution would be to modify the affected tests to add `TypeError` to the list of exceptions in the call to `assertRaises` (e.g. line 93 in test_PAML_baseml.py). However, I have to wonder if this was just poorly done on my part. 

At the very least, lines 76, 78 and 81 of `Bio/Phylo/PAML/_paml` should be `if not foo:` instead of `if foo is not None:`.  But maybe they should be try/except blocks instead, in order to raise a uniform exception. Alternatively, maybe those tests are just stupid, since they're effectively testing how the Python `os.path` library reacts: if we're going to rely on `os.path` to raise exceptions in the case of an invalid path, there's no real reason to test the result in Biopython.

What do you think would  be the best way to proceed?

**Comment by brandoninvergo** [comment]
Sorry, forgot to mention that I don't have a Windows machine on hand to test....

**Comment by peterjc** [comment]
We'll have to use appveyor to test any proposal, or ask for a volunteer. Perhaps Ben could help?

I was puzzled where the list came from. I had assumed your paths would be strings or ``None``, with ``.`` as an explicit PWD, so am not sure if ``if self.working_dir is not None:`` is better than ``if self.working_dir:`` or not.

If you think removing the path test is most sensible, that's OK with me.

**Comment by peterjc** [comment]
For reference, see also http://mailman.open-bio.org/pipermail/biopython-dev/2017-May/021705.html

> By copying the NumPy AppVeyor setup, I was able to get a useful
Windows test run on my first attempt for Biopython (running via my
personal fork, not the official GitHub repository):
>
> https://github.com/numpy/numpy/blob/master/appveyor.yml
>
>  https://github.com/peterjc/biopython/blob/appveyor/.appveyor.yml
>
> https://ci.appveyor.com/project/peterjc/biopython/build/0.0.1
>
> ...

**Comment by brandoninvergo** [comment]
I would suggest just dropping those tests.

**Comment by peterjc** [comment]
Could you make a pull request doing that please?

**Comment by brandoninvergo** [comment]
Sure, I'll try to do it today.

**Comment by peterjc** [comment]
Hi @brandoninvergo - would you be able to remove these tests this week, or should I tackle this? Thanks!

**Comment by peterjc** [comment]
I'm trying this without those three tests...

https://ci.appveyor.com/project/peterjc/biopython/build/0.0.7

**Comment by peterjc** [comment]
AppVeyor is now live :)
