### ISSUE TITLE
mysql connector, InterfaceError: Use multi=True when executing multiple statements

### ISSUE THREAD

**Issue by peterjc** [biopython/biopython#1274]
Seen on a TravisCI run using the new PyPy 5.8 release, https://travis-ci.org/peterjc/biopython/jobs/241126458 which probably actually down to an update of ``mysql-connector-python-rf``?

```
======================================================================
ERROR: test_server (common_BioSQL.DeleteTest)
Check BioSeqDatabase methods.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/peterjc/biopython/Tests/common_BioSQL.py", line 616, in setUp
    load_database("GenBank/cor6_6.gb")
  File "/home/travis/build/peterjc/biopython/Tests/common_BioSQL.py", line 228, in load_database
    TESTDB = create_database()
  File "/home/travis/build/peterjc/biopython/Tests/common_BioSQL.py", line 205, in create_database
    server.load_database_sql(SQL_FILE)
  File "/home/travis/build/peterjc/biopython/build/lib.linux-x86_64-2.7/BioSQL/BioSeqDatabase.py", line 306, in load_database_sql
    self.adaptor.cursor.execute(sql_line)
  File "/home/travis/build/peterjc/biopython/.tox/pypy-nocov/site-packages/mysql/connector/cursor.py", line 555, in execute
    "Use multi=True when executing multiple statements")
InterfaceError: Use multi=True when executing multiple statements

```

(and many similar failures).

Probably cause: https://stackoverflow.com/questions/15288594/update-database-with-multiple-sql-statments

**Comment by peterjc** [comment]
The above failing build used this under PyPy 5.8:

``pypy-nocov installed: cffi==1.10.1,greenlet==0.4.12,isodate==0.5.4,mysql-connector-python-rf==2.2.2,numpy==1.13.0,pluggy==0.4.0,py==1.4.34,pyparsing==2.2.0,rdflib==4.2.2,readline==6.2.4.1,tox==2.7.0,virtualenv==15.1.0
``

Recent passing build https://travis-ci.org/biopython/biopython/jobs/240302092 using PyPy 5.7.1 had:

``pypy-nocov installed: cffi==1.10.0,greenlet==0.4.12,isodate==0.5.4,mysql-connector-python-rf==2.2.2,numpy==1.12.1,pluggy==0.4.0,py==1.4.34,pyparsing==2.2.0,rdflib==4.2.2,readline==6.2.4.1,tox==2.7.0,virtualenv==15.1.0
``

So curiously both have ``mysql-connector-python-rf==2.2.2``

**Comment by peterjc** [comment]
It may be related to the changes in the recently released NumPy 1.13.0 which has incidentally broken PyPy on the master branch - hopefully that's fixed with https://github.com/biopython/biopython/commit/3c964ec627334002cbb2450610c9e1b294456123

**Comment by peterjc** [comment]
Curious https://travis-ci.org/peterjc/biopython/jobs/241147686 is running PyPy v5.8 and:

```
pypy-nocov installed: cffi==1.10.1,greenlet==0.4.12,isodate==0.5.4,mysql-connector-python-rf==2.2.2,numpy==1.12.1,pluggy==0.4.0,py==1.4.34,pyparsing==2.2.0,rdflib==4.2.2,readline==6.2.4.1,tox==2.7.0,virtualenv==15.1.0

```

This fails too, so it is not ``numpy==1.12.1`` vs ``numpy==1.13.0`` but rather seems to be something linked to PyPy itself?

**Comment by peterjc** [comment]
Trying to debug this, ``self.adaptor.cursor.execute(sql_line)`` within ``create_database`` is already breaking down the SQL schema into individual SQL commands which are run one by one. Thus ``InterfaceError: Use multi=True when executing multiple statements`` seems to be a false positive...

Looking at https://travis-ci.org/peterjc/biopython/jobs/361586842 where I catch the exception to log the SQL itself, it seems usually to be ``CREATE INDEX ...`` commands which break - but not consistently at the same point in ``Tests/BioSQL/biosqldb-mysql.sql``.

Command 2, ``CREATE INDEX db_auth on biodatabase(authority)`` broke 17 times.

Command 4, ``CREATE INDEX taxparent ON taxon(parent_taxon_id)`` broke 5 times

Command 6, ``CREATE INDEX taxnametaxonid ON taxon_name(taxon_id)`` broke 6 times

Later command ``CREATE INDEX trmdbxref_dbxrefid ON term_dbxref(dbxref_id)`` broke twice.

And also command ``ALTER TABLE seqfeature_qualifier_value ADD CONSTRAINT FKseqfeature_featqual FOREIGN KEY (seqfeature_id) REFERENCES seqfeature(seqfeature_id) ON DELETE CASCADE`` broke once.

Still broken under PyPy2.7 v5.10.0, see https://travis-ci.org/peterjc/biopython/jobs/361602647 and https://travis-ci.org/peterjc/biopython/jobs/361614311 with this extra logging.

**Comment by peterjc** [comment]
Also broken on PyPy3.5 v5.10.1 as well, see https://travis-ci.org/peterjc/biopython/builds/361617843 - with a slightly different pattern of failed SQL commands during database schema loading.

**Comment by peterjc** [comment]
For reference, in case I remove the test branches mentioned, the debugging was using this patch:

```diff
$ git show 4906da0e4398dfdab9060f3cc2e8d4620c8890e7
commit 4906da0e4398dfdab9060f3cc2e8d4620c8890e7
Author: peterjc <p.j.a.cock@googlemail.com>
Date:   Tue Apr 3 11:50:05 2018 +0100

    Debugging for mysql connector multi=True error

diff --git a/BioSQL/BioSeqDatabase.py b/BioSQL/BioSeqDatabase.py
index 6ebd37518..07abe0c5e 100644
--- a/BioSQL/BioSeqDatabase.py
+++ b/BioSQL/BioSeqDatabase.py
@@ -304,7 +304,10 @@ class DBServer(object):
             sql_parts = sql.split(";")  # one line per sql command
             # don't use the last item, it's blank
             for sql_line in sql_parts[:-1]:
-                self.adaptor.cursor.execute(sql_line)
+                try:
+                    self.adaptor.cursor.execute(sql_line.replace("\n", " ").strip())
+                except Exception as e:
+                    raise RuntimeError("Got %r from %r" % (str(e), sql_line))
         else:
             raise ValueError("Module %s not supported by the loader." %
                              (self.module_name))
```
