### ISSUE TITLE
Phenotype doctests in Tutorial

### ISSUE THREAD

**Issue by peterjc** [biopython/biopython#1316]
We currently only run a limited subset of Windows platforms via AppVeyor for continuous integration. I am currently trying a broader set as part of building wheels - and that has found a new test failure:

https://ci.appveyor.com/project/biopython/biopython-wheels/build/1.0.11/job/cqn7aj3dnvbx99y8

32-bit Python 3.5 (via miniconda):

```
======================================================================
ERROR: test_doctests (test_Tutorial.TutorialTestCase)
Run tutorial doctests.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\projects\biopython-wheels\biopython\Tests\test_Tutorial.py", line 256, in test_doctests
    (len(failures), ", ".join(failures)))
ValueError: 1 Tutorial doctests failed: test_chapter_phenotype_line_00115
======================================================================
FAIL: test_WellRecord (test_phenotype.TestPhenoMicro)
Test basic functionalities of WellRecord objects
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\projects\biopython-wheels\biopython\Tests\test_phenotype.py", line 259, in test_WellRecord
    self.assertEqual(min(w2), (0.0, 63.0))
AssertionError: Tuples differ: (0.0, nan) != (0.0, 63.0)
First differing element 1:
nan
63.0
- (0.0, nan)
+ (0.0, 63.0)
======================================================================
FAIL: test_phenotype_IO (test_phenotype.TestPhenoMicro)
Test basic functionalities of phenotype IO methods
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\projects\biopython-wheels\biopython\Tests\test_phenotype.py", line 76, in test_phenotype_IO
    self.assertEqual(p1, records[0])
AssertionError: Plate[26 chars] WellRecord['A02'], WellRecord['A03'], ..., WellRecord['B12']') != Plate[26 chars] WellRecord['A02'], WellRecord['A03'], ..., WellRecord['B12']')
----------------------------------------------------------------------
Ran 272 tests in 151.504 seconds
FAILED (failures = 2)
```

**Comment by peterjc** [comment]
@mgalardini do you have any idea where a nan would come from here?

**Comment by peterjc** [comment]
This is also failing here, apparently on all the Linux Python 3.x builds as part of my wheel building experiment:

https://travis-ci.org/biopython/biopython-wheels/builds/252763946

e.g.

https://travis-ci.org/biopython/biopython-wheels/jobs/252763956

```
======================================================================
ERROR: test_doctests (test_Tutorial.TutorialTestCase)
Run tutorial doctests.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/io/biopython/Tests/test_Tutorial.py", line 256, in test_doctests
    (len(failures), ", ".join(failures)))
ValueError: 2 Tutorial doctests failed: test_chapter_phenotype_line_00115, test_chapter_phylo_line_00074
======================================================================
FAIL: test_WellRecord (test_phenotype.TestPhenoMicro)
Test basic functionalities of WellRecord objects
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/io/biopython/Tests/test_phenotype.py", line 259, in test_WellRecord
    self.assertEqual(min(w2), (0.0, 63.0))
AssertionError: Tuples differ: (0.0, nan) != (0.0, 63.0)
First differing element 1:
nan
63.0
- (0.0, nan)
+ (0.0, 63.0)
======================================================================
FAIL: test_phenotype_IO (test_phenotype.TestPhenoMicro)
Test basic functionalities of phenotype IO methods
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/io/biopython/Tests/test_phenotype.py", line 76, in test_phenotype_IO
    self.assertEqual(p1, records[0])
AssertionError: Plate[26 chars] WellRecord['A02'], WellRecord['A03'], ..., WellRecord['B12']') != Plate[26 chars] WellRecord['A02'], WellRecord['A03'], ..., WellRecord['B12']')
----------------------------------------------------------------------
```

This is using a subtly different Python setup to our main TravisCI Linux tests which use the Travis provided Python 3.x

**Comment by peterjc** [comment]
This also broke on a TravisCI Mac build,
https://travis-ci.org/biopython/biopython-wheels/jobs/252763959

Might the version of NumPy be part of the problem? These wheel builds used a range of numpy versions...

**Comment by peterjc** [comment]
Looking over the matrix at https://travis-ci.org/biopython/biopython-wheels/builds/252763946 this isn't as simple a particular version of NumPy causing the problem.

**Comment by mgalardini** [comment]
Hi @peterjc, sorry to see that! I'll look into it asap.

**Comment by mgalardini** [comment]
Hi @peterjc,

I've tried running the tests on yesterday's latest commit `b32f43f`, using python 3.5.2, numpy 1.13.1 and scipy 0.19.1. No error was reported. Should I run the tests differently? So far I did it through the command line...

Best,
Marco

**Comment by peterjc** [comment]
There is something subtly different about the Wheel setup https://github.com/biopython/biopython-wheels (where the ``nan`` appears), compared to most setups where everything seems fine - like  my local machines and our main TravisCI and AppVeyor setup.

Given this is a floating point problem of some kind, it may be down to the underlying fast maths libraries used by NumPy?
