### ISSUE TITLE
AlignIO fails to read in emboss reads when using -sreverse parameter.

### ISSUE THREAD

**Issue by croth1** [biopython/biopython#1376]
### Setup

I am reporting a problem with Biopython version, Python version, and operating
system as follows:

```python
import sys; print(sys.version)
import platform; print(platform.python_implementation()); print(platform.platform())
import Bio; print(Bio.__version__)
```

3.5.4 | packaged by conda-forge | (default, Aug 10 2017, 01:41:15) 
[GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.53)]
CPython
Darwin-16.7.0-x86_64-i386-64bit
1.70

### Expected behaviour

Successfully reading in emboss file.

### Actual behaviour

```
AssertionError: Found 9 chars so far for sequence 1 (test, '---TTTAAATTT', start=8), file says end 1:
test               9 ---TTTAAATTT      1
```

### Steps to reproduce

test.fa
```
>test
AAATTTAAA
```

`needle -asequence test.fa -bsequence test.fa -gapopen 10 -gapextend 2 -sreverse2 -outfile needle.ali`

needle.ali
```
########################################
# Program: needle
# Rundate: Sat 26 Aug 2017 07:53:45
# Commandline: needle
#    -asequence test.fa
#    -bsequence test.fa
#    -gapopen 10
#    -gapextend 2
#    -sreverse2
#    -outfile /Users/ch/tmp/needle.ali
# Align_format: srspair
# Report_file: /Users/ch/tmp/needle.ali
########################################

#=======================================
#
# Aligned_sequences: 2
# 1: test
# 2: test
# Matrix: EDNAFULL
# Gap_penalty: 10.0
# Extend_penalty: 2.0
#
# Length: 12
# Identity:       6/12 (50.0%)
# Similarity:     6/12 (50.0%)
# Gaps:           6/12 (50.0%)
# Score: 30.0
# 
#
#=======================================

test               1 AAATTTAAA---      9
                        ||||||   
test               9 ---TTTAAATTT      1


#---------------------------------------
#---------------------------------------
```

`AlignIO.read('needle.ali', 'emboss')` -> Assertion Error

**Comment by peterjc** [comment]
Confirmed, I can reproduce your test case locally on Linux using a slightly out of date EMBOSS,

```
$ needle --version
EMBOSS:6.5.7.0
$ needle -asequence test.fa -bsequence test.fa -gapopen 10 -gapextend 2 -sreverse2 -outfile needle.ali
Needleman-Wunsch global alignment of two sequences
```

and then something like this (with the latest Biopython from GitHub, which in this area is unchanged from Biopython 1.70):

```
$ python3 -c "from Bio import AlignIO; print(AlignIO.read('needle.ali', 'emboss'))"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/pc40583/lib/python3.5/site-packages/Bio/AlignIO/__init__.py", line 429, in read
    first = next(iterator)
  File "/home/pc40583/lib/python3.5/site-packages/Bio/AlignIO/__init__.py", line 376, in parse
    for a in i:
  File "/home/pc40583/lib/python3.5/site-packages/Bio/AlignIO/EmbossIO.py", line 183, in __next__
    seq_starts[index], end, line)
AssertionError: Found 9 chars so far for sequence 1 (test, '---TTTAAATTT', start=8), file says end 1:
test               9 ---TTTAAATTT      1
```

**Comment by peterjc** [comment]
I think this is due to the reverse complement and the decreasing sequence coordinates...

**Comment by peterjc** [comment]
Yes, on re-reading the code which I last did any major changes to in 2009, it does not expect reverse complemented sequences where the coordinates decrease.

Some additional logic would be required if ``start > end`` for this case, to check the numbers work out - plus some additional test cases.

Is this something you'd be will to try to work on?

**Comment by croth1** [comment]
Unfortunately due to time pressure I already had to move on and change to a format that is easier to parse - I will not have time to work on that in the next weeks.

**Comment by peterjc** [comment]
Thanks - EMBOSS is great in that it supports multiple output formats so I'm glad you are not held up by this.
