### ISSUE TITLE
BioPython Throws a KeyError 'X'

### ISSUE THREAD

**Issue by VikramMisra** [biopython/biopython#1392]
### Setup

Biopython 1.7.0, Python 2.7.13, and Mac OSX 10.12.6

I am trying to run the MEME parser on a file with protein motifs, but it returns a KeyError with 'X'.
The protein motifs occasionally contain the 'X' ambiguous residue.

### Expected behaviour

I expected the parser to print information from the motif record, whether or not the X was present in the protein sequences.

### Actual behaviour

I run the command: python meme-parser.py phae-mst-sansparallel_meme.txt

This is the output:

```
Traceback (most recent call last):
  File "meme-parser.py", line 10, in <module>
    record = motifs.parse(handle, "MEME")
  File "/Users/vikrammisra/miniconda2/lib/python2.7/site-packages/Bio/motifs/__init__.py", line 73, in parse
    record = meme.read(handle)
  File "/Users/vikrammisra/miniconda2/lib/python2.7/site-packages/Bio/motifs/meme.py", line 42, in read
    motif = Motif(alphabet, instances)
  File "/Users/vikrammisra/miniconda2/lib/python2.7/site-packages/Bio/motifs/meme.py", line 70, in __init__
    motifs.Motif.__init__(self, alphabet, instances)
  File "/Users/vikrammisra/miniconda2/lib/python2.7/site-packages/Bio/motifs/__init__.py", line 236, in __init__
    counts = self.instances.count()
  File "/Users/vikrammisra/miniconda2/lib/python2.7/site-packages/Bio/motifs/__init__.py", line 193, in count
    counts[letter][position] += 1
KeyError: 'X'
```

### Steps to reproduce

This is my code:

```
#!/Users/vikrammisra/miniconda2/bin/python                                                                                                                                                            
import sys
from Bio import motifs
from Bio.motifs import meme
from Bio.Alphabet import IUPAC

infile = sys.argv[1]

with open(infile) as handle:
    record = motifs.parse(handle, "MEME")

for motif in record:
    for instance in motif.instances:
        print(instance.sequence_name, instance.motif_name, instance.pvalue)
```

**Comment by peterjc** [comment]
Can you share a (small) test case protein motif file with an X in it? Ideally something you could give permission to be included with Biopython as part of our test suite?

**Comment by peterjc** [comment]
CC @mdehoon @barwil

**Comment by VikramMisra** [comment]
@peterjc @mdehoon @barwil Here is a file that produces the same error:

[soy-sut-meme.txt](https://github.com/biopython/biopython/files/1309655/soy-sut-meme.txt)

**Comment by peterjc** [comment]
My guess would be replacing line 182 in ``Bio/motifs/meme.py`` might help, https://github.com/biopython/biopython/blob/biopython-170/Bio/motifs/meme.py#L182

Changing:

```python
al = IUPAC.protein
```

to:

```python
al = IUPAC.extended_protein
```

That will add the following extra letters:

- `B` = "Asx";  Aspartic acid (R) or Asparagine (N)
- `X` = "Xxx";  Unknown or 'other' amino acid
- `Z` = "Glx";  Glutamic acid (E) or Glutamine (Q)
- `J` = "Xle";  Leucine (L) or Isoleucine (I), used in mass-spec (NMR)
- `U` = "Sec";  Selenocysteine
- `O` = "Pyl";  Pyrrolysine

I have not tried this, and do not know the MEME and motif code enough to say if this would have any side effect.

**Comment by VikramMisra** [comment]
@peterjc I just tried changing 182 to:
```al = IUPAC.extended_protein ```

Unfortunately, I got the same error.

**Comment by peterjc** [comment]
@zaidurrehman is this something you might be able to help with (given your recent contribution for RNA support in pull request #1421)? Thanks!

**Comment by zaidurrehman** [comment]
@VikramMisra Does your protein samples use the [standard protein](http://meme-suite.org/doc/alphabets.html#protein) alphabet or have you defined your own custom alphabet? 

Can you give a small meme output file which has X alphabet?

**Comment by mdehoon** [comment]
This bug still exists with the current XML parser; see the attached XML output from MEME.
I think this can be fixed by modifying `__read_alphabet` in `Bio/motifs/meme.py`, but we'd have to decide what to do with the ambiguous amino acids B, Z, J, which are D or N, E or Q, I or L respectively. Ignore them completely, or somehow count them partially?

[meme.xml.gz](https://github.com/biopython/biopython/files/6846506/meme.xml.gz)

**Comment by ReKiritsugu** [comment]
5years past, I meet the same bugs too...

**Comment by peterjc** [comment]
Can the motifs code cope with ambiguous nucleotide bases, and if so treat ambiguous amino acids in a similar way?

**Comment by Kiri2002** [comment]
Well, 6 years past, also meet...

**Comment by Kiri2002** [comment]
> @VikramMisra Does your protein samples use the [standard protein](http://meme-suite.org/doc/alphabets.html#protein) alphabet or have you defined your own custom alphabet?
> 
> Can you give a small meme output file which has X alphabet?
[all.meme.xml.txt](https://github.com/biopython/biopython/files/15349276/all.meme.xml.txt)
