### ISSUE TITLE
Entrez tests failing due to NCBI espell problem

### ISSUE THREAD

**Issue by peterjc** [biopython/biopython#1430]
e.g.

```
$ python3 run_tests.py
...
======================================================================
ERROR: test_espell (test_Entrez_online.EntrezOnlineCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/pc40583/repositories/biopython/Tests/test_Entrez_online.py", line 187, in test_espell
    record = Entrez.read(handle)
  File "/Users/pc40583/repositories/biopython/build/lib.macosx-10.6-intel-3.6/Bio/Entrez/__init__.py", line 454, in read
    record = handler.read(handle)
  File "/Users/pc40583/repositories/biopython/build/lib.macosx-10.6-intel-3.6/Bio/Entrez/Parser.py", line 238, in read
    self.parser.ParseFile(handle)
  File "/Users/sysadmin/build/v3.6.0/Modules/pyexpat.c", line 468, in EndElement
  File "/Users/pc40583/repositories/biopython/build/lib.macosx-10.6-intel-3.6/Bio/Entrez/Parser.py", line 395, in endElementHandler
    raise RuntimeError(value)
RuntimeError: Couldn't resolve #PubmedSpellSrv, the address table is empty.

======================================================================
ERROR: test_doctests (test_Tutorial.TutorialTestCase)
Run tutorial doctests.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/pc40583/repositories/biopython/Tests/test_Tutorial.py", line 256, in test_doctests
    (len(failures), ", ".join(failures)))
ValueError: 1 Tutorial doctests failed: test_chapter_entrez_line_00567

----------------------------------------------------------------------
Ran 274 tests in 459.825 seconds

FAILED (failures = 2)
```

This is a general problem in Entrez itself, which I have reported by email, cross reference https://blastedbio.blogspot.co.uk/2017/10/entrez-espell-cant-resolve.html#more

**Comment by peterjc** [comment]
At some point this was resolved, closing issue.
