### ISSUE TITLE
Setting description to None in Seqrecord causes error on write

### ISSUE THREAD

**Issue by ctSkennerton** [biopython/biopython#1443]
I've found that `SeqIO.write` assumes that attributes like description in seqrecords are filled in and fails if they are `None`. The default constructor for SeqRecord provides dummy values but there is nothing stopping anyone from changing the value to `None`.

### Background 
In my actual use case, I have a BioSQL database where some of the records were added in not using biopython and do not have any description (the description is allowed to be null in the BioSQL schema). When reading these records back out I get the following error.  

### Setup

```
>>> import sys; print(sys.version)
3.6.1 |Continuum Analytics, Inc.| (default, May 11 2017, 13:04:09) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)]
>>> import platform; print(platform.python_implementation()); print(platform.platform())
CPython
Darwin-16.7.0-x86_64-i386-64bit
>>> import Bio; print(Bio.__version__)
1.71.dev0
```
### Expected behaviour

\>test_id
GATC

### Actual behaviour

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/connor/local/biopython/Bio/SeqIO/__init__.py", line 492, in write
    count = writer_class(fp).write_file(sequences)
  File "/Users/connor/local/biopython/Bio/SeqIO/Interfaces.py", line 215, in write_file
    count = self.write_records(records)
  File "/Users/connor/local/biopython/Bio/SeqIO/Interfaces.py", line 200, in write_records
    self.write_record(record)
  File "/Users/connor/local/biopython/Bio/SeqIO/FastaIO.py", line 189, in write_record
    description = self.clean(record.description)
  File "/Users/connor/local/biopython/Bio/SeqIO/Interfaces.py", line 107, in clean
    return text.replace("\n", " ").replace("\r", " ").replace("  ", " ")
AttributeError: 'NoneType' object has no attribute 'replace'
```

### Steps to reproduce

```python
from Bio.Seq import Seq
from Bio.SeqRecord import SeqRecord
from Bio import SeqIO
import sys

simple_seq = Seq("GATC")
from Bio.SeqRecord import SeqRecord
simple_seq_r = SeqRecord(simple_seq, id='test_id')
simple_seq_r.description = None
SeqIO.write(simple_seq_r, sys.stdout, 'fasta')
```

**Comment by peterjc** [comment]
Yes, this is (unfortunately perhaps) by design.

There are so many ``SeqIO`` back ends that rather updating them all to allow ``None`` for common attributes like the ``.id``, ``.name`` and ``.description`` I suggest you use the empty string, or allow ``SeqRecord`` to use its current horrible default values. However, I'd review a pull request to handle this (most likely using the empty string if the output format requires a value).

Alternatively, it may be worth opening a pull request on the BioSQL mappings to better handle these null values by mapping them to/from the ugly but distinctive default values used in the ``SeqRecord``.

On a related point, looking back to the early days of ``Bio.SeqIO``, I would with hindsight have removed the default values from the ``SeqRecord`` and explicitly set a default of ``''`` or ``None``. Sadly making this (and many other) cleanup now seems most likely just to break other people's code.
