### ISSUE TITLE
NCBIStandalone ValueError: Line does not start with 'S2'

### ISSUE THREAD

**Issue by dixonmd** [biopython/biopython#1449]
### Setup

I am reporting a problem with Biopython version, Python version, and operating
system as follows:

```python
import sys; print(sys.version)
import platform; print(platform.python_implementation()); print(platform.platform())
import Bio; print(Bio.__version__)
```

(*Please copy and run the above in your Python, and copy-and-paste the output*)
>>> import sys; print(sys.version)
2.7.12 (default, Nov 19 2016, 06:48:10) 
[GCC 5.4.0 20160609]
>>> import platform; print(platform.python_implementation()); print(platform.platform())
CPython
Linux-4.4.0-98-generic-x86_64-with-Ubuntu-16.04-xenial
>>> import Bio; print(Bio.__version__)
1.70
>>> 

### Expected behaviour

Blast text parser

### Actual behaviour

Getting the error 
Traceback (most recent call last):
  File "OrganismAnnotation.py", line 106, in <module>
    organism = OrganismAnnotation(args.blastfile, args.fastafile, args.outputfile)
  File "OrganismAnnotation.py", line 23, in __init__
    self.blast_parse = BlastParser.text_blast_parse(self.blastfile)
  File "/home/dixon/Python/SVN/BASIC_LIBS/BlastParser.py", line 20, in text_blast_parse
    for blast_record in blast_iterator:
  File "/home/dixon/.local/lib/python2.7/site-packages/Bio/Blast/NCBIStandalone.py", line 1676, in __next__
    return self._parser.parse(StringIO(data))
  File "/home/dixon/.local/lib/python2.7/site-packages/Bio/Blast/NCBIStandalone.py", line 815, in parse
    self._scanner.feed(handle, self._consumer)
  File "/home/dixon/.local/lib/python2.7/site-packages/Bio/Blast/NCBIStandalone.py", line 104, in feed
    self._scan_parameters(uhandle, consumer)
  File "/home/dixon/.local/lib/python2.7/site-packages/Bio/Blast/NCBIStandalone.py", line 800, in _scan_parameters
    read_and_call(uhandle, consumer.blast_cutoff, start='S2')
  File "/home/dixon/.local/lib/python2.7/site-packages/Bio/ParserSupport.py", line 140, in read_and_call
    raise ValueError(errmsg)
ValueError: Line does not start with 'S2':
  Database: All non-redundant GenBank CDS translations+PDB+SwissProt+PIR+PRF

### Steps to reproduce

(*Please fill this in *)
Parsing the blast text file

BLASTX 2.6.0+

Reference: Stephen F. Altschul, Thomas L. Madden, Alejandro A.
Schaffer, Jinghui Zhang, Zheng Zhang, Webb Miller, and David J.
Lipman (1997), "Gapped BLAST and PSI-BLAST: a new generation of
protein database search programs", Nucleic Acids Res. 25:3389-3402.

Database: All non-redundant GenBank CDS translations+PDB+SwissProt+PIR+PRF
excluding environmental samples from WGS projects
           113,411,368 sequences; 41,561,330,932 total letters

**Comment by peterjc** [comment]
Can you make a short Python example which fails with this error, or share some of your code? It is clear from the exception traceback you are using ``Bio.Blast.NCBIStandalone`` but not clear how you are using it.

**Comment by peterjc** [comment]
Also can you share a complete sample BLAST text file which breaks?
