### ISSUE TITLE
BioSQL mysql connector, InterfaceError: Use multi=True when executing multiple statements

### ISSUE THREAD

**Issue by peterjc** [biopython/biopython#1520]
### Setup

I am reporting a problem with Biopython version 1.70.dev0, Python version PyPy 5.8.0, under TravisCI:

https://travis-ci.org/peterjc/biopython/jobs/335109271

### Expected behaviour

Test pass, as seen with PyPy 5.7.1, e.g.

```
pypy-nocov installed: cffi==1.10.0,greenlet==0.4.12,isodate==0.6.0,mysql-connector-python-rf==2.2.2,numpy==1.12.1,pyparsing==2.2.0,rdflib==4.2.2,readline==6.2.4.1,six==1.11.0
pypy-nocov runtests: PYTHONHASHSEED='2910044087'
pypy-nocov runtests: commands[0] | bash -c \python setup.py install > /dev/null\
warning: no previously-included files matching '*.pyc' found anywhere in distribution
warning: no previously-included files matching '*.pyo' found anywhere in distribution
warning: no previously-included files matching '*.py{}' found anywhere in distribution
warning: no previously-included files matching '*.py-e' found anywhere in distribution
pypy-nocov runtests: commands[1] | bash -c \cd Tests && python run_tests.py --offline\
test_Ace ... ok
...
test_BioSQL_MySQLdb ... skipping. Install MySQLdb if you want to use mysql with BioSQL 
test_BioSQL_MySQLdb_online ... skipping. internet not available
test_BioSQL_mysql_connector ... ok
test_BioSQL_mysql_connector_online ... skipping. internet not available
test_BioSQL_psycopg2 ... skipping. Install psycopg2 if you want to use pg with BioSQL 
test_BioSQL_psycopg2_online ... skipping. internet not available
test_BioSQL_sqlite3 ... ok
test_BioSQL_sqlite3_online ... skipping. internet not available
...
```

Excerpt from https://travis-ci.org/biopython/biopython/jobs/335102378

### Actual behaviour

Using PyPy 5.8.0 fails:

```
pypy-nocov installed: cffi==1.10.1,greenlet==0.4.12,isodate==0.6.0,mysql-connector-python-rf==2.2.2,numpy==1.12.1,pyparsing==2.2.0,rdflib==4.2.2,readline==6.2.4.1,six==1.11.0
pypy-nocov runtests: PYTHONHASHSEED='109575238'
pypy-nocov runtests: commands[0] | bash -c \python setup.py install > /dev/null\
warning: no previously-included files matching '*.pyc' found anywhere in distribution
warning: no previously-included files matching '*.pyo' found anywhere in distribution
warning: no previously-included files matching '*.py{}' found anywhere in distribution
warning: no previously-included files matching '*.py-e' found anywhere in distribution
pypy-nocov runtests: commands[1] | bash -c \cd Tests && python run_tests.py --offline\
test_Ace ... ok
...
test_BioSQL_MySQLdb ... skipping. Install MySQLdb if you want to use mysql with BioSQL 
test_BioSQL_MySQLdb_online ... skipping. internet not available
test_BioSQL_mysql_connector ... FAIL
test_BioSQL_mysql_connector_online ... skipping. internet not available
test_BioSQL_psycopg2 ... skipping. Install psycopg2 if you want to use pg with BioSQL 
test_BioSQL_psycopg2_online ... skipping. internet not available
test_BioSQL_sqlite3 ... ok
test_BioSQL_sqlite3_online ... skipping. internet not available
...
======================================================================
ERROR: test_server (common_BioSQL.DeleteTest)
Check BioSeqDatabase methods.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/peterjc/biopython/Tests/common_BioSQL.py", line 646, in setUp
    load_database("GenBank/cor6_6.gb")
  File "/home/travis/build/peterjc/biopython/Tests/common_BioSQL.py", line 240, in load_database
    TESTDB = create_database()
  File "/home/travis/build/peterjc/biopython/Tests/common_BioSQL.py", line 217, in create_database
    server.load_database_sql(SQL_FILE)
  File "/home/travis/build/peterjc/biopython/build/lib.linux-x86_64-2.7/BioSQL/BioSeqDatabase.py", line 307, in load_database_sql
    self.adaptor.cursor.execute(sql_line)
  File "/home/travis/build/peterjc/biopython/.tox/pypy-nocov/site-packages/mysql/connector/cursor.py", line 555, in execute
    "Use multi=True when executing multiple statements")
InterfaceError: Use multi=True when executing multiple statements

...

----------------------------------------------------------------------
Ran 272 tests in 409.041 seconds

FAILED (failures = 1)
```

Excerpt from https://travis-ci.org/peterjc/biopython/jobs/335109271

### Steps to reproduce

Run the test suite on TravisCI with the current default version of pypy,

```diff
--- a/.travis.yml
+++ b/.travis.yml
@@ -51,7 +51,7 @@ matrix:
       python: 3.6
       env: TOXENV=py36-cover
     - stage: test
-      python: pypy-5.7.1
+      python: pypy
       env: TOXENV=pypy-nocov
     - stage: test
       python: pypy3
```

Confusingly both the example above have ``mysql-connector-python-rf==2.2.2``

**Comment by peterjc** [comment]
Duplicate of #1274 - I should have searched, I thought this felt familiar.
