### ISSUE TITLE
test_water_file (test_Emboss.PairwiseAlignmentTests) error

### ISSUE THREAD

**Issue by muffinman563** [biopython/biopython#1523]
Hello, i am trying to install Biopython 1.70 and ran the following code:

python setup.py test

I noticed 1 failure which was:

FAIL: test_water_file (test_Emboss.PairwiseAlignmentTests)
water with the asis trick, output to a file.

How can i amend this?
Thank you

### Setup

I am reporting a problem with Biopython version, Python version, and operating
system as follows:

```python
3.6.3 |Anaconda custom (64-bit)| (default, Oct  6 2017, 12:04:38) 
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)]
CPython
Darwin-17.4.0-x86_64-i386-64bit
1.70
```

**Comment by peterjc** [comment]
What version of EMBOSS do you have? e.g.

```
$ water --version
EMBOSS:6.5.7.0
```

Can you share the full error message from the tests? I would expect a stack trace.

**Comment by muffinman563** [comment]
Sorry for the late reply, i have

EMBOSS:6.5.7.0

**Comment by peterjc** [comment]
Summary: This is not a Biopython bug, or an Emboss bug, it is a bioconda bug.

--

I wanted to tee the full test output. Running just ``test_Emboss.py`` locally on macOS, with EMBOSS 6.5.7 installed via conda, I get:

```
python3 test_Emboss.py
test_needle_file (__main__.PairwiseAlignmentTests)
Run needle with the asis trick, output to a file. ... FAIL
test_needle_needs_output (__main__.PairwiseAlignmentTests)
Run needle without output file or stdout/filter should give error. ... ok
test_needle_piped (__main__.PairwiseAlignmentTests)
Run needle with asis trick, output piped to stdout. ... ok
test_needle_piped2 (__main__.PairwiseAlignmentTests)
Run needle with asis trick, and nucleotide FASTA file, output piped to stdout. ... ok
test_seqtmatchall_piped (__main__.PairwiseAlignmentTests)
Run seqmatchall with pair output piped to stdout. ... ok
test_water_file (__main__.PairwiseAlignmentTests)
Run water with the asis trick, output to a file. ... FAIL
test_water_file2 (__main__.PairwiseAlignmentTests)
Run water with the asis trick and nucleotide FASTA file, output to a file. ... ok
test_water_file3 (__main__.PairwiseAlignmentTests)
Run water with the asis trick and GenBank file, output to a file. ... ok
test_water_file4 (__main__.PairwiseAlignmentTests)
Run water with the asis trick and SwissProt file, output to a file. ... ok
test_water_needs_output (__main__.PairwiseAlignmentTests)
Run water without output file or stdout/filter should give error. ... ok
test_water_piped (__main__.PairwiseAlignmentTests)
Run water with asis trick, output piped to stdout. ... ok
test_align_clustalw (__main__.SeqRetAlignIOTests)
Check AlignIO & EMBOSS reading each other's conversions of a ClustalW file. ... ok
test_clustalw (__main__.SeqRetAlignIOTests)
Check AlignIO & EMBOSS reading each other's conversions of a PHYLIP file. ... ok
test_abi (__main__.SeqRetSeqIOTests)
Check SeqIO agrees with EMBOSS' Abi to FASTQ conversion. ... ok
test_clustalw (__main__.SeqRetSeqIOTests)
Check SeqIO & EMBOSS reading each other's conversions of a Clustalw file. ... ok
test_embl (__main__.SeqRetSeqIOTests)
Check SeqIO & EMBOSS reading each other's conversions of an EMBL file. ... ok
test_genbank (__main__.SeqRetSeqIOTests)
Check SeqIO & EMBOSS reading each other's conversions of a GenBank file. ... ok
test_genbank2 (__main__.SeqRetSeqIOTests)
Check SeqIO & EMBOSS reading each other's conversions of another GenBank file. ... ok
test_ig (__main__.SeqRetSeqIOTests)
Check SeqIO & EMBOSS reading each other's conversions of an ig file. ... ok
test_pir (__main__.SeqRetSeqIOTests)
Check SeqIO & EMBOSS reading each other's conversions of a PIR file. ... ok
test_all_unambig_dna_codons (__main__.TranslationTests)
Run transeq vs Bio.Seq on unambiguous DNA codons (inc. alt tables). ... ok
test_all_unambig_rna_codons (__main__.TranslationTests)
Run transeq vs Bio.Seq on unambiguous RNA codons (inc. alt tables). ... ok
test_mixed_unambig_rna_codons (__main__.TranslationTests)
Run transeq vs Bio.Seq on unambiguous DNA/RNA codons (inc. alt tables). ... ok
test_simple (__main__.TranslationTests)
Run transeq vs Bio.Seq for simple translations (including alt tables). ... ok

======================================================================
FAIL: test_needle_file (__main__.PairwiseAlignmentTests)
Run needle with the asis trick, output to a file.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_Emboss.py", line 565, in test_needle_file
    "Missing output file %r from:\n%s" % (filename, cline))
AssertionError: False is not true : Missing output file 'Emboss/temp with space.needle' from:
needle -outfile="Emboss/temp with space.needle" -asequence=asis:ACCCGGGCGCGGT -bsequence=asis:ACCCGAGCGCGGT -gapopen=10 -gapextend=0.5 -snucleotide=True

======================================================================
FAIL: test_water_file (__main__.PairwiseAlignmentTests)
Run water with the asis trick, output to a file.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_Emboss.py", line 505, in test_water_file
    self.run_water(cline)
  File "test_Emboss.py", line 488, in run_water
    "Missing output file %r from:\n%s" % (cline.outfile, cline))
AssertionError: False is not true : Missing output file 'Emboss/temp with space.water' from:
water -outfile="Emboss/temp with space.water" -asequence=asis:ACCCGGGCGCGGT -bsequence=asis:ACCCGAGCGCGGT -gapopen=10 -gapextend=0.5

----------------------------------------------------------------------
Ran 24 tests in 10.388s

FAILED (failures=2)
```

That's probably the same as you - last time I was checking on Linux where EMBOSS was installed directly (not via conda).

I think this is a bug in the Conda packaging of EMBOSS when using filenames with spaces. This command is writing to ``Emboss/temp`` which is wrong:

```
$ needle -outfile="Emboss/temp with space.needle" -asequence=asis:ACCCGGGCGCGGT -bsequence=asis:ACCCGAGCGCGGT -gapopen=10 -gapextend=0.5 -snucleotide=True
```

Likewise:

```
$ water -outfile="Emboss/temp with space.water" -asequence=asis:ACCCGGGCGCGGT -bsequence=asis:ACCCGAGCGCGGT -gapopen=10 -gapextend=0.5
```

I can fix this locally by editing the BioConda scripts under ``~/anaconda3/bin/needle`` and ``~/anaconda3/bin/water`` and will open an issue on the BioConda package...

**Comment by peterjc** [comment]
If you update your Emboss from bioconda, it ought to work now. e.g.

```
conda update emboss
```

Please could you try this and report back? Thanks!
