### ISSUE TITLE
MMCIFParser error loading 4xlh

### ISSUE THREAD

**Issue by chriswaudby** [biopython/biopython#1548]
### Setup

I am reporting a problem with Biopython version, Python version, and operating
system as follows:

```python
import sys; print(sys.version)
import platform; print(platform.python_implementation()); print(platform.platform())
import Bio; print(Bio.__version__)
```
```
3.5.2 |Anaconda 4.2.0 (x86_64)| (default, Jul  2 2016, 17:52:12) 
[GCC 4.2.1 Compatible Apple LLVM 4.2 (clang-425.0.28)]
CPython
Darwin-17.4.0-x86_64-i386-64bit
1.70
```

### Expected behaviour

Attempting to download PDB structure - code that's worked for hundreds of other pdb entries fails for 4xlh.

### Actual behaviour

Calling `get_structure()` on an `MMCIFParser` object throws an error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/chris/anaconda/envs/python35/lib/python3.5/site-packages/Bio/PDB/MMCIFParser.py", line 64, in get_structure
    self._build_structure(structure_id)
  File "/Users/chris/anaconda/envs/python35/lib/python3.5/site-packages/Bio/PDB/MMCIFParser.py", line 131, in _build_structure
    x = x_list[i]
IndexError: list index out of range
```

### Steps to reproduce

```python
import Bio.PDB as bp
pdbl = bp.PDBList()
pdb = '4xlh'
filename = pdbl.retrieve_pdb_file(pdb, file_format='mmCif')
parser = bp.MMCIFParser()
structure = parser.get_structure(pdb,filename)
```

output:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/chris/anaconda/envs/python35/lib/python3.5/site-packages/Bio/PDB/MMCIFParser.py", line 64, in get_structure
    self._build_structure(structure_id)
  File "/Users/chris/anaconda/envs/python35/lib/python3.5/site-packages/Bio/PDB/MMCIFParser.py", line 131, in _build_structure
    x = x_list[i]
IndexError: list index out of range
```

**Comment by peterjc** [comment]
Is it easy for you to try this with the latest Biopython from git, as there have been a few CIF changes since the last release?

@JoaoRodrigues, @jgreener64 - any thoughts?

**Comment by jgreener64** [comment]
Tried this on the master branch and it works without an error, I guess one of the mmCIF changes since the last release fixed it.

**Comment by JoaoRodrigues** [comment]
This seems to have been solved, so I'm closing the issue. Feel free to let me know if it should be re-opened.
