### ISSUE TITLE
Math domain error using cal_dn_ds 

### ISSUE THREAD

**Issue by Grendel26** [biopython/biopython#1611]
I would like to calculate the dN and dS between two sequences, to do so I had to make a codon alignment such like that:

 ```
   nuc1="ATGGGTACCGTGTTGTAT"
    nuc2="ATGGCTACCGTGTTAGTA"
    nuc1 = SeqRecord(Seq(nuc1,alphabet=IUPAC.IUPACUnambiguousDNA()), id='nuc1')
    nuc2 = SeqRecord(Seq(nuc2,alphabet=IUPAC.IUPACUnambiguousDNA()), id='nuc2')

    prot1="MGTVLY"
    prot2="MATVLV"
    prot1 = SeqRecord(Seq(prot1, alphabet=IUPAC.protein),id='prot1') 
    prot2 = SeqRecord(Seq(prot2, alphabet=IUPAC.protein),id='prot2')

    aln = MultipleSeqAlignment([prot1, prot2])

    corr_dict = {'prot1': 'nuc1', 'prot2': 'nuc2'}
    codon_aln = codonalign.build(aln, [nuc1, nuc2],alphabet=codonalign.default_codon_alphabet,corr_dict=corr_dict)

    print(codon_aln)

CodonAlphabet(Standard) CodonAlignment with 2 rows and 18 columns (6 codons)
ATGGGTACCGTGTTGTAT nuc1
ATGGCTACCGTGTTAGTA nuc2

dN, dS = cal_dn_ds(codon_aln[0], codon_aln[1], method="YN00",codon_table=default_codon_table, k=1)

```
And I get a message error :

RuntimeWarning: invalid value encountered in double_scalars
  path_prob = [3 * i / sum(path_prob) for i in path_prob]
Traceback (most recent call last):
  File "dico.py", line 169, in <module>
    print(divergence("concatenate_0035_fna_renamed.fst","concatenate_0042_fna_renamed.fst","concatenate_0035_faa_renamed.fst","concatenate_0042_faa_renamed.fst"))
  File "dico.py", line 75, in divergence
    dN, dS = cal_dn_ds(codon_aln[0], codon_aln[1], method="YN00",codon_table=default_codon_table, k=1)
  File "/usr/local/lib/python3.5/site-packages/Bio/codonalign/codonseq.py", line 358, in cal_dn_ds
    return dnds_func[method](seq1, seq2, k, codon_table)
  File "/usr/local/lib/python3.5/site-packages/Bio/codonalign/codonseq.py", line 763, in _yn00
    dSdN.append(_get_kappa_t(f, tv, t=True))
  File "/usr/local/lib/python3.5/site-packages/Bio/codonalign/codonseq.py", line 809, in _get_kappa_t
    (1 - TV[1] / (2 * pi['Y'] * pi['R'])) - TV[0]) / \
ZeroDivisionError: float division by zero

And the same when I use the LWL85 method:

File "dico.py", line 169, in <module>
    print(divergence("concatenate_0035_fna_renamed.fst","concatenate_0042_fna_renamed.fst","concatenate_0035_faa_renamed.fst","concatenate_0042_faa_renamed.fst"))
  File "dico.py", line 75, in divergence
    dN, dS = cal_dn_ds(codon_aln[0], codon_aln[1], method="LWL85",codon_table=default_codon_table, k=1)
  File "/usr/local/lib/python3.5/site-packages/Bio/codonalign/codonseq.py", line 358, in cal_dn_ds
    return dnds_func[method](seq1, seq2, k, codon_table)
  File "/usr/local/lib/python3.5/site-packages/Bio/codonalign/codonseq.py", line 576, in _lwl85
    for i, j in zip(P, Q)]
  File "/usr/local/lib/python3.5/site-packages/Bio/codonalign/codonseq.py", line 576, in <listcomp>
    for i, j in zip(P, Q)]
ValueError: math domain error

Do you have an idea what is going on? Thanks you

**Comment by peterjc** [comment]
Could you confirm what version of Biopython you are using (Biopython 1.71 was released recently)?

**Comment by peterjc** [comment]
Could you look at this please @zruan? Thanks!

**Comment by Grendel26** [comment]
I'm actually using python 3. I tried with 2 sequences with some substitutions and it did works, it seems that when the two sequences are too divergent, it does not work. Can i fixe it or display something like 9.999 when the sequences are too divergent? Indeed my sequences are separate from 200 000 000 y.a. Thanks you for your help.

**Comment by peterjc** [comment]
I had to add the missing import statements, but can reproduce your example using the latest Biopython code from GitHub (so there is no need for you to update you system yet).

I don't know enough about the algorithms and their assumptions to say if these sequences are simply too far apart (or not close enough), but that may explain the division by zero problem.

**Comment by Grendel26** [comment]
ok, can I give you an example and can you try to run it to see if we have the same problem?
I give you the codon alignment file and the two nucleotides sequences: 

[seq1.fst.zip](https://github.com/biopython/biopython/files/1907055/seq1.fst.zip)
[dnds.out.zip](https://github.com/biopython/biopython/files/1907052/dnds.out.zip)

Wen I run it with YN00 method I get: 
```
Traceback (most recent call last):
  File "dico.py", line 156, in <module>
    print(divergence("concatenate_0035_fna_renamed.fst","concatenate_0042_fna_renamed.fst","concatenate_0035_faa_renamed.fst","concatenate_0042_faa_renamed.fst"))
  File "dico.py", line 146, in divergence
    dN, dS = cal_dn_ds(codon_aln[0], codon_aln[1], method="YN00")
  File "/Users/etudiant/Desktop/Horizon_project/busco/Divergence/codonseq2.py", line 359, in cal_dn_ds
    return dnds_func[method](seq1, seq2, k, codon_table)
  File "/Users/etudiant/Desktop/Horizon_project/busco/Divergence/codonseq2.py", line 768, in _yn00
    dSdN.append(_get_kappa_t(f, tv, t=True))
  File "/Users/etudiant/Desktop/Horizon_project/busco/Divergence/codonseq2.py", line 822, in _get_kappa_t
    a = -0.5 * log(A)  # this seems to be an error in YANG's original paper
ValueError: math domain error
```
The issue seem to be that the A is negatif, then log(-x) is impossible 

And when I try to run the LWL85 method it work but for another sequence it displays;

```
Traceback (most recent call last):
  File "dico.py", line 153, in <module>
    print(divergence("concatenate_0035_fna_renamed.fst","concatenate_0042_fna_renamed.fst","concatenate_0035_faa_renamed.fst","concatenate_0042_faa_renamed.fst"))
  File "dico.py", line 143, in divergence
    dN, dS = cal_dn_ds(codon_aln[0], codon_aln[1], method="LWL85")
  File "/Users/etudiant/Desktop/Horizon_project/busco/Divergence/codonseq2.py", line 359, in cal_dn_ds
    return dnds_func[method](seq1, seq2, k, codon_table)
  File "/Users/etudiant/Desktop/Horizon_project/busco/Divergence/codonseq2.py", line 577, in _lwl85
    for i, j in zip(P, Q)]
  File "/Users/etudiant/Desktop/Horizon_project/busco/Divergence/codonseq2.py", line 577, in <listcomp>
    for i, j in zip(P, Q)]
ValueError: math domain error
```

**Comment by peterjc** [comment]
You attached two nucleotide files, which does not match your example. Also how are you loading the alignments?

**Comment by Grendel26** [comment]
Here is my all script, in fact, I give 4 files, one with two nucleotides sequences and one with two protein sequences: 

```

def divergence(fic1dna,fic2dna,fic1prot,fic2prot):

	from Bio import SeqIO
	from Bio import pairwise2
	from Bio.pairwise2 import format_alignment
	#outfile="codon_align.out"
	outfile_dn_ds="dn_ds.out"
	outfile=open(outfile,"w",encoding='utf-8')
	outfile_dn_ds=open(outfile_dn_ds,"w",encoding='utf-8')
	
	seq1dna = list(SeqIO.parse(fic1dna, "fasta",alphabet=IUPAC.IUPACUnambiguousDNA()))
	seq2dna = list(SeqIO.parse(fic2dna, "fasta",alphabet=IUPAC.IUPACUnambiguousDNA()))
	seq1prot = list(SeqIO.parse(fic1prot, "fasta",alphabet=IUPAC.protein))
	seq2prot= list(SeqIO.parse(fic2prot, "fasta",alphabet=IUPAC.protein))



	u=0
	print(len(seq1dna))
	while u < (len(seq1dna)): # make an alignment betwen each element on 2 files for 2 paires files 

		matrix = matlist.blosum62
		gap_open = -10
		gap_extend = -0.5
		
		nuc1=str(seq1dna[u].seq)
		nuc2=str(seq2dna[u].seq)
		prot1=str(seq1prot[u].seq)
		prot2=str(seq2prot[u].seq)



		nuc2 = SeqRecord(Seq(nuc2,alphabet=IUPAC.IUPACUnambiguousDNA()), id='nuc2')
		nuc1 = SeqRecord(Seq(nuc1,alphabet=IUPAC.IUPACUnambiguousDNA()), id='nuc1')

		alns = pairwise2.align.globalds(prot1 ,prot2, matrix, gap_open, gap_extend)

		
		top_aln = alns[0]

	
		prot1, prot2, score, begin, end = top_aln

		#print (prot1+'\n'+prot2)


		prot1 = SeqRecord(Seq(prot1, alphabet=IUPAC.protein),id='pro1') 
		prot2 = SeqRecord(Seq(prot2, alphabet=IUPAC.protein),id='pro2')

		aln = MultipleSeqAlignment([prot1, prot2])
		

		codon_aln = codonalign.build(aln, [nuc1, nuc2])


		#AlignIO.write(codon_aln, outfile, 'fasta')
	

		seq1_aligned=""
	
		for i in codon_aln[0, :]:
			seq1_aligned+=i

		seq2_aligned=""
		for i in codon_aln[1, :]:
			seq2_aligned+=i
	
	
		#print(codon_aln[0])
		#print(codon_aln[1])


		from scipy.linalg import expm
		#Calcule de divergence synonyme et non-synonyme selon LI 1985
		dN, dS = cal_dn_ds(codon_aln[0], codon_aln[1], method="ML")

		print(dN, dS)

		print("seq:",seq1dna[u].id,";",dN,";",dS,file=outfile_dn_ds)

		u+=1

	

print(divergence("concatenate_0035_fna_renamed.fst","concatenate_0042_fna_renamed.fst","concatenate_0035_faa_renamed.fst","concatenate_0042_faa_renamed.fst"))
	




```

here are the 4 files : 
[exemple.zip](https://github.com/biopython/biopython/files/1907451/exemple.zip)

**Comment by Grendel26** [comment]
yes sorry, here is the really one: 
from collections import OrderedDict
```

from Bio import codonalign
from Bio.Alphabet import IUPAC
from Bio.Align import MultipleSeqAlignment
from Bio.SeqRecord import SeqRecord
from Bio.Seq import Seq
from Bio.Alphabet import IUPAC
from Bio.Seq import Seq
from Bio.SeqRecord import SeqRecord
from Bio.Align import MultipleSeqAlignment
from Bio import AlignIO
from Bio import pairwise2
from Bio.Alphabet import generic_dna
from codonseq2 import _get_codon_list, CodonSeq, cal_dn_ds 
from Bio import SeqIO
from Bio import AlignIO
from Bio.Align.Applications import ClustalwCommandline
from Bio.Phylo.PAML import baseml, yn00
import scipy
from Bio.Phylo.PAML import baseml, yn00


from Bio import AlignIO

from Bio.Align.Applications import MuscleCommandline

from Bio import AlignIO
from Bio.Align import MultipleSeqAlignment

from Bio.Align.Applications import ClustalOmegaCommandline

from Bio.SubsMat import MatrixInfo as matlist
print(divergence("seq1_faa.fst","seq1_fna.fst","seq2.faa.fst","seq2_faa.fst"))

def divergence(fic1dna,fic2dna,fic1prot,fic2prot):

	from Bio import SeqIO
	from Bio import pairwise2
	from Bio.pairwise2 import format_alignment
	#outfile="codon_align.out"
	outfile_dn_ds="dn_ds.out"
	outfile=open(outfile,"w",encoding='utf-8')
	outfile_dn_ds=open(outfile_dn_ds,"w",encoding='utf-8')
	
	seq1dna = list(SeqIO.parse(fic1dna, "fasta",alphabet=IUPAC.IUPACUnambiguousDNA()))
	seq2dna = list(SeqIO.parse(fic2dna, "fasta",alphabet=IUPAC.IUPACUnambiguousDNA()))
	seq1prot = list(SeqIO.parse(fic1prot, "fasta",alphabet=IUPAC.protein))
	seq2prot= list(SeqIO.parse(fic2prot, "fasta",alphabet=IUPAC.protein))



	u=0
	print(len(seq1dna))
	while u < (len(seq1dna)): # make an alignment betwen each element on 2 files for 2 paires files 

		matrix = matlist.blosum62
		gap_open = -10
		gap_extend = -0.5
		
		nuc1=str(seq1dna[u].seq)
		nuc2=str(seq2dna[u].seq)
		prot1=str(seq1prot[u].seq)
		prot2=str(seq2prot[u].seq)



		nuc2 = SeqRecord(Seq(nuc2,alphabet=IUPAC.IUPACUnambiguousDNA()), id='nuc2')
		nuc1 = SeqRecord(Seq(nuc1,alphabet=IUPAC.IUPACUnambiguousDNA()), id='nuc1')

		alns = pairwise2.align.globalds(prot1 ,prot2, matrix, gap_open, gap_extend)

		
		top_aln = alns[0]

	
		prot1, prot2, score, begin, end = top_aln

		#print (prot1+'\n'+prot2)


		prot1 = SeqRecord(Seq(prot1, alphabet=IUPAC.protein),id='pro1') 
		prot2 = SeqRecord(Seq(prot2, alphabet=IUPAC.protein),id='pro2')

		aln = MultipleSeqAlignment([prot1, prot2])
		

		codon_aln = codonalign.build(aln, [nuc1, nuc2])


		#AlignIO.write(codon_aln, outfile, 'fasta')
	

		seq1_aligned=""
	
		for i in codon_aln[0, :]:
			seq1_aligned+=i

		seq2_aligned=""
		for i in codon_aln[1, :]:
			seq2_aligned+=i
	
	
		#print(codon_aln[0])
		#print(codon_aln[1])


		from scipy.linalg import expm
		#Calcule de divergence synonyme et non-synonyme selon LI 1985
		dN, dS = cal_dn_ds(codon_aln[0], codon_aln[1], method="ML")

		print(dN, dS)

		print("seq:",seq1dna[u].id,";",dN,";",dS,file=outfile_dn_ds)

		u+=1

	

print(divergence("seq1_faa.fst","seq1_fna.fst","seq2.faa.fst","seq2_faa.fst"))
	
Ps : do not pay attention to all modules I called, I use them for other things. 



```

**Comment by Grendel26** [comment]
To see the error, you have to change method="YN00" instead of ML and you will se my error. Thanks for your help.

**Comment by peterjc** [comment]
I had to comment out this line:

```python
#from codonseq2 import _get_codon_list, CodonSeq, cal_dn_ds
```

and this one near the start:
```python
#print(divergence("seq1_faa.fst","seq1_fna.fst","seq2.faa.fst","seq2_faa.fst"))
```

And uncomment this line:
```python
#outfile="codon_align.out"
```

Then I got this error:
```
$ python3 issue1611.py 
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/Bio/codonalign/__init__.py:27: BiopythonExperimentalWarning: Bio.codonalign is an experimental module which may undergo significant changes prior to its future official release.
  BiopythonExperimentalWarning)
1
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/Bio/pairwise2.py", line 982, in __call__
    return self.score_dict[(charA, charB)]
KeyError: ('P', 'a')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "issue1611.py", line 118, in <module>
    print(divergence("seq1_faa.fst","seq1_fna.fst","seq2.faa.fst","seq2_faa.fst"))
  File "issue1611.py", line 69, in divergence
    alns = pairwise2.align.globalds(prot1 ,prot2, matrix, gap_open, gap_extend)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/Bio/pairwise2.py", line 407, in __call__
    return _align(**keywds)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/Bio/pairwise2.py", line 457, in _align
    align_globally, score_only)
SystemError: <built-in function _make_score_matrix_fast> returned a result with an error set
```

This points at lower case being a possible issue, but adding ``.upper()`` didn't fix things - something else broke - but not ``ValueError: math domain error``.

Separately, I don't understand why you rebuild the ``SeqRecord`` objects here:

```python
		nuc2 = SeqRecord(Seq(nuc2,alphabet=IUPAC.IUPACUnambiguousDNA()), id='nuc2')
		nuc1 = SeqRecord(Seq(nuc1,alphabet=IUPAC.IUPACUnambiguousDNA()), id='nuc1')
```

If all you mean to do is change the ID, do this:

```
		nuc2.id = 'nuc2'
		nuc1.id = 'nuc1'
```

**Comment by Grendel26** [comment]
and what if you run this : 
```

from collections import OrderedDict

from Bio import codonalign
from Bio.Alphabet import IUPAC
from Bio.Align import MultipleSeqAlignment
from Bio.SeqRecord import SeqRecord
from Bio.Seq import Seq
from Bio.Alphabet import IUPAC
from Bio.Seq import Seq
from Bio.SeqRecord import SeqRecord
from Bio.Align import MultipleSeqAlignment
from Bio import AlignIO
from Bio import pairwise2
from Bio.Alphabet import generic_dna
from Bio import SeqIO
from Bio import AlignIO
from Bio.Align.Applications import ClustalwCommandline
from Bio.Phylo.PAML import baseml, yn00
import scipy
from Bio.Phylo.PAML import baseml, yn00
from Bio.codonalign.codonseq import _get_codon_list, CodonSeq, cal_dn_ds 


from Bio import AlignIO

from Bio.Align.Applications import MuscleCommandline

from Bio import AlignIO
from Bio.Align import MultipleSeqAlignment

from Bio.Align.Applications import ClustalOmegaCommandline

from Bio.SubsMat import MatrixInfo as matlist

def divergence(fic1dna,fic2dna,fic1prot,fic2prot):

	from Bio import SeqIO
	from Bio import pairwise2
	from Bio.pairwise2 import format_alignment
	
	
	
	seq1dna = list(SeqIO.parse(fic1dna, "fasta",alphabet=IUPAC.IUPACUnambiguousDNA()))
	seq2dna = list(SeqIO.parse(fic2dna, "fasta",alphabet=IUPAC.IUPACUnambiguousDNA()))
	seq1prot = list(SeqIO.parse(fic1prot, "fasta",alphabet=IUPAC.protein))
	seq2prot= list(SeqIO.parse(fic2prot, "fasta",alphabet=IUPAC.protein))


	u=0
	print(len(seq1dna))
	while u < (len(seq1dna)-421): # make an alignment betwen each element on 2 files for 2 paires files 

		matrix = matlist.blosum62
		gap_open = -10
		gap_extend = -0.5
		
		nuc1=str(seq1dna[u].seq)
		nuc2=str(seq2dna[u].seq)
		prot1=str(seq1prot[u].seq)
		prot2=str(seq2prot[u].seq)

		nuc2 = SeqRecord(Seq(nuc2,alphabet=IUPAC.IUPACUnambiguousDNA()), id='nuc2')
		nuc1 = SeqRecord(Seq(nuc1,alphabet=IUPAC.IUPACUnambiguousDNA()), id='nuc1')


		alns = pairwise2.align.globalds(prot1 ,prot2, matrix, gap_open, gap_extend)

		
		top_aln = alns[0]

	
		prot1, prot2, score, begin, end = top_aln

		#print (prot1+'\n'+prot2)


		prot1 = SeqRecord(Seq(prot1, alphabet=IUPAC.protein),id='pro1') 
		prot2 = SeqRecord(Seq(prot2, alphabet=IUPAC.protein),id='pro2')

		aln = MultipleSeqAlignment([prot1, prot2])
		

		codon_aln = codonalign.build(aln, [nuc1, nuc2])


		from scipy.linalg import expm



		#Calcule de divergence synonyme et non-synonyme selon LI 1985
		dN, dS = cal_dn_ds(codon_aln[0], codon_aln[1], method="YN00")


		print(dN, dS)


		u+=1
	


print(divergence("seq1_faa.fst","seq1_fna.fst","seq2.faa.fst","seq2_faa.fst"))
	

because it works for me 
```

**Comment by peterjc** [comment]
Progress 👍 

```
$ python3 new.py 
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/Bio/codonalign/__init__.py:27: BiopythonExperimentalWarning: Bio.codonalign is an experimental module which may undergo significant changes prior to its future official release.
  BiopythonExperimentalWarning)
1
None
```

That is with ``method="YN00"``, same with ``method="LWL85"``

Perhaps the version of the underlying libraries is important too, here I had the following under macOS:

```
$ python3 --version
Python 3.6.0
$ python3 -c "import numpy; print(numpy.__version__)"
1.13.1
$ python3 -c "import scipy; print(scipy.__version__)"
0.19.0
```

**Comment by Grendel26** [comment]
And you do not get any error message? because it should display the dn ds values, here it is just 1 , why? 

```
python3 -c "import numpy; print(numpy.__version__)"
1.14.2

python3 -c "import scipy; print(scipy.__version__)"
1.0.1

python3 --version
Python 3.5.0

```

**Comment by Grendel26** [comment]
How can I get the same version?

**Comment by peterjc** [comment]
Good news that your NumPy and SciPy are more up to date than mine (but that could be an important difference given the numerical nature of this calculation). Python 3.5 is a little old now, but should be fine.

**Comment by Grendel26** [comment]
OK, so what could I do to fix the situation?

**Comment by Grendel26** [comment]
ok let's wait then, thanks you very much for your help.

**Comment by zruan** [comment]
I can manage to run your code and get dn ds values using NG86, LWL85 and ML methods without any error and their dN estimates are similar. There is indeed a numerical error for YN00 in which it tries to take the log of a negative number. I attached my code and the output.

[exemple_zruan.zip](https://github.com/biopython/biopython/files/1908295/exemple_zruan.zip)

**Comment by Grendel26** [comment]
Hi. For the LWL85 it works for me as well but I have 242 sequences and for the third it displays  a math error as well.

Do you know why the value A is negative? It should not be like that is not it?
Thanks for your help 

By the way do you know which method is the best one for sequence being separated since 200000000 y.a? And for the NG86 - 1 means it is too saturated to estimate a value right?

**Comment by zruan** [comment]
The dN dS methods can only be applied to closely related sequences, especially for the counting based methods (NG86, LWL85 and YN00). These methods count the number of synonymous and non-synonymous substitutions per synonymous or non-synonymous site and then infer the rate of substitution when t->0.

If your sequences are too divergent, then the counting based methods will not be able to correctly infer the true rate of substitution, as the substitution events are saturated and there is no way to reliably estimate the correct substitution pathway for the aligned codon positions.

The NG86, LWL85 and YN00 all take different assumptions to categorize substitution events. If these assuptions are not violated, you should not receive the error. However, your sequences might undergo a complex evolutionary history and some of these assumptions are violated. For example, in the simplest Jukes-Cantor model, if the ancestor sequence is `A` at a particular position, after time `t` the probability of observing the position being a `G` is `1/4-1/4*exp(-4at)`, where `a` is the substitution rate. Therefore, according to the model, you are never expected to observe the `A` to `G` substitutions with a frequency more than 0.25. If the frequency of observing a `G` is 0.5 for example by counting your input sequences, then this method will fail.

The Maximum-Likelihood is the best method to estimate dN and dS, as it uses all the information to come up with the MLEs. However, it is much slower and won't give you a reliable estimate if the substitutions are saturated. But it is the most robust one.

**Comment by Grendel26** [comment]
Allright, i got it, I wil use the ML method, I think it is the best method for my situation indeed. And what if I would like to only desplay a threshold if the dS value is for exemple above 10, could I display 9.999 for exemple instead of the mathematic error? 

And I guess it is the same problem for the LPB93 method as the counting based methods above is not it?

Anyway thank you both for taking the time to help me, it was really nice of you.

**Comment by zruan** [comment]
The easiest way to achieve this is probably to catch the numerical error and then assign the dN and dS value of your choice.

**Comment by Grendel26** [comment]
OK I'll do it, thanks you for your help.

**Comment by Grendel26** [comment]
And last thing. Do you think it would be possible to have the LPB93 method included in the module?

**Comment by zruan** [comment]
I think I initially planned to implement the LPB93 method, but we later decide to only have the simple (NG86, LWL85) and the most sophisticated yn00 methods. Is there any particular reason that you want to have LPB93?

Also, the LPB93 and many other dN/dS methods are implemented in PAML and biopython has a wrapper for it.

**Comment by Grendel26** [comment]
Yes here they are: 
[Archive.zip](https://github.com/biopython/biopython/files/1956444/Archive.zip)

And here is my code: 
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from Bio import codonalign
from Bio.Align import MultipleSeqAlignment
from Bio.SeqRecord import SeqRecord
from Bio.Alphabet import IUPAC
from Bio.Seq import Seq
from Bio import AlignIO
from Bio import pairwise2
from Bio.codonalign.codonseq import _get_codon_list, CodonSeq, cal_dn_ds
import scipy
from Bio.Align.Applications import MuscleCommandline
from Bio.Align import MultipleSeqAlignment
from scipy.linalg import expm
from Bio import SeqIO
import sys
import numpy as np

from docopt import docopt



if len(sys.argv) < 7:
    sys.exit("Usage: python3 divergence.py <sp1.dna file> <sp2.dna file> <sp1.aa file> <sp2.aa file> <outfile name> <method> <path to muscle.exe> ")



"""Exemple of:

python3 divergence.py concatenate_0035_fna_renamed.fst concatenate_0042_fna_renamed.fst concatenate_0035_faa_renamed.fst concatenate_0042_faa_renamed.fst dn_ds.out ML /Users/etudiant/Downloads/muscle3.8.31_i86darwin64

"""
def divergence():


	fic1dna=sys.argv[1] 
	fic2dna=sys.argv[2] 
	fic1prot=sys.argv[3] 
	fic2prot=sys.argv[4] 
	

	outfile_dn_ds=sys.argv[5] 
	outfile_dn_ds=open(outfile_dn_ds,"w",encoding='utf-8')
	method=sys.argv[6]
	muscle_exe=sys.argv[7] 


	seq1dna = list(SeqIO.parse(fic1dna, "fasta",alphabet=IUPAC.IUPACUnambiguousDNA()))
	seq2dna = list(SeqIO.parse(fic2dna, "fasta",alphabet=IUPAC.IUPACUnambiguousDNA()))
	seq1prot = list(SeqIO.parse(fic1prot, "fasta",alphabet=IUPAC.protein))
	seq2prot= list(SeqIO.parse(fic2prot, "fasta",alphabet=IUPAC.protein))
	
	
	print("seq.id",";","dN",";","dS",";","Dist_third_pos",";","Dist_brute",file=outfile_dn_ds)


	print("Nombre de paires de sequences a analyser: ",len(seq1dna))

	
	u=0
	while u < (len(seq1dna)): 



		nuc1=str(seq1dna[u].seq) 
		nuc2=str(seq2dna[u].seq)
		prot1=str(seq1prot[u].seq)
		prot2=str(seq2prot[u].seq)




		protein2 = SeqRecord(Seq(prot2,alphabet=IUPAC.protein), id='protein2') 
		protein1 = SeqRecord(Seq(prot1,alphabet=IUPAC.protein), id='protein1')


		with open("outfile_unaligned.fa", "w",encoding='utf-8') as output_handle: 
			SeqIO.write(protein1, output_handle, "fasta")
			SeqIO.write(protein2, output_handle, "fasta")


		muscle_cline = MuscleCommandline(muscle_exe, input="outfile_unaligned.fa", out="outfile_aligned.aln") 
		stdout, stderr = muscle_cline()
		alns = AlignIO.read("outfile_aligned.aln", "fasta") 
		
		prot1=str(alns[0].seq) 
		prot2=str(alns[1].seq) 

		nuc2 = SeqRecord(Seq(nuc2,alphabet=IUPAC.IUPACUnambiguousDNA()), id='nuc2') 
		nuc1 = SeqRecord(Seq(nuc1,alphabet=IUPAC.IUPACUnambiguousDNA()), id='nuc1')


		prot1 = SeqRecord(Seq(prot1, alphabet=IUPAC.protein),id='pro1') 
		prot2 = SeqRecord(Seq(prot2, alphabet=IUPAC.protein),id='pro2')

		aln = MultipleSeqAlignment([prot1, prot2]) 
		

		codon_aln = codonalign.build(aln, [nuc1, nuc2]) 


		try:
        
			dN, dS = cal_dn_ds(codon_aln[0], codon_aln[1], method=method)

			print(dN, dS)
			print(seq1dna[u].id,";",dN,";",dS,";",distance_third_pos,";",distance_brute,file=outfile_dn_ds)

		except ValueError:
			result = 9.999 

			print(seq1dna[u].id,";",result,";",result,";",distance_third_pos,";",distance_brute,file=outfile_dn_ds)

		except ZeroDivisionError:
			result = 9.999
			
			print(seq1dna[u].id,";",result,";",result,";",distance_third_pos,";",distance_brute,file=outfile_dn_ds)

		except KeyError:
			result = 9.999
			
			print(seq1dna[u].id,";",result,";",result,";",distance_third_pos,";",distance_brute,file=outfile_dn_ds)

		u+=1

	outfile_dn_ds.close() 

if __name__ == '__main__':
	print(divergence())
```

**Comment by Grendel26** [comment]
Did you manage to do it with my data?

**Comment by zruan** [comment]
Sorry for the delay. I'm working on my PhD dissertation these days. I looked into your code. While I cannot run your code due to many dependency issues and internal errors, I can reproduce the dN, dS values you got (except for EOG090X005Q in which your protein and dna sequences doesn't match). For the pairs of comparison you calculate, the dN and dS estimates among different methods are consistent (You cannot trust dS > 1 as it typically indicates saturation). I also checked to use PAML package to perform the calculation and the result I got is very similar.

The YN00 method in biopython is prone to have some numerical problems compared with others. Using the yn00 program in PAML I'm able to calculate the dN and dS, but with very large uncertainties. For example, the dN and dS estimate for EOG090X002Z are numerically unstable using YN00 method in biopython. Using yn00 in PAML, I got dN=0.1282+-0.0066 and dS=3.6050+-24.0882. Obviously, the dS is unreliable. Therefore, there are some inherent problems for YN00 method if dN or dS values are large (>1).

As far as I can see, the ML method is the most robust and gives dN and dS estimates when other counting methods cannot. The estimates from ML method also produces consistent estimates with other counting methods in many cases.

**Comment by Grendel26** [comment]
Allright, thank you for your help it was really usefull and good luck for your thesis  :)

**Comment by mdehoon** [comment]
@StromTroopers 

We are adding some convenience functions to `Bio.Align`, which similar functionality as the functions provided by `Bio.pairwise2`. If you have any comments or suggestions for these convenience functions, please let us know at issue #5290.
