### ISSUE TITLE
SeqIO.write(..., 'fasta') gives error with SeqRecord description that contains only whitespace

### ISSUE THREAD

**Issue by aowi** [biopython/biopython#1624]
### Setup

I am reporting a problem with Biopython version, Python version, and operating
system as follows:

```python
import sys; print(sys.version)
import platform; print(platform.python_implementation()); print(platform.platform())
import Bio; print(Bio.__version__)
```

```
>>> import sys; print(sys.version)
3.4.3 (default, Nov 28 2017, 16:41:13) 
[GCC 4.8.4]
>>> import platform; print(platform.python_implementation()); print(platform.platform())
CPython
Linux-3.19.0-77-generic-x86_64-with-Ubuntu-14.04-trusty
>>> import Bio; print(Bio.__version__)
1.70
```

### Expected behaviour

Biopython creates my fasta file

### Actual behaviour

Biopython gives a stacktrace

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/z/datalake/virtual_envs/20180419T162906/lib/python3.4/site-packages/Bio/SeqIO/__init__.py", line 491, in write
    count = writer_class(fp).write_file(sequences)
  File "/z/datalake/virtual_envs/20180419T162906/lib/python3.4/site-packages/Bio/SeqIO/Interfaces.py", line 214, in write_file
    count = self.write_records(records)
  File "/z/datalake/virtual_envs/20180419T162906/lib/python3.4/site-packages/Bio/SeqIO/Interfaces.py", line 199, in write_records
    self.write_record(record)
  File "/z/datalake/virtual_envs/20180419T162906/lib/python3.4/site-packages/Bio/SeqIO/FastaIO.py", line 190, in write_record
    if description and description.split(None, 1)[0] == id:
IndexError: list index out of range
```

### Steps to reproduce

```
>>> from Bio import SeqIO, SeqRecord, Seq
>>> SeqIO.write([SeqRecord.SeqRecord(seq=Seq.Seq('MMMM'), id='FOO', description=' ')], '/tmp/wat.fasta', 'fasta')
```cd

**Comment by peterjc** [comment]
Wow. That code has been in use for years without anyone finding that bug - the FASTA writer does not like the description to be white space only. The short fix on your end would be to add ``.strip()`` or similar to your code where you create the record.

Or our end, I think it would be practical to do something similar - or do you actually want a trailing space in the output?

**Comment by peterjc** [comment]
That was the fix I was considering too, but I had not got as far as trying it out. Do you want to turn this into a pull request?

**Comment by aowi** [comment]
Will do.
