### ISSUE TITLE
Searching for related items in NCBI Entrez using biopython module ELink

### ISSUE THREAD

**Issue by peterhabib** [biopython/biopython#1654]
i'm new to biopython and while using ID to search for the related items it gives me error.

I am reporting a problem with biopython-1.71, Python version 3.6.5, and operating
system Ubuntu (bio-linux)

from Bio import Entrez
Entrez.email = "A.N.Other@example.com"
pmid = "19304878"
record = Entrez.read(Entrez.elink(dbfrom="pubmed", id=pmid))
record[0]["DbFrom"]
record[0]["IdList"]
len(record[0]["LinkSetDb"])
for linksetdb in record[0]["LinkSetDb"]:
    print(linksetdb["DbTo"], linksetdb["LinkName"], len(linksetdb["Link"]))

### Expected behaviour

pubmed pubmed_pubmed 162
pubmed pubmed_pubmed_alsoviewed 3
pubmed pubmed_pubmed_citedin 430
pubmed pubmed_pubmed_combined 6
pubmed pubmed_pubmed_five 6
pubmed pubmed_pubmed_refs 17
pubmed pubmed_pubmed_reviews 7
pubmed pubmed_pubmed_reviews_five 6

### Actual behaviour

Traceback (most recent call last):
  File "/home/peter/9898.py", line 4, in <module>
    record = Entrez.read(Entrez.elink(dbfrom="pubmed", id=pmid))
  File "/usr/lib/python2.7/dist-packages/Bio/Entrez/__init__.py", line 372, in read

    record = handler.read(handle)
  File "/usr/lib/python2.7/dist-packages/Bio/Entrez/Parser.py", line 187, in read
    self.parser.ParseFile(handle)
  File "/usr/lib/python2.7/dist-packages/Bio/Entrez/Parser.py", line 485, in externalEntityRefHandler
    self.dtd_urls.append(url)
UnboundLocalError: local variable 'url' referenced before assignment

### Steps to reproduce

1-copy code from biopython tutorial
2-Run

**Comment by MarkusPiotrowski** [comment]
It works fine for me:
```python
>>> from Bio import Entrez
>>> Entrez.email = "my.email@my_home.com"  # Use your e-mail here!
>>> pmid = '19304878'
>>> record = Entrez.read(Entrez.elink(dbfrom="pubmed", id=pmid))
>>> record[0]["DbFrom"]
'pubmed'
>>> record[0]['IdList']
['19304878']
>>> len(record[0]['LinkSetDb'])
8
>>> for linksetdb in record[0]['LinkSetDb']:
	print(linksetdb["DbTo"], linksetdb['LinkName'], len(linksetdb["Link"]))

	
('pubmed', 'pubmed_pubmed', 191)
('pubmed', 'pubmed_pubmed_alsoviewed', 5)
('pubmed', 'pubmed_pubmed_citedin', 538)
('pubmed', 'pubmed_pubmed_combined', 6)
('pubmed', 'pubmed_pubmed_five', 6)
('pubmed', 'pubmed_pubmed_refs', 17)
('pubmed', 'pubmed_pubmed_reviews', 8)
('pubmed', 'pubmed_pubmed_reviews_five', 6)
```
Maybe it's again a problem with the connection, maybe you can try first to establish the handle and then read the record:
```python
>>> my_handle = Entrez.elink(dbfrom='pubmed', id=pmid)
>>> record = Entrez.read(my_handle)
```

**Comment by peterhabib** [comment]
still not working for me.

**Comment by peterhabib** [comment]
This is the code what i run:

from Bio import Entrez
Entrez.email = "Beter59792@student.must.edu.eg"  # Use your e-mail here!
pmid = '19304878'
handle = Entrez.elink(dbfrom='pubmed', id=pmid)
record = Entrez.read(handle)


And this is the Error:

Traceback (most recent call last):
  File "/home/peter/9898.py", line 30, in <module>
    record = Entrez.read(Entrez.elink(dbfrom="pubmed", id=pmid))
  File "/usr/lib/python2.7/dist-packages/Bio/Entrez/__init__.py", line 372, in read

    record = handler.read(handle)
  File "/usr/lib/python2.7/dist-packages/Bio/Entrez/Parser.py", line 187, in read
    self.parser.ParseFile(handle)
  File "/usr/lib/python2.7/dist-packages/Bio/Entrez/Parser.py", line 485, in externalEntityRefHandler
    self.dtd_urls.append(url)
UnboundLocalError: local variable 'url' referenced before assignment

**Comment by MarkusPiotrowski** [comment]
@peterhabib This error can't be from that script. It says "line 30" and it references the line:
```record = Entrez.read(Entrez.elink(dbfrom="pubmed", id=pmid))``` which is not present in that script.

**Comment by peterjc** [comment]
This reminds me of an old issue #925 which also had the error message:

```
UnboundLocalError: local variable 'url' referenced before assignment
```

That was a problem in a much older version of Biopython. Can you double check the version of Biopython you are running (which may not be the Biopython 1.71 you think you are using), i.e.

```
import Bio
print(Bio.__version__)
```

**Comment by peterhabib** [comment]
@MarkusPiotrowski MarkusPiotrowski

here is the code: 
from Bio import Entrez
Entrez.email = "Beter59792@student.must.edu.eg"
pmid = "19304878"
record = Entrez.read(Entrez.elink(dbfrom="pubmed", id=pmid))
record[0]["DbFrom"]
record[0]["IdList"]
len(record[0]["LinkSetDb"])
for linksetdb in record[0]["LinkSetDb"]:
    print(linksetdb["DbTo"], linksetdb["LinkName"], len(linksetdb["Link"]))

it gives same error:

Traceback (most recent call last):
  File "/home/peter/9898.py", line 30, in <module>
    record = Entrez.read(Entrez.elink(dbfrom="pubmed", id=pmid))
  File "/usr/lib/python2.7/dist-packages/Bio/Entrez/__init__.py", line 372, in read

    record = handler.read(handle)
  File "/usr/lib/python2.7/dist-packages/Bio/Entrez/Parser.py", line 187, in read
    self.parser.ParseFile(handle)
  File "/usr/lib/python2.7/dist-packages/Bio/Entrez/Parser.py", line 485, in externalEntityRefHandler
    self.dtd_urls.append(url)
UnboundLocalError: local variable 'url' referenced before assignment

**Comment by peterhabib** [comment]
@peterjc 

running the code: 

import Bio
print(Bio.__version__)


and it gives me: 1.63
so should i update the biopython?

**Comment by peterjc** [comment]
Bingo! This does indeed seem like a duplicate of #925, and yes you should update as Biopython 1.63 was released back in 4 December 2013 and a lot has changed.

Looking at this more carefully (paths in the error messages), I suspect you have Python 2.7 with Biopython 1.63 (as the Ubuntu provided default Python), and that you also have Python 3.6.5 with Biopython 1.71, but are not using it.

**Comment by peterjc** [comment]
This might be helpful in working out where the Biopython you are using is on disk:

```
import Bio
print(Bio.__version__)
print(Bio.__file__)
```

**Comment by peterhabib** [comment]
okay so i have to update biopython and use python 3 instade. Thanks alot.

**Comment by peterjc** [comment]
Not necessarily. First run Python 3 and confirm what version of Biopython that has, it may be up to date (Biopython 1.71). If so, just use Python 3 and ignore the old Python 2 on your computer.

If it is not clear, usually each copy of Python on your system will have its own separate set of installed Python libraries (like Biopython in this case).

**Comment by peterhabib** [comment]
OK, Thank you very much.

**Comment by peterhabib** [comment]
i promise i would. Thank You :))
