### ISSUE TITLE
SeqIO unable to parse the string "<unknown description>" in the DEFINITION field for Genbank files 

### ISSUE THREAD

**Issue by arudhir** [biopython/biopython#1663]
Apologies if this is in the wrong place; what I am about to describe isn't a "problem" per se (it's not a bug), but it's unexpected behavior.

When I export a sequence as a Genbank from Geneious that has `<unknown description>` as the value for the `Definition` field, `SeqIO.read` raises `ValueError: Failed to parse the record's description`

### Setup

```3.6.5 (default, Mar 29 2018, 03:28:50) 
[GCC 5.4.0 20160609]
CPython
Linux-4.4.0-1052-aws-x86_64-with-Ubuntu-16.04-xenial
1.70
```
### Expected behaviour

I would expect `SeqIO.read` to be able to parse a Genbank file with the value `<unknown description>` in the definition field.

### Actual behaviour

`SeqIO.read` raises `ValueError: Failed to parse the record's description`

### Steps to reproduce

Use `SeqIO.read` or `SeqIO.parse` with any Genbank file that has `<unknown description>` in the DEFINITION field.

**Comment by arudhir** [comment]
Ah, sorry, apologies, after some quick testing, I found that the issue _isn't_ the "< >" characters, but is weirder.

When the DEFINITION field has the specific value `<unknown description>`, it fails.

When the value is `<unknown>`, `unknown descrip`, `unknown descriptionn`, it can read in the Genbank fine.

```
>>> SeqIO.read('1757026.gb', 'genbank')
SeqRecord(seq=Seq('TTTGCCGCCCAAAGAGCCGAACGAACTACCTTAACATTCCCTTTTAATCATCCG...GGA', IUPACAmbiguousDNA()), id='urn.local...3a-91uolpf', name='1757026', description='<unknown descriptionn>', dbxrefs=[])
```

The stacktrace is:

```
>>> SeqIO.read('1757026.gb', 'genbank')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/Bio/SeqIO/__init__.py", line 676, in read
    first = next(iterator)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/Bio/SeqIO/__init__.py", line 611, in parse
    for r in i:
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/Bio/GenBank/Scanner.py", line 494, in parse_records
    raise ValueError("Failed to parse the record's description")
ValueError: Failed to parse the record's description
```

This is the default description given by Geneious when I throw nucleotide string into it (to be precise, the default is `<unknown description>.` (with the extra period, but this also fails)

**Comment by peterjc** [comment]
OK, this is a bug in Biopython which has only been revealed now because Geneious have unfortunately picked the exact same default value that we have been using.

The bug is here, https://github.com/biopython/biopython/blob/biopython-171/Bio/GenBank/Scanner.py#L496 - this assumes that if the description (or name) have our default values after parsing the record, that parsing failed in some way.

I think the fix would be to deliberately set these initially to a flag value which cannot come from the parsing code, e.g. rather than a string, use the special Python object ``None``.

**Comment by arudhir** [comment]
Why would both `<unknown description>` and `<unknown description>.` fail in this case?

**Comment by MarkusPiotrowski** [comment]
The code strips away a trailing ```.``` so both ```<unknown description>``` and ```<unknown description>.``` become ```<unknown description>```, which triggers the exception.
```<unknown description>..``` becomes ```<unknown description>.``` which does not raise the error.

**Comment by peterjc** [comment]
To expand on Markus' answer, the trailing dot in the GenBank DE line is considered part of the file format and not part of the data itself. See #616 for more details.
