### ISSUE TITLE
test_Tutorial.py failing on Entrez chapter

### ISSUE THREAD

**Issue by peterjc** [biopython/biopython#1685]
### Setup

I am reporting a problem with Biopython version, Python version, and operating
system as follows:

```
>>> import sys; print(sys.version)
3.6.0 (v3.6.0:41df79263a11, Dec 22 2016, 17:23:13) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)]
>>> import platform; print(platform.python_implementation()); print(platform.platform())
CPython
Darwin-16.7.0-x86_64-i386-64bit
>>> import Bio; print(Bio.__version__)
1.71.dev0
```

(*Please copy and run the above in your Python, and copy-and-paste the output*)

### Expected behaviour

```
$ python3 test_Tutorial.py ; echo "Return code $?"
...
Return code 0
```

### Actual behaviour

```
$ python3 test_Tutorial.py ; echo "Return code $?"
Running Tutorial doctests...
**********************************************************************
File "test_Tutorial.py", line 239, in __main__.TutorialDocTestHolder.doctest_test_chapter_entrez_line_00066
Failed example:
    handle = Entrez.einfo()
Exception raised:
    Traceback (most recent call last):
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/doctest.py", line 1330, in __run
        compileflags, 1), test.globs)
      File "<doctest __main__.TutorialDocTestHolder.doctest_test_chapter_entrez_line_00066[4]>", line 1, in <module>
        handle = Entrez.einfo()
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/Bio/Entrez/__init__.py", line 287, in einfo
        return _open(cgi, variables)
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/Bio/Entrez/__init__.py", line 533, in _open
        raise exception
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/Bio/Entrez/__init__.py", line 531, in _open
        handle = _urlopen(cgi)
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 223, in urlopen
        return opener.open(url, data, timeout)
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 532, in open
        response = meth(req, response)
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 642, in http_response
        'http', request, response, code, msg, hdrs)
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 570, in error
        return self._call_chain(*args)
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 504, in _call_chain
        result = func(*args)
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 650, in http_error_default
        raise HTTPError(req.full_url, code, msg, hdrs, fp)
    urllib.error.HTTPError: HTTP Error 400: Bad Request
**********************************************************************
File "test_Tutorial.py", line 240, in __main__.TutorialDocTestHolder.doctest_test_chapter_entrez_line_00066
Failed example:
    result = handle.read()
Exception raised:
    Traceback (most recent call last):
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/doctest.py", line 1330, in __run
        compileflags, 1), test.globs)
      File "<doctest __main__.TutorialDocTestHolder.doctest_test_chapter_entrez_line_00066[5]>", line 1, in <module>
        result = handle.read()
    NameError: name 'handle' is not defined
**********************************************************************
File "test_Tutorial.py", line 241, in __main__.TutorialDocTestHolder.doctest_test_chapter_entrez_line_00066
Failed example:
    handle.close()
Exception raised:
    Traceback (most recent call last):
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/doctest.py", line 1330, in __run
        compileflags, 1), test.globs)
      File "<doctest __main__.TutorialDocTestHolder.doctest_test_chapter_entrez_line_00066[6]>", line 1, in <module>
        handle.close()
    NameError: name 'handle' is not defined
**********************************************************************
File "test_Tutorial.py", line 238, in __main__.TutorialDocTestHolder.doctest_test_chapter_entrez_line_00124
Failed example:
    handle = Entrez.einfo()
Exception raised:
    Traceback (most recent call last):
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/doctest.py", line 1330, in __run
        compileflags, 1), test.globs)
      File "<doctest __main__.TutorialDocTestHolder.doctest_test_chapter_entrez_line_00124[3]>", line 1, in <module>
        handle = Entrez.einfo()
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/Bio/Entrez/__init__.py", line 287, in einfo
        return _open(cgi, variables)
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/Bio/Entrez/__init__.py", line 533, in _open
        raise exception
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/Bio/Entrez/__init__.py", line 531, in _open
        handle = _urlopen(cgi)
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 223, in urlopen
        return opener.open(url, data, timeout)
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 532, in open
        response = meth(req, response)
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 642, in http_response
        'http', request, response, code, msg, hdrs)
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 570, in error
        return self._call_chain(*args)
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 504, in _call_chain
        result = func(*args)
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 650, in http_error_default
        raise HTTPError(req.full_url, code, msg, hdrs, fp)
    urllib.error.HTTPError: HTTP Error 400: Bad Request
**********************************************************************
...
```

i.e. ``chapter_entrez.tex`` line 66 fails with ``urllib.error.HTTPError: HTTP Error 400: Bad Request`` (and more noise after that), likewise line 124, etc.

These are trivial examples:

```python
>>> from Bio import Entrez                                                                                                                                          
>>> Entrez.email = "A.N.Other@example.com"  # Always tell NCBI who you are                                                                                          
>>> handle = Entrez.einfo()                                                                                                                                         
>>> result = handle.read()                                                                                                                                          
>>> handle.close() 
```

and:

```python
>>> from Bio import Entrez                                                                                                                                          
>>> Entrez.email = "A.N.Other@example.com"  # Always tell NCBI who you are                                                                                          
>>> handle = Entrez.einfo(db="pubmed")                                                                                                                              
>>> record = Entrez.read(handle)                                                                                                                                    
>>> record["DbInfo"]["Description"]                                                                                                                                 
'PubMed bibliographic record' 
```

### Steps to reproduce

As above. Also breaks on Python 2.7 for me.

Strangely, copy-and-pasting the doctest examples into a Python prompt everything seems fine.

The email setting does not seem to be to blame, 733d89671938ca5e89c89eadfc00163a7d34963d had no effect.

**Comment by peterjc** [comment]
Fails the same way for me using the latest code from git under Linux as well.

**Comment by peterjc** [comment]
Downgrading to Biopython 1.71 this worked, here on Linux:

```
$ python3 test_Tutorial.py ; echo "Return code $?"
Running Tutorial doctests...
Tests done
Return code 0
```

Looking over the recent history, using 898c74b802c498093921ce98e5e6938a5d6c5abf also works.

This strongly suggests the changes for Entrez API key support are to blame, i.e. #1569 and #1645 

Traced it to this change:

https://github.com/biopython/biopython/commit/d7b8b59092f470d411f243f888b1f037bb8a9c9a#diff-b038e2a5494e54dd13be8658485560d5
