### ISSUE TITLE
Support input of compressed data files in Bio.SearchIO

### ISSUE THREAD

**Issue by mmokrejs** [biopython/biopython#1686]
Hi,
  I mentioned the below on biopython's emailing list on 12 Jun 2018:

Hi,
  I just realized that SearchIO does not automatically detect compressed files on its input using file extension. Could .gz, .bz2 be supported?

```
>>> for record in SearchIO.parse('blah.xml.gz', 'blast-xml'):
...     print record.id
... 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib64/python2.7/site-packages/Bio/SearchIO/__init__.py", line 312, in parse
    generator = iterator(source_file, **kwargs)
  File "/usr/lib64/python2.7/site-packages/Bio/SearchIO/BlastIO/blast_xml.py", line 211, in __init__
    self._meta, self._fallback = self._parse_preamble()
  File "/usr/lib64/python2.7/site-packages/Bio/SearchIO/BlastIO/blast_xml.py", line 225, in _parse_preamble
    for event, elem in self.xml_iter:
  File "<string>", line 91, in next
cElementTree.ParseError: not well-formed (invalid token): line 1, column 0
>>> 
```

@peterjc wrote:

```
My feeling is a strong negative one - filenames are fragile.
However, when given a filename and we own the handle
and can therefore seek or reopen it as needed, I would
be more neutral on sniffing the filetype instead. If we are
going to do it, we should do it centrally for Bio.SeqIO,
Bio.AlignIO and Bio.SearchIO in one place - but I don't
want to rush that given my intended time frame for getting
Biopython 1.72 out before GCC BOSC 2018.
```

I worked around by

```
from Bio import SearchIO
import gzip
for record in SearchIO.parse(gzip.open(infile), 'blast-xml'):
   print record.id
```

but I think biopython could be smarter. I think filename extensions .gz and .bz2 are safe to rely-on and that relying on some file magic numbers like is more fragile and more work for you, but I do not mind.

**Comment by peterjc** [comment]
The workaround is the expected usage, which we document in the Tutorial several times for various parsers within Biopython (most of which expect a handle not a filename).

Some modules including SeqIO, AlignIO, and SearchIO accepts either a handle or a filename. In the later case we take care of opening the file in the appropriate mode (some formats are binary) and closing it. Here we _could_ also handle decompression. This should be done centrally, e.g. under ``Bio/File.py``.

GZIP etc can be determined automatically from the first few bytes ("magic numbers") which should be more robust than trusting file name extension conventions.

**Comment by bow** [comment]
Hi @mmokrejs,

Thanks for the suggestion. Unfortunately, the more I think about this, the less I am convinced this should be in SearchIO (or even Biopython) as the benefit of user-friendliness doesn't seem to be justified.

The example doing an `import gzip` is how it should be for the client script (and it is already simple enough, without too much magic). For running in the command line, without doing an explicit `import gzip`, the option of decompressing using an external tool and then piping (e.g. `zcat results.xml.gz | python script.py /dev/stdin`) is also already available. This is probably even the preferred option, since parts of the stdlib gzip and bz2 module may not be as fast as using zcat ([this is an old benchmark](http://aripollak.com/pythongzipbenchmarks/), but I have similar speedups testing on my machine with Python 2.7 and 3.6).

If we decide to support decompression by sniffing (let's not even talk about filenames as like @peterjc said, they can be anything regardless of the actual file format), we have to sniff the file for magic bytes against multiple compression schemes. This is an unecessary penalty for cases where the files are not compressed.

So in this case, I prefer to have an explicit `import gzip` or an explicit use of `zcat` in client + piping, to  implicitly decompressing the file.

**Comment by smsaladi** [comment]
FWIW, pandas automatically handles compressed files. I would advocate for their approach of adding another kwarg, say `compression`, and having that default to `infer`, but also to allow the user to specify their file format.

I've had only good experiences with this.

docs:
```
compression : {'infer', 'gzip', 'bz2', 'zip', 'xz', None}, default 'infer'
    For on-the-fly decompression of on-disk data. If 'infer' and
    `filepath_or_buffer` is path-like, then detect compression from the
    following extensions: '.gz', '.bz2', '.zip', or '.xz' (otherwise no
    decompression). If using 'zip', the ZIP file must contain only one data
    file to be read in. Set to None for no decompression.
```
https://github.com/pandas-dev/pandas/blob/v0.23.1/pandas/io/parsers.py#L225


From the source, it looks like they look at the extension as opposed to sniffing. I wonder why they went that route (and agree with @bow, @peterjc that file names can be anything). I didn't find an issue about this, but I opened one up in case there might be some useful logic there to consider for biopython.

https://github.com/pandas-dev/pandas/blob/v0.23.1/pandas/io/common.py#L238

**Comment by peterjc** [comment]
Retitled to cover SeqIO and AlignIO too.

Note this is for parsing only, not indexing, and not writing.

**Comment by peterjc** [comment]
i.e. You'd support automatic detection of gzipped files based on their content when parsing via ``Bio.SeqIO.parse(filename, ...)`` etc.

**Comment by chris-rands** [comment]
I quite like the idea for biopython to support parsing compressed files like `.gz`. The original suggestion here with `for record in SearchIO.parse(gzip.open(infile), 'blast-xml')` is not optimal since the open file handle is never closed explicitly. This is also a popular question on SO, where I suggested a solution that could be generalised (but relies on file extension currently): https://stackoverflow.com/a/52839332/6260170

**Comment by peterjc** [comment]
Right, you'd use ``gzip.open(...)`` as a context manager - hopefully that's what all our examples do?

**Comment by peterjc** [comment]
I would previously have looked at ``as_handle`` in ``Bio/File.py`` as the obvious place to do  include universal transparent support for parsing gzipped files.

@mdehoon in light of your recent refactoring of how handles/filenames are dealt with in SeqIO (having the file format specific code open the handles in the appropriate mode), do you have any suggestions on how we might best tackle this?

**Comment by chris-rands** [comment]
> Right, you'd use gzip.open(...) as a context manager - hopefully that's what all our examples do?

Yes, the example in the Tutorial is correct

**Comment by mdehoon** [comment]
@peterjc  The `SequenceIterator` class in `Bio/SeqIO/Interfaces.py` could handle this. If we do this, then I would suggest to check the magic number to confirm that the file is gzipped, instead of relying on the file extension only. There is a (small but not zero) chance that a file simply happens to start with the magic number for a particular compression scheme.

Personally I think that just using `gzip.open` as a context manager is good enough.

**Comment by peterjc** [comment]
Thanks @mdehoon - yes, the base class would make sense.
