### ISSUE TITLE
TravisCI/Tox setup fails with tox v3.1.x

### ISSUE THREAD

**Issue by peterjc** [biopython/biopython#1730]
There have been no recent changes to our TravisCI configuration but our automated tests are now failing as follows (the style stage passes, the main test stage fails):

```
$ pip install tox
Collecting tox
  Downloading https://files.pythonhosted.org/packages/dd/f7/0b8d50092548a9ce1c328dbf8eb8fcc2545786fb9bf8d73fbe5d3324b180/tox-3.1.1-py2.py3-none-any.whl (61kB)
Collecting packaging>=17.1 (from tox)
  Downloading https://files.pythonhosted.org/packages/ad/c2/b500ea05d5f9f361a562f089fc91f77ed3b4783e13a08a3daf82069b1224/packaging-17.1-py2.py3-none-any.whl
Requirement already satisfied: py<2,>=1.4.17 in /home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages (from tox) (1.5.2)
Requirement already satisfied: six<2,>=1.0.0 in /home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages (from tox) (1.11.0)
Requirement already satisfied: pluggy<1,>=0.3.0 in /home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages (from tox) (0.6.0)
Collecting virtualenv>=1.11.2 (from tox)
  Using cached https://files.pythonhosted.org/packages/b6/30/96a02b2287098b23b875bc8c2f58071c35d2efe84f747b64d523721dc2b5/virtualenv-16.0.0-py2.py3-none-any.whl
Collecting pyparsing>=2.0.2 (from packaging>=17.1->tox)
  Using cached https://files.pythonhosted.org/packages/6a/8a/718fd7d3458f9fab8e67186b00abdd345b639976bc7fb3ae722e1b026a50/pyparsing-2.2.0-py2.py3-none-any.whl
Installing collected packages: pyparsing, packaging, virtualenv, tox
Successfully installed packaging-17.1 pyparsing-2.2.0 tox-3.1.1 virtualenv-16.0.0
```

```
$ tox -c .travis-tox.ini -e $TOXENV --notest
Traceback (most recent call last):
  File "/home/travis/virtualenv/python2.7.14/bin/tox", line 11, in <module>
    sys.exit(cmdline())
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/tox/session.py", line 39, in cmdline
    main(args)
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/tox/session.py", line 44, in main
    config = prepare(args)
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/tox/session.py", line 26, in prepare
    config = parseconfig(args)
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/tox/config.py", line 246, in parseconfig
    parseini(config, inipath)
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/tox/config.py", line 975, in __init__
    config.envconfigs[name] = self.make_envconfig(name, section, reader._subs, config)
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/tox/config.py", line 1012, in make_envconfig
    res = reader.getlist(env_attr.name, sep="\n")
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/tox/config.py", line 1156, in getlist
    s = self.getstring(name, None)
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/tox/config.py", line 1218, in getstring
    x = self._replace_if_needed(x, name, replace, crossonly)
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/tox/config.py", line 1261, in _replace_if_needed
    x = self._replace(x, name=name, crossonly=crossonly)
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/tox/config.py", line 1248, in _replace
    replaced = Replacer(self, crossonly=crossonly).do_replace(value)
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/tox/config.py", line 1289, in do_replace
    expanded = substitute_once(value)
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/tox/config.py", line 1287, in substitute_once
    return self.RE_ITEM_REF.sub(self._replace_match, x)
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/tox/config.py", line 1330, in _replace_match
    return self._replace_substitution(match)
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/tox/config.py", line 1365, in _replace_substitution
    val = self._substitute_from_other_section(sub_key)
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/tox/config.py", line 1359, in _substitute_from_other_section
    raise tox.exception.ConfigError("substitution key {!r} not found".format(key))
tox.exception.ConfigError: ConfigError: substitution key 'py27' not found
```

The most recent passing build used Tox 3.0.0, while Tox 3.1.1 has broken.

From the timing, this is most likely due to the release of Tox 3.1.0 (2018-07-09) and 3.1.1 (2018-07-10), and from the release notes https://pypi.org/project/tox/#history this looks like the cause:

> Add ``ignore_basepython_conflict``, which determines whether conflicting ``basepython`` settings for environments containing default factors, such as ``py27`` or ``django18-py35``, should be ignored or result in warnings. This was a common source of misconfiguration and is rarely, if ever, desirable from a user perspective - by stephenfin (https://github.com/tox-dev/tox/issues/477)

**Comment by peterjc** [comment]
I've changed our TravisCI setup to use Tox v3.0.0 as a workaround.

Leaving issue open to resolve what it is about our configuration which Tox v3.1 does not like.

Note we do not use the ``basepython`` setting.

**Comment by peterjc** [comment]
Logged with Tox team as https://github.com/tox-dev/tox/issues/899

If this is related to the ``basepython`` settings change in Tox v3.0.0, is seems to be indirectly as we don't explicitly use that.

**Comment by peterjc** [comment]
We've updated our Tox configuration to work with this change, but in any case the Tox team have reverted this in Tox 3.1.2 as enough other projects were affected that they considered it an important regression.
