### ISSUE TITLE
`Bio.SeqIO.write` fails in Python 2 when using `io` module

### ISSUE THREAD

**Issue by althonos** [biopython/biopython#1739]
### Setup

I am reporting a problem with Biopython version, Python version, and operating
system as follows:

```python
>>> import sys; print(sys.version)
2.7.15 (default, Jun 27 2018, 13:05:28) 
[GCC 8.1.1 20180531]
>>> import platform; print(platform.python_implementation()); print(platform.platform())
CPython
Linux-4.17.8-1-ARCH-x86_64-with-glibc2.2.5
>>> import Bio; print(Bio.__version__)
1.72
```

### Expected behaviour

For a given record `r`,  `Bio.SeqIO.write(r, io.StringIO(), 'gb')` should write the record to the `StringIO`.
and `write(r, io.TextIOWrapper(gzip.open('/tmp/test.gb.gz', 'wb')), 'gb')` shoudl write the record to the gzip-compressed test file.

### Actual behaviour

Attempting to use an object from the `io` module that only accepts `unicode` will result in the following issue being raised:
```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/althonos/.local/lib/python2.7/site-packages/Bio/SeqIO/__init__.py", line 517, in write
    count = writer_class(fp).write_file(sequences)
  File "/home/althonos/.local/lib/python2.7/site-packages/Bio/SeqIO/Interfaces.py", line 237, in write_file
    count = self.write_records(records)
  File "/home/althonos/.local/lib/python2.7/site-packages/Bio/SeqIO/Interfaces.py", line 222, in write_records
    self.write_record(record)
  File "/home/althonos/.local/lib/python2.7/site-packages/Bio/SeqIO/InsdcIO.py", line 815, in write_record
    self._write_the_first_line(record)
  File "/home/althonos/.local/lib/python2.7/site-packages/Bio/SeqIO/InsdcIO.py", line 703, in _write_the_first_line
    self.handle.write(line)
TypeError: write() argument 1 must be unicode, not str
```

### Steps to reproduce

```python
#!/usr/bin/env python2

import gzip
import io
from Bio.SeqIO import read, write

rec = read('pYTK003.gb', 'genbank')

write(rec, io.StringIO(), 'genbank')      # this fails with the error above

with gzip.open('/tmp/test.gb.gz', 'w') as f:    
    write(rec, io.TextIOWrapper(f), 'genbank')  # idem
```
 where `pYTK003.gb` comes from [here](https://media.addgene.org/snapgene-media/v1.5.26-0-g82d7ad5/sequences/01/63/110163/addgene-plasmid-65110-sequence-110163.gbk).

**Comment by althonos** [comment]
> Under Python 2, with SeqIO do not use io.StringIO (which expects unicode), use StringIO.StringIO instead (which expects strings). Under Python 2, with SeqIO do not use io.StringIO (which expects unicode), use StringIO.StringIO instead (which expects strings).

Yes, but when trying to write to a compressed file, you may not have any other choice that writing in binary mode and using a `TextIOWrapper` to turn it into a text file. I'm writing my code in Python 3, so it more a question of being *past-proof*

Actually, I managed to fix the `biopython` source, so I could open a PR if you're interested. It's just a question of a `from __future__ import unicode_literals` and changing the few `str` in the code to `unicode` imported from `Bio._py3k`.

**Comment by peterjc** [comment]
So the real issue you are interested in is writing to a gzip handle, not using ``io.StringIO``? You don't need to use ``TextIOWrapper`` here though.

It reminds me of https://bugs.python.org/issue13989 which has been fixed, so this works for me on Python 2.7 and 3.6:

```
$ python3
Python 3.6.4 |Anaconda, Inc.| (default, Jan 16 2018, 12:04:33) 
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from Bio import SeqIO
>>> import gzip
>>> record = SeqIO.read("NC_005816.gb", "genbank")
>>> with gzip.open("/tmp/example.gb.gz", "wt") as handle:
...     SeqIO.write(record, handle, "genbank")
... 
1
>>> quit()
```
