### ISSUE TITLE
problem with cross links between tracks

### ISSUE THREAD

**Issue by peterhabib** [biopython/biopython#1740]
i am trying to cross link between three records as described and shown in biopython tutorial

I am reporting a problem with biopython-1.71, Python version 3.4, and operating
system Ubuntu (bio-linux)

```python
from Bio import SeqIO
A_rec = SeqIO.read("/home/peter/Desktop/OUT-DATA/NC_002703.gbk", "gb")
B_rec = SeqIO.read("/home/peter/Desktop/Sample-Data/AF323668.gbk", "gb")
C_rec = SeqIO.read("/home/peter/Desktop/OUT-DATA/NC_003212.gbk", "gb")[2587879:2625807].reverse_complement(name=True)
from reportlab.lib.colors import red, grey, orange, green, brown, blue, lightblue, purple
A_colors = [red]*5 + [grey]*7 + [orange]*2 + [grey]*2 + [orange] + [grey]*11 + [green]*4 \
    + [grey] + [green]*2 + [grey, green] + [brown]*5 + [blue]*4 + [lightblue]*5 \
    + [grey, lightblue] + [purple]*2 + [grey]

B_colors = [red]*5 + [grey]*7 + [orange]*2 + [grey]*2 + [orange] + [grey]*11 + [green]*4 \
    + [grey] + [green]*2 + [grey, green] + [brown]*5 + [blue]*4 + [lightblue]*5 \
    + [grey, lightblue] + [purple]*2 + [grey]

C_colors = [grey]*30 + [green]*5 + [brown]*4 + [blue]*2 + [grey, blue] + [lightblue]*2 \
    + [grey]*5


from Bio.Graphics import GenomeDiagram
name = "Proux Fig 6"
gd_diagram = GenomeDiagram.Diagram(name)
max_len = 0
for record, gene_colors in zip([A_rec, B_rec, C_rec], [A_colors, B_colors, C_colors]):
    max_len = max(max_len, len(record))
    gd_track_for_features = gd_diagram.new_track(1,
                                                 name=record.name,
                                                 greytrack=True,
                                                 start=0, end=len(record))
    gd_feature_set = gd_track_for_features.new_set()
    i = 0
    for feature in record.features:
        if feature.type != "gene":
            continue
        gd_feature_set.add_feature(feature, sigil="ARROW",color=gene_colors[i], label=True,name=str(i + 1),label_position="start",label_size=6, label_angle=0)
gd_diagram.draw(format="linear", pagesize='A4', fragments = 1,start = 0, end = max_len)
gd_diagram.write(name + ".pdf", "PDF")
gd_diagram.write(name + ".eps", "EPS")
gd_diagram.write(name + ".svg", "SVG")



A_vs_B = [
    (99, "Tuc2009_01", "int"),
    (33, "Tuc2009_03", "orf4"),
    (94, "Tuc2009_05", "orf6"),
    (100,"Tuc2009_06", "orf7"),
    (97, "Tuc2009_07", "orf8"),
    (98, "Tuc2009_08", "orf9"),
    (98, "Tuc2009_09", "orf10"),
    (100,"Tuc2009_10", "orf12"),
    (100,"Tuc2009_11", "orf13"),
    (94, "Tuc2009_12", "orf14"),
    (87, "Tuc2009_13", "orf15"),
    (94, "Tuc2009_14", "orf16"),
    (94, "Tuc2009_15", "orf17"),
    (88, "Tuc2009_17", "rusA"),
    (91, "Tuc2009_18", "orf20"),
    (93, "Tuc2009_19", "orf22"),
    (71, "Tuc2009_20", "orf23"),
    (51, "Tuc2009_22", "orf27"),
    (97, "Tuc2009_23", "orf28"),
    (88, "Tuc2009_24", "orf29"),
    (26, "Tuc2009_26", "orf38"),
    (19, "Tuc2009_46", "orf52"),
    (77, "Tuc2009_48", "orf54"),
    (91, "Tuc2009_49", "orf55"),
    (95, "Tuc2009_52", "orf60")]





B_vs_C = [
    (42,"orf39", "lin2581"),
    (31,"orf40", "lin2580"),
    (49,"orf41", "lin2579"), #terL
    (54,"orf42", "lin2578"), #portal
    (55,"orf43", "lin2577"), #protease
    (33,"orf44", "lin2576"), #mhp
    (51,"orf46", "lin2575"),
    (33,"orf47", "lin2574"),
    (40,"orf48", "lin2573"),
    (25,"orf49", "lin2572"),
    (50,"orf50", "lin2571"),
    (48,"orf51", "lin2570"),
    (24,"orf52", "lin2568"),
]


def get_feature(features, id, tags=["locus_tag", "gene"]):
    for f in features:
        for key in tags:
            for x in f.qualifiers.get(key, []):
                if x == id:
                    return f
    raise KeyError(id)



from Bio.Graphics.GenomeDiagram import CrossLink
from reportlab.lib import colors

for rec_X, tn_X, rec_Y, tn_Y, X_vs_Y in [(A_rec, 3, B_rec, 2, A_vs_B),(B_rec, 2, C_rec, 1, B_vs_C)]:
    track_X = gd_diagram.tracks[tn_X]
    track_Y = gd_diagram.tracks[tn_Y]
    for score, id_X, id_Y in X_vs_Y:
        feature_X = get_feature(rec_X.features, id_X)
        feature_Y = get_feature(rec_Y.features, id_Y)
        color = colors.linearlyInterpolatedColor(colors.white, colors.firebrick, 0, 100, score)
        link_xy = CrossLink((track_X, feature_X.location.start, feature_X.location.end),
                            (track_Y, feature_Y.location.start, feature_Y.location.end),
                            color, colors.lightgrey)
gd_diagram.cross_track_links.append(link_xy)
```

(*Please copy and run the above in your Python, and copy-and-paste the output*)

### Expected behaviour

give me figure like Figure 17.11 in page 285 of biopython tutorial

### Actual behaviour

```
/usr/bin/python3.4 "/home/peter/Desktop/Scripts/image relationship.py"
Traceback (most recent call last):
  File "/home/peter/Desktop/Scripts/image relationship.py", line 107, in <module>
    feature_Y = get_feature(rec_Y.features, id_Y)
  File "/home/peter/Desktop/Scripts/image relationship.py", line 95, in get_feature
    raise KeyError(id)
KeyError: 'lin2581'
```

### Steps to reproduce

1 - download records
2 - copying code from tutorial 
3 - run

**Comment by peterjc** [comment]
Does an unmodified https://github.com/biopython/biopython/blob/master/Doc/examples/Proux_et_al_2002_Figure_6.py work for you (other than adjusting the filenames)?

**Comment by peterhabib** [comment]
it gives the same error like follow:

    raise KeyError(id)
KeyError: 'lin2581'

**Comment by peterjc** [comment]
I think it is likely the NCBI have changed the GenBank files again, and that the feature annotation does not quite match up anymore - most likely something simple like renaming ``locustag`` as happened before with https://github.com/biopython/biopython/commit/8457989f090df0e304e83cabff6d8cdc1a61a88e#diff-1d459d35ff06c386cd3dc362ccc22963

Can you find the string ``lin2581`` in your downloaded GenBank file in the annotation of one of the genes?

You may find after fixing this, that the total number of features changed too in some way - a pull request updating the example would be most welcome!

**Comment by peterjc** [comment]
Did you solve this then?

**Comment by JinyuanSun** [comment]
@peterhabib It looks like you didn't download the full genbank file.

**Comment by peterjc** [comment]
Do you mean the "full" verses "minimal" GenBank file the NCBI offers?

**Comment by JinyuanSun** [comment]
Yes. By default, NCBI offers a short version of GenBank file (maybe to prevent the browser from breaking?), and in this minimal version, there is not any gene name. 
I just successfully reproduced the `KeyError: 'lin2581'` with that short version and successfully ran this piece of code with the full version.

**Comment by peterjc** [comment]
That's frustrating. Maybe we need to add URLs to the example for fetching a compatible GenBank file, or tweak the code to work with either version?

**Comment by JinyuanSun** [comment]
The short version is simply unusable:
```
LOCUS       NC_003212            3011208 bp    DNA     circular CON 13-DEC-2020
DEFINITION  Listeria innocua Clip11262, complete sequence.
ACCESSION   NC_003212
VERSION     NC_003212.1
DBLINK      BioProject: PRJNA224116
            BioSample: SAMEA3138320
            Assembly: GCF_000195795.1
KEYWORDS    RefSeq.
SOURCE      Listeria innocua Clip11262
  ORGANISM  Listeria innocua Clip11262
            Bacteria; Firmicutes; Bacilli; Bacillales; Listeriaceae; Listeria.
REFERENCE   1
  AUTHORS   Glaser,P., Frangeul,L., Buchrieser,C., Rusniok,C., Amend,A.,
            Baquero,F., Berche,P., Bloecker,H., Brandt,P., Chakraborty,T.,
            Charbit,A., Chetouani,F., Couve,E., de Daruvar,A., Dehoux,P.,
            Domann,E., Dominguez-Bernal,G., Duchaud,E., Durant,L.,
            Dussurget,O., Entian,K.D., Fsihi,H., Garcia-del Portillo,F.,
            Garrido,P., Gautier,L., Goebel,W., Gomez-Lopez,N., Hain,T.,
            Hauf,J., Jackson,D., Jones,L.M., Kaerst,U., Kreft,J., Kuhn,M.,
            Kunst,F., Kurapkat,G., Madueno,E., Maitournam,A., Vicente,J.M.,
            Ng,E., Nedjari,H., Nordsiek,G., Novella,S., de Pablos,B.,
            Perez-Diaz,J.C., Purcell,R., Remmel,B., Rose,M., Schlueter,T.,
            Simoes,N., Tierrez,A., Vazquez-Boland,J.A., Voss,H., Wehland,J. and
            Cossart,P.
  TITLE     Comparative genomics of Listeria species
  JOURNAL   Science 294 (5543), 849-852 (2001)
   PUBMED   11679669
REFERENCE   2  (bases 1 to 3011208)
  AUTHORS   Glaser,P., Frangeul,L. and Rusniok,C.
  TITLE     Direct Submission
  JOURNAL   Submitted (09-JUL-2001) Glaser P., Institut Pasteur, Genomique des
            Microorganismes Pathogenes, 25 rue du Docteur Roux, 75724 Paris
            Cedex 15, FRANCE
COMMENT     REFSEQ INFORMATION: The reference sequence is identical to
            AL592022.1.
            The annotation was added by the NCBI Prokaryotic Genome Annotation
            Pipeline (PGAP). Information about PGAP can be found here:
            https://www.ncbi.nlm.nih.gov/genome/annotation_prok/
            E-mail: pglaser@pasteur.fr
            Phone: +33 (0)1 45 68 89 96, Fax: +33 (0)1 45 68 87 86.
            
            ##Genome-Annotation-Data-START##
            Annotation Provider               :: NCBI RefSeq
            Annotation Date                   :: 12/13/2020 08:59:44
            Annotation Pipeline               :: NCBI Prokaryotic Genome
                                                 Annotation Pipeline (PGAP)
            Annotation Method                 :: Best-placed reference protein
                                                 set; GeneMarkS-2+
            Annotation Software revision      :: 5.0
            Features Annotated                :: Gene; CDS; rRNA; tRNA; ncRNA;
                                                 repeat_region
            Genes (total)                     :: 3,202
            CDSs (total)                      :: 3,113
            Genes (coding)                    :: 3,077
            CDSs (with protein)               :: 3,077
            Genes (RNA)                       :: 89
            rRNAs                             :: 6, 6, 6 (5S, 16S, 23S)
            complete rRNAs                    :: 6, 6, 6 (5S, 16S, 23S)
            tRNAs                             :: 67
            ncRNAs                            :: 4
            Pseudo Genes (total)              :: 36
            CDSs (without protein)            :: 36
            Pseudo Genes (ambiguous residues) :: 0 of 36
            Pseudo Genes (frameshifted)       :: 12 of 36
            Pseudo Genes (incomplete)         :: 21 of 36
            Pseudo Genes (internal stop)      :: 5 of 36
            Pseudo Genes (multiple problems)  :: 2 of 36
            CRISPR Arrays                     :: 1
            ##Genome-Annotation-Data-END##
            COMPLETENESS: full length.
FEATURES             Location/Qualifiers
     source          1..3011208
                     /organism="Listeria innocua Clip11262"
                     /mol_type="genomic DNA"
                     /strain="Clip11262"
                     /db_xref="taxon:272626"
CONTIG      join(AL596163.1:1..231450,AL596164.1:51..224650,
            AL596165.1:51..249050,AL596166.1:51..260050,AL596167.1:51..253050,
            AL596168.1:51..333050,AL596169.1:51..239050,AL596170.1:51..313450,
            AL596171.1:51..258650,AL596172.1:51..248050,AL596173.1:51..305050,
            AL596174.1:51..96208)
//
```
I am not familiar with Bio.Entrez package, although I believe it can get the right file.
I tried to use `datasets` as follows:
```
datasets download genome accession GCA_000195795.1 --include-gbff && unzip ncbi_dataset.zip
```
`ncbi_dataset/data/GCA_000195795.1/genomic.gbff` looks like the right GenBank file.

**Comment by JinyuanSun** [comment]
Or we can just simply remind users to check the GenBank file they downloaded.

**Comment by JinyuanSun** [comment]
@peterjc 
> That's frustrating. Maybe we need to add URLs to the example for fetching a compatible GenBank file, or tweak the code to work with either version?

Hi, Peter
I realized that using `dataset` is not a good idea, and I tried with some native Bio.Entrez:
```python
from Bio import Entrez
Entrez.email = "A.N.Other@example.com"     # Always tell NCBI who you are
handle = Entrez.esearch(db="nuccore", term="NC_003212")
gbk = Entrez.efetch(db="nuccore", id=Entrez.read(handle)["IdList"][0], rettype="gbwithparts", retmode="text")
with open("NC_003212.gbk",'w') as gbkfile:
    gbkfile.write(gbk.read())
    gbkfile.close()
```
Using this code can get the right file of `NC_003212.gbk` to produce the pic. Also, `Don't have color for NC_003212 gene 56` has complained, and seems to need to add one more color for `C_colors` to solve this issue.

**Comment by peterjc** [comment]
Yes, occasionally the NCBI update the annotation so the details and even the number of features can change - see #563. The version in ``NC_003212.1`` is the genome sequence itself, not the annotation.

It seems simplest to edit the text about downloading the files to say get the "gbwithparts" version (which includes the annotated genes), and adjust the color list as needed. Would you like to make a pull request?
