### ISSUE TITLE
biopython SeqIO.parse pukes trying to parse IMGT.dat db file

### ISSUE THREAD

**Issue by maquino1985** [biopython/biopython#1754]
### Setup

I am reporting a problem with Biopython version, Python version, and operating
system as follows:

```
3.6.4 |Anaconda, Inc.| (default, Jan 16 2018, 18:10:19) 
[GCC 7.2.0]
CPython
Linux-3.10.0-514.21.1.el7.x86_64-x86_64-with-redhat-7.3-Maipo
1.71
```

```
seq_records = SeqIO.parse(imgt_db, "imgt")

for rec in seq_records:
    pass
```

### Expected behaviour

expect: No errors

### Actual behaviour

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-34-34daf4d90dc1> in <module>()
      4 seq_records = SeqIO.parse(imgt_db, "imgt")
      5 
----> 6 for rec in seq_records:
      7     print(rec.name)

~/anaconda3/lib/python3.6/site-packages/Bio/SeqIO/__init__.py in parse(handle, format, alphabet)
    615             raise ValueError("Unknown format '%s'" % format)
    616         # This imposes some overhead... wait until we drop Python 2.4 to fix it
--> 617         for r in i:
    618             yield r
    619 

~/anaconda3/lib/python3.6/site-packages/Bio/GenBank/Scanner.py in parse_records(self, handle, do_features)
    487         # This is a generator function
    488         while True:
--> 489             record = self.parse(handle, do_features)
    490             if record is None:
    491                 break

~/anaconda3/lib/python3.6/site-packages/Bio/GenBank/Scanner.py in parse(self, handle, do_features)
    471                                     feature_cleaner=FeatureValueCleaner())
    472 
--> 473         if self.feed(handle, consumer, do_features):
    474             return consumer.data
    475         else:

~/anaconda3/lib/python3.6/site-packages/Bio/GenBank/Scanner.py in feed(self, handle, consumer, do_features)
    439         # First line and header:
    440         self._feed_first_line(consumer, self.line)
--> 441         self._feed_header_lines(consumer, self.parse_header())
    442 
    443         # Features (common to both EMBL and GenBank):

~/anaconda3/lib/python3.6/site-packages/Bio/GenBank/Scanner.py in _feed_header_lines(self, consumer, lines)
    831                     # Note could be multi-line, and end with a comma
    832                     parts = [bases.replace("-", " to ").strip() for bases in data.split(",") if bases.strip()]
--> 833                     consumer.reference_bases("(bases %s)" % "; ".join(parts))
    834             elif line_type == 'RT':
    835                 # Remove the enclosing quotes and trailing semi colon.

~/anaconda3/lib/python3.6/site-packages/Bio/GenBank/__init__.py in reference_bases(self, content)
    887             # get rid of the beginning 'bases'
    888             ref_base_info = ref_base_info[5:]
--> 889             locations = self._split_reference_locations(ref_base_info)
    890             all_locations.extend(locations)
    891         elif 'residues' in ref_base_info and 'to' in ref_base_info:

~/anaconda3/lib/python3.6/site-packages/Bio/GenBank/__init__.py in _split_reference_locations(self, location_string)
    923         new_locations = []
    924         for base_info in all_base_info:
--> 925             start, end = base_info.split('to')
    926             new_start, new_end = \
    927                 self._convert_to_python_numbers(int(start.strip()),

ValueError: too many values to unpack (expected 2)
```

### Steps to reproduce

Download imgt.dat.Z from IMGT http://www.imgt.org/download/LIGM-DB/, gunzip the file, and parse it with SeqIO as 'imgt' format.

**Comment by peterjc** [comment]
Biopython 1.72 is the current release, but does not fix this. Reproduced with:

```
$ curl -L -O http://www.imgt.org/download/LIGM-DB/imgt.dat.Z
$ uncompress imgt.dat.Z
$ python -c "from Bio import SeqIO; print([r.id for r in SeqIO.parse('imgt.dat', 'imgt')])"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/Bio/SeqIO/__init__.py", line 637, in parse
    for r in i:
  File "/Library/Python/2.7/site-packages/Bio/GenBank/Scanner.py", line 489, in parse_records
    record = self.parse(handle, do_features)
  File "/Library/Python/2.7/site-packages/Bio/GenBank/Scanner.py", line 473, in parse
    if self.feed(handle, consumer, do_features):
  File "/Library/Python/2.7/site-packages/Bio/GenBank/Scanner.py", line 441, in feed
    self._feed_header_lines(consumer, self.parse_header())
  File "/Library/Python/2.7/site-packages/Bio/GenBank/Scanner.py", line 833, in _feed_header_lines
    consumer.reference_bases("(bases %s)" % "; ".join(parts))
  File "/Library/Python/2.7/site-packages/Bio/GenBank/__init__.py", line 901, in reference_bases
    locations = self._split_reference_locations(ref_base_info)
  File "/Library/Python/2.7/site-packages/Bio/GenBank/__init__.py", line 937, in _split_reference_locations
    start, end = base_info.split('to')
ValueError: too many values to unpack
```

**Comment by maquino1985** [comment]
Thanks Peter.  I'll let the folks at IMGT know.
