### ISSUE TITLE
ProteinAnalysis should handle ambiguous amino acid codes - 

### ISSUE THREAD

**Issue by pmet007** [biopython/biopython#1863]
### Setup

I am reporting a problem with Biopython version, Python version, and operating
system as follows:

2.7.15 | packaged by conda-forge | (default, Jul 27 2018, 10:23:44) 
[GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.53)]
CPython
Darwin-18.2.0-x86_64-i386-64bit
1.72

### Expected behaviour - ProteinAnalysis should deal with ambiguous amino acid codes

from Bio.SeqUtils.ProtParam import ProteinAnalysis
ambiguous_codes = 'BZXJ'
for seq in ['AAAAAYYYLLLEE', 'AAAABYYYLLLEE']:
    analysed_seq = ProteinAnalysis(seq)
    print seq, analysed_seq.molecular_weight(), analysed_seq.isoelectric_point()

**Comment by peterjc** [comment]
You missed out the current behaviour,

```python
>>> from Bio.SeqUtils.ProtParam import ProteinAnalysis
>>> ambiguous_codes = 'BZXJ'
>>> for seq in ['AAAAAYYYLLLEE', 'AAAABYYYLLLEE']:
...     analysed_seq = ProteinAnalysis(seq)
...     print(seq, analysed_seq.molecular_weight(), analysed_seq.isoelectric_point())
... 
AAAAAYYYLLLEE 1460.6252 4.24041748046875
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/Bio/SeqUtils/__init__.py", line 435, in molecular_weight
    weight = sum(weight_table[x] for x in seq) - (len(seq) - 1) * water
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/Bio/SeqUtils/__init__.py", line 435, in <genexpr>
    weight = sum(weight_table[x] for x in seq) - (len(seq) - 1) * water
KeyError: 'B'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 3, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/Bio/SeqUtils/ProtParam.py", line 127, in molecular_weight
    return molecular_weight(self.sequence, monoisotopic=self.monoisotopic)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/Bio/SeqUtils/__init__.py", line 440, in molecular_weight
    % (e, seq_type))
ValueError: 'B' is not a valid unambiguous letter for protein
```

i.e. An explicit clear exception.

You also didn't say what behaviour you expected or would like. What would you expect from B, Z, X and J? You might argue for the mean value of aspartic acid and asparagine (D or N) be used for B (and similarly for Z and J), but is that useful for X? Would NaN be better than the current exception?

**Comment by pmet007** [comment]
Hi Peter

First - thanks for all your work on BioPython - I use it often.

I guess how ProtParam responds to ambiguous amino acids depends on what it is being used for

e.g The. Isoleucine / Leucine ambiguity  should be allowed for MW and pI estimation since it doesn’t affect the results.

If there are a limited number of ambiguities one could calculate results for all combinations and if there is significant difference warn the user.

What is significant depends on the function and use - 1% with a warning may be OK for MW, 10% is probably OK for pI since the values are a poor estimate of real pIs

Perhaps there could be a mode - strict or permissive and warnings rather than exceptions for ‘permissive'

I have a suggestion about the error message which has a double negative 'is not a valid unambiguous letter for protein’

Could it be something more obvious - e.g.  ‘Plotparams requires unambiguous protein codes. ‘B’ is an ambiguous protein code.

I just typed ‘AAAABSSSS’ into https://web.expasy.org/cgi-bin/protparam/protparam. and it didn’t die.

Cheers

Peter M



On 27/11/2018, at 12:36 AM, Peter Cock <notifications@github.com<mailto:notifications@github.com>> wrote:


You missed out the current behaviour,

>>> from Bio.SeqUtils.ProtParam import ProteinAnalysis
>>> ambiguous_codes = 'BZXJ'
>>> for seq in ['AAAAAYYYLLLEE', 'AAAABYYYLLLEE']:
...     analysed_seq = ProteinAnalysis(seq)
...     print(seq, analysed_seq.molecular_weight(), analysed_seq.isoelectric_point())
...
AAAAAYYYLLLEE 1460.6252 4.24041748046875
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/Bio/SeqUtils/__init__.py", line 435, in molecular_weight
    weight = sum(weight_table[x] for x in seq) - (len(seq) - 1) * water
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/Bio/SeqUtils/__init__.py", line 435, in <genexpr>
    weight = sum(weight_table[x] for x in seq) - (len(seq) - 1) * water
KeyError: 'B'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 3, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/Bio/SeqUtils/ProtParam.py", line 127, in molecular_weight
    return molecular_weight(self.sequence, monoisotopic=self.monoisotopic)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/Bio/SeqUtils/__init__.py", line 440, in molecular_weight
    % (e, seq_type))
ValueError: 'B' is not a valid unambiguous letter for protein

i.e. An explicit clear exception.

You also didn't say what behaviour you expected or would like. What would you expect from B, Z, X and J? You might argue for the mean value of aspartic acid and asparagine (D or N) be used for B (and similarly for Z and J), but is that useful for X? Would NaN be better than the current exception?

**Comment by peterjc** [comment]
There are several properties being calculated here. Starting with molecular weight, are you saying for B, Z and J using the mean of the two possible meanings is sensible (perhaps with a warning)? What about X?

If instead for changing the code behaviour, you wanted to submit a pull request to re-phrase the current molecular weight error message, that would be great.

**Comment by hrshitagowda** [comment]
Hi, 

I'm running into the same issue as pmet007. When I try using protparam package to calculate the molecular weight and the GRAVY score, it gives me the same error: 
for molecular weight: 
"ValueError: 'X' is not a valid unambiguous letter for protein" 
and for GRAVY score: 
"KeyError: 'U'"
Is there a fix to this? 

Thanks,
Hrshita

**Comment by peterjc** [comment]
@hrshitagowda one fix or workaround is for you remove the "X" from your sequence. What would you expect an unknown amino acid to contribute to the molecular weight? NaN is probably not going to be useful.

**Comment by cfz1998** [comment]
Hi @peterjc  
Maybe use the average weight of 20 amino acids to replace the "X"? Or just remove it?

Thank you for your reply.
