### ISSUE TITLE
Changes to Entity.py in 1.69 break residue 'renumber' scenario.

### ISSUE THREAD

**Issue by ChrisMoth** [biopython/biopython#1908]
### Setup

I am reporting a problem with Biopython version 1.69 and higher, Python versions 2.7 and 3.7, and operating system Redhat Linux 6 and 7

Prior to Biopython 1.69 our PDB residue renumbering code could renumber a residue to itself (and perhaps that is itself the bug) without causing a crash.  The new behavior clearly comes from changes in Entity.py.  Indeed, copying Entity.py from earlier version over 1.69 and higher Entity.py "solves" our problem.

You may rule that it is the calling code that is at fault.... but at least know that BioPython's crash is a side-effect of changes to Entity.py

```
import sys
from Bio.PDB import *

p = PDBParser()

print ("Ignore warnings about chain discontinuities - not relevant to our bug report")
s = p.get_structure('my2a9u','2a9u.pdb')
for r in s.get_residues():
  print (r)
  print ("Using current version of biopython, I can change the residue ID to something not already in the dictionary")
  print ("r.id = (' ',1000,' ')")
  r.id = (' ',1000,' ')
  print ("success - now back to 6")
  print ("And, I can change the residue ID back to 6")
  print ("r.id = (' ',6,' ')")
  r.id = (' ',6,' ')
  print ("success - back to 6 worked fine")
  print ("BUT - I can't change from 6 to 6")
  # This line works on BioPython Entity.py <= 1.68, but fails on 1.69 and higher
  print ("r.id = (' ',6,' ')")
  r.id = (' ',6,' ')
  # To arrive here you fixed the bug, or are using BioPython 1.68 or earlier
  print ("success - back to 6")
  sys.exit()
```

(*Please copy and run the above in your Python, and copy-and-paste the output*)

### Expected behaviour
Does not terminate

### Actual behaviour
When Biopython version >= 1.69, you get for final output
.........
BUT - I can't change from 6 to 6
r.id = (' ',6,' ')
Traceback (most recent call last):
  File "demo.py", line 21, in <module>
    r.id = (' ',6,' ')
  File "/dors/capra_lab/users/mothcw/psbadmin/anaconda3/envs/py2/lib/python2.7/site-packages/Bio/PDB/Entity.py", line 173, in id
    " this entity.".format(self._id, value, value))

ValueError: Cannot change id from `(' ', 6, ' ')` to `(' ', 6, ' ')`. The id `(' ', 6, ' ')` is already used for a sibling of this entity.

### Steps to reproduce
Make an empty directory, paste in demo.py as shown above, Download 2a9u.pdb from rcsb into that directory.  Run either python2 or 3 with:

python demo.py

**Comment by peterjc** [comment]
This sounds like the bug fixed in biopython 1.73 by this change: ff52656bd93b207ae12e008b897a9cb0548582c1 from PR #1744

Does updating to Biopython 1.73 fix things for you?

**Comment by ChrisMoth** [comment]
YES and NO sort of, and a documentation request.

1 of 3) YES: First Thank you.  I'm embarrassed to have missed this.  
Anaconda2 (we're moving to 3 ASAP) only _just_ moved to Biopython 1.73, 
and so YES I see now that the problem I reported is fixed in that bug.

2 of 3 ) NO sort of :)

In 1.68 and earlier Entity.py was much less sophisticated.  It lacked 
the "id.@setter id" function.  Now, As I move forward to 1.73, I am 
seeing this tiny 1.68-compatible demo program now fail:

--------------------------------------------------

/tmp$ cat demochain.py
import sys
from Bio.PDB import *

p = PDBParser(QUIET=True)

print ("Ignore warnings about chain discontinuities - not relevant to 
our bug report")
s = p.get_structure('my2a9u','2a9u.pdb')
for c in list(s.get_chains()):
   print ("Changing chain %s to 'X'"%c.id)
   # import pdb; pdb.set_trace()
   # Remove the chain from the parent model's dictionary - required in 
Biopython 1.68 and earlier
   del c.get_parent().child_dict[c.id]
*  # Crash with Biopython 1.73, OK with Biopython Entity.py 1.68**
**  c.id ='X'*
   c.get_parent().child_dict[c.id] = c

   print ("Success")
   sys.exit(0)
--------------------------------------------------

Naturally, you will ask, "Why on earth is that del line in there?  
Please get rid of that for 1.73, as the new id,@setter function handles 
this!".

However, as I sleuthed the crashing 1.73 Entity.py code, I concluded 
that it might be good defensive programing for you to check that 
self._id is in the child_dict before "del"ing it there (Though that 
makes for trouble for the class instance, from the unknown state of 
child_list)

Please consider insert the test I comment below with ### and the <<<<<<

    @id.setter

     def id(self, value):
         """Change the id of this entity.

         This will update the child_dict of this entity's parent
         and invalidate all cached full ids involving this entity.

         @raises: ValueError
         """
         if value == self._id:
             return
         if self.parent:
             if value in self.parent.child_dict:
                 raise ValueError(
                               "Cannot change id from `{}` to `{}`. "
                               "The id `{}` is already used for a 
sibling of"
                               " this entity.".format(self._id, value, 
value))

              ### NEXT, PLEASE TEST THAT self._id is, in fact in that 
parent dictionary before you del it - just to be CAREFUL ###

             if self.parent.has_id(self._id): <<<<< Requested NEW LINE 
OF CODE
               del self.parent.child_dict[self._id] <<<<< Indented 
existing line of code
             self.parent.child_dict[value] = self

-------------------------------------------------------------------------------------------------------------------------------

Thank you for working on this with me, and for considering this tiny 
change.  The new Entity.py is welcome, and I will change my code to no 
longer manage these dictionaries.

I would imagine that others may still have some of these legacy 
constructs in their code, and your "little check" may go a long way to 
helping them.

Thanks for considering it.


*3 of 3) Documentation request*

You might want specifically document the new power of Entity.py to allow 
changes, and detect errors.

Your current documentation

http://biopython.org/DIST/docs/tutorial/Tutorial.html

says this below - and it is no longer true (because you *_do_* indeed 
_*now*_ check for existing sibling entities with same IDs.

Your documentation reads,

"To get the entity’s id, use the |get_id| method:

>>> entity.get_id()   *<<<< Actually, you now have @property.id which bears mentioning*

You can check if the entity has a child with a given id by using the 
|has_id| method:

>>> entity.has_id(entity_id)

The length of an entity is equal to its number of children:

>>> nr_children = len(entity)

I*t is possible to delete, rename, add, etc. child entities from a 
parent entity, but this does not include any sanity checks* (e.g. it is 
possible to add two residues with the same id to one chain). This really 
should be done via a nice Decorator class that includes integrity 
checking, but you can take a look at the code (Entity.py) if you want to 
use the raw interface."

**Comment by peterjc** [comment]
GitHub didn't manage to make your email formatting as readable as it might have been, but it was still clear - thank you.

1. Fixed, great. Sorry the conda-forge channel package for Biopython 1.73 took longer than expected to get updated.

2. Old script broke (tries to delete something new Biopython has now already deleted). Unfortunate but you can probably wrap the delete in a try/except of similar if you really need to support old and new Biopython here. However, the defensive check sounds sensible - could you open a new issue on that please?

3. Documentation updates - good idea. The source to what you quoted is here https://github.com/biopython/biopython/blob/master/Doc/Tutorial/chapter_pdb.tex - a pull request or again a new issue for that would be great.
