### ISSUE TITLE
test_BioSQL_MySQLdb fails under python 3.6 with MySQL 5.7

### ISSUE THREAD

**Issue by nimne** [biopython/biopython#1928]
### Setup

I am reporting a problem with Biopython version, Python version, and operating
system as follows: Python 3.6.7 (and probably all 3.x), biopython version 1.74.dev0, on linux with mysqlclient version 1.3.10.

I am running the test_BioSQL_MySQLdb against a MySQL 5.7.25 server on ubuntu linux, with whatever default configuration comes with the packages from https://dev.mysql.com/

Not sure how critical this is in light of #821

### Actual behavior
```
python3 ./Tests/run_tests.py -v test_BioSQL_MySQLdb
Python version: 3.6.7 (default, Oct 22 2018, 11:32:17) 
[GCC 8.2.0]
Operating system: posix linux
test_BioSQL_MySQLdb ... FAIL
test_SeqIO_loading (common_BioSQL.AutoSeqIOTests) ... FAIL
test_NC_000932 (common_BioSQL.ClosedLoopTest)
From GenBank file to BioSQL and back to a GenBank file, NC_000932. ... FAIL
test_NC_005816 (common_BioSQL.ClosedLoopTest)
From GenBank file to BioSQL and back to a GenBank file, NC_005816. ... ok
test_NT_019265 (common_BioSQL.ClosedLoopTest)
From GenBank file to BioSQL and back to a GenBank file, NT_019265. ... ok
test_arab1 (common_BioSQL.ClosedLoopTest)
From GenBank file to BioSQL and back to a GenBank file, arab1. ... FAIL
test_cor6_6 (common_BioSQL.ClosedLoopTest)
From GenBank file to BioSQL and back to a GenBank file, cor6_6. ... ok
test_no_ref (common_BioSQL.ClosedLoopTest)
From GenBank file to BioSQL and back to a GenBank file, noref. ... ok
test_one_of (common_BioSQL.ClosedLoopTest)
From GenBank file to BioSQL and back to a GenBank file, one_of. ... ok
test_protein_refseq2 (common_BioSQL.ClosedLoopTest)
From GenBank file to BioSQL and back to a GenBank file, protein_refseq2. ... ok
test_del_db_items (common_BioSQL.DeleteTest)
Check all associated data is deleted from an item. ... ok
test_server (common_BioSQL.DeleteTest)
Check BioSeqDatabase methods. ... ok
test_duplicate_id_load (common_BioSQL.DupLoadTest)
Make sure can't import records with same ID (in one go). ... ok
test_duplicate_load (common_BioSQL.DupLoadTest)
Make sure can't import a single record twice (in one go). ... ok
test_duplicate_load2 (common_BioSQL.DupLoadTest)
Make sure can't import a single record twice (in steps). ... ok
test_record_loading (common_BioSQL.InDepthLoadTest)
Make sure all records are correctly loaded. ... ok
test_reload (common_BioSQL.InDepthLoadTest)
Make sure can't reimport existing records. ... ok
test_seq_feature (common_BioSQL.InDepthLoadTest)
In depth check that SeqFeatures are transmitted through the db. ... ok
test_transfer (common_BioSQL.InDepthLoadTest)
Make sure can load record into another namespace. ... ok
test_load_database (common_BioSQL.LoaderTest)
Load SeqRecord objects into a BioSQL database. ... ok
test_cross_retrieval_of_items (common_BioSQL.MultiReadTest)
Test that valid ids can't be retrieved between namespaces. ... ok
test_get_db_items (common_BioSQL.MultiReadTest)
Check list, keys, length etc. ... ok
test_server (common_BioSQL.MultiReadTest)
Check BioSeqDatabase methods. ... ok
test_get_db_items (common_BioSQL.ReadTest)
Check list, keys, length etc. ... ok
test_lookup_items (common_BioSQL.ReadTest)
Test retrieval of items using various ids. ... ok
test_server (common_BioSQL.ReadTest)
Check BioSeqDatabase methods. ... ok
test_addition (common_BioSQL.SeqInterfaceTest)
Check can add DBSeq objects together. ... ok
test_convert (common_BioSQL.SeqInterfaceTest)
Check can turn a DBSeq object into a Seq or MutableSeq. ... ok
test_multiplication (common_BioSQL.SeqInterfaceTest)
Check can multiply DBSeq objects by integers. ... ok
test_record_slicing (common_BioSQL.SeqInterfaceTest)
Check that slices of DBSeqRecord are retrieved properly. ... ok
test_seq (common_BioSQL.SeqInterfaceTest)
Make sure Seqs from BioSQL implement the right interface. ... ok
test_seq_features (common_BioSQL.SeqInterfaceTest)
Check SeqFeatures of a sequence. ... ok
test_seq_record (common_BioSQL.SeqInterfaceTest)
Make sure SeqRecords from BioSQL implement the right interface. ... ok
test_seq_slicing (common_BioSQL.SeqInterfaceTest)
Check that slices of sequences are retrieved properly. ... ok
test_ambiguous_location (common_BioSQL.SwissProtUnknownPositionTest)
Loaded uniprot-xml with ambiguous location in BioSQL. ... ok
test_NC_000932 (common_BioSQL.TransferTest)
From GenBank file to BioSQL, then again to a new namespace, NC_000932. ... FAIL
test_NC_005816 (common_BioSQL.TransferTest)
From GenBank file to BioSQL, then again to a new namespace, NC_005816. ... ok
test_NT_019265 (common_BioSQL.TransferTest)
From GenBank file to BioSQL, then again to a new namespace, NT_019265. ... ok
test_arab1 (common_BioSQL.TransferTest)
From GenBank file to BioSQL, then again to a new namespace, arab1. ... FAIL
test_cor6_6 (common_BioSQL.TransferTest)
From GenBank file to BioSQL, then again to a new namespace, cor6_6. ... ok
test_no_ref (common_BioSQL.TransferTest)
From GenBank file to BioSQL, then again to a new namespace, noref. ... ok
test_one_of (common_BioSQL.TransferTest)
From GenBank file to BioSQL, then again to a new namespace, one_of. ... ok
test_protein_refseq2 (common_BioSQL.TransferTest)
From GenBank file to BioSQL, then again to a new namespace, protein_refseq2. ... ok

======================================================================
FAIL: test_SeqIO_loading (common_BioSQL.AutoSeqIOTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/nick/syncthing/git_repos/nimne_biopython/Tests/common_BioSQL.py", line 1187, in test_SeqIO_loading
    self.check('genbank', 'GenBank/arab1.gb')
  File "/home/nick/syncthing/git_repos/nimne_biopython/Tests/common_BioSQL.py", line 1122, in check
    compare_record(record, db_rec)
  File "/home/nick/syncthing/git_repos/nimne_biopython/Tests/seq_tests_common.py", line 227, in compare_record
    compare_sequence(old.seq, new.seq)
  File "/home/nick/syncthing/git_repos/nimne_biopython/Tests/seq_tests_common.py", line 153, in compare_sequence
    assert str(old) == str(new)
AssertionError

======================================================================
FAIL: test_NC_000932 (common_BioSQL.ClosedLoopTest)
From GenBank file to BioSQL and back to a GenBank file, NC_000932.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/nick/syncthing/git_repos/nimne_biopython/Tests/common_BioSQL.py", line 815, in test_NC_000932
    self.loop("GenBank/NC_000932.gb", "gb")
  File "/home/nick/syncthing/git_repos/nimne_biopython/Tests/common_BioSQL.py", line 859, in loop
    self.assertTrue(compare_records(original_records, biosql_records))
  File "/home/nick/syncthing/git_repos/nimne_biopython/Tests/seq_tests_common.py", line 311, in compare_records
    if not compare_record(old_r, new_r):
  File "/home/nick/syncthing/git_repos/nimne_biopython/Tests/seq_tests_common.py", line 227, in compare_record
    compare_sequence(old.seq, new.seq)
  File "/home/nick/syncthing/git_repos/nimne_biopython/Tests/seq_tests_common.py", line 153, in compare_sequence
    assert str(old) == str(new)
AssertionError

======================================================================
FAIL: test_arab1 (common_BioSQL.ClosedLoopTest)
From GenBank file to BioSQL and back to a GenBank file, arab1.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/nick/syncthing/git_repos/nimne_biopython/Tests/common_BioSQL.py", line 842, in test_arab1
    self.loop("GenBank/arab1.gb", "gb")
  File "/home/nick/syncthing/git_repos/nimne_biopython/Tests/common_BioSQL.py", line 859, in loop
    self.assertTrue(compare_records(original_records, biosql_records))
  File "/home/nick/syncthing/git_repos/nimne_biopython/Tests/seq_tests_common.py", line 311, in compare_records
    if not compare_record(old_r, new_r):
  File "/home/nick/syncthing/git_repos/nimne_biopython/Tests/seq_tests_common.py", line 227, in compare_record
    compare_sequence(old.seq, new.seq)
  File "/home/nick/syncthing/git_repos/nimne_biopython/Tests/seq_tests_common.py", line 153, in compare_sequence
    assert str(old) == str(new)
AssertionError

======================================================================
FAIL: test_NC_000932 (common_BioSQL.TransferTest)
From GenBank file to BioSQL, then again to a new namespace, NC_000932.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/nick/syncthing/git_repos/nimne_biopython/Tests/common_BioSQL.py", line 897, in test_NC_000932
    self.trans("GenBank/NC_000932.gb", "gb")
  File "/home/nick/syncthing/git_repos/nimne_biopython/Tests/common_BioSQL.py", line 941, in trans
    self.assertTrue(compare_records(original_records, biosql_records))
  File "/home/nick/syncthing/git_repos/nimne_biopython/Tests/seq_tests_common.py", line 311, in compare_records
    if not compare_record(old_r, new_r):
  File "/home/nick/syncthing/git_repos/nimne_biopython/Tests/seq_tests_common.py", line 227, in compare_record
    compare_sequence(old.seq, new.seq)
  File "/home/nick/syncthing/git_repos/nimne_biopython/Tests/seq_tests_common.py", line 153, in compare_sequence
    assert str(old) == str(new)
AssertionError

======================================================================
FAIL: test_arab1 (common_BioSQL.TransferTest)
From GenBank file to BioSQL, then again to a new namespace, arab1.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/nick/syncthing/git_repos/nimne_biopython/Tests/common_BioSQL.py", line 924, in test_arab1
    self.trans("GenBank/arab1.gb", "gb")
  File "/home/nick/syncthing/git_repos/nimne_biopython/Tests/common_BioSQL.py", line 941, in trans
    self.assertTrue(compare_records(original_records, biosql_records))
  File "/home/nick/syncthing/git_repos/nimne_biopython/Tests/seq_tests_common.py", line 311, in compare_records
    if not compare_record(old_r, new_r):
  File "/home/nick/syncthing/git_repos/nimne_biopython/Tests/seq_tests_common.py", line 227, in compare_record
    compare_sequence(old.seq, new.seq)
  File "/home/nick/syncthing/git_repos/nimne_biopython/Tests/seq_tests_common.py", line 153, in compare_sequence
    assert str(old) == str(new)
AssertionError

----------------------------------------------------------------------
Ran 1 test in 171.052 seconds

FAILED (failures = 1)


```

I was looking into #1882 and was unable to get the `MySQLdb` test working under python3. It doesn't look like TravisCI checks this, only `mysql-connector`.

It looks like an issue with the sequence being returned as a bytestring. Seq from file:
```
[SeqRecord(seq=Seq('AAGCTTTGCTACGATCTACATTTGGGAATGTGAGTCTCTTATTGTAACCTTAGG...CTT', IUPACAmbiguousDNA()), id='AC007323.5', name='AC007323', description='Genomic sequence for Arabidopsis thaliana BAC T25K16 from chromosome I, complete sequence', dbxrefs=[])]
```
Seq from database:
```
[DBSeqRecord(seq=DBSeq('b'AAGCTTTGCTACGATCTACATTTGGGAATGTGAGTCTCTTATTGTAACCTTA...TT'', DNAAlphabet()), id='AC007323.5', name='AC007323', description='Genomic sequence for Arabidopsis thaliana BAC T25K16 from chromosome I, complete sequence', dbxrefs=[])]
```
This means that calling `str()` on the `DBSeqRecord` object results in something like this, including the extra quotes and the 'B':
```
B'AAGCTTTGCTACGATC...TCAAAATTTCAACACGAGCACGAAGCTT'
```
Looking through `BioSeqDatabase.py` it seems like this has been fixed before for mysql.connector. Making a change [here](https://github.com/biopython/biopython/blob/b6d87a6cf414ae993a71735a4e8dd01ce24218a4/BioSQL/BioSeqDatabase.py#L650) fixes this issue:
```python
_interface_specific_adaptors = {
    # If SQL interfaces require a specific adaptor, use this to map the adaptor
    "mysql.connector": MysqlConnectorAdaptor,
    "MySQLdb": MysqlConnectorAdaptor
}
```
It's not clear if this is a change in the MySQLdb plugin or if this is a result of how Python3 handles strings / bytestrings. Is this the right way to go about it? Passes TracisCI on my fork, but I'm not sure if there is a better option.

**Comment by peterjc** [comment]
Which version of MySQLdb did you install, and how? I though it wasn't available on Python 3, and that's what we have written in the README file still:

> * MySQL Connector/Python, see http://dev.mysql.com/downloads/connector/python/ This package is used by BioSQL to access a MySQL database, and is supported on Python 2 and 3 and PyPy too.
> * MySQLdb, see http://sourceforge.net/projects/mysql-python (optional) This is an older alternative package used by BioSQL to access a MySQL database, but it is not available for Python 3 or PyPy.

https://github.com/biopython/biopython/blob/biopython-173/README.rst

**Comment by peterjc** [comment]
I think your proposed fix is correct BTW.

**Comment by nimne** [comment]
Ha, I was so curious as to why my test suite started to fail after setting up `biosql.ini` that I didn't check the readme!

It looks like the package that I have is called `mysqlclient` ([pypi link](https://pypi.org/project/mysqlclient/), [github link](https://github.com/PyMySQL/mysqlclient-python)) and I installed it through pip. It's not quite a compatibility layer, but a MySQLdb rewrite. I probably installed this for some other project, and it 'just worked' when I tried running the tests.

```
$ python3 ./Tests/run_tests.py test_BioSQL_MySQLdb
Python version: 3.6.7 (default, Oct 22 2018, 11:32:17) 
[GCC 8.2.0]
Operating system: posix linux
test_BioSQL_MySQLdb ... skipping. Install MySQLdb if you want to use mysql with BioSQL 
----------------------------------------------------------------------
Ran 1 test in 0.090 seconds
```
```
$ python3 -m pip install mysqlclient
```
```
$ python3 ./Tests/run_tests.py test_BioSQL_MySQLdb
Python version: 3.6.7 (default, Oct 22 2018, 11:32:17) 
[GCC 8.2.0]
Operating system: posix linux
test_BioSQL_MySQLdb ... ok
----------------------------------------------------------------------
Ran 1 test in 200.330 seconds
```
Should I submit a PR with this change, ignore this test on Python3, or something else?

**Comment by peterjc** [comment]
So it looks like a Python 3 fork of a Python 2 only GitHub fork of the Python 2 only SourceForge project. Curious.

I think a pull request with this fix is a good idea, perhaps also adding ``mysqlclient`` to the dependencies installed on one of the Python 3 targets in ``.tox-travis.ini`` as well?

Do you think we should still go ahead and deprecate support for MySQLdb anyway as per #821?

**Comment by nimne** [comment]
I think it makes sense to keep the MySQLdb support as implemented by `mysqlclient`. It looks like `mysqlclient` is under active development, works with the current code, and it appears that it could be faster for many queries than `mysql-connector`. Although, I haven't tested this myself.

While `mysql-connector` has no additional dependencies, I don't think it makes sense to remove support for `mysqlclient` if it works with nearly no code changes.

I'll get this added to `.tox-travis.ini` and possibly add a note in the test code to read something like `Install MySQLdb or mysqlclient if you want to use mysql with BioSQL` before I submit a PR.

**Comment by nimne** [comment]
Thanks for merging #1931!
