### ISSUE TITLE
Support for esummary for database 'pccompound'

### ISSUE THREAD

**Issue by philshem** [biopython/biopython#1966]
### Setup

Python 3.7.2 in virtual environment on macOS 10.14.3
biopython==1.73
numpy==1.16.2

```python
from Bio import Entrez
handle = Entrez.esummary(db='pccompound',id='7488')
print (handle.__dict__)
record = Entrez.read(handle)

```

the handle with esummary is then a valid XML, see the URL:

https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=pccompound&id=7488&tool=biopython

### Expected behaviour

based on the [documentation](https://biopython.readthedocs.io/en/latest/Tutorial/chapter_entrez.html#esummary-retrieving-summaries-from-primary-ids), I would expect that variable `record` would be be a chemical compound object (or at least not return a parsing error)

### Actual behaviour

Output:

```
{'url': 'https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=pccompound&id=7488&tool=biopython'}
Traceback (most recent call last):
  File "debug_pubchem.py", line 5, in <module>
    record = Entrez.read(handle)
  File "/Users/philip/data/fpf/env/lib/python3.7/site-packages/Bio/Entrez/__init__.py", line 463, in read
    record = handler.read(handle)
  File "/Users/philip/data/fpf/env/lib/python3.7/site-packages/Bio/Entrez/Parser.py", line 378, in read
    self.parser.ParseFile(handle)
  File "/private/tmp/python-20190212-23618-1mc8xz1/Python-3.7.2/Modules/pyexpat.c", line 471, in EndElement
  File "/Users/philip/data/fpf/env/lib/python3.7/site-packages/Bio/Entrez/Parser.py", line 570, in endElementHandler
    value = consumer.value
  File "/Users/philip/data/fpf/env/lib/python3.7/site-packages/Bio/Entrez/Parser.py", line 252, in value
    value = int("".join(self.data))
ValueError: invalid literal for int() with base 10: ''
```

### Steps to reproduce

See the code above.

**Comment by mdehoon** [comment]
Fixed by #1968
