### ISSUE TITLE
BioSQL tests fail with psycopg2-binary==2.8 AssertionError: UniqueViolation

### ISSUE THREAD

**Issue by peterjc** [biopython/biopython#1999]
The new release psycopg2-binary==2.8 seems to have broken our BioSQL tests, noticed on #1998,

```
======================================================================
FAIL: test_duplicate_id_load (common_BioSQL.DupLoadTest)
Make sure can't import records with same ID (in one go).
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/biopython/biopython/Tests/common_BioSQL.py", line 795, in test_duplicate_id_load
    err.__class__.__name__)
AssertionError: UniqueViolation
======================================================================
FAIL: test_duplicate_load (common_BioSQL.DupLoadTest)
Make sure can't import a single record twice (in one go).
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/biopython/biopython/Tests/common_BioSQL.py", line 763, in test_duplicate_load
    err.__class__.__name__)
AssertionError: UniqueViolation
======================================================================
FAIL: test_duplicate_load2 (common_BioSQL.DupLoadTest)
Make sure can't import a single record twice (in steps).
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/biopython/biopython/Tests/common_BioSQL.py", line 779, in test_duplicate_load2
    err.__class__.__name__)
AssertionError: UniqueViolation
======================================================================
FAIL: test_reload (common_BioSQL.InDepthLoadTest)
Make sure can't reimport existing records.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/biopython/biopython/Tests/common_BioSQL.py", line 1009, in test_reload
    err.__class__.__name__)
AssertionError: UniqueViolation
----------------------------------------------------------------------
```

**Comment by peterjc** [comment]
This needs investigating, and if needed filing a bug here:
https://github.com/psycopg/psycopg2/issues

**Comment by peterjc** [comment]
More details from Python 3.6 output,

```
======================================================================
FAIL: test_duplicate_id_load (common_BioSQL.DupLoadTest)
Make sure can't import records with same ID (in one go).
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/biopython/biopython/Tests/common_BioSQL.py", line 790, in test_duplicate_id_load
    count = self.db.load([record1, record2])
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "bioentry_accession_biodatabase_id_version_key"
DETAIL:  Key (accession, biodatabase_id, version)=(TestA, 1, 0) already exists.
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/travis/build/biopython/biopython/Tests/common_BioSQL.py", line 795, in test_duplicate_id_load
    err.__class__.__name__)
AssertionError: False is not true : UniqueViolation
======================================================================
FAIL: test_duplicate_load (common_BioSQL.DupLoadTest)
Make sure can't import a single record twice (in one go).
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/biopython/biopython/Tests/common_BioSQL.py", line 755, in test_duplicate_load
    count = self.db.load([record, record])
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "bioentry_accession_biodatabase_id_version_key"
DETAIL:  Key (accession, biodatabase_id, version)=(Test1, 1, 0) already exists.
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/travis/build/biopython/biopython/Tests/common_BioSQL.py", line 763, in test_duplicate_load
    err.__class__.__name__)
AssertionError: False is not true : UniqueViolation
======================================================================
FAIL: test_duplicate_load2 (common_BioSQL.DupLoadTest)
Make sure can't import a single record twice (in steps).
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/biopython/biopython/Tests/common_BioSQL.py", line 774, in test_duplicate_load2
    count = self.db.load([record])
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "bioentry_accession_biodatabase_id_version_key"
DETAIL:  Key (accession, biodatabase_id, version)=(Test2, 1, 0) already exists.
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/travis/build/biopython/biopython/Tests/common_BioSQL.py", line 779, in test_duplicate_load2
    err.__class__.__name__)
AssertionError: False is not true : UniqueViolation
======================================================================
FAIL: test_reload (common_BioSQL.InDepthLoadTest)
Make sure can't reimport existing records.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/biopython/biopython/Tests/common_BioSQL.py", line 1004, in test_reload
    count = self.db.load([record])
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "bioentry_accession_biodatabase_id_version_key"
DETAIL:  Key (accession, biodatabase_id, version)=(X55053, 1, 1) already exists.
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/travis/build/biopython/biopython/Tests/common_BioSQL.py", line 1009, in test_reload
    err.__class__.__name__)
AssertionError: False is not true : UniqueViolation
----------------------------------------------------------------------
```

Apparently their ``UniqueViolation`` is new in 2.8, a subclass of ``IntegrityError``:

http://initd.org/psycopg/docs/errors.html

**Comment by peterjc** [comment]
Fixing as part of PR #1998.
