### ISSUE TITLE
Error running index_db() on a large fastq file: Duplicate key? UNIQUE constraint failed: offset_data.key

### ISSUE THREAD

**Issue by TomHarrop** [biopython/biopython#2038]
### Setup

I am reporting a problem with Biopython version, Python version, and operating
system as follows.

The script is running in a singularity container, which is set up as follows:

```python
>>> import sys; print(sys.version)
3.7.3 (default, Apr  3 2019, 05:39:12) 
[GCC 8.3.0]
>>> import platform; print(platform.python_implementation()); print(platform.platform())
CPython
Linux-3.10.0-862.11.6.el7.x86_64-x86_64-with-Ubuntu-19.04-disco
>>> import Bio; print(Bio.__version__)
1.73
```

The script is being called from a snakemake workflow, on a host configured as follows (biopython is not installed on the host):

```python
>>> import sys; print(sys.version)
3.6.3 (default, Jan  9 2018, 10:19:07) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]
>>> import platform; print(platform.python_implementation()); print(platform.platform())
CPython
Linux-3.10.0-862.11.6.el7.x86_64-x86_64-with-redhat-7.6-Maipo
```

### Expected behaviour

I'm trying to index a large fastq file with 613,974,956 records using `SeqIO.index_db()`.

### Actual behaviour

I'm getting an error about duplicate read IDs,using `index_db()`, but I'm sure there are no duplicate identifiers. I've tried replacing the standard fastq identifier (e.g. `@MG00HS20:1017:CAK56ANXX:6:1101:12529:2055 1:N:0:`) with a single integer, but the error still occurs.

```python
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/Bio/File.py", line 732, in _build_index
    con.execute("CREATE UNIQUE INDEX IF NOT EXISTS "
sqlite3.IntegrityError: UNIQUE constraint failed: offset_data.key

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Volumes/archive/deardenlab/tomharrop/projects/racon-chunks/.snakemake/scripts/tmpliab3waj.index_reads.py", line 14, in <module>
    'fastq')
  File "/usr/local/lib/python3.7/dist-packages/Bio/SeqIO/__init__.py", line 1032, in index_db
    key_function, repr)
  File "/usr/local/lib/python3.7/dist-packages/Bio/File.py", line 563, in __init__
    self._build_index()
  File "/usr/local/lib/python3.7/dist-packages/Bio/File.py", line 738, in _build_index
    raise ValueError("Duplicate key? %s" % err)
ValueError: Duplicate key? UNIQUE constraint failed: offset_data.key
```

### Steps to reproduce

```python
#!/usr/bin/env python3

from Bio import SeqIO

read_file = 'path/to/reads.fq'
db_file = 'path/to/reads.idx'

read_index = SeqIO.index_db(db_file,
                            read_file,
                            'fastq')
```

I don't know if it's relevant, but I've tried indexing the first 100,000,000 records and it worked. I don't see how to share a reproducible data set for this.

Thanks for reading!

**Comment by peterjc** [comment]
Unfortunately ``index_db`` does the indexing at the end (after scanning the entire file and extracting all the record names and offsets), and only then does SQLite3 report any name clash. We do it this way as it is faster than updating the SQLite3 index as we go along (although that way it is much easier to report any record name which is duplicated).

Do you happen to know how many records are in the file? e.g. run ``wc -l`` and divide by four. It might help in narrowing this down (e.g. strange behaviour at a 32bit integer boundary)

Does this work (or run out of memory):

```python
import sys
from Bio.SeqIO.QualityIO import FastqGeneralIterator

read_file = 'path/to/reads.fq'

all_names = set()
with open(read_file) as handle:
    for title, seq, qual in FastqGeneralIterator(handle):
        name = title.split(None, 1)[0]
        if name in all_names:
            sys.exit("Duplicate: %s" % name)
        all_names.add(name)
print("%i unique names" % len(all_names))
```

**Comment by TomHarrop** [comment]
Hi Peter, thanks a lot for the quick reply.

I've just got my original code to work on the following machine:

```python
>>> import sys; print(sys.version)
3.6.3 (default, Jan  9 2018, 10:19:07) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]
>>> import platform; print(platform.python_implementation()); print(platform.platform())
CPython
Linux-3.10.0-862.11.6.el7.x86_64-x86_64-with-redhat-7.6-Maipo
>>> import Bio; print(Bio.__version__)
1.73
```

This is the *exact same* code and files run in the same location on the same filesystem, on the same machine - just outside the `singularity` container.

Could the original error be related to a missing dependency in my `singularity` container? Does `index_db()` have any additional dependencies?

Unfortunately I need the code to work inside the container (for reproducibility), so any troubleshooting suggestions would be great. Thanks again!

**Comment by TomHarrop** [comment]
Sorry - didn't answer your question - it's 613,974,956 records.

**Comment by peterjc** [comment]
This is very strange - that you can index the exact same FASTQ file confirms there is no duplicated key.

It looks like the same version of Python 3.6.3, and of Biopython 1.73.

I wonder if there is a difference in the SQLite3 library between the singularity container and the host? Can you try these commands - I doubt they'll tell us much but it might be a clue:

```
$ sqlite3 --version # may not be present, and likely not relevant
$ python3 -c "import sqlite3; print(sqlite3.version)"   # probably always 2.6.0
```

Also worth checking, is the locale the same (I am clutching at straws a bit now, but Unicode can have strange side effects):

```
$ locale
```

Out of interest, if you build the index outside of singularity (then make the SQlite file read only if you want to), can you load the index and use it fine within singularity?

**Comment by TomHarrop** [comment]
By the way, it's **python 3.7.3** inside the container.

I'm just testing your suggestion of using the built index inside the container. I think it's working, but it's not ideal because I can't rely on running the whole workflow with other data on other systems.

Regarding the sqlite3 requirements - inside the container:

```bash
$ sqlite3 --version
bash: sqlite3: command not found
$ python3 -c "import sqlite3; print(sqlite3.version)"
2.6.0
$ locale
LANG=en_NZ.UTF-8
LANGUAGE=
LC_CTYPE="en_NZ.UTF-8"
LC_NUMERIC="en_NZ.UTF-8"
LC_TIME="en_NZ.UTF-8"
LC_COLLATE="en_NZ.UTF-8"
LC_MONETARY="en_NZ.UTF-8"
LC_MESSAGES="en_NZ.UTF-8"
LC_PAPER="en_NZ.UTF-8"
LC_NAME="en_NZ.UTF-8"
LC_ADDRESS="en_NZ.UTF-8"
LC_TELEPHONE="en_NZ.UTF-8"
LC_MEASUREMENT="en_NZ.UTF-8"
LC_IDENTIFICATION="en_NZ.UTF-8"
LC_ALL=
```

On the host:

```bash
$ sqlite3 --version
3.7.17 2013-05-20 00:56:22 118a3b35693b134d56ebd780123b7fd6f1497668
$ python3 -c "import sqlite3; print(sqlite3.version)"
2.6.0
$ locale
LANG=en_NZ.UTF-8
LC_CTYPE="en_NZ.UTF-8"
LC_NUMERIC="en_NZ.UTF-8"
LC_TIME="en_NZ.UTF-8"
LC_COLLATE="en_NZ.UTF-8"
LC_MONETARY="en_NZ.UTF-8"
LC_MESSAGES="en_NZ.UTF-8"
LC_PAPER="en_NZ.UTF-8"
LC_NAME="en_NZ.UTF-8"
LC_ADDRESS="en_NZ.UTF-8"
LC_TELEPHONE="en_NZ.UTF-8"
LC_MEASUREMENT="en_NZ.UTF-8"
LC_IDENTIFICATION="en_NZ.UTF-8"
LC_ALL=
```
I can add `sqlite3` to the container and see if that changes anything?

**Comment by peterjc** [comment]
We don't need the binary tool ``sqlite3``, although it can be useful - for example you could look at the contents of the index using it.

Thanks for spotting my misreading on Python version. So it works outside singularity with Python 3.6.3, but breaks inside singularity with Python 3.7.3 or now Python 3.7.17 - very strange.

We currently test Python 3.7.3 on Windows on AppVeyor, but don't have Python 3.7 on Linux right now via TravisCI. My main development machine has Python 3.7.2 currently.

**Comment by peterjc** [comment]
On the off chance that it helps throw some light on this, pull request #2041 updates our TravisCI configuration to use Ubuntu Xenial and include Python 3.7 in the test matrix.

**Comment by peterjc** [comment]
OK, TravisCI worked with Python 3.7.1 on Linux. This is a long shot, but could you try Python 3.7.1 (where we know the tests pass) under singularity? That would then point to a Python 3.7.x specific issue. 

Another suggestion from a colleague is to check the memory (RAM) usage on the singularity container - perhaps it runs out of memory while indexing the 600 million entries, and fails in a less than clear way?

**Comment by TomHarrop** [comment]
Thanks, I'm running tests (obviously they take a while with a file this large).

The machine has 1 TB of RAM. I'm not certain how much `index_db()` used. I was watching the PID in `top` and I would've noticed if the RAM usage came near 1 TB, but I will record it from now on.

**Comment by peterjc** [comment]
1TB or RAM feels like it should be more than enough - but I don't recall if I've personally pushed the indexing code as far as 600 million entries.

For debugging, perhaps we could just switch to building the SQLite index as we go?

https://github.com/biopython/biopython/blob/biopython-173/Bio/File.py#L670

I looked back over the history, the master branch has always had the index at the end - see adb28a3b33ac196f83cb0b4da4c15049000479b6 - but in the early branches working on this, I tried creating the index along side the empty tables themselves. I should be able to recreate that fairly easily on a branch...

**Comment by peterjc** [comment]
This change turns out to be easy enough, just uncomment these two lines in ``Bio/File.py``:

```python
        # Don't index the key column until the end (faster)
        con.execute("CREATE TABLE offset_data (key TEXT PRIMARY KEY, "
                    "offset INTEGER);")
```

https://github.com/biopython/biopython/blob/biopython-173/Bio/File.py#L670

Happily, the code to add the index at the end is already conditional so becomes a no-operation.

Fingers crossed this gives us a more informative error...

**Comment by TomHarrop** [comment]
I'm still working on testing the various python3 / biopython versions. Our computers have been busy this week.

Meanwhile, I tried changing those lines in `Bio/File.py`. Here's the traceback:

```python
Traceback (most recent call last):
  File "/path/to/tmp1e60lg5t.index_reads.py", line 37, in <module>
    'fastq')
  File "/usr/local/lib/python3.7/dist-packages/Bio/SeqIO/__init__.py", line 1032, in index_db
    key_function, repr)
  File "/usr/local/lib/python3.7/dist-packages/Bio/File.py", line 563, in __init__
    self._build_index()
  File "/usr/local/lib/python3.7/dist-packages/Bio/File.py", line 684, in _build_index
    con.execute("CREATE TABLE offset_data (key TEXT, "
sqlite3.OperationalError: table offset_data already exists
```

**Comment by TomHarrop** [comment]
I've tried the same code in some different environments. It seems to be a problem with the singularity containers. I'm also going to run 3.6.3 and 3.7.1 containers when I can get back on the machine.

- python3.6.3 on the host machine (**worked**)
- python3.6.8 via singularity (failed)
- python3.6.8 with modified `File.py` via singularity (failed)
- python3.7.3 via singularity (failed)
- python3.7.3 with modified `File.py` via singularity (failed)

I'd appreciate any other ideas you have for troubleshooting. Could it be something outside python that I need to add to the container?

According to the benchmark it only used 17.14 MB of RAM when it worked.

Everything below here is the log for each of those runs, pardon the wall of text. The script is right at the end.

./host/r1.log
```python
DEBUG:root:sys.version
DEBUG:root:3.6.3 (default, Jan  9 2018, 10:19:07) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]
DEBUG:root:sqlite3.version
DEBUG:root:2.6.0
DEBUG:root:platform.python_implementation()
DEBUG:root:CPython
DEBUG:root:platform.platform()
DEBUG:root:Linux-3.10.0-862.11.6.el7.x86_64-x86_64-with-redhat-7.6-Maipo
DEBUG:root:Bio.__version__
DEBUG:root:1.73
```

./py36/r1.log
```python
DEBUG:root:sys.version
DEBUG:root:3.6.8 (default, Apr  9 2019, 04:59:38) 
[GCC 8.3.0]
DEBUG:root:sqlite3.version
DEBUG:root:2.6.0
DEBUG:root:platform.python_implementation()
DEBUG:root:CPython
DEBUG:root:platform.platform()
DEBUG:root:Linux-3.10.0-862.11.6.el7.x86_64-x86_64-with-Ubuntu-18.10-cosmic
DEBUG:root:Bio.__version__
DEBUG:root:1.73
ERROR:root:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/Bio/File.py", line 732, in _build_index
    con.execute("CREATE UNIQUE INDEX IF NOT EXISTS "
sqlite3.IntegrityError: UNIQUE constraint failed: offset_data.key

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/path/to/index_reads.py", line 38, in <module>
    'fastq')
  File "/usr/local/lib/python3.6/dist-packages/Bio/SeqIO/__init__.py", line 1032, in index_db
    key_function, repr)
  File "/usr/local/lib/python3.6/dist-packages/Bio/File.py", line 563, in __init__
    self._build_index()
  File "/usr/local/lib/python3.6/dist-packages/Bio/File.py", line 738, in _build_index
    raise ValueError("Duplicate key? %s" % err)
ValueError: Duplicate key? UNIQUE constraint failed: offset_data.key
```

./py36_mod/r1.log
```python
DEBUG:root:sys.version
DEBUG:root:3.6.8 (default, Apr  9 2019, 04:59:38) 
[GCC 8.3.0]
DEBUG:root:sqlite3.version
DEBUG:root:2.6.0
DEBUG:root:platform.python_implementation()
DEBUG:root:CPython
DEBUG:root:platform.platform()
DEBUG:root:Linux-3.10.0-862.11.6.el7.x86_64-x86_64-with-Ubuntu-18.10-cosmic
DEBUG:root:Bio.__version__
DEBUG:root:1.73
ERROR:root:
Traceback (most recent call last):
  File "/path/to/index_reads.py", line 38, in <module>
    'fastq')
  File "/usr/local/lib/python3.6/dist-packages/Bio/SeqIO/__init__.py", line 1032, in index_db
    key_function, repr)
  File "/usr/local/lib/python3.6/dist-packages/Bio/File.py", line 563, in __init__
    self._build_index()
  File "/usr/local/lib/python3.6/dist-packages/Bio/File.py", line 684, in _build_index
    con.execute("CREATE TABLE offset_data (key TEXT, "
sqlite3.OperationalError: table offset_data already exists
```

./py37/r1.log
```python
DEBUG:root:sys.version
DEBUG:root:3.7.3 (default, Apr  3 2019, 05:39:12) 
[GCC 8.3.0]
DEBUG:root:sqlite3.version
DEBUG:root:2.6.0
DEBUG:root:platform.python_implementation()
DEBUG:root:CPython
DEBUG:root:platform.platform()
DEBUG:root:Linux-3.10.0-862.11.6.el7.x86_64-x86_64-with-Ubuntu-19.04-disco
DEBUG:root:Bio.__version__
DEBUG:root:1.73
ERROR:root:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/Bio/File.py", line 732, in _build_index
    con.execute("CREATE UNIQUE INDEX IF NOT EXISTS "
sqlite3.IntegrityError: UNIQUE constraint failed: offset_data.key

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/path/to/index_reads.py", line 38, in <module>
    'fastq')
  File "/usr/local/lib/python3.7/dist-packages/Bio/SeqIO/__init__.py", line 1032, in index_db
    key_function, repr)
  File "/usr/local/lib/python3.7/dist-packages/Bio/File.py", line 563, in __init__
    self._build_index()
  File "/usr/local/lib/python3.7/dist-packages/Bio/File.py", line 738, in _build_index
    raise ValueError("Duplicate key? %s" % err)
ValueError: Duplicate key? UNIQUE constraint failed: offset_data.key
```

./py37_mod/r1.log
```python
DEBUG:root:sys.version
DEBUG:root:3.7.3 (default, Apr  3 2019, 05:39:12) 
[GCC 8.3.0]
DEBUG:root:sqlite3.version
DEBUG:root:2.6.0
DEBUG:root:platform.python_implementation()
DEBUG:root:CPython
DEBUG:root:platform.platform()
DEBUG:root:Linux-3.10.0-862.11.6.el7.x86_64-x86_64-with-Ubuntu-19.04-disco
DEBUG:root:Bio.__version__
DEBUG:root:1.73
ERROR:root:
Traceback (most recent call last):
  File "/path/to/index_reads.py", line 38, in <module>
    'fastq')
  File "/usr/local/lib/python3.7/dist-packages/Bio/SeqIO/__init__.py", line 1032, in index_db
    key_function, repr)
  File "/usr/local/lib/python3.7/dist-packages/Bio/File.py", line 563, in __init__
    self._build_index()
  File "/usr/local/lib/python3.7/dist-packages/Bio/File.py", line 684, in _build_index
    con.execute("CREATE TABLE offset_data (key TEXT, "
sqlite3.OperationalError: table offset_data already exists
```

**`index_reads.py`**
```python
#!/usr/bin/env python3

import Bio
from Bio import SeqIO
import sys
import logging
import sqlite3
import platform

# set up log
logging.basicConfig(
    filename=snakemake.log[0],
    level=logging.DEBUG)

# log environment info
logging.debug('sys.version')
logging.debug(sys.version)
logging.debug('sqlite3.version')
logging.debug(sqlite3.version)
logging.debug('platform.python_implementation()')
logging.debug(platform.python_implementation())
logging.debug('platform.platform()')
logging.debug(platform.platform())
logging.debug('Bio.__version__')
logging.debug(Bio.__version__)


read_file = snakemake.input[0]
db_file = snakemake.output[0]

try:
    read_index = SeqIO.index_db(db_file,
                                read_file,
                                'fastq')
except Exception as e:
    logging.exception('')
    raise e
```

**Comment by peterjc** [comment]
The message ``table offset_data already exists`` suggests I didn't test that one line debugging change properly. Oops. Sorry about that.

Still your work is narrowing down the problem - it is not specific to Python 3.7 but affects Python 3.6 as well, with singularity as the common factor. We do have access to singularity locally as a 'last resort' for getting tools to run on the cluster when conda fails - but I'd have to get one of our systems administrators to help setting up a test environment.

I remain rather puzzled about what is causing this cryptic failure.

**Comment by TomHarrop** [comment]
I've just got it to work on my desktop with python3.7.3 via singularity. This suggests it's machine-specific, but singularity is meant to make things portable and reproducible across systems, so I've opened a ticket on sylabs/singularity: https://github.com/sylabs/singularity/issues/3484

I think you can hold off doing any more work on this issue until I hear from them - I'll update this ticket if there's any news.

I appreciate your time and effort helping with this.

**Comment by TomHarrop** [comment]
Hi again,

I've had some help from Singularity on this. We've worked on making sure the environment is exactly the same on both computers, but the error still happens on one machine and not the other.

Do you have any suggestions for getting more logging output for the sqlite3 part of `index_db()`, such as the key that causes the issue?

The relevant part of the singularity ticket starts here: https://github.com/sylabs/singularity/issues/3484#issuecomment-490260082

Thanks,
Tom

**Comment by vsoch** [comment]
hey @peterjc I'm trying to help on the Singularity boards - I had a quick question about your suggestion to uncomment these lines:

```
        con.execute("CREATE TABLE offset_data (key TEXT PRIMARY KEY, "
                     "offset INTEGER);")
```
I did that, and it triggered a (now earlier) error that the table already exists:

```bash
ERROR:root:
Traceback (most recent call last):
  File "/index_reads.py", line 38, in <module>
    'fastq')
  File "/usr/local/lib/python3.7/site-packages/Bio/SeqIO/__init__.py", line 1073, in index_db
    key_function, repr)
  File "/usr/local/lib/python3.7/site-packages/Bio/File.py", line 609, in __init__
    self._build_index()
  File "/usr/local/lib/python3.7/site-packages/Bio/File.py", line 775, in _build_index
    con.execute("CREATE TABLE offset_data (key TEXT, "
sqlite3.OperationalError: table offset_data already exists
Traceback (most recent call last):
  File "/index_reads.py", line 41, in <module>
    raise e
  File "/index_reads.py", line 38, in <module>
    'fastq')
  File "/usr/local/lib/python3.7/site-packages/Bio/SeqIO/__init__.py", line 1073, in index_db
    key_function, repr)
  File "/usr/local/lib/python3.7/site-packages/Bio/File.py", line 609, in __init__
    self._build_index()
  File "/usr/local/lib/python3.7/site-packages/Bio/File.py", line 775, in _build_index
    con.execute("CREATE TABLE offset_data (key TEXT, "
sqlite3.OperationalError: table offset_data already exists
```
Is there another few lines that need to be commented out? Shouldn't we not have two commands to create the table? Note that this comes a bit later:

```python
        con.execute("CREATE TABLE offset_data (key TEXT, "
                    "file_number INTEGER, offset INTEGER, length INTEGER);")
```
I'm going to modify the first to create the entire table (with the index) and remove the second of this. I'm rebuilding and will post if it works or not. Here is what I'm updating the first bit to (combining the previous two):

```python
        con.execute("CREATE TABLE offset_data (key TEXT PRIMARY KEY, "
                    "file_number INTEGER, offset INTEGER, length INTEGER);")

```

**Comment by vsoch** [comment]
@peterjc could you comment on disabling PRAGMA? https://www.sqlite.org/howtocorrupt.html#_disabling_sync_using_pragmas

**Comment by peterjc** [comment]
Interesting question. That dates back to the first commit on the master branch in 2010,

adb28a3b33ac196f83cb0b4da4c15049000479b6

I'm not sure if I still have the old branches leading up to that anymore. As I recall, it was faster with no downsides in my testing at the time. However, the documentation you pointed to is clear that it can have downsides.

Have you tried commenting it out (leaving the default slower safer SQLite behaviour)?

**Comment by vsoch** [comment]
Yes we tried commenting out, I believe per @TomHarrop report it didn't make a difference. From personal running, it does slow it down quite a bit, so I'd probably have done the same thing!

Since we know it's an index error, is there some simple way to figure out what the repeated index is?

**Comment by peterjc** [comment]
That's the strange thing - from the debugging thus far, it doesn't seem to be a repeated entry in index (after all the file can be indexed outside the container), but something else which causes building the SQLite index to fail. My error message is perhaps misleading, but repeated entries are the only way I've seen this fail until now.

It should be possible to toggle between building the SQLite index at the end (current behaviour) and as the file is indexed (original prototype behaviour), but the quick edit I though would make that happen needs a little more work:

https://github.com/biopython/biopython/issues/2038#issuecomment-488245527

**Comment by vsoch** [comment]
I tried that suggestion (moving the indexing to the beginning) but I believe it just triggered the error sooner - @TomHarrop can comment! (I'm not able to reproduce his error, so I'm building the testing container recipe and then he's running where he can reproduce).

**Comment by TomHarrop** [comment]
@vsoch If you're referring to [this change](https://github.com/sylabs/singularity/issues/3484#issuecomment-491353356), the error still happened **at the end** (after all the `Inserting batch of 100 offsets...` messages). Sorry, I obviously should have mentioned that. So I suppose the indexing works, and then the error happens **after** `EOF` when it does this:

```python
EOF
END of of FastqRandomAccess __iter__
Inserting batch of 1 offsets, K00171:456:HKGMHBBXX:5:2228:31517:49247 ... K00171:456:HKGMHBBXX:5:2228:31517:49247
length of random_access_proxies is less than max_open 10
Previously indexed entries here, now should skip, finding it exists.
CREATE UNIQUE INDEX IF NOT EXISTS key_index ON offset_data(key);
We triggered the error, closing connection and proxies.
ERROR:root:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/Bio/File.py", line 877, in _build_index
    con.execute("CREATE UNIQUE INDEX IF NOT EXISTS "
sqlite3.IntegrityError: UNIQUE constraint failed: offset_data.key

## SNIP
```

I've updated the output on the original comment: https://github.com/sylabs/singularity/issues/3484#issuecomment-491632622

**Comment by vsoch** [comment]
@peterjc what can we do to print / show the offending index?

**Comment by vsoch** [comment]
hey @peterjc we are still working on this over in https://github.com/sylabs/singularity/issues/3484. Can you help with the command to figure out the index?
