### ISSUE TITLE
ZeroDivisionError in test_GraphicsGeneral.py

### ISSUE THREAD

**Issue by peterjc** [biopython/biopython#2040]
There is a long standing problem with the scatter plot test in ``test_GraphicsGeneral.py`` in that because it uses random points, sometimes they are co-linear or something, and we get a divide by zero error. This periodically triggers a false alarm in our continuous integration testing, often on a pull request for something completely unrelated which is confusing.

The test should either set a random seed (to ensure the same pseudo random numbers are used), or more simply use a fixed set of data points.

Example failure:

```
======================================================================
ERROR: test_simple_scatter_plot_1 (test_GraphicsGeneral.ComparativeTest)
Test creation of a simple ScatterPlot with one list.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/biopython/biopython/Tests/test_GraphicsGeneral.py", line 71, in test_simple_scatter_plot_1
    compare_plot.draw_to_file(output_file, "Testing Scatter Plots")
  File "/home/travis/build/biopython/biopython/build/lib.linux-x86_64-3.5/Bio/Graphics/Comparative.py", line 85, in draw_to_file
    return _write(cur_drawing, output_file, self.output_format)
  File "/home/travis/build/biopython/biopython/build/lib.linux-x86_64-3.5/Bio/Graphics/__init__.py", line 84, in _write
    return drawmethod.drawToFile(drawing, output_file)
  File "/home/travis/build/biopython/biopython/.tox/py35-cover/lib/python3.5/site-packages/reportlab/graphics/renderPDF.py", line 302, in drawToFile
    draw(d, c, 0, 0, showBoundary=showBoundary)
  File "/home/travis/build/biopython/biopython/.tox/py35-cover/lib/python3.5/site-packages/reportlab/graphics/renderPDF.py", line 29, in draw
    R.draw(renderScaledDrawing(drawing), canvas, x, y, showBoundary=showBoundary)
  File "/home/travis/build/biopython/biopython/.tox/py35-cover/lib/python3.5/site-packages/reportlab/graphics/renderbase.py", line 205, in draw
    self.drawNode(drawing)
  File "/home/travis/build/biopython/biopython/.tox/py35-cover/lib/python3.5/site-packages/reportlab/graphics/renderPDF.py", line 54, in drawNode
    self.drawNodeDispatcher(node)
  File "/home/travis/build/biopython/biopython/.tox/py35-cover/lib/python3.5/site-packages/reportlab/graphics/renderbase.py", line 286, in drawNodeDispatcher
    self.drawGroup(node)
  File "/home/travis/build/biopython/biopython/.tox/py35-cover/lib/python3.5/site-packages/reportlab/graphics/renderbase.py", line 305, in drawGroup
    node = _expandUserNode(node,canvas)
  File "/home/travis/build/biopython/biopython/.tox/py35-cover/lib/python3.5/site-packages/reportlab/graphics/renderbase.py", line 166, in _expandUserNode
    node = node.provideNode()
  File "/home/travis/build/biopython/biopython/.tox/py35-cover/lib/python3.5/site-packages/reportlab/graphics/widgetbase.py", line 151, in provideNode
    return self.draw()
  File "/home/travis/build/biopython/biopython/.tox/py35-cover/lib/python3.5/site-packages/reportlab/graphics/charts/lineplots.py", line 366, in draw
    yA.configure(self.data)
  File "/home/travis/build/biopython/biopython/.tox/py35-cover/lib/python3.5/site-packages/reportlab/graphics/charts/axes.py", line 1086, in configure
    self._configure_end()
  File "/home/travis/build/biopython/biopython/.tox/py35-cover/lib/python3.5/site-packages/reportlab/graphics/charts/axes.py", line 1089, in _configure_end
    self._calcTickmarkPositions()
  File "/home/travis/build/biopython/biopython/.tox/py35-cover/lib/python3.5/site-packages/reportlab/graphics/charts/axes.py", line 1387, in _calcTickmarkPositions
    self._tickValues = self._calcTickPositions()
  File "/home/travis/build/biopython/biopython/.tox/py35-cover/lib/python3.5/site-packages/reportlab/graphics/charts/axes.py", line 1339, in _calcTickPositions
    return self._calcStepAndTickPositions()[1]
  File "/home/travis/build/biopython/biopython/.tox/py35-cover/lib/python3.5/site-packages/reportlab/graphics/charts/axes.py", line 1326, in _calcStepAndTickPositions
    i0 = int(float(valueMin)/valueStep)
ZeroDivisionError: float division by zero
----------------------------------------------------------------------
```

**Comment by peterjc** [comment]
Closed by #2063
