### ISSUE TITLE
AppVeyor (Windows) failures from test_BioSQL_mysql_connector.py

### ISSUE THREAD

**Issue by peterjc** [biopython/biopython#2120]
Somethings has broken recently on the 32bit Python 3 Windows (AppVeyors) tests, noticed on multiple unrelated pull requests overnight (which are passing on Linux / TravisCI):

e.g. https://ci.appveyor.com/project/biopython/biopython/builds/25133972/job/5r7ld842y743gksm

```
...
test_BWA_tool ... skipping. Install bwa and correctly set the file path to the program if you want to use it from Biopython
test_BioSQL_MySQLdb ... skipping. Install MySQLdb or mysqlclient if you want to use mysql with BioSQL 
test_BioSQL_MySQLdb_online ... skipping. internet not available
test_BioSQL_mysql_connector ... FAIL
test_BioSQL_mysql_connector_online ... skipping. internet not available
test_BioSQL_psycopg2 ... ok
test_BioSQL_psycopg2_online ... skipping. internet not available
test_BioSQL_sqlite3 ... ok
test_BioSQL_sqlite3_online ... skipping. internet not available
test_CAPS ... ok
...
======================================================================
FAIL: test_SeqIO_loading (common_BioSQL.AutoSeqIOTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\projects\biopython\Tests\common_BioSQL.py", line 1168, in test_SeqIO_loading
    self.check('swiss', 'SwissProt/sp015')
  File "C:\projects\biopython\Tests\common_BioSQL.py", line 1110, in check
    compare_record(record, db_rec)
  File "C:\projects\biopython\Tests\seq_tests_common.py", line 298, in compare_record
    % (key, old.annotations[key], new.annotations[key])
AssertionError: Annotation 'sequence_version' changed by load/retrieve
Was:2.28
Now:[2.28]
======================================================================
FAIL: test_NC_000932 (common_BioSQL.ClosedLoopTest)
From GenBank file to BioSQL and back to a GenBank file, NC_000932.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\projects\biopython\Tests\common_BioSQL.py", line 802, in test_NC_000932
    self.loop("GenBank/NC_000932.gb", "gb")
  File "C:\projects\biopython\Tests\common_BioSQL.py", line 846, in loop
    self.assertTrue(compare_records(original_records, biosql_records))
  File "C:\projects\biopython\Tests\seq_tests_common.py", line 313, in compare_records
    if not compare_record(old_r, new_r):
  File "C:\projects\biopython\Tests\seq_tests_common.py", line 238, in compare_record
    if not compare_features(old.features, new.features):
  File "C:\projects\biopython\Tests\seq_tests_common.py", line 219, in compare_features
    if not compare_feature(old_f, new_f):
  File "C:\projects\biopython\Tests\seq_tests_common.py", line 148, in compare_feature
    "%s -> %s" % (old_f.qualifiers[key], new_f.qualifiers[key])
AssertionError: ['1'] -> [1]
======================================================================
FAIL: test_NC_005816 (common_BioSQL.ClosedLoopTest)
From GenBank file to BioSQL and back to a GenBank file, NC_005816.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\projects\biopython\Tests\common_BioSQL.py", line 798, in test_NC_005816
    self.loop("GenBank/NC_005816.gb", "gb")
  File "C:\projects\biopython\Tests\common_BioSQL.py", line 846, in loop
    self.assertTrue(compare_records(original_records, biosql_records))
  File "C:\projects\biopython\Tests\seq_tests_common.py", line 313, in compare_records
    if not compare_record(old_r, new_r):
  File "C:\projects\biopython\Tests\seq_tests_common.py", line 238, in compare_record
    if not compare_features(old.features, new.features):
  File "C:\projects\biopython\Tests\seq_tests_common.py", line 219, in compare_features
    if not compare_feature(old_f, new_f):
  File "C:\projects\biopython\Tests\seq_tests_common.py", line 148, in compare_feature
    "%s -> %s" % (old_f.qualifiers[key], new_f.qualifiers[key])
AssertionError: ['91001'] -> [91001]
======================================================================
FAIL: test_NT_019265 (common_BioSQL.ClosedLoopTest)
From GenBank file to BioSQL and back to a GenBank file, NT_019265.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\projects\biopython\Tests\common_BioSQL.py", line 806, in test_NT_019265
    self.loop("GenBank/NT_019265.gb", "gb")
  File "C:\projects\biopython\Tests\common_BioSQL.py", line 846, in loop
    self.assertTrue(compare_records(original_records, biosql_records))
  File "C:\projects\biopython\Tests\seq_tests_common.py", line 313, in compare_records
    if not compare_record(old_r, new_r):
  File "C:\projects\biopython\Tests\seq_tests_common.py", line 238, in compare_record
    if not compare_features(old.features, new.features):
  File "C:\projects\biopython\Tests\seq_tests_common.py", line 219, in compare_features
    if not compare_feature(old_f, new_f):
  File "C:\projects\biopython\Tests\seq_tests_common.py", line 148, in compare_feature
    "%s -> %s" % (old_f.qualifiers[key], new_f.qualifiers[key])
AssertionError: ['1'] -> [1]
======================================================================
FAIL: test_arab1 (common_BioSQL.ClosedLoopTest)
From GenBank file to BioSQL and back to a GenBank file, arab1.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\projects\biopython\Tests\common_BioSQL.py", line 829, in test_arab1
    self.loop("GenBank/arab1.gb", "gb")
  File "C:\projects\biopython\Tests\common_BioSQL.py", line 846, in loop
    self.assertTrue(compare_records(original_records, biosql_records))
  File "C:\projects\biopython\Tests\seq_tests_common.py", line 313, in compare_records
    if not compare_record(old_r, new_r):
  File "C:\projects\biopython\Tests\seq_tests_common.py", line 238, in compare_record
    if not compare_features(old.features, new.features):
  File "C:\projects\biopython\Tests\seq_tests_common.py", line 219, in compare_features
    if not compare_feature(old_f, new_f):
  File "C:\projects\biopython\Tests\seq_tests_common.py", line 148, in compare_feature
    "%s -> %s" % (old_f.qualifiers[key], new_f.qualifiers[key])
AssertionError: ['1'] -> [1]
======================================================================
FAIL: test_cor6_6 (common_BioSQL.ClosedLoopTest)
From GenBank file to BioSQL and back to a GenBank file, cor6_6.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\projects\biopython\Tests\common_BioSQL.py", line 825, in test_cor6_6
    self.loop("GenBank/cor6_6.gb", "gb")
  File "C:\projects\biopython\Tests\common_BioSQL.py", line 846, in loop
    self.assertTrue(compare_records(original_records, biosql_records))
  File "C:\projects\biopython\Tests\seq_tests_common.py", line 313, in compare_records
    if not compare_record(old_r, new_r):
  File "C:\projects\biopython\Tests\seq_tests_common.py", line 238, in compare_record
    if not compare_features(old.features, new.features):
  File "C:\projects\biopython\Tests\seq_tests_common.py", line 219, in compare_features
    if not compare_feature(old_f, new_f):
  File "C:\projects\biopython\Tests\seq_tests_common.py", line 148, in compare_feature
    "%s -> %s" % (old_f.qualifiers[key], new_f.qualifiers[key])
AssertionError: ['1'] -> [1]
======================================================================
FAIL: test_no_ref (common_BioSQL.ClosedLoopTest)
From GenBank file to BioSQL and back to a GenBank file, noref.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\projects\biopython\Tests\common_BioSQL.py", line 817, in test_no_ref
    self.loop("GenBank/noref.gb", "gb")
  File "C:\projects\biopython\Tests\common_BioSQL.py", line 846, in loop
    self.assertTrue(compare_records(original_records, biosql_records))
  File "C:\projects\biopython\Tests\seq_tests_common.py", line 313, in compare_records
    if not compare_record(old_r, new_r):
  File "C:\projects\biopython\Tests\seq_tests_common.py", line 238, in compare_record
    if not compare_features(old.features, new.features):
  File "C:\projects\biopython\Tests\seq_tests_common.py", line 219, in compare_features
    if not compare_feature(old_f, new_f):
  File "C:\projects\biopython\Tests\seq_tests_common.py", line 148, in compare_feature
    "%s -> %s" % (old_f.qualifiers[key], new_f.qualifiers[key])
AssertionError: ['16'] -> [16]
======================================================================
FAIL: test_one_of (common_BioSQL.ClosedLoopTest)
From GenBank file to BioSQL and back to a GenBank file, one_of.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\projects\biopython\Tests\common_BioSQL.py", line 821, in test_one_of
    self.loop("GenBank/one_of.gb", "gb")
  File "C:\projects\biopython\Tests\common_BioSQL.py", line 846, in loop
    self.assertTrue(compare_records(original_records, biosql_records))
  File "C:\projects\biopython\Tests\seq_tests_common.py", line 313, in compare_records
    if not compare_record(old_r, new_r):
  File "C:\projects\biopython\Tests\seq_tests_common.py", line 238, in compare_record
    if not compare_features(old.features, new.features):
  File "C:\projects\biopython\Tests\seq_tests_common.py", line 219, in compare_features
    if not compare_feature(old_f, new_f):
  File "C:\projects\biopython\Tests\seq_tests_common.py", line 148, in compare_feature
    "%s -> %s" % (old_f.qualifiers[key], new_f.qualifiers[key])
AssertionError: ['12'] -> [12]
======================================================================
FAIL: test_protein_refseq2 (common_BioSQL.ClosedLoopTest)
From GenBank file to BioSQL and back to a GenBank file, protein_refseq2.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\projects\biopython\Tests\common_BioSQL.py", line 813, in test_protein_refseq2
    self.loop("GenBank/protein_refseq2.gb", "gb")
  File "C:\projects\biopython\Tests\common_BioSQL.py", line 846, in loop
    self.assertTrue(compare_records(original_records, biosql_records))
  File "C:\projects\biopython\Tests\seq_tests_common.py", line 313, in compare_records
    if not compare_record(old_r, new_r):
  File "C:\projects\biopython\Tests\seq_tests_common.py", line 238, in compare_record
    if not compare_features(old.features, new.features):
  File "C:\projects\biopython\Tests\seq_tests_common.py", line 219, in compare_features
    if not compare_feature(old_f, new_f):
  File "C:\projects\biopython\Tests\seq_tests_common.py", line 148, in compare_feature
    "%s -> %s" % (old_f.qualifiers[key], new_f.qualifiers[key])
AssertionError: ['4'] -> [4]
======================================================================
FAIL: test_seq_feature (common_BioSQL.InDepthLoadTest)
In depth check that SeqFeatures are transmitted through the db.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\projects\biopython\Tests\common_BioSQL.py", line 1041, in test_seq_feature
    self.assertEqual(test_feature.qualifiers["codon_start"], ["2"])
AssertionError: Lists differ: [2] != ['2']
First differing element 0:
2
'2'
- [2]
+ ['2']
?  + +
======================================================================
FAIL: test_seq_features (common_BioSQL.SeqInterfaceTest)
Check SeqFeatures of a sequence.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\projects\biopython\Tests\common_BioSQL.py", line 586, in test_seq_features
    self.assertEqual(cds_feature.qualifiers["codon_start"], ["1"])
AssertionError: Lists differ: [1] != ['1']
First differing element 0:
1
'1'
- [1]
+ ['1']
?  + +
======================================================================
FAIL: test_NC_000932 (common_BioSQL.TransferTest)
From GenBank file to BioSQL, then again to a new namespace, NC_000932.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\projects\biopython\Tests\common_BioSQL.py", line 884, in test_NC_000932
    self.trans("GenBank/NC_000932.gb", "gb")
  File "C:\projects\biopython\Tests\common_BioSQL.py", line 928, in trans
    self.assertTrue(compare_records(original_records, biosql_records))
  File "C:\projects\biopython\Tests\seq_tests_common.py", line 313, in compare_records
    if not compare_record(old_r, new_r):
  File "C:\projects\biopython\Tests\seq_tests_common.py", line 238, in compare_record
    if not compare_features(old.features, new.features):
  File "C:\projects\biopython\Tests\seq_tests_common.py", line 219, in compare_features
    if not compare_feature(old_f, new_f):
  File "C:\projects\biopython\Tests\seq_tests_common.py", line 148, in compare_feature
    "%s -> %s" % (old_f.qualifiers[key], new_f.qualifiers[key])
AssertionError: ['1'] -> [1]
======================================================================
FAIL: test_NC_005816 (common_BioSQL.TransferTest)
From GenBank file to BioSQL, then again to a new namespace, NC_005816.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\projects\biopython\Tests\common_BioSQL.py", line 880, in test_NC_005816
    self.trans("GenBank/NC_005816.gb", "gb")
  File "C:\projects\biopython\Tests\common_BioSQL.py", line 928, in trans
    self.assertTrue(compare_records(original_records, biosql_records))
  File "C:\projects\biopython\Tests\seq_tests_common.py", line 313, in compare_records
    if not compare_record(old_r, new_r):
  File "C:\projects\biopython\Tests\seq_tests_common.py", line 238, in compare_record
    if not compare_features(old.features, new.features):
  File "C:\projects\biopython\Tests\seq_tests_common.py", line 219, in compare_features
    if not compare_feature(old_f, new_f):
  File "C:\projects\biopython\Tests\seq_tests_common.py", line 148, in compare_feature
    "%s -> %s" % (old_f.qualifiers[key], new_f.qualifiers[key])
AssertionError: ['91001'] -> [91001]
======================================================================
FAIL: test_NT_019265 (common_BioSQL.TransferTest)
From GenBank file to BioSQL, then again to a new namespace, NT_019265.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\projects\biopython\Tests\common_BioSQL.py", line 888, in test_NT_019265
    self.trans("GenBank/NT_019265.gb", "gb")
  File "C:\projects\biopython\Tests\common_BioSQL.py", line 928, in trans
    self.assertTrue(compare_records(original_records, biosql_records))
  File "C:\projects\biopython\Tests\seq_tests_common.py", line 313, in compare_records
    if not compare_record(old_r, new_r):
  File "C:\projects\biopython\Tests\seq_tests_common.py", line 238, in compare_record
    if not compare_features(old.features, new.features):
  File "C:\projects\biopython\Tests\seq_tests_common.py", line 219, in compare_features
    if not compare_feature(old_f, new_f):
  File "C:\projects\biopython\Tests\seq_tests_common.py", line 148, in compare_feature
    "%s -> %s" % (old_f.qualifiers[key], new_f.qualifiers[key])
AssertionError: ['1'] -> [1]
======================================================================
FAIL: test_arab1 (common_BioSQL.TransferTest)
From GenBank file to BioSQL, then again to a new namespace, arab1.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\projects\biopython\Tests\common_BioSQL.py", line 911, in test_arab1
    self.trans("GenBank/arab1.gb", "gb")
  File "C:\projects\biopython\Tests\common_BioSQL.py", line 928, in trans
    self.assertTrue(compare_records(original_records, biosql_records))
  File "C:\projects\biopython\Tests\seq_tests_common.py", line 313, in compare_records
    if not compare_record(old_r, new_r):
  File "C:\projects\biopython\Tests\seq_tests_common.py", line 238, in compare_record
    if not compare_features(old.features, new.features):
  File "C:\projects\biopython\Tests\seq_tests_common.py", line 219, in compare_features
    if not compare_feature(old_f, new_f):
  File "C:\projects\biopython\Tests\seq_tests_common.py", line 148, in compare_feature
    "%s -> %s" % (old_f.qualifiers[key], new_f.qualifiers[key])
AssertionError: ['1'] -> [1]
======================================================================
FAIL: test_cor6_6 (common_BioSQL.TransferTest)
From GenBank file to BioSQL, then again to a new namespace, cor6_6.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\projects\biopython\Tests\common_BioSQL.py", line 907, in test_cor6_6
    self.trans("GenBank/cor6_6.gb", "gb")
  File "C:\projects\biopython\Tests\common_BioSQL.py", line 928, in trans
    self.assertTrue(compare_records(original_records, biosql_records))
  File "C:\projects\biopython\Tests\seq_tests_common.py", line 313, in compare_records
    if not compare_record(old_r, new_r):
  File "C:\projects\biopython\Tests\seq_tests_common.py", line 238, in compare_record
    if not compare_features(old.features, new.features):
  File "C:\projects\biopython\Tests\seq_tests_common.py", line 219, in compare_features
    if not compare_feature(old_f, new_f):
  File "C:\projects\biopython\Tests\seq_tests_common.py", line 148, in compare_feature
    "%s -> %s" % (old_f.qualifiers[key], new_f.qualifiers[key])
AssertionError: ['1'] -> [1]
======================================================================
FAIL: test_no_ref (common_BioSQL.TransferTest)
From GenBank file to BioSQL, then again to a new namespace, noref.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\projects\biopython\Tests\common_BioSQL.py", line 899, in test_no_ref
    self.trans("GenBank/noref.gb", "gb")
  File "C:\projects\biopython\Tests\common_BioSQL.py", line 928, in trans
    self.assertTrue(compare_records(original_records, biosql_records))
  File "C:\projects\biopython\Tests\seq_tests_common.py", line 313, in compare_records
    if not compare_record(old_r, new_r):
  File "C:\projects\biopython\Tests\seq_tests_common.py", line 238, in compare_record
    if not compare_features(old.features, new.features):
  File "C:\projects\biopython\Tests\seq_tests_common.py", line 219, in compare_features
    if not compare_feature(old_f, new_f):
  File "C:\projects\biopython\Tests\seq_tests_common.py", line 148, in compare_feature
    "%s -> %s" % (old_f.qualifiers[key], new_f.qualifiers[key])
AssertionError: ['16'] -> [16]
======================================================================
FAIL: test_one_of (common_BioSQL.TransferTest)
From GenBank file to BioSQL, then again to a new namespace, one_of.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\projects\biopython\Tests\common_BioSQL.py", line 903, in test_one_of
    self.trans("GenBank/one_of.gb", "gb")
  File "C:\projects\biopython\Tests\common_BioSQL.py", line 928, in trans
    self.assertTrue(compare_records(original_records, biosql_records))
  File "C:\projects\biopython\Tests\seq_tests_common.py", line 313, in compare_records
    if not compare_record(old_r, new_r):
  File "C:\projects\biopython\Tests\seq_tests_common.py", line 238, in compare_record
    if not compare_features(old.features, new.features):
  File "C:\projects\biopython\Tests\seq_tests_common.py", line 219, in compare_features
    if not compare_feature(old_f, new_f):
  File "C:\projects\biopython\Tests\seq_tests_common.py", line 148, in compare_feature
    "%s -> %s" % (old_f.qualifiers[key], new_f.qualifiers[key])
AssertionError: ['12'] -> [12]
======================================================================
FAIL: test_protein_refseq2 (common_BioSQL.TransferTest)
From GenBank file to BioSQL, then again to a new namespace, protein_refseq2.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\projects\biopython\Tests\common_BioSQL.py", line 895, in test_protein_refseq2
    self.trans("GenBank/protein_refseq2.gb", "gb")
  File "C:\projects\biopython\Tests\common_BioSQL.py", line 928, in trans
    self.assertTrue(compare_records(original_records, biosql_records))
  File "C:\projects\biopython\Tests\seq_tests_common.py", line 313, in compare_records
    if not compare_record(old_r, new_r):
  File "C:\projects\biopython\Tests\seq_tests_common.py", line 238, in compare_record
    if not compare_features(old.features, new.features):
  File "C:\projects\biopython\Tests\seq_tests_common.py", line 219, in compare_features
    if not compare_feature(old_f, new_f):
  File "C:\projects\biopython\Tests\seq_tests_common.py", line 148, in compare_feature
    "%s -> %s" % (old_f.qualifiers[key], new_f.qualifiers[key])
AssertionError: ['4'] -> [4]
----------------------------------------------------------------------
```

This example had installed:

```
...
    mysql-connector-c-6.1.11   |       h33f27b4_0         4.8 MB
    mysql-connector-python-8.0.16|   py37h13ed8b8_0         575 KB
...
```

First bad test failing this way was 12 hours ago, same versions as above. The last good test (17 hours ago):

```
    mysql-connector-c-6.1.11   |       h33f27b4_0         4.8 MB
    mysql-connector-python-8.0.13|   py37h13ed8b8_0         566 KB
```

This looks like it was caused by updating from mysql-connector-python-8.0.13 to mysql-connector-python-8.0.16

CC @mdehoon - some of your PR are showing this too.

**Comment by peterjc** [comment]
Release notes here, may need to read 8.0.14, 8.0.15 and 8.0.16:

https://dev.mysql.com/doc/relnotes/connector-python/en/news-8-0.html

**Comment by peterjc** [comment]
Nothing really obvious. There are a couple of points in 8.0.14 about pure Python vs C and Python 2 vs 3, perhaps relevant?

**Comment by MarkusPiotrowski** [comment]
@peterjc I tried to investigate/test this on Windows, but actually I get caught by this error:
```
Character set 'utf8mb4' is not a compiled character set and is not specified in the 'c:\Program Files\MySQL\MySQL Server 5.1\\share\charsets\Index.xml' file
test_BioSQL_mysql_connector ... skipping. Connection failed, check settings if you plan to use BioSQL: 2019 (HY000): Can't initialize character set utf8mb4 (path: c:\Program Files\MySQL\MySQL Server 5.1\\share\charsets\)
```
I had installed **MySQL Server 8.0** and I wonder why it is looking in a non-existing `...\MySQL Server 5.1\` folder. There is nothing obvious in my system paths and I just wonder, if `5.1` is hardcoded anywhere in the Biopython's config files?

**Comment by peterjc** [comment]
As far as I can recall, the only SQL configuration we have is in our tests setup (different for TravisCI and AppVeyor). Are you installing this via pip, conda, source?

**Comment by MarkusPiotrowski** [comment]
I installed mySQL with a Windows installer and the connector via conda. However, I gave up on this. To complicate for me to set up. I'm sorry.

**Comment by sagitter** [comment]
> This looks like it was caused by updating from mysql-connector-python-8.0.13 to mysql-connector-python-8.0.16

Looks same error but with much older version of `mysql-connector-python` (1.1.6) (or not?): [log](https://copr-be.cloud.fedoraproject.org/results/sagitter/python3.8/fedora-rawhide-x86_64/00940756-python-biopython/builder-live.log)

**Comment by peterjc** [comment]
@sagitter that issue with ``ValueError: invalid literal for int() with base 10: 'ExactPosition(0)'`` looks different to me, likely something about Python 3.8.0b1 - could you log a separate issue for that please?

**Comment by nimne** [comment]
I couldn't figure out what change in the mysql-connector code specifically caused this to happen, but this looks like this problem has been reported in the [mysql-connector bugtracker](https://bugs.mysql.com/bug.php?id=95437). From the bug report: "TEXT column with only digits reads in as int". This matches the failed tests above.

**Comment by peterjc** [comment]
Thanks @nimne - I agree, that looks like the cause, logged against v8.0.16 too.

MySQL Bug 95437: mysql-connector-python: TEXT column with only digits reads in as int
https://bugs.mysql.com/bug.php?id=95437

Does anyone have an account on that tracker to add a "me too" and point at this Biopython issue?

**Comment by peterjc** [comment]
[See our issue #2145 for the separate problem @sagitter found - related to Python 3.8 changes]

**Comment by nimne** [comment]
It looks like this specific problem was fixed in mysql-connector 8.0.21 but I haven't had a chance to test it myself. This  version was released on pypi on Jul 12, 2020 so it will probably take time for it to end up in the CI systems.

[From the bugtracker](https://bugs.mysql.com/bug.php?id=95437):
>
>[29 Jun 22:46] Philip Olson 
> Posted by developer:
>  
> Fixed as of the upcoming MySQL Connector/Python 8.0.21 release, and here's the proposed changelog entry from the documentation team:
> 
> Because MySQL stores TEXT types as BLOB and JSON as LONGBLOB, the TEXT and
> JSON types are now converted to str and the rest of the BLOB types as
> bytes. Previously, as an example, a column of type TEXT that only
> contained digits was read as type=integer by Connector/Python.
> 
> Thank you for the bug report.

**Comment by peterjc** [comment]
https://anaconda.org/conda-forge/mysql-connector-python now has v8.0.21
