### ISSUE TITLE
test_Affy.py UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf0 in position 0: invalid continuation byte 

### ISSUE THREAD

**Issue by sagitter** [biopython/biopython#2128]
Hi all.

### Setup

I am reporting a problem with Biopython version, Python version, and operating
system as follows:

```python
Python-3.8.0~b1
kernel version == 5.0.17-300
GCC-9.1.1
BioPython-1.73
Fedora-31 (devel branch) x86_64
```

### Expected behaviour

All offline tests passed.

### Actual behaviour

```
Skipping any tests requiring internet access
Python version: 3.8.0b1 (default, Jun  5 2019, 08:48:48) 
[GCC 9.1.1 20190503 (Red Hat 9.1.1-1)]
Operating system: posix linux
+ for test in `ls test_*.py | grep -v Nexus | grep -v Phylo | grep -v Tutorial | grep -v bgzf | grep -v SearchIO_blast`
+ echo C
+ export PYTHONPATH=/builddir/build/BUILDROOT/python-biopython-1.73-3.fc31.x86_64/usr/lib64/python3.8/site-packages
+ PYTHONPATH=/builddir/build/BUILDROOT/python-biopython-1.73-3.fc31.x86_64/usr/lib64/python3.8/site-packages
C
+ /usr/bin/python3 run_tests.py --offline -v test_Affy.py
test_Affy ... FAIL
testAffy3 (test_Affy.AffyTest) ... ok
testAffy3Backwards (test_Affy.AffyTest) ... ok
testAffy4 (test_Affy.AffyTest) ... ok
testAffyBadHeader (test_Affy.AffyTest) ... ok
testAffyStrict (test_Affy.AffyTest) ... ok
testAffyWrongModeRead (test_Affy.AffyTest) ... ERROR
testAffyWrongModeReadV4 (test_Affy.AffyTest) ... ERROR

======================================================================
ERROR: testAffyWrongModeRead (test_Affy.AffyTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/python-biopython-1.73/python3/Tests/test_Affy.py", line 117, in testAffyWrongModeRead
    record = CelFile.read(f)
  File "/builddir/build/BUILD/python-biopython-1.73/python3/build/lib.linux-x86_64-3.8/Bio/Affy/CelFile.py", line 136, in read
    return read_v3(handle)
  File "/builddir/build/BUILD/python-biopython-1.73/python3/build/lib.linux-x86_64-3.8/Bio/Affy/CelFile.py", line 303, in read_v3
    for line in handle:
  File "/usr/lib64/python3.8/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf0 in position 0: invalid continuation byte

======================================================================
ERROR: testAffyWrongModeReadV4 (test_Affy.AffyTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/python-biopython-1.73/python3/Tests/test_Affy.py", line 105, in testAffyWrongModeReadV4
    record = CelFile.read_v4(f)
  File "/builddir/build/BUILD/python-biopython-1.73/python3/build/lib.linux-x86_64-3.8/Bio/Affy/CelFile.py", line 173, in read_v4
    preHeadersMap[name] = struct.unpack("<i", f.read(4))[0]
TypeError: a bytes-like object is required, not 'str'

----------------------------------------------------------------------
Ran 1 test in 0.016 seconds
```

**Comment by peterjc** [comment]
There are a few as yet unresolved problems on unusual locales (several other open issues on other tests), but this could be due to you testing an early version of Python 3.8?

What do these return?

```
$ python3 -c "import locale; print(locale.getlocale())"
```

```
$ locale
```

**Comment by sagitter** [comment]
(Sorry for delay)

```
+ /usr/bin/python3 -c 'import locale; print(locale.getlocale())'
('en_US', 'UTF-8')
+ locale
LANG=C
LC_CTYPE="C"
LC_NUMERIC="C"
LC_TIME="C"
LC_COLLATE="C"
LC_MONETARY="C"
LC_MESSAGES="C"
LC_PAPER="C"
LC_NAME="C"
LC_ADDRESS="C"
LC_TELEPHONE="C"
LC_MEASUREMENT="C"
LC_IDENTIFICATION="C"
LC_ALL=
```

**Comment by peterjc** [comment]
Unless you are having issues with the Affy code in your own scripts, this is most likely a problem in the tests under your particular locale settings (which are unusual in being just ``C`` instead of say ``en_US.UTF-8`` or ``en_GB.UTF-8`` or anything - usually with UTF-8).

Strangley temporarily setting my locale that way does not reproduce the errror:

```
$ LANG=C locale
LANG=C
LC_CTYPE="C"
LC_NUMERIC="C"
LC_TIME="C"
LC_COLLATE="C"
LC_MONETARY="C"
LC_MESSAGES="C"
LC_PAPER="C"
LC_NAME="C"
LC_ADDRESS="C"
LC_TELEPHONE="C"
LC_MEASUREMENT="C"
LC_IDENTIFICATION="C"
LC_ALL=
```

```
$ LANG=C python3 run_tests.py --offline -v test_Affy.py
Skipping any tests requiring internet access
Python version: 3.7.2 (default, Dec 29 2018, 06:19:36) 
[GCC 7.3.0]
Operating system: posix linux
test_Affy ... ok
testAffy3 (test_Affy.AffyTest) ... ok
testAffy3Backwards (test_Affy.AffyTest) ... ok
testAffy4 (test_Affy.AffyTest) ... ok
testAffyBadHeader (test_Affy.AffyTest) ... ok
testAffyStrict (test_Affy.AffyTest) ... ok
testAffyWrongModeRead (test_Affy.AffyTest) ... ok
testAffyWrongModeReadV4 (test_Affy.AffyTest) ... ok
----------------------------------------------------------------------
Ran 1 test in 0.039 seconds
```

Perhaps I need to try the latest pre-release Python 3.8 too?

**Comment by sagitter** [comment]
> Perhaps I need to try the latest pre-release Python 3.8 too?

I used Python-3.8.0b1

**Comment by sagitter** [comment]
Can [this solved ticket](https://bugs.python.org/issue24214) help you?
