### ISSUE TITLE
SearchIO does not support nhmmscan outout from HMMER3

### ISSUE THREAD

**Issue by peterjc** [biopython/biopython#2139]
### Setup

I am reporting a problem with Biopython version, Python version, and operating
system as follows:

```pycon
>>> import sys; print(sys.version)
3.7.2 (default, Dec 29 2018, 06:19:36) 
[GCC 7.3.0]
>>> import platform; print(platform.python_implementation()); print(platform.platform())
CPython
Linux-3.10.0-957.12.2.el7.x86_64-x86_64-with-centos-7.6.1810-Core
>>> import Bio; print(Bio.__version__)
1.74.dev0
```

(*Please copy and run the above in your Python, and copy-and-paste the output*)

### Expected behaviour

The pair of tools ``nhmmer`` / ``nhmmscan`` are new to HMMER3.1.

Much as we can parser the output from protein based HMMER3 tool ``hmmscan``, I would like to parse output from the DNA based HMMER3 tool ``nhmmscan`` as well.

### Actual behaviour

Parsing fails.

### Steps to reproduce

Using HMMER 3.2.1, tested under both Linux and macOS:

Get sample data,

```
$ curl -L -O http://eddylab.org/software/hmmer/hmmer-3.2.1.tar.gz
$ tar -zxvf hmmer-3.2.1.tar.gz
$ cd hmmer-3.2.1/tutorial/
$ ls MADE1.hmm dna_target.fa 
```

Compile the DNA HMM:

```
$ hmmpress MADE1.hmm 
Working...    done.
Pressed and indexed 1 HMMs (1 names and 1 accessions).
Models pressed into binary file:   MADE1.hmm.h3m
SSI index for binary model file:   MADE1.hmm.h3i
Profiles (MSV part) pressed into:  MADE1.hmm.h3f
Profiles (remainder) pressed into: MADE1.hmm.h3p
```

Run test search with ``nhmmscan``, getting multiple output formats:

```
$ nhmmscan -o n.txt --tblout n.table --dfamtblout n.dfam MADE1.hmm dna_target.fa
```

Run similar search but with ``hmmscan`` (intended for proteins):
```
$ hmmscan -o p.txt --tblout p.table --domtblout p.domtable --pfamtblout p.pfam MADE1.hmm dna_target.fa
```

First, the ``hmmscan`` output parses two of the four possible outputs:

```pycon
>>> from Bio import SearchIO
>>> print(len(list(SearchIO.parse("p.txt", "hmmer3-text"))))
1
>>> print(len(list(SearchIO.parse("p.table", "hmmer3-tab"))))
1
>>> print(len(list(SearchIO.parse("p.domtable", "hmmscan3-domtab"))))
1
```

For the ``nhmmscan`` output there is no domain table option, but text and the main table output fail:

```pycon
>>> from Bio import SearchIO
>>> print(len(list(SearchIO.parse("n.txt", "hmmer3-text"))))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/Bio/SearchIO/__init__.py", line 320, in parse
    for qresult in generator:
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/Bio/SearchIO/HmmerIO/hmmer3_text.py", line 48, in __iter__
    for qresult in self._parse_qresult():
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/Bio/SearchIO/HmmerIO/hmmer3_text.py", line 137, in _parse_qresult
    hit_list = self._parse_hit(qid, qdesc)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/Bio/SearchIO/HmmerIO/hmmer3_text.py", line 213, in _parse_hit
    'domain_exp_num': float(row[6]),
ValueError: could not convert string to float: 'MADE1'
```

```python
>>> from Bio import SearchIO
>>> print(len(list(SearchIO.parse("n.table", "hmmer3-tab"))))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/Bio/SearchIO/__init__.py", line 320, in parse
    for qresult in generator:
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/Bio/SearchIO/HmmerIO/hmmer3_tab.py", line 35, in __iter__
    for qresult in self._parse_qresult():
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/Bio/SearchIO/HmmerIO/hmmer3_tab.py", line 105, in _parse_qresult
    cur = self._parse_row()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/Bio/SearchIO/HmmerIO/hmmer3_tab.py", line 62, in _parse_row
    hit['region_num'] = int(cols[11])           # reg
ValueError: invalid literal for int() with base 10: '+'
```

The tables are quite different (both in number of rows, but more importantly for the parser, in their columns). Likewise the tables within the text output.

**Comment by peterjc** [comment]
Sample plain text output (would have to rename the tabular files for quick github upload):

[n.txt](https://github.com/biopython/biopython/files/3301030/n.txt)

[p.txt](https://github.com/biopython/biopython/files/3301031/p.txt)

**Comment by peterjc** [comment]
Quoting the manual http://eddylab.org/software/hmmer3/3.1b2/Userguide.pdf - this part is relevant for parsing the alternative reporting presentation from ``nhmmscan``:

> ## There are no domains, but there are envelopes.
> In HMMER’s protein-search programs, multiple matches of the model to a target sequence are treated as domains contained within a single hit for that sequence. In the DNA-search programs, each match of the model to a subsequence is treated as an independent hit - there’s no notion of a domain. This is largely a difference in reporting; both pipelines rely on essentially the same envelope detection code; envelopes lead to domains in protein search, and hits in DNA search.

**Comment by RebbyAnne** [comment]
Hi, is there a solution to parsing nhmmer outputs? Using SearchIO or any another tools?

**Comment by peterjc** [comment]
@bow You haven't looked into this yet for Biopython, have you?

@RebbyAnne parsing the tabular output should be easy - what comes next depends what you want to do with it though.
