### ISSUE TITLE
win32 Python 2.7 SeqIO gzip test failure, Invalid mode ('rtb')

### ISSUE THREAD

**Issue by peterjc** [biopython/biopython#2159]
Noticed by @MarkusPiotrowski on #2157 and https://github.com/biopython/biopython/pull/2152#issuecomment-507853870, we were accidentally not testing on 32-bit Windows 2.7 recently, and recent pull request #2151 should have failed:

https://ci.appveyor.com/project/biopython/biopython/builds/25703642/job/6tomvsxafe0vxucn

```
======================================================================
ERROR: test_gzip_fasta (test_SeqIO.TestZipped)
Testing FASTA with gzip.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\projects\biopython\Tests\test_SeqIO.py", line 146, in test_gzip_fasta
    with gzip.open("Fasta/flowers.pro.gz", "rt") as handle:
  File "C:\Py\lib\gzip.py", line 34, in open
    return GzipFile(filename, mode, compresslevel)
  File "C:\Py\lib\gzip.py", line 94, in __init__
    fileobj = self.myfileobj = __builtin__.open(filename, mode or 'rb')
ValueError: Invalid mode ('rtb')
======================================================================
ERROR: test_gzip_fastq (test_SeqIO.TestZipped)
Testing FASTQ with gzip.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\projects\biopython\Tests\test_SeqIO.py", line 136, in test_gzip_fastq
    with gzip.open("Quality/example.fastq.gz", "rt") as handle:
  File "C:\Py\lib\gzip.py", line 34, in open
    return GzipFile(filename, mode, compresslevel)
  File "C:\Py\lib\gzip.py", line 94, in __init__
    fileobj = self.myfileobj = __builtin__.open(filename, mode or 'rb')
ValueError: Invalid mode ('rtb')
======================================================================
ERROR: test_gzip_genbank (test_SeqIO.TestZipped)
Testing GenBank with gzip.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\projects\biopython\Tests\test_SeqIO.py", line 157, in test_gzip_genbank
    with gzip.open("GenBank/cor6_6.gb.bgz", "rt") as handle:
  File "C:\Py\lib\gzip.py", line 34, in open
    return GzipFile(filename, mode, compresslevel)
  File "C:\Py\lib\gzip.py", line 94, in __init__
    fileobj = self.myfileobj = __builtin__.open(filename, mode or 'rb')
ValueError: Invalid mode ('rtb')
----------------------------------------------------------------------
Ran 497 tests in 845.401 seconds
```

It is a return of https://bugs.python.org/issue30012 which requires a hack like the following:

```
if sys.version_info >= (3,):
    handle = gzip.open(filename, "rt")
else:
    handle = gzip.open(filename)
```

**Comment by peterjc** [comment]
Closed via  #2160
