### ISSUE TITLE
MMCIFParser. Non integer _atom_site.auth_seq_id

### ISSUE THREAD

**Issue by andrei-istrate** [biopython/biopython#2259]
I get an error when the _atom_site.auth_seq_id is not an integer number.

According to http://mmcif.wwpdb.org/dictionaries/mmcif_pdbx_v40.dic/Items/_atom_site.auth_seq_id.html
this item does not have to be an integer.

### Setup
I am reporting a problem with Biopython version, Python version, and operating
system as follows:

import sys; print(sys.version)
3.6.4 (v3.6.4:d48ecebad5, Dec 18 2017, 21:07:28) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)]
import platform; print(platform.python_implementation()); print(platform.platform())
CPython
Darwin-18.5.0-x86_64-i386-64bit
import Bio; print(Bio.__version__)
1.74

### Actual behaviour

Traceback (most recent call last):
  File "/Users/andrei/PycharmProjects/3D-STRUDEL/playground/test.py", line 15, in <module>
    model = parser.get_structure(in_path.split('/')[-1].split('.')[0], in_path)
  File "/Users/andrei/PycharmProjects/3D-STRUDEL/venv/lib/python3.6/site-packages/Bio/PDB/MMCIFParser.py", line 64, in get_structure
    self._build_structure(structure_id)
  File "/Users/andrei/PycharmProjects/3D-STRUDEL/venv/lib/python3.6/site-packages/Bio/PDB/MMCIFParser.py", line 144, in _build_structure
    int_resseq = int(seq_id_list[i])
ValueError: invalid literal for int() with base 10: '20A'

### Steps to reproduce
parser = MMCIFParser()
model = parser.get_structure('structure_id', 'test.cif')

data_zzz
loop_
  _atom_site.group_PDB
  _atom_site.id
  _atom_site.type_symbol
  _atom_site.label_atom_id
  _atom_site.label_alt_id
  _atom_site.label_comp_id
  _atom_site.label_asym_id
  _atom_site.label_entity_id
  _atom_site.label_seq_id
  _atom_site.pdbx_PDB_atom_name
  _atom_site.pdbx_PDB_ins_code
  _atom_site.pdbx_PDB_residue_name
  _atom_site.pdbx_PDB_residue_no
  _atom_site.Cartn_x
  _atom_site.Cartn_y
  _atom_site.Cartn_z
  _atom_site.occupancy
  _atom_site.B_iso_or_equiv
  _atom_site.pdbx_formal_charge
  _atom_site.auth_seq_id
  _atom_site.auth_comp_id
  _atom_site.auth_asym_id
  _atom_site.auth_atom_id
  _atom_site.calc_flag
  _atom_site.pdbx_PDB_model_num
ATOM       55888 P  P    . U   2   46    20          P    . U     20   121.774   110.035   131.463 1.000    215.295 .    20    U   2 P    .    1
ATOM       55889 O  OP1  . U   2   46    20          OP1  . U     20   121.566   109.693   130.044 1.000    164.677 .    20    U   2 OP1  .    1
ATOM       55890 O  O5'  . U   2   46    20          O5'  . U     20   120.414   110.603   132.073 1.000    261.140 .    20    U   2 O5'  .    1
ATOM       55891 C  C5'  . U   2   46    20          C5'  . U     20   120.205   110.733   133.500 1.000    294.363 .    20    U   2 C5'  .    1
ATOM       55892 C  C4'  . U   2   46    20          C4'  . U     20   120.145   112.186   133.927 1.000    276.505 .    20    U   2 C4'  .    1
ATOM       55893 C  C3'  . U   2   46    20          C3'  . U     20   119.544   113.172   132.936 1.000    274.725 .    20    U   2 C3'  .    1
ATOM       55894 O  O3'  . U   2   46    20          O3'  . U     20   118.119   113.100   132.947 1.000    277.853 .    20    U   2 O3'  .    1
ATOM       55895 C  C2'  . U   2   46    20          C2'  . U     20   120.111   114.522   133.399 1.000    245.537 .    20    U   2 C2'  .    1
ATOM       55896 O  O2'  . U   2   46    20          O2'  . U     20   119.240   115.225   134.260 1.000    276.719 .    20    U   2 O2'  .    1
ATOM       55897 C  C1'  . U   2   46    20          C1'  . U     20   121.405   114.121   134.125 1.000    221.883 .    20    U   2 C1'  .    1
ATOM       55898 O  O4'  . U   2   46    20          O4'  . U     20   121.477   112.709   134.128 1.000    253.647 .    20    U   2 O4'  .    1
ATOM       55899 N  N1   . U   2   46    20          N1   . U     20   122.657   114.667   133.569 1.000    213.478 .    20    U   2 N1   .    1
ATOM       55900 C  C6   . U   2   46    20          C6   . U     20   123.501   115.406   134.372 1.000    230.661 .    20    U   2 C6   .    1
ATOM       55901 C  C5   . U   2   46    20          C5   . U     20   124.652   115.928   133.926 1.000    248.512 .    20    U   2 C5   .    1
ATOM       55902 C  C4   . U   2   46    20          C4   . U     20   125.048   115.715   132.566 1.000    223.259 .    20    U   2 C4   .    1
ATOM       55903 N  N3   . U   2   46    20          N3   . U     20   124.160   114.969   131.821 1.000    215.175 .    20    U   2 N3   .    1
ATOM       55904 C  C2   . U   2   46    20          C2   . U     20   122.972   114.424   132.239 1.000    228.400 .    20    U   2 C2   .    1
ATOM       55905 O  O2   . U   2   46    20          O2   . U     20   122.259   113.776   131.491 1.000    261.839 .    20    U   2 O2   .    1
ATOM       55906 O  O4   . U   2   46    20          O4   . U     20   126.077   116.138   132.037 1.000    219.206 .    20    U   2 O4   .    1
ATOM       55907 O  OP2  . U   2   46    20          OP2  . U     20   122.860   110.989   131.831 1.000    281.697 .    20    U   2 OP2  .    1
ATOM       55908 P  P    . U   2   46    20          P    A U     20   117.291   113.219   131.570 1.000    267.495 .    20A   U   2 P    .    1
ATOM       55909 O  OP1  . U   2   46    20          OP1  A U     20   115.884   113.551   131.914 1.000    264.565 .    20A   U   2 OP1  .    1
ATOM       55910 O  O5'  . U   2   46    20          O5'  A U     20   117.958   114.491   130.879 1.000    291.031 .    20A   U   2 O5'  .    1
ATOM       55911 C  C5'  . U   2   46    20          C5'  A U     20   117.884   114.721   129.458 1.000    286.127 .    20A   U   2 C5'  .    1
ATOM       55912 C  C4'  . U   2   46    20          C4'  A U     20   117.538   116.171   129.185 1.000    294.269 .    20A   U   2 C4'  .    1
ATOM       55913 C  C3'  . U   2   46    20          C3'  A U     20   118.358   117.211   129.949 1.000    280.955 .    20A   U   2 C3'  .    1
ATOM       55914 O  O3'  . U   2   46    20          O3'  A U     20   118.789   118.290   129.124 1.000    234.195 .    20A   U   2 O3'  .    1
ATOM       55915 C  C2'  . U   2   46    20          C2'  A U     20   117.417   117.651   131.075 1.000    337.964 .    20A   U   2 C2'  .    1
ATOM       55916 O  O2'  . U   2   46    20          O2'  A U     20   117.562   118.974   131.550 1.000    337.825 .    20A   U   2 O2'  .    1
ATOM       55917 C  C1'  . U   2   46    20          C1'  A U     20   116.046   117.505   130.417 1.000    363.058 .    20A   U   2 C1'  .    1
ATOM       55918 O  O4'  . U   2   46    20          O4'  A U     20   116.146   116.403   129.535 1.000    325.295 .    20A   U   2 O4'  .    1
ATOM       55919 N  N1   . U   2   46    20          N1   A U     20   114.924   117.259   131.347 1.000    406.886 .    20A   U   2 N1   .    1
ATOM       55920 C  C6   . U   2   46    20          C6   A U     20   115.093   117.300   132.719 1.000    434.242 .    20A   U   2 C6   .    1
ATOM       55921 C  C5   . U   2   46    20          C5   A U     20   114.090   117.079   133.583 1.000    435.334 .    20A   U   2 C5   .    1
ATOM       55922 C  C4   . U   2   46    20          C4   A U     20   112.777   116.789   133.085 1.000    434.735 .    20A   U   2 C4   .    1
ATOM       55923 N  N3   . U   2   46    20          N3   A U     20   112.679   116.766   131.706 1.000    425.493 .    20A   U   2 N3   .    1
ATOM       55924 C  C2   . U   2   46    20          C2   A U     20   113.682   116.990   130.793 1.000    409.259 .    20A   U   2 C2   .    1
ATOM       55925 O  O2   . U   2   46    20          O2   A U     20   113.486   116.945   129.588 1.000    377.597 .    20A   U   2 O2   .    1
ATOM       55926 O  O4   . U   2   46    20          O4   A U     20   111.775   116.568   133.770 1.000    424.679 .    20A   U   2 O4   .    1
ATOM       55927 O  OP2  . U   2   46    20          OP2  A U     20   117.574   112.011   130.751 1.000    265.784 .    20A   U   2 OP2  .    1
#

**Comment by peterjc** [comment]
Your steps to reproduce are incomplete (missing imports, and what's the text below the two lines of Python?).

Can you share an example mmCIF file with a non-integer ``_atom_site.auth_seq_id`` field?

**Comment by svalqui** [comment]
Hi @andrei-istrate , yes the value doesn't need to be an integer.

I have an issue with the test_cif.txt, it seems that when I download it, it contains single quotes

ATOM       55890 O  O5'  . U   2   46    20          O5'  . U     20   120.414   110.603   132.073 1.000    261.140 .    20    U   2 O5'  .    1
ATOM       55891 C  C5'  . U   2   46    20          C5'  . U     20   120.205   110.733   133.500 1.000    294.363 .    20    U   2 C5'  .    1
ATOM       55892 C  C4'  . U   2   46    20          C4'  . U     20   120.145   112.186   133.927 1.000    276.505 .    20    U   2 C4'  .    1

which makes the parser fail.

  File "/usr/local/lib/python3.6/dist-packages/Bio/PDB/MMCIF2Dict.py", line 82, in _splitline
    raise ValueError("Opening quote in middle of word: " + line)
ValueError: Opening quote in middle of word: ATOM       55890 O  O5'  . U   2   46    20          O5'  . U     20   120.414   110.603   132.073 1.000    261.140 .    20    U   2 O5'  .    1

Is this the same as the file you got? the same content "O5'" ?

**Comment by andrei-istrate** [comment]
Hi @svalqui 

Thanks for looking into this.
The issue with single quotes was discussed here: https://github.com/biopython/biopython/issues/2261

I have attached a file with no single quotes:
[test_cif.txt](https://github.com/biopython/biopython/files/3733343/test_cif.txt)

**Comment by jgreener64** [comment]
According to the spec non-integer values are allowed, though they don't appear in any PDB entries. The `_atom_site.pdbx_PDB_ins_code` field is used for insertion codes by the PDB and by the Biopython mmCIF parser; putting the insertion code there should make this work.

The lines that cause the error are:
https://github.com/biopython/biopython/blob/f97a7ada67b597ac557aae51fb08868348e0943b/Bio/PDB/MMCIFParser.py#L112-L117
and:
https://github.com/biopython/biopython/blob/f97a7ada67b597ac557aae51fb08868348e0943b/Bio/PDB/MMCIFParser.py#L144

The reason `auth_seq_id` is used rather than `label_seq_id` to get the residue number is for compatibility with the PDB parser.

One option would be to use the `label_seq_id` if the conversion of `auth_seq_id` to an integer fails, though this would have to be applied across the whole file to make ensure consistent numbering. Another option would be to add a keyword argument to the mmCIF parser to use `label_seq_id`, which is guaranteed to be an integer, for residue numbering.

**Comment by svalqui** [comment]
@andrei-istrate , Thank you, I can replicate the error now.
@jgreener64 , Thank you for your input.
I'll review this; I'll comment in a couple of days.

**Comment by svalqui** [comment]
@jgreener64 , if you have sometime could you please review the above PR?

**Comment by svalqui** [comment]
Hi @peterjc 
Could you please close #2307  , that doesn't address this issue.

To resolve this _atom_site.auth_seq_id would need to be taken as character as defined in the specification, PDB currently uses it as integer, changing it requires initial changes to

Bio.PDB.MMCIFParser.py
Bio.PDB.StructureBuilder.py

affects the structure of Residue, needs further changes in Bio.PDB and Bio.SeqIO
would also require updates to test and documentation.

While the change is needed to comply with the current standard, it risks the existing backward compatibility, requires a significant amount of time to be tested; My current time availability won't allow me to do this.

Considering there are talks to redesign and build a newer Bio.PDB, it might me more suitable to acknowledge the module do not fully support the current specification and to prioritize the development to address this issue.

Hi @andrei-istrate , @jgreener64 , I'm sorry the needed change expands to wider for the time I got available.

Cheers,
