### ISSUE TITLE
PAML issue : Empty results file.

### ISSUE THREAD

**Issue by StromTroopers** [biopython/biopython#2311]
### Setup

I am reporting a problem with Python 3.7.4 (default, Aug 13 2019, 20:35:49) , and BioPython on

```pycon
>>> import sys; print(sys.version)
3.7.4 (default, Aug 13 2019, 20:35:49) 
[GCC 7.3.0]
>>> import platform; print(platform.python_implementation()); print(platform.platform())
CPython
Linux-4.9.0-6-amd64-x86_64-with-debian-buster-sid
>>> import Bio; print(Bio.__version__)
1.73
```

### Expected behaviour

It is supposed to produce an output file but I keep getting the error shown below:

### Actual behaviour

I downloaded PAML from the latest release  by doing :

```
conda install -c bioconda paml
```

Then I activated my conda env : 

```
conda activate /beegfs/data/grindel/myconda/
```

Then I opened python3 and produced de following command: 

```python
from Bio.Phylo.PAML import codeml
cml = codeml.Codeml()
cml.alignment = "/beegfs/data/grindel/fasta_seq.phy"
cml.tree = "/beegfs/data/grindel/test_tree.nwk"
cml.out_file = "/beegfs/data/grindel/output_file"
result = cml.run(command="/beegfs/data/grindel/myconda/bin/codeml")
```

and I get the following issue: 

```
>>> result = cml.run(command="/beegfs/data/grindel/myconda/bin/codeml")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/beegfs/data/soft/python_modules/Bio/Phylo/PAML/codeml.py", line 184, in run
    return read(self.out_file)
  File "/beegfs/data/soft/python_modules/Bio/Phylo/PAML/codeml.py", line 196, in read
    raise ValueError("Empty results file.  Did CODEML exit successfully?  "
ValueError: Empty results file.  Did CODEML exit successfully?  Run 'Codeml.run()' with 'verbose=True'.
```

Have you an idea where here the issue? 

### Steps to reproduce

Here are the files: 

Tree:

```
((((UDEW01010040.1_3617-3887_+__Eupelmus_annulatus:0.00376527,scaffold_13129_4609-4879_+__Eupelmus_azureus:1e-08)0.99    :0.0354058,(scaffold_137842_420-690_+__Eupelmus_kiefferi:0.00567115,scaffold_27654_4324-4549_-__Eupelmus_azureus:0.0187664)0.88    :0.0171806)0.14    :0.0134734,(scaffold_33993_53-317_-__Eupelmus_azureus:0.0273228,scaffold_44256_1364-1589_-__Eupelmus_azureus:0.0382704)0.86    :0.0277671):0.123792,(scaffold_44166_1761-2046_-__Eupelmus_azureus:0.156866,((scaffold_11770_3196-3466_+__Eupelmus_azureus:0.0427527,UDEW01021107.1_442-700_+__Eupelmus_annulatus:0.0381533)0.97    :0.0485985,(scaffold_14031_2804-3029_+__Eupelmus_azureus:0.0719598,(scaffold_47698_1234-1504_+__Eupelmus_azureus:0.0388197,((UDEW01030446.1_230-509_+__Eupelmus_annulatus:0.0113297,(scaffold_272724_19-268_+__Eupelmus_azureus:0.0166447,scaffold_62315_351-609_+__Eupelmus_azureus:0.0200791)0.00    :2.9e-07)0.80    :0.00377075,(scaffold_102168_266-530_-__Eupelmus_azureus:0.0203506,scaffold_44167_913-1183_+__Eupelmus_azureus:0.042876)0.00    :2.4e-07)0.00    :1.8e-07)0.97    :0.0373197)0.71    :0.00906376)0.94    :0.0580638):0.0329636)1.00    ;
```

Alignment: 

```
16   276
scaffold_44166_1761-2046_-__Eu  ---TCGCTTC AAATCGTCCA ACACGGTCCT ACTCACAAGC ACAGCCCCTA TGTTTCGAGC
UDEW01010040.1_3617-3887_+__Eu  CTCTCACTGC AAATTGTCCA GCACGGTTCG ACGCACAAGC ACAACTCCTT TGTGTCGAGC
scaffold_13129_4609-4879_+__Eu  CTCTCACTGC AAATTGTCCA GCACGGTTCG ACGCACAAGC ACAACTCCTT TGTGTCGAGC
UDEW01030446.1_230-509_+__Eupe  CTCTCACTGC AGATCGTCCA GCATGGTCCG ACTCATAAGC ACAGCCCCTA TGTTTCTAGC
scaffold_44167_913-1183_+__Eup  CTCTCACTGC AGATCGTTCA GCATGGTCCG ACTCATAAGC ACAGCCCCTA TGTTTCTAGC
scaffold_137842_420-690_+__Eup  CTCTCACTGC AAATTGTCCA GCACGGTCCA ACGCACAAGC ACAGCTCCTT TGTGTCGAGC
scaffold_47698_1234-1504_+__Eu  CTCTCACTGA AGATCGTCCA GCATGGTCCG ACTCATAAGC ATAGCCTCTA TGTTTCTGGC
scaffold_11770_3196-3466_+__Eu  CTTTCACTGC AGATCGTCCA GCATGGTCCG ACTCACAAGC ACAGCCCTTA TGTATCTAGT
scaffold_62315_351-609_+__Eupe  CTCTCACTAC AGATCGTCCA GCATGGTCAG ACTCATAAGC ACAGCCCCTA TGTTTCTAGC
UDEW01021107.1_442-700_+__Eupe  CTTTCACTGC AGATCGTCCA GCATGGTCCA ACTCACAAGC GCAGCCCTTA TGTATTTAGC
scaffold_33993_53-317_-__Eupel  ---TCATTGC AAATTGTCCA GCACGGTCCA ACGCACAAAC ACAGCTCATT TGTGTCGAGC
scaffold_102168_266-530_-__Eup  ------CTGC AGATCATCCA GCATGGTCCG ACTCATAAGC ACAGCCCCTA TGTTTCTAGC
scaffold_272724_19-268_+__Eupe  ---------- ---------- -CATGGTCCG ACTCATAAGC ACAGCGCCTA TGTTTCTAGC
scaffold_14031_2804-3029_+__Eu  CTTTCACTGC AGATCGTCCA GCATGGTCCA ACTCACAAGC ATAGCCCTTA TGTTTCTAGT
scaffold_44256_1364-1589_-__Eu  ---TCACTGC AAATTTTCCA GCACGGTCCT ACGCATAAAC ACAGCTCCTT TGTGTCGAGC
scaffold_27654_4324-4549_-__Eu  ---TCACTGC AAATTGTCCA GCACGGTCCA ACGCACAAGC ACAGCTCCTT TGTCTCGAGC

                                ACTTGGATTG ACTTAGTACT TGTTGACGAC AGTGACATCG TGATTAACTC TGATAATCAT
                                ACATGGATTG ACATAATACT TGTGGATGAC GCCGACACTA TACTCGACTT TGACAATCAT
                                ACATGGATTG ACATAATACT TGTGGATGAC GCCGACACTA TACTCGACTT TGACAATCAT
                                ACGTGGATTG ACGTGATGTT TGTTGACGAT AATGACACGG TGCTTGTCTA TGACAATCAT
                                ACGTGGATTG ACGGGATGTT TGTTGAAGAT AATGATACGG TGCTTGACTA TGACAATCAT
                                ACATGGATTG ACATAATACT TGTAGATGAC GCTGACACTG TACTCGACTT TGACAATCAT
                                CCGTGGATTG ACGCGATGGT TGTTGACGAT AATGACACGG TGCTTGACTA TGACAATCAT
                                ACATCGAACG ACGTGATGTT TTTTGATGAC TGTGACCTAG TGCTTGACCA TGACAATTAT
                                ACGTGGATTG ACGTGATGTT TGTTGACGAT AATGACACGG TGCTTGACTA TGACAATCAA
                                ACATGGATCG ACGTGATGTT TGTTGATGAC TGTGACCTAG TGTTTGACCA CGACAATCGT
                                ACATGGATTG ACAGAATACT CGTGGATGAC GCCGACACTG TACTTGACTT TGATAATCAT
                                ACGTGGATTG ACGTGATGTT TGTTGACGAT AATGACACGG CGCTTGCCTA TGACAATCAT
                                ACGTGGATTG ACGTGATGTT TGTTGACGAT AATGACACGG TACTTGACTA TGACAATCAT
                                ACACGGATTG ACGTCATGCT CGTAGACGAC AGTGACACGG TGCTTGACTA CGACAATCAT
                                ACATGGATTG ACATAATACT CGTGGATGAC GCCGACACTG TACTTGACTT TGATAATCAT
                                ACATGGATTG ACATAATACT TGTAGATGAC GCTGACACTG TACTCGACTT TGACAATCAT

                                CCTCCGACCC GGCATAGTTA TCACCACGTT ATTGGTGTTA CGATTAAGTC GCAGTCTCAG
                                CCTCCGCCAT GGCATGGCAG ACATAATATC ATTAATGTCT CTATCCGGAG GCAACCTCGG
                                CCTCCGCCAT GGCATGGCAG ACATAATATC ATTAATGTCT CTATCCGGAC GCAACCTCGG
                                CCTCCAACCT GGCACGGTCG TCACCATGTA CTTAGTGTCA CTATTAAAAC GAAACCTCAG
                                CCCCCAATCT GGCATGGTCG TCACCATGTA CTTAGTGTCA CTATTAAAAC GAAACCTCAG
                                CCTCCGCCAT GGCATGGCAG ACATAATATA ATTAATGTCT CTATCCAGAC ACAGCCTCGG
                                CCCCCAACCT GGCATGGTCG TCACCCTGTA CTTAGTGTCA CTATTAAAAC GAAACCTCAG
                                CCCCCGACCT GGCATAGTCG TCACCATGTA ATTAGTGTCA CTACTAAAAC GAAACCTCGG
                                CCTCCAACCT TGCATGGTCG TCACCATGTA CTTAGTGTCA CTATTAAAAC GAAACCTCAG
                                CCCCCGACCT GGCATGGTCG TCACCATGTA ATTAGTGTCA CTATTAAAAC GAAACCTCGG
                                CCTCCACCAT GGCACGGTAG ACATAATATA ATTAATGTTT CTGTCCGGAC ACAGCCTCGG
                                CCCCCAACCT GGCATGGTCG TCACCATGTA CTTAGTGTCA CTATTAAAAC GAAACCTCAG
                                CCTCCAACGT GGCATGGTCG TCACCATGTA CTTAGTGTCA CTATTAAAAC GAAACCTCAG
                                CCCCCGACTT GGCATGGTCG TCACCATGTA CTTAGCGTTA CTATTAAAAC GAAACCTCGG
                                CCTTCGCCAT GGTATGGTAG ACATAATATA ATTAATGATA CTGTCCGGAC ACAGCCTCGG
                                TCTCCGCCAT GGCATGGCAG ACATAATATA ATTAATGTCT CTATCCGGAC ACAGCCTCGA

                                GAGCTGACTG GTGATGGTTT TACTTATCGT GACTTTAAGA ATATTAATGA TGACGAACTG
                                GAACTGATCA GCGATTGTTT TACTTATCGT GACTTCAAGA ATATCAATAA TGACGAGCTG
                                GAACTGATCA GCGATTGTTT TACTTATCGT GACTTCAAGA ATATCAATAA TGACGAGCTG
                                GAACTGACCA GTGAATGTTT TACATACCGT GACTTTAAGA ATATCAATAA TGACGAACTG
                                GAACTGACAT GTGACTGTTT TACATACCAT GACTTTAAAA ATATCAATAA TGACGAACTG
                                GAACCGATCA GCGATTGTTT TACTTATCGT GACTTCAAGA ATATTAATAA TGACGAGCTG
                                GAACTGACCA GTGAATGTTT TACATTCCGT GACATTAAGA ATATCAATAA TGACGAACTG
                                GAACTGACCA GTGATAGTTT AACATATCGT GACTTTAAAA ATATCAATAA TGACGAACTG
                                GAACTGACCA GTGAATCTTT TACATACCGT GACTTTAAGA ATATCAATAA TGACGAACTG
                                GAAAGGACCA GTGATAGATT TACATATCgt gactttaaaa atatcaataa tgacGAATTG
                                GAGCTGATCA GCGATTGTTT TACTTATCTT GACTTTAAGA ATATCAATAA TGACGAGCTG
                                GAACTGACCA GTGAATGTTT TACATACCGT GATTTTAAGA ATATCAATAA TGATGAACTG
                                GAACTGACCA GTGCATGTTT TACATACCGT GACTTTAAGA ATATCAATAA TGACGAACTG
                                GAACTCGTCA GTGATTGTTT TACATACCGT GACTTTAAGA AT-------- ----------
                                GAGCTGATCG GCGATTGTTT TACTTATCGT GACTTTAAGA AT-------- ----------
                                GAACCGATCA GCGATTGTTT TACTTATCGT GACTTGAAGA AT-------- ----------

                                GTCGGTTTTC TGAGAGACTA CGACTGGTCT CGGTTT
                                ATCAGGTACC TCAGAGGCTG TGACTGG--- ------
                                ATCAGGTACC TCAGAGGCTG TGACTGG--- ------
                                GTCAGTTTCC TGAGAAGTTG TGACTGG--- ------
                                GTCAGGTTCC TGAGAAGCTG TGACTGG--- ------
                                ATCGGTTACC TCAGGGGCTG TGACTGG--- ------
                                GTCAGTTTCC TGAGAAGCTG TGACTGG--- ------
                                GTCAGTTTCC TGGGACGATG TGACTGG--- ------
                                GTCAGTTTCC TGAGA----- ---------- ------
                                GTCAGTTTCC TGAGA----- ---------- ------
                                ATCAGTTACC TTAGG----- ---------- ------
                                GTCAGTTTCC TGAGA----- ---------- ------
                                GTCAGTTTCC TGAGAAGCTG TGACTGG--- ------
                                ---------- ---------- ---------- ------
                                ---------- ---------- ---------- ------
                                ---------- ---------- ---------- ------

```

**Comment by Benjamin-Guinet** [comment]
Hi, I get the following error message: 

>>> result = cml.run(command="/beegfs/data/grindel/myconda/bin/codeml",verbose=True)
AAML in paml version 4.9, March 2015

```
error when opening file .
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/beegfs/data/soft/python_modules/Bio/Phylo/PAML/codeml.py", line 182, in run
    Paml.run(self, ctl_file, verbose, command)
  File "/beegfs/data/soft/python_modules/Bio/Phylo/PAML/_paml.py", line 127, in run
    % (command, result_code))
Bio.Phylo.PAML._paml.PamlError: /beegfs/data/grindelt/myconda/bin/codeml has failed (return code 255). Run with verbose = True to view error message
```

**Comment by peterjc** [comment]
It looks like you're going to have to run PAML directly to work out what is breaking, since I don't see any helpful error message that Biopython could pass on.

**Comment by peterjc** [comment]
@brandoninvergo As the author of Biopython's PAML wrapper, do you have any ideas?

**Comment by brandoninvergo** [comment]
I agree, first test the PAML tools outside of Biopython.

However, one thing jumps out at me: that's a nucleotide alignment and the verbose output indicates that AAML is running, which is for amino acid sequences.

One hint: try changing the sequence IDs in your alignment.  Make them much shorter and remove the special characters.  PAML has a pretty dumb Phylip parser (or maybe it strictly adheres to the original PHYLIP restrictions, I dunno).

But in any case, do make sure that it's working outside of Biopython first.

**Comment by peterjc** [comment]
Closing as no further information provided.
