### ISSUE TITLE
Failing doctests in C code

### ISSUE THREAD

**Issue by peterjc** [biopython/biopython#2350]
Cross reference #2347 (missing C doctests raising an exception on Python 2), Debian packaging team report issues under Python 3:

https://alioth-lists.debian.net/pipermail/debian-med-packaging/2019-November/074789.html

```
======================================================================
FAIL: kmedoids (Bio.Cluster._cluster)
Doctest: Bio.Cluster._cluster.kmedoids
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.8/doctest.py", line 2196, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for Bio.Cluster._cluster.kmedoids
  File "/build/python-biopython-1.75+dfsg/.pybuild/cpython3_3.8/build/Bio/Cluster/_cluster.cpython-38-x86_64-linux-gnu.so", line unknown line number, in kmedoids

----------------------------------------------------------------------
File "/build/python-biopython-1.75+dfsg/.pybuild/cpython3_3.8/build/Bio/Cluster/_cluster.cpython-38-x86_64-linux-gnu.so", line ?, in Bio.Cluster._cluster.kmedoids
Failed example:
    distance = array([[0.0, 1.1, 2.3],
                      [1.1, 0.0, 4.5],
                      [2.3, 4.5, 0.0]])
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python3.8/doctest.py", line 1328, in __run
        exec(compile(example.source, filename, "single",
      File "<doctest Bio.Cluster._cluster.kmedoids[0]>", line 1, in <module>
        distance = array([[0.0, 1.1, 2.3],
    NameError: name 'array' is not defined
----------------------------------------------------------------------
File "/build/python-biopython-1.75+dfsg/.pybuild/cpython3_3.8/build/Bio/Cluster/_cluster.cpython-38-x86_64-linux-gnu.so", line ?, in Bio.Cluster._cluster.kmedoids
Failed example:
    distance = array([1.1, 2.3, 4.5])
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python3.8/doctest.py", line 1328, in __run
        exec(compile(example.source, filename, "single",
      File "<doctest Bio.Cluster._cluster.kmedoids[1]>", line 1, in <module>
        distance = array([1.1, 2.3, 4.5])
    NameError: name 'array' is not defined
----------------------------------------------------------------------
File "/build/python-biopython-1.75+dfsg/.pybuild/cpython3_3.8/build/Bio/Cluster/_cluster.cpython-38-x86_64-linux-gnu.so", line ?, in Bio.Cluster._cluster.kmedoids
Failed example:
    distance = [array([]),
                array([1.1]),
                array([2.3, 4.5])]
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python3.8/doctest.py", line 1328, in __run
        exec(compile(example.source, filename, "single",
      File "<doctest Bio.Cluster._cluster.kmedoids[2]>", line 1, in <module>
        distance = [array([]),
    NameError: name 'array' is not defined


======================================================================
FAIL: pca (Bio.Cluster._cluster)
Doctest: Bio.Cluster._cluster.pca
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.8/doctest.py", line 2196, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for Bio.Cluster._cluster.pca
  File "/build/python-biopython-1.75+dfsg/.pybuild/cpython3_3.8/build/Bio/Cluster/_cluster.cpython-38-x86_64-linux-gnu.so", line unknown line number, in pca

----------------------------------------------------------------------
File "/build/python-biopython-1.75+dfsg/.pybuild/cpython3_3.8/build/Bio/Cluster/_cluster.cpython-38-x86_64-linux-gnu.so", line ?, in Bio.Cluster._cluster.pca
Failed example:
    columnmean + dot(coordinates, pc)
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python3.8/doctest.py", line 1328, in __run
        exec(compile(example.source, filename, "single",
      File "<doctest Bio.Cluster._cluster.pca[0]>", line 1, in <module>
        columnmean + dot(coordinates, pc)
    NameError: name 'columnmean' is not defined


======================================================================
FAIL: treecluster (Bio.Cluster._cluster)
Doctest: Bio.Cluster._cluster.treecluster
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.8/doctest.py", line 2196, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for Bio.Cluster._cluster.treecluster
  File "/build/python-biopython-1.75+dfsg/.pybuild/cpython3_3.8/build/Bio/Cluster/_cluster.cpython-38-x86_64-linux-gnu.so", line unknown line number, in treecluster

----------------------------------------------------------------------
File "/build/python-biopython-1.75+dfsg/.pybuild/cpython3_3.8/build/Bio/Cluster/_cluster.cpython-38-x86_64-linux-gnu.so", line ?, in Bio.Cluster._cluster.treecluster
Failed example:
    distance = array([[0.0, 1.1, 2.3],
                      [1.1, 0.0, 4.5],
                      [2.3, 4.5, 0.0]])
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python3.8/doctest.py", line 1328, in __run
        exec(compile(example.source, filename, "single",
      File "<doctest Bio.Cluster._cluster.treecluster[0]>", line 1, in <module>
        distance = array([[0.0, 1.1, 2.3],
    NameError: name 'array' is not defined
----------------------------------------------------------------------
File "/build/python-biopython-1.75+dfsg/.pybuild/cpython3_3.8/build/Bio/Cluster/_cluster.cpython-38-x86_64-linux-gnu.so", line ?, in Bio.Cluster._cluster.treecluster
Failed example:
    distance = array([1.1, 2.3, 4.5])
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python3.8/doctest.py", line 1328, in __run
        exec(compile(example.source, filename, "single",
      File "<doctest Bio.Cluster._cluster.treecluster[1]>", line 1, in <module>
        distance = array([1.1, 2.3, 4.5])
    NameError: name 'array' is not defined
----------------------------------------------------------------------
File "/build/python-biopython-1.75+dfsg/.pybuild/cpython3_3.8/build/Bio/Cluster/_cluster.cpython-38-x86_64-linux-gnu.so", line ?, in Bio.Cluster._cluster.treecluster
Failed example:
    distance = [array([]),
                array([1.1]),
                array([2.3, 4.5])]
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python3.8/doctest.py", line 1328, in __run
        exec(compile(example.source, filename, "single",
      File "<doctest Bio.Cluster._cluster.treecluster[2]>", line 1, in <module>
        distance = [array([]),
    NameError: name 'array' is not defined


----------------------------------------------------------------------
Ran 521 tests in 210.480 seconds

FAILED (failures = 1)
```

Evidently our continuous integration setup is not looking at the compiled C code modules - but the Debian test environment does.

**Comment by peterjc** [comment]
The ``Bio.Cluster._cluster.kmedoids`` and ``Bio.Cluster._cluster.treecluster`` doctest failures but look like a missing numpy import @mdehoon?

https://github.com/biopython/biopython/blob/master/Bio/Cluster/clustermodule.c#L1441
https://github.com/biopython/biopython/blob/master/Bio/Cluster/clustermodule.c#L1599

However, we need to tweak Travis and/or AppVeyor to include these C doctests tests...

**Comment by tillea** [comment]
Any news about this?  I'd love to update the Biopython Debian package.

**Comment by SoapGentoo** [comment]
We're running into this issue in Gentoo too, and it's blocking us from updating Biopython there too

**Comment by peterjc** [comment]
Can anyone see an simple tweak to the the Windows AppVeyor and/or the Linux TravisCI tox setup which would run the C doctests for us?

**Comment by tillea** [comment]
On Sun, Dec 08, 2019 at 02:42:42PM -0800, Peter Cock wrote:
> Can anyone see an simple tweak to the the Windows AppVeyor and/or the Linux TravisCI tox setup which would run the C doctests for us?
Sorry, no idea about Windows at all and I also did not used TravisCI directly.  What about trying a minimized [Debian Docker container](https://hub.docker.com/_/debian) and run your usual test suite in this manually.  Should be pretty similar to what happens in the chroot where the Debian package is built.

**Comment by mr-c** [comment]
@peterjc 
The issue is in `Tests/run_tests.py`

The correct path for loading the extensions is added to the system path:
https://github.com/biopython/biopython/blob/9e6a09cc5457e64a7e4170c06bf33663cd10d193/Tests/run_tests.py#L221

But `find_modules(path)` is only called on the source path:
https://github.com/biopython/biopython/blob/9e6a09cc5457e64a7e4170c06bf33663cd10d193/Tests/run_tests.py#L310

Due to the way Debian runs vs the way Travis CI runs, `find_modules` finds the extensions during the Debian build but not the Travis build

**Comment by mr-c** [comment]
I have a PR to fix the failing doctests (but not Travis CI lack of seeing them) at https://github.com/biopython/biopython/pull/2403

**Comment by peterjc** [comment]
I'm re-opening this for the underlying issue that we're not running the C doctests on TravisCI/AppVeyor - we need to look at ``Tests/run_tests.py``
