### ISSUE TITLE
Windows installation path clash with bio versus Bio

### ISSUE THREAD

**Issue by ondrejcinek** [biopython/biopython#2363]
### Setup

Dear Colleagues, 
I am reporting a problem with Biopython version, Python version, and operating
system as follows:

```C:\Program Files\Microsoft SDKs\Windows\v7.0>python
Python 3.6.8 (tags/v3.6.8:3c6b436a57, Dec 24 2018, 00:16:47) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import bio
>>> bio.__version__
'1.75'
>>> from bio import SeqIO
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Program Files\Python36\lib\site-packages\bio\SeqIO\__init__.py", line 344, in <module>
    from Bio._py3k import basestring
ModuleNotFoundError: No module named 'Bio'
>>>C:\Program Files\Microsoft SDKs\Windows\v7.0>python
Python 3.6.8 (tags/v3.6.8:3c6b436a57, Dec 24 2018, 00:16:47) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import bio
>>> bio.__version__
'1.75'
>>> from bio import SeqIO
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Program Files\Python36\lib\site-packages\bio\SeqIO\__init__.py", line 344, in <module>
    from Bio._py3k import basestring
ModuleNotFoundError: No module named 'Bio'
>>>
```

(*Please copy and run the above in your Python, and copy-and-paste the output*)

### Expected behaviour

from bio import SeqIO 
would import the module

### Actual behaviour

>>> from bio import SeqIO
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Program Files\Python36\lib\site-packages\bio\SeqIO\__init__.py", line 344, in <module>
    from Bio._py3k import basestring
ModuleNotFoundError: No module named 'Bio'

It appears that line 344 contains captialised Bio instead of lowercase bio

### Steps to reproduce
run in python 3.6.8 and biopython 1.75:
>>> from bio import SeqIO

**Comment by ondrejcinek** [comment]
However, it appears to be fixed by correcting the package directory name "bio" to "Bio"...

**Comment by peterjc** [comment]
As per our documentation, yes, you should use "Bio" (title case).

Python is case sensitive in most regards, but the Windows file system is not - which explains this otherwise puzzling behaviour. When you said "import bio" the system found the "Bio/" folder but makes the module available as "bio" (lower case) as instructed. But this means "Bio" (upper case B) has not been imported.

**Comment by ondrejcinek** [comment]
Well - thank you very much for such a prompt response!!

the problem actually is that the installer installs into a "bio" folder - so unless you manually rewrite its name, 'import Bio' now throws an error in Windows. 

 

It would be nice if you might rewrite the Windows installer options in order to name the newly created package folder Bio, not bio. 

 

Thanks a lot,

best wishes,

 

Ondrej

**Comment by ondrejcinek** [comment]
Well, but the biopython installer (in Windows) creates a directory named bio, not Bio. Consequently, the canonical import Bio throws an error...

**Comment by peterjc** [comment]
That is very strange.

How did you install Biopython? We stopped releasing the old ``*.exe`` or ``*.msi`` graphical Windows installers years ago.

What version of Windows are using? And do you know what file system (anything special like a networked drive, rather than a local hard drive)?

**Comment by ondrejcinek** [comment]
This is a brand new installation of python 3.6.8, via pip install biopython.

I seem to remember that a similar problem happened on my previous computer some four years ago.

The system is Win 10 Pro, v 1809, build 17763.864. Locale and keyboard is Czech.

The installation was performed on the local C drive, which is a RAID0 of two SSD's.

 

The Biopython ended up in C:\Program Files\Python36\Lib\site-packages\bio

 

Thanks a lot,

Ondrej

**Comment by peterjc** [comment]
It seems there is a known issue with ``pip`` and/or ``setuptools`` if the installation path already existed but with the wrong case: https://github.com/pypa/pip/issues/3309

However, I'm not aware of any other Python package which might claim ``Bio/`` or in this case ``bio/`` - are you?

Oh well, at least you could solve this.

**Comment by ondrejcinek** [comment]
Thanks a lot for the effort - yes, now I see how this can be reproduced. 

 

During installation of multiple packages on the new python, I probably first pip installed a package called 'bio' (by mistake, indeed). The package exists, please see https://pypi.org/project/bio/

This apparently created the 'bio' directory. Then, according to the bug description at pypa/pip#3309 <https://github.com/pypa/pip/issues/3309> , the Biopython ended up in this (wrong, lowercase) directory 'bio'.

 

So, yes, there is a name conflict with the package named (lowercase) bio, which when accidentally installed first on Windows, may cause the Biopython to crash.

 

Thanks a lot for solving the issue!

 

Ondrej

**Comment by MarkusPiotrowski** [comment]
I can remember that we had this problem already earlier, don't recall the issue. But the reason was exactly the same, that someone did `pip install Bio` instead of `pip install Biopython` at some point during installation which resulted in having the Biopython installation in a lowercase `bio` folder. 
Maybe this is something that can be checked during installation on Windows computers? That there is no existing `bio` folder in the installation path?

**Comment by MarkusPiotrowski** [comment]
Found the other issue #2238.

**Comment by chris-rands** [comment]
Cross-posted on SO: https://stackoverflow.com/questions/59080862/module-not-found-error-bio-in-miniconda-environment

Perhaps off-topic, but if biopython makes a new incompatible release someday, there could be some renaming. It would seem natural to `import biopython as bp` and module names should be lower case according to PEP8. The most common example I've seen of confusion from this is people doing `from Bio import Seq` instead of `from Bio.Seq import Seq`

**Comment by peterjc** [comment]
You're right Markus, this was a duplicate of #2238.

And I agree, the proposal on the pip issue to check for a pre-existing wrong-case folder on case-insensitive platforms would be a big improvement.

@chris-rands yes - I would want to switch to PEP8 compatible lower-case modules names in any major back-ward compatible version change, which would solve the module vs class confusion in several key parts of Biopython.

**Comment by HLAvieira** [comment]
> Well, but the biopython installer (in Windows) creates a directory incorrectly named bio, not Bio with a capital B. Consequently, the canonical import Bio throws an error... the only solution was to manually correct the folder name to 'Bio'.

For me, this was the only solution that worked, thank you very much

**Comment by MarkusPiotrowski** [comment]
> Well, but the biopython installer (in Windows) creates a directory incorrectly named bio, not Bio with a capital B. Consequently, the canonical import Bio throws an error... the only solution was to manually correct the folder name to 'Bio'.

I just want to add that the lowercase `bio` folder is not created by Biopython but by a different package which, unfortunately, uses the name `bio`. This happens when people do by mistake

```python
pip install bio
```
instead of 
```python
pip install biopython
```
@peterjc had contacted the author of the other package, with no response so far (afaik).

**Comment by chris-rands** [comment]
I wonder if there are multiple issues here?  If renaming `bio` to `Bio` sometimes 'works', then in some cases `bio` is created upon the installation of biopython i guess- Peter suggested somewhere this was related to https://github.com/pypa/pip/issues/3309

At least 1 user has also reported this on macOS with conda, so i'm also not clear it's specific to Windows https://stackoverflow.com/questions/60928176/error-in-conda-list-biopython-in-jupyter-notebook-macos

**Comment by ondrejcinek** [comment]
Yes, this was exactly what I did by mistake, my fault. Still, it might be useful to consider renaming Biopython components in accord with the current naming conventions for modules and packages.

**Comment by peterjc** [comment]
We can't rename ``Bio/`` and ``BioSQL/`` without breaking backward compatibility dramatically - to me that only makes sense as part of a larger Biopython v2 effort (which can also address other non-lowercase module names like ``Bio.SeqIO`` etc).

Sadly no reply yet on https://github.com/ylathouris/bio/issues/1

**Comment by chris-rands** [comment]
`ylathouris/bio` is "Used by" 99 other packages (via `requirements.txt`) but from what I can see, they are all meant to biopython, highlighting the scale of the confusion!

pyPI recommends the following process: https://www.python.org/dev/peps/pep-0541/#how-to-request-a-name-transfer

**Comment by peterjc** [comment]
Maybe.

If we go down the PyPI name clash resolution route, would we want to ensure "pip install bio" fails (if that is possible)? Or can we setup a replacement dummy package which just depends on the existing "biopython" package? Or we could opt to make separate ``Bio/`` and ``BioSQL/`` packages on PyPI, and make "biopython" a dummy package with those two as dependencies. Lots of questions.

**Comment by MarkusPiotrowski** [comment]
As already suggested [earlier](https://github.com/biopython/biopython/issues/2363#issuecomment-559597786), 
> Maybe this is something that can be checked during installation on Windows computers? That there is no existing `bio` folder in the installation path?

Possibly don't restrict this to Windows machines. This would solve the problem that a Biopython installation ends up in a `bio` folder. And I guess that will cover 99% of the problematic cases. 

Also, this is now a well known issue that we can publish somewhere, e.g. in a FAQ, in our installation instructions or elsewhere?

BTW,  `pip install bio` will also install in a Biopython `Bio` folder, overwriting it's `__init__.py` file. For this case we could possibly supply a copy of our `__init__.py` e.g. within a script `_repair.py`?

**Comment by peterjc** [comment]
Good idea on the FAQ, I agree that is overdue in fact.

And yes, ``pip install biopython`` followed by ``pip install bio`` is also going to break Biopython, although here I would expect reinstalling to fix it?

**Comment by ylathouris** [comment]
Hello,

I am the author/owner of the bio package on pypi. It was just a playground project. I have removed it from the following repositories:

- https://pypi.org/  
- https://test.pypi.org/

This will likely break the 100 packages that reference it as a dependency. However, it seemed like the lesser evil in this case.  This means you could make Biopython available under the name `bio` and it will be installable via `pip install bio`. 

Hope it helps!

Let me know if there is anything else I can do to help.

**Comment by peterjc** [comment]
Thank you @ylathouris - that is appreciated 💖

**Comment by ialbert** [comment]
Just to avoid any confusion here. I was unaware of this discussion here and a few hours ago I have asked @ylathouris  (in a private email) to release the name so that bioinformaticians can make use of it. He graciously agreed. Thanks again @ylathouris .

I requested the name since I am planning to develop a set of tools that, once installed will launch as:

```
bio fetch
bio align
bio convert
...
```

and cover a number of commonly needed bioinformatics operations (many of which will rely on BioPython).

I'd like to be able to install the package as 

    pip install bio

Since BioPython will be a dependency to `bio`, perhaps the original issue will be solved automatically with that. In the meantime, I went ahead and registered the package name on PyPI.

**Comment by peterjc** [comment]
I was thinking "bio" on PyPI could be a dummy package pointing at "biopython" but wasn't sure the best way to do that in practice.

@ialbert If you take "bio" on PyPI for your tool, what folder name would it use for any Python modules? If it uses "Bio/" it would clash with Biopython's code. If you use any case variation like "bio/" it still clash on case insensitive platforms like Windows which was the main problem here.

**Comment by ialbert** [comment]
@peterjc, I see, I'll avoid that module name to mitigate the problem - actually since the tool will depend on BioPython and it ought to be usable on Windows as well avoiding the `bio` as a folder name will be a necessity.

**Comment by peterjc** [comment]
Good. I'd prefer you avoided "bio" on PyPI but as long as you avoid "bio" (and any case variations) in the module names, things should be OK. Thank you.

**Comment by chris-rands** [comment]
@ialbert  According to the current [dependancy graph](https://github.com/ylathouris/bio/network/dependents), 126 repositories and 14 packages specify `bio`/`Bio` and it appears these are all accidental, where instead `biopython` was the intended dependancy. There are more examples outside of github repositories from issues/StackOverflow and I imagine users will continue to run `pip install bio` instead of `pip install biopython`. So, avoiding the `bio`/`Bio` module name is useful, but I fear that any `bio` name on PyPI will still be mixed-up with `biopython` in at least the short to medium term- do you have any suggestions on how to avoid this confusion? (In the long term, perhaps biopython will rename/restructure the modules to permit `import biopython`, but it's not likely because of backwards incompatibility)

**Comment by ialbert** [comment]
@chris-rands one "solution/mitigation" is that bio will depend on biopython, thus when installing `bio` people will get biopython installed automatically. 

The important issue as I understood is the case-insensitivity of the folder name, which is much harder to diagnose/troubleshoot.

**Comment by chris-rands** [comment]
> one "solution/mitigation" is that bio will depend on biopython, thus when installing bio people will get biopython installed automatically.

@ialbert I can see that helps, but it also means those people will be unaware they installed the bio package too. Also, in the future, you might want to remove biopython as a dependency for your package or fix the version like `biopython==1.76`

**Comment by peterjc** [comment]
Having "bio" on PyPI be a dummy package which depends on "biopython" (any version) seems OK. Having it depend on a pinned version sounds like trouble (unless we do matching releases which seems like a long term hassle).

Can we make "bio" on PyPI into a dummy package which prints a message via pip install that you should do "pip install biopython" instead? That would seem better.

**Comment by ialbert** [comment]
I think is that the Bio/bio problem caused by case insensitive folder names on Windows is a valid problem that developers should make some concerted effort to avoid. This is because the errors it leads to can be confusing, the diagnosis can be misleading, which could lead to lots of time wasted.

On the other hand, creating mock packages to indicate the "correct" module feels like a solution that tries to put a bandaid over a symptom rather than fixing the actual problem: have people list a correct dependency.  Perhaps an automated email could be generated to the maintainers of each package to notify them that they are listing the wrong dependency.

Printing a message is hardly a solution, it easily buried in the output, there is too much output during installation anyway. If you were to raise an error then it would preclude the code to install even if one had Biopython already installed.

**Comment by peterjc** [comment]
I'm not sure if you meant to suggest it, but a dummy "bio" on PyPI which would always fail to install might work (if we can make it fail with a custom message like "Don't depend on 'bio' in PyPI, you probably want 'biopython' instead.")

**Comment by ialbert** [comment]
If you follow the example to the end you'll see how it is not quite a proper solution. Suppose you do 

    pip install foo

and  `foo` depends on a package that deliberately fails with the error message you suggest. Now what? 

Will installing biopython fix the problem of not being to install/run `foo` ? No, because even after you've installed `biopython` the error remains:

    pip install foo 

will fail as before.  The user is even worse off than before. 

Before you could solve the problem by telling the user to install biopython.

Now the solution is to figure out where the requirements are located,  could be in several locations, perhaps not even the package that was downloaded, then to edit and list the correct package.  That is not a better solution IMHO.

**Comment by peterjc** [comment]
In that example, package foo is broken. Having a clear failure is probably the best case.

**Comment by peterjc** [comment]
We could start manually reporting issues where people are depending on "bio" when it should from from context be "biopython"...

**Comment by mdehoon** [comment]
I agree with @peterjc 's suggestion here. In the example of @ialbert , package `foo` is broken. We can provide a meaningful error message that allows the user to contact the developer of `foo` to let them know their package is broken. Beyond that, it is not our responsibility to fix `foo` or to provide a workaround.

**Comment by MarkusPiotrowski** [comment]
Coming back to the original problem. I hadn't had a look into it, but would it hard to check during installation if a lowercase "bio" folder does exist and then exit the installation?

**Comment by mdehoon** [comment]
@MarkusPiotrowski 
It's possible, but not so easy on Windows. Can somebody here run some tests on Windows?

**Comment by peterjc** [comment]
Just found https://pypi.org/project/precommit/ is an example of a dummy project where trying to install it triggers:

```
Exception: You probably meant to install and run pre-commit
```

This could be even clearer, but ``pip install precommit`` is wrong, should be ``pip install pre-commit``

We could do the same with ``pip install bio`` giving an error suggesting ``pip install biopython``
