### ISSUE TITLE
s390x: test_matrix_correlations: ndmin bigger than allowable number of dimensions NPY_MAXDIMS (=32)

### ISSUE THREAD

**Issue by mr-c** [biopython/biopython#2404]
Log: https://travis-ci.org/biopython/biopython/jobs/625300915#L845 & https://github.com/biopython/biopython/pull/2401#issuecomment-565821110

**Comment by peterjc** [comment]
To me at least the error message is contradictory:

```
======================================================================
ERROR: test_matrix_correlations (test_SubsMat.TestGeo)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/biopython/biopython/Tests/test_SubsMat.py", line 1511, in test_matrix_correlations
    correlation = SubsMat.two_mat_correlation(blosum30, blosum90)
  File "/home/travis/build/biopython/biopython/build/lib.linux-s390x-3.8/Bio/SubsMat/__init__.py", line 640, in two_mat_correlation
    correlation_matrix = numpy.corrcoef(values, rowvar=0)
  File "<__array_function__ internals>", line 5, in corrcoef
  File "/home/travis/build/biopython/biopython/.tox/py38-cover/lib/python3.8/site-packages/numpy/lib/function_base.py", line 2526, in corrcoef
    c = cov(x, y, rowvar)
  File "<__array_function__ internals>", line 5, in cov
  File "/home/travis/build/biopython/biopython/.tox/py38-cover/lib/python3.8/site-packages/numpy/lib/function_base.py", line 2381, in cov
    X = array(m, ndmin=2, dtype=dtype)
ValueError: ndmin bigger than allowable number of dimensions NPY_MAXDIMS (=32)
```

Clearly ``ndmin = 2 < 32 = NPY_MAXDIMS``, so at very least the message needs a tweak, and perhaps this test ought to be skipped on the s390x CPU?

**Comment by nimne** [comment]
It looks like this problem is related to this numpy issue: https://github.com/numpy/numpy/issues/14767. The fix was merged, so hopefully it's fixed in an upcoming release.

**Comment by peterjc** [comment]
Agreed, looks like we can safely ignore this as a numpy problem for now.
