### ISSUE TITLE
TravisCI failures with release of NumPy 1.18.0

### ISSUE THREAD

**Issue by peterjc** [biopython/biopython#2426]
NumPy 1.18.0 was released 22 December https://pypi.org/project/numpy/#history
https://numpy.org/devdocs/release/1.18.0-notes.html

At that point the master branch on TravisCI started failing, pypy3:

```
================================== log start ===================================
Collecting numpy
  Downloading https://files.pythonhosted.org/packages/31/0a/5df350c29a06835d534a6c4f5681075304da38d85f1c69e5226a635a67ce/numpy-1.18.0.zip (5.4MB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
Exception:
Traceback (most recent call last):
  File "/home/travis/build/biopython/biopython/.tox/pypy3-nocov/site-packages/pip/_internal/cli/base_command.py", line 179, in main
    status = self.run(options, args)
  File "/home/travis/build/biopython/biopython/.tox/pypy3-nocov/site-packages/pip/_internal/commands/install.py", line 315, in run
    resolver.resolve(requirement_set)
  File "/home/travis/build/biopython/biopython/.tox/pypy3-nocov/site-packages/pip/_internal/resolve.py", line 131, in resolve
    self._resolve_one(requirement_set, req)
  File "/home/travis/build/biopython/biopython/.tox/pypy3-nocov/site-packages/pip/_internal/resolve.py", line 294, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/home/travis/build/biopython/biopython/.tox/pypy3-nocov/site-packages/pip/_internal/resolve.py", line 242, in _get_abstract_dist_for
    self.require_hashes
  File "/home/travis/build/biopython/biopython/.tox/pypy3-nocov/site-packages/pip/_internal/operations/prepare.py", line 349, in prepare_linked_requirement
    abstract_dist.prep_for_dist(finder, self.build_isolation)
  File "/home/travis/build/biopython/biopython/.tox/pypy3-nocov/site-packages/pip/_internal/operations/prepare.py", line 149, in prep_for_dist
    reqs = self.req.pep517_backend.get_requires_for_build_wheel()
  File "/home/travis/build/biopython/biopython/.tox/pypy3-nocov/site-packages/pip/_vendor/pep517/wrappers.py", line 71, in get_requires_for_build_wheel
    'config_settings': config_settings
  File "/home/travis/build/biopython/biopython/.tox/pypy3-nocov/site-packages/pip/_vendor/pep517/wrappers.py", line 162, in _call_hook
    raise BackendUnavailable
pip._vendor.pep517.wrappers.BackendUnavailable
=================================== log end ====================================
```

This might be related to https://github.com/pypa/pip/issues/6100 and/or https://github.com/pypa/setuptools/issues/1644 somehow... see also:
https://pip.pypa.io/en/stable/reference/pip/?highlight=no-use-pep517#pep-517-and-518-support

ARM64 is also failing but in a different way, possibly a compile/dependency change:

```
...
ERROR: Could not build wheels for numpy which use PEP 517 and cannot be installed directly
```

**Comment by peterjc** [comment]
We already have the latest pip and setuptools before installing tox:

https://github.com/biopython/biopython/blob/biopython-176/.travis.yml#L189

```
# This is minimal and used under all stages
install:
  - pip install --upgrade pip setuptools
  - pip install tox
  - tox -c .travis-tox.ini -e $TOXENV --notest
```

However, perhaps we need to specify setuptools explicitly within the Tox environments...

**Comment by peterjc** [comment]
I have tried but failed to reproduce this using pypy3 locally on 64-bit Linux.
