### ISSUE TITLE
test_ColorSpiral missing cmath dependency

### ISSUE THREAD

**Issue by kblin** [biopython/biopython#2583]
### Setup

I am reporting a problem with Biopython version, Python version, and operating
system as follows:

```python
import sys; print(sys.version)
import platform; print(platform.python_implementation()); print(platform.platform())
import Bio; print(Bio.__version__)
```

(*Please copy and run the above in your Python, and copy-and-paste the output*)

### Expected behaviour

Tests pass on a clean checkout with all named dependencies installed.

### Actual behaviour

```
test_ColorSpiral ... loading tests failed:
Failed to import test module: test_ColorSpiral
Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/loader.py", line 153, in loadTestsFromName
    module = __import__(module_name)
  File "/home/kai/dev/libs/biopython/Tests/test_ColorSpiral.py", line 14, in <module>
    from cmath import rect
ModuleNotFoundError: No module named 'cmath'
```

### Steps to reproduce

__In a Python 3.6.8 virtualenv__

```
git clone https://github.com/biopython/biopython
cd biopython
pip3 install -e .
python3 setup.py build
python3 setup.py test
```

**Comment by kblin** [comment]
Ah, sorry, just saw that I forgot to paste my Python info
```
3.6.9 (default, Nov  7 2019, 10:44:02) 
[GCC 8.3.0]
CPython
Linux-4.15.0-72-generic-x86_64-with-Ubuntu-18.04-bionic
/home/kai/dev/libs/biopython/Bio/__init__.py:129: BiopythonWarning: You may be importing Biopython from inside the source tree. This is bad practice and might lead to downstream issues. In particular, you might encounter ImportErrors due to missing compiled C extensions. We recommend that you try running your code from outside the source tree. If you are outside the source tree then you have a setup.py file in an unexpected directory: /home/kai/dev/libs/biopython.
  BiopythonWarning,
1.77.dev0
```

**Comment by kblin** [comment]
Hm, I just retested my reproducer and can't reproduce after all, so I must have been seeing things.
