### ISSUE TITLE
Support NCBI GenBank Targeted Locus Study (TLS)

### ISSUE THREAD

**Issue by peterjc** [biopython/biopython#2620]
Targeted Locus Study (TLS) are defined here: https://www.ncbi.nlm.nih.gov/genbank/tls/

Example https://www.ncbi.nlm.nih.gov/nuccore/KBUV00000000.1

```
LOCUS       KBUV01000000            3714 rc    DNA     linear   ENV 26-FEB-2018
DEFINITION  TLS: soil metagenome 16S ribosomal RNA, targeted locus study.
ACCESSION   KBUV00000000
VERSION     KBUV00000000.1
DBLINK      BioProject: PRJNA420556
            BioSample: SAMN08114915
KEYWORDS    TLS; Targeted Locus Study.
SOURCE      soil metagenome
  ORGANISM  soil metagenome
            unclassified sequences; metagenomes; ecological metagenomes.
REFERENCE   1  (bases 1 to 3714)
  AUTHORS   Buscardo,E., Geml,J., Schmidt,S., Freitas,H., Brandao,H. and
            Nagy,L.
  TITLE     Spatio-temporal dynamics of soil bacterial communities in function
            of Amazon forest phenology
  JOURNAL   Unpublished
REFERENCE   2  (bases 1 to 3714)
  AUTHORS   Buscardo,E., Geml,J., Schmidt,S., Freitas,H., Brandao,H. and
            Nagy,L.
  TITLE     Direct Submission
  JOURNAL   Submitted (22-NOV-2017) Centre for Functional Ecology, University
            of Coimbra, Calcada Martim de Freitas, Coimbra, Portugal
COMMENT     The soil metagenome targeted locus study (TLS) project has the
            project accession KBUV00000000.  This version of the project (01)
            has the accession number KBUV01000000, and consists of sequences
            KBUV01000001-KBUV01003714.
FEATURES             Location/Qualifiers
     source          1..3714
                     /organism="soil metagenome"
                     /mol_type="genomic DNA"
                     /isolation_source="soil samples in a lowland tropical
                     evergreen rain forest in Amazonia"
                     /db_xref="taxon:410658"
                     /environmental_sample
                     /country="Brazil: Manaus"
                     /lat_lon="2.92 S 59.95 W"
                     /collection_date="2013"
                     /note="metagenomic"
TLS         KBUV01000001-KBUV01003714
//
```

Note the LOCUS line is in units of read count (``rc``) not base pairs (``bp``) or amino acids (``aa``).

Just like WGS and transcriptome shotgun assembly records (TSA, see #2268), these do not have a sequence of their own - they are like a table of contents pointing at other accessions.

By following the work from @kblin on #2269 for TSA files, I think this would be straightforward enough to make a good issue for a first time contributor.

**Comment by peterjc** [comment]
If you try to parse this file with a recent Biopython it should fail as follows:

```
$ python -c "from Bio import SeqIO; print(SeqIO.read('KDHP01000000.gb', 'gb'))"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/xxx/miniconda3/lib/python3.7/site-packages/Bio/SeqIO/__init__.py", line 730, in read
    first = next(iterator)
  File "/Users/xxx/miniconda3/lib/python3.7/site-packages/Bio/GenBank/Scanner.py", line 515, in parse_records
    record = self.parse(handle, do_features)
  File "/Users/xxx/miniconda3/lib/python3.7/site-packages/Bio/GenBank/Scanner.py", line 498, in parse
    if self.feed(handle, consumer, do_features):
  File "/Users/xxx/miniconda3/lib/python3.7/site-packages/Bio/GenBank/Scanner.py", line 469, in feed
    self._feed_feature_table(consumer, self.parse_features(skip=False))
  File "/Users/xxx/miniconda3/lib/python3.7/site-packages/Bio/GenBank/Scanner.py", line 175, in parse_features
    raise ValueError("Premature end of features table, marker '//' found")
ValueError: Premature end of features table, marker '//' found
```

**Comment by Andrey-Raspopov** [comment]
I've created PR with minimal support. As I can see, there were no further commits addressing TSA as well, do we want to expand on that in Record?

**Comment by peterjc** [comment]
There is scope to do something with the TSA and TLS lines on output and in the Record class. If you have a motivating use case, great - otherwise improving round trip data preservation is a good guide.

**Comment by peterjc** [comment]
Closing with #22662 merged - although there is room for further work here on output etc. Thank you!
