### ISSUE TITLE
Errors running test_Tutorial, chapter Entrez

### ISSUE THREAD

**Issue by svalqui** [biopython/biopython#2725]
### Setup

I am reporting a problem with Biopython version, Python version, and operating
system as follows:

```python
import sys; print(sys.version) 3.6.9 (default, Nov  7 2019, 10:44:02) [GCC 8.3.0]
import platform; print(platform.python_implementation()); print(platform.platform())
CPython
Linux-4.15.0-76-generic-x86_64-with-Ubuntu-18.04-bionic
import Bio; print(Bio.__version__)
1.77.dev0
```

### Expected behaviour

Run the test and pass it

### Actual behaviour

```
Python version: 3.6.9 (default, Nov  7 2019, 10:44:02) 
[GCC 8.3.0]
Operating system: posix linux
test_Tutorial ... FAIL
======================================================================
ERROR: test_doctests (test_Tutorial.TutorialTestCase)
Run tutorial doctests.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/sergio/PythonProjects/biopython/Tests/test_Tutorial.py", line 256, in test_doctests
    (len(failures), ", ".join(failures)))
ValueError: 4 Tutorial doctests failed: test_chapter_entrez_line_00202, test_chapter_entrez_line_00325, test_chapter_entrez_line_00419, test_chapter_entrez_line_00466

----------------------------------------------------------------------
Ran 1 test in 48.020 seconds

FAILED (failures = 1)
```
### Steps to reproduce

Build, install and run the test:
```
~/PythonProjects/biopython$ sudo python3 setup.py build
~/PythonProjects/biopython$ sudo python3 setup.py install
~/PythonProjects/biopython$ cd Tests/
~/PythonProjects/biopython/Tests$ python3 run_tests.py test_Tutorial.py
```

**Comment by peterjc** [comment]
Links pointing at the current master branch tip, which should be the same as what you used in terms of ``Bio.Entrez`` and the tutorial,
 
- test_chapter_entrez_line_00202 -https://github.com/biopython/biopython/blob/bbfefc134fff6ae9cf2838b1e4dbdba560e1bc51/Doc/Tutorial/chapter_entrez.tex#L202
- test_chapter_entrez_line_00325 - https://github.com/biopython/biopython/blob/bbfefc134fff6ae9cf2838b1e4dbdba560e1bc51/Doc/Tutorial/chapter_entrez.tex#L325
- test_chapter_entrez_line_00419 - https://github.com/biopython/biopython/blob/bbfefc134fff6ae9cf2838b1e4dbdba560e1bc51/Doc/Tutorial/chapter_entrez.tex#L419
- test_chapter_entrez_line_00466 - https://github.com/biopython/biopython/blob/bbfefc134fff6ae9cf2838b1e4dbdba560e1bc51/Doc/Tutorial/chapter_entrez.tex#L466

**Comment by peterjc** [comment]
Can you run ``tests_Tutorial.py`` directly? That gives some big clues:

```
$ python test_Tutorial.py
**********************************************************************
File "test_Tutorial.py", line 240, in __main__.TutorialDocTestHolder.doctest_test_chapter_entrez_line_00202
Failed example:
    "19304878" in record["IdList"]
Expected:
    True
Got:
    False
**********************************************************************
...
**********************************************************************
File "test_Tutorial.py", line 240, in __main__.TutorialDocTestHolder.doctest_test_chapter_entrez_line_00419
Failed example:
    record = SeqIO.read(handle, "genbank")
Exception raised:
    Traceback (most recent call last):
      File "/Users/pc40583/miniconda3/lib/python3.7/doctest.py", line 1329, in __run
        compileflags, 1), test.globs)
      File "<doctest __main__.TutorialDocTestHolder.doctest_test_chapter_entrez_line_00419[6]>", line 1, in <module>
        record = SeqIO.read(handle, "genbank")
      File "/Users/pc40583/repositories/biopython/Bio/SeqIO/__init__.py", line 730, in read
        raise ValueError("More than one record found in handle")
    ValueError: More than one record found in handle
**********************************************************************
...
**********************************************************************
File "test_Tutorial.py", line 241, in __main__.TutorialDocTestHolder.doctest_test_chapter_entrez_line_00466
Failed example:
    record[0]["GBSeq_definition"]
Expected:
    'Selenipedium aequinoctiale maturase K (matK) gene, partial cds; chloroplast'
Got:
    'Giant Panda satellite 1 DNA'
**********************************************************************
...
```

Note you'll see multiple errors from some of these, the first is usually the key.

There seems to be something very strange with Giant Panda results coming back unexpectedly...

**Comment by MarkusPiotrowski** [comment]
This is possibly related to #2707? Could it be that there is always an `efetch` call with single IDs as string?

**Comment by peterjc** [comment]
Very likely linked, yes.

**Comment by MarkusPiotrowski** [comment]
At least a few of them may be related to #2707. But also some examples may need updating, e.g.
```
>>> handle = Entrez.esearch(db="pubmed", term="biopython")
>>> record = Entrez.read(handle)
>>> record["IdList"]
['32044951', '31762715', '31278684', '31069053', '30013827', '29641230', '28011774', '24929426', '24497503', '24267035', '24194598', '23842806', '23157543', '22909249', '22399473', '21666252', '21210977', '20015970', '19811691', '19773334']
>>> "19304878" in record["IdList"]
False
```
with Biopython 1.76

**Comment by svalqui** [comment]
I'll work on test_chapter_entrez_line_00202.
esearch returns 20 UIDs by default, "19304878" is not included in the first 20.

**Comment by MarkusPiotrowski** [comment]
Sorting the result list may be an option? It seems they are retrieved in the order from "more recent" to "less recent"

**Comment by svalqui** [comment]
That address the first issue, the rest are efetch so I'll wait for #2707 before reviewing it.

**Comment by svalqui** [comment]
@peterjc after #2707 the test now passes, this can be closed.
@MarkusPiotrowski  Thank you.

```
~/PythonProjects/biopython/Tests$  python3 run_tests.py test_Tutorial.py
Python version: 3.6.9 (default, Nov  7 2019, 10:44:02) 
[GCC 8.3.0]
Operating system: posix linux
test_Tutorial ... ok
----------------------------------------------------------------------
Ran 1 test in 32.018 seconds

```

**Comment by peterjc** [comment]
Excellent, thanks all.
