### ISSUE TITLE
PIL Version Error ( Unable To Open Cinnamon Settings )

### ISSUE THREAD

**Issue by LWFlouisa** [biopython/biopython#2794]
### Setup

I'm not sure if this is a Python error or a Linux Mint 19.1 error:

~~~
Traceback (most recent call last):
  File "/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py", line 619, in <module>
    window = MainWindow()
  File "/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py", line 247, in __init__
    for module in modules:
  File "/usr/share/cinnamon/cinnamon-settings/modules/cs_backgrounds.py", line 5, in <module>
    import imtools
  File "/usr/share/cinnamon/cinnamon-settings/bin/imtools.py", line 623, in <module>
    if Image.VERSION == '1.1.7':
AttributeError: module 'PIL.Image' has no attribute 'VERSION'
~~~

Whenever I try to install PIL, it has no matching version. I just want my cinnamon-settings to get back to normal.

**Comment by peterjc** [comment]
What does this have to do with Biopython?

Note PIL is a defunct Python library for working with images, you probably want the replacement Pillow library instead.

Cross reference https://github.com/biopython/biopython/issues/1995#issuecomment-597335695 where you also commented.

**Comment by peterjc** [comment]
Closing given here https://github.com/biopython/biopython/issues/1995#issuecomment-597352365 you said it was working for you
