### ISSUE TITLE
string formatting error when loading PDB

### ISSUE THREAD

**Issue by collinarnett** [biopython/biopython#2842]
### Setup

I am reporting a problem with Biopython version, Python version, and operating
system as follows:

```python
import sys; print(sys.version)
import platform; print(platform.python_implementation()); print(platform.platform())
import Bio; print(Bio.__version__)
```

3.6.9 (default, Nov  7 2019, 10:44:02) 
[GCC 8.3.0]
CPython
Linux-4.15.0-96-generic-x86_64-with-Ubuntu-18.04-bionic
1.76

### Expected behaviour

Structure loaded succesfully

### Actual behaviour

"""
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "<ipython-input-7-16c1a618ba3e>", line 10, in generate_maps
    structure = parser.get_structure('X', files)
  File "/home/collin/.virtualenvs/protein_gan/lib/python3.6/site-packages/Bio/PDB/PDBParser.py", line 92, in get_structure
    self._parse(lines)
  File "/home/collin/.virtualenvs/protein_gan/lib/python3.6/site-packages/Bio/PDB/PDBParser.py", line 115, in _parse
    self.trailer = self._parse_coordinates(coords_trailer)
  File "/home/collin/.virtualenvs/protein_gan/lib/python3.6/site-packages/Bio/PDB/PDBParser.py", line 241, in _parse_coordinates
    resname, hetero_flag, resseq, icode
  File "/home/collin/.virtualenvs/protein_gan/lib/python3.6/site-packages/Bio/PDB/StructureBuilder.py", line 177, in init_residue
    self.chain.add(self.residue)
  File "/home/collin/.virtualenvs/protein_gan/lib/python3.6/site-packages/Bio/PDB/Entity.py", line 215, in add
    raise PDBConstructionException("%s defined twice" % entity_id)
TypeError: not all arguments converted during string formatting
"""

### Steps to reproduce

let me run my hour long job again with logging this time to find out which file it is.
Edit: it's 4uu7

**Comment by peterjc** [comment]
Looks like ``entity_id`` is a tuple, a corner case with the Python % string formatting. Probably switching to a new Python 3 style f-string would be the simplest fix:

```python
raise PDBConstructionException(f"{entity_id} defined twice")
```

Can you try making that change? Either by installing from source, or as a quick hack editing ``/home/collin/.virtualenvs/protein_gan/lib/python3.6/site-packages/Bio/PDB/Entity.py`` directly for debugging purposes only.

**Comment by collinarnett** [comment]
@peterjc Sorry for getting around to this so late.

Other than a bunch of Biopython warnings, your suggestion worked.

**Comment by collinarnett** [comment]
I can submit a PR but I assume if you want f-strings to be the new method of string formatting you would want to change all the instances at once.

**Comment by peterjc** [comment]
Given this is a bug fix, I would prioritise that one string. So the tiny pull request would be welcome.

From a stylistic point of view, the Biopython developers are not yet making any mass string formatting style changes, see #2510
