### ISSUE TITLE
extractDataBlastXMLBiopython --> ('*', 'M') KeyError: ('*', 'M')

### ISSUE THREAD

**Issue by narsapuramvijaykumar** [biopython/biopython#2843]
### Setup

I am reporting a problem with Biopython version, Python version, and operating
system as follows:

```python
import sys; print(sys.version)
import platform; print(platform.python_implementation()); print(platform.platform())
import Bio; print(Bio.__version__)
```
'2.7.2 (default, Apr 21 2015, 13:01:47) \n[GCC 4.4.7 20120313 (Red Hat 4.4.7-4)]'
'CPython';'Linux-2.6.32-696.30.1.el6.x86_64-x86_64-with-redhat-6.9-Santiago'
'1.60'

### Expected behaviour

The extractDataBlastXMLBiopython has to parse the blast xml generated by psiblast and return the extracted data

### Actual behaviour
2020-04-20 14:12:52,257 : -->Error in extractDataBlastXMLBiopython --> ('*', 'M')
Traceback (most recent call last):
  File "/home/blastXMLParser.py", line 45, in extractDataBlastXMLBiopython
    pctIdFounder = alignmentBiopy.align_sequences(dict_record_query[qresult.id],dict_record_pep[each_hit.id])
  File "/home/alignmentBiopy.py", line 48, in align_sequences
    penalize_end_gaps=(False, False) )
  File "/home/Bio/pairwise2.py", line 317, in __call__
    return _align(**keywds)
  File "/home/Bio/pairwise2.py", line 338, in _align
    score_only)
  File "/home/Bio/pairwise2.py", line 489, in _make_score_matrix_fast
    score = match_fn(sequenceA[0], sequenceB[i])
  File "/home/Bio/pairwise2.py", line 818, in __call__
    return self.score_dict[(charA, charB)]
KeyError: ('*', 'M')

### Steps to reproduce

for qresult in SearchIO.parse(blast_xml_output,'blast-xml'):
            for each_hit in qresult:
                for each_hsp in each_hit:
                    #percentage Identity of input query verses the hit peptide sequence over full length of peptide
                    pctIdFounder = alignmentBiopy.align_sequences(dict_record_query[qresult.id],dict_record_pep[each_hit.id])

Let me know, if you need any additional data..!!

Regards,
Vijay N

**Comment by peterjc** [comment]
Your example is not self contained - can you grab the two failing sequences ``dict_record_query[qresult.id]`` and ``dict_record_pep[each_hit.id]`` so the example becomes something like:

```python
# import lines here
query_seq = "..."
pep_seq = "..."
#percentage Identity of input query verses the hit peptide sequence over full length of peptide
pctIdFounder = alignmentBiopy.align_sequences(query_seq, pep_seq)
```

**Comment by narsapuramvijaykumar** [comment]
Thanks @peterjc . It got rectified the error is because of the "*" character in my "pep_seq".
I removed and character and it runs fine..!! 
Out of curiosity, Is there a  scope in Biopython to incoorporate the "*" character exception and try to ignore it when it come across such cases..!!

PS: Sorry for the delayed response

Thanks,
Vijay N

**Comment by peterjc** [comment]
Are you saying you have the empty string as a character in your peptide? If so, I don't understand why or how, but that fits with the exception message ``KeyError: ('', 'M')`` that the combination empty string and letter M has not been defined.

Could you make a self contained example as requested earlier?

**Comment by narsapuramvijaykumar** [comment]
IT was not empty string, its star character "*", Below is the example
>GCF_001296435_00003 hypothetical protein
MNKIAELRKEKLISQEKLAEQVGLSRTYISEIENNKKQPNVKLAIKIAKVLGTSVESIFG
TTCKL*

**Comment by peterjc** [comment]
I see what confused me, I have edited your initial post to use triple-back-ticks round the quoted output. Now ``KeyError: ('*', 'M')`` appears instead of ``KeyError: ('', 'M')`` which is what was confusing me.

**Comment by peterjc** [comment]
Belated closing as resolved.

**Comment by mdehoon** [comment]
@narsapuramvijaykumar 

We are adding some convenience functions to `Bio.Align`, which similar functionality as the functions provided by `Bio.pairwise2`. If you have any comments or suggestions for these convenience functions, please let us know at issue #5290.
