### ISSUE TITLE
SeqIO.read GenBank Parser Error

### ISSUE THREAD

**Issue by dnanto** [biopython/biopython#2859]
### Setup

I am reporting a problem with Biopython version, Python version, and operating
system as follows:

```python
>>> import sys; print(sys.version)
3.7.7 (default, Mar 23 2020, 17:31:31) 
[Clang 4.0.1 (tags/RELEASE_401/final)]
>>> import platform; print(platform.python_implementation()); print(platform.platform())
CPython
Darwin-18.7.0-x86_64-i386-64bit
>>> import Bio; print(Bio.__version__)
1.76
```

### Expected behaviour

Successfully read the GenBank record.

### Actual behaviour

```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/dnanto/miniconda3/lib/python3.7/site-packages/Bio/SeqIO/__init__.py", line 744, in read
    first = next(iterator)
  File "/Users/dnanto/miniconda3/lib/python3.7/site-packages/Bio/GenBank/Scanner.py", line 516, in parse_records
    record = self.parse(handle, do_features)
  File "/Users/dnanto/miniconda3/lib/python3.7/site-packages/Bio/GenBank/Scanner.py", line 499, in parse
    if self.feed(handle, consumer, do_features):
  File "/Users/dnanto/miniconda3/lib/python3.7/site-packages/Bio/GenBank/Scanner.py", line 466, in feed
    self._feed_header_lines(consumer, self.parse_header())
  File "/Users/dnanto/miniconda3/lib/python3.7/site-packages/Bio/GenBank/Scanner.py", line 1802, in _feed_header_lines
    structured_comment_key
KeyError: 'Assembly-Data'
```

### Steps to reproduce

```bash
efetch -db nuccore -id MF993533.1 -format gb > MF993533.1.gbk
python -c 'from Bio import SeqIO; SeqIO.read("MF993533.1.gbk", "gb");'
```

### Suggestion

* Add a degree a permissiveness?
* Ignore this kind of `KeyError`?

**Comment by peterjc** [comment]
Sounds just like #2844 which was hopefully fixed in #2851. Are you able to install the latest Biopython from source and retest?

Again https://www.ncbi.nlm.nih.gov/nuccore/MF993533.1 looks to have a stray trailing full stop in the structured comment:

```
LOCUS       MF993533               11391 bp    RNA     linear   VRL 01-SEP-2019
DEFINITION  Mucambo virus strain AR816662, complete genome.
ACCESSION   MF993533
VERSION     MF993533.1
KEYWORDS    .
SOURCE      Mucambo virus
  ORGANISM  Mucambo virus
            Viruses; ssRNA viruses; ssRNA positive-strand viruses, no DNA
            stage; Togaviridae; Alphavirus.
REFERENCE   1  (bases 1 to 11391)
  AUTHORS   Araujo,P.A., Casseb,S.M., Ferreira,M.S., Silva,S.P., Silva,F.A.,
            Martins,L.C., Chiang,J.O., Cruz,A.C.R. and Vasconcelos,P.F.C.
  TITLE     Genomic detection and Phylogenetic Analysis of Mucambo virus from
            hematophagus arthropods of Caxiuana Nacional Forest, municipality
            of Melgaco, Para
  JOURNAL   Unpublished
REFERENCE   2  (bases 1 to 11391)
  AUTHORS   Araujo,P.A., Casseb,S.M., Ferreira,M.S., Silva,S.P., Silva,F.A.,
            Martins,L.C., Chiang,J.O., Cruz,A.C.R. and Vasconcelos,P.F.C.
  TITLE     Direct Submission
  JOURNAL   Submitted (22-SEP-2017) Section of Arbovirology and Hemorrhagic
            Fevers, Evandro Chagas Institute, Highway BR 316, Ananindeua, Para
            67030-000, Brazil
COMMENT     EMAIL: pedroarthuraraujo@yahoo.com.br
            ##Assembly-Data-START##
            Assembly method: IDBA-UD
            Sequencing Technology: MiniSeq
            ##Assembly-Data-END##.
FEATURES             Location/Qualifiers
...
```

Also, please report this to the NCBI

CC @biologyguy; maybe this is a widespread issue not just one or two problem records?

**Comment by dnanto** [comment]
I built from source on my other laptop
```python
>>> import sys; print(sys.version)
3.7.6 (default, Jan  8 2020, 13:42:34) 
[Clang 4.0.1 (tags/RELEASE_401/final)]
>>> import platform; print(platform.python_implementation()); print(platform.platform())
CPython
Darwin-19.4.0-x86_64-i386-64bit
>>> import Bio; print(Bio.__version__)
1.77.dev0
```

and it worked, generating a warning:
>>> from Bio import SeqIO
>>> SeqIO.read("MF993533.1.gbk", "gb")
/Users/dnanto/miniconda3/lib/python3.7/site-packages/biopython-1.77.dev0-py3.7-macosx-10.9-x86_64.egg/Bio/GenBank/Scanner.py:1809: BiopythonParserWarning: Structured comment not parsed for MF993533. Is it malformed?
  BiopythonParserWarning,
SeqRecord(seq=Seq('ATGGGCGGCGTATGAGAGTAGCCCAAATTAAAACTACCCATTATGGAGAAAGTT...TTC', IUPACAmbiguousDNA()), id='MF993533.1', name='MF993533', description='Mucambo virus strain AR816662, complete genome', dbxrefs=[])

Thanks for the quick response! Hopefully it's not so widespread...

**Comment by biologyguy** [comment]
Looks like maybe they updated the record? I'm not seeing the malformed structured comment in MF993533. Also, AYW00820 seems to be fixed as well, which coincidentially, is related to MF993533 (both from the same group of submissions). I'm guessing it's relatively isolated but I'm happy to make further changes if it starts to crop up more frequently.
