### ISSUE TITLE
Feature request: add support for NeXML <network> 

### ISSUE THREAD

**Issue by Artoria2e5** [biopython/biopython#2876]
### Setup

I am reporting a problem with Biopython version, Python version, and operating
system as follows:

```
3.7.7 (default, Mar 23 2020, 02:22:49) 
[Clang 11.0.0 (clang-1100.0.33.17)]
CPython
Darwin-19.4.0-x86_64-i386-64bit
1.76
```

### Expected behaviour

With the NeXML below, biopython should be able to recover the edges and attempt to make a cladogram (duplicate edges? that's fine, graphviz &c. can eat that):

<details><summary>Code sample (py3 & xml)</summary>

```XML
<nex:nexml
   version="0.9"
   generator="eclipse"
   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance "
   xmlns:xml="http://www.w3.org/XML/1998/namespace"
   xmlns:nex="http://www.nexml.org/2009"
   xmlns="http://www.nexml.org/2009"
   xsi:schemaLocation="http://www.nexml.org/2009 http://www.nexml.org/2009/nexml.xsd">
<otus id="tax1">
   <otu id="t1"/>
   <otu id="t2"/>
   <otu id="t3"/>
   <otu id="t4"/>
   <otu id="t5"/>
</otus>
<trees otus="tax1" id="Trees" label="TreesBlockFromXML">
<network id="tree3" xsi:type="nex:IntNetwork" label="tree2">
  <node id="n1" label="n1" root="true"/>
  <node id="n2" label="n2" otu="t1"/>
  <node id="n3" label="n3"/>
  <node id="n4" label="n4"/>
  <node id="n5" label="n5" otu="t3"/>
  <node id="n6" label="n6" otu="t2"/>
  <node id="n7" label="n7"/>
  <node id="n8" label="n8" otu="t5"/>
  <node id="n9" label="n9" otu="t4"/>
  <edge source="n1" target="n3" id="e1" length="1"/>
  <edge source="n1" target="n2" id="e2" length="2"/>
  <edge source="n3" target="n4" id="e3" length="3"/>
  <edge source="n3" target="n7" id="e4" length="1"/>
  <edge source="n4" target="n5" id="e5" length="2"/>
  <edge source="n4" target="n6" id="e6" length="1"/>
  <edge source="n7" target="n6" id="e7" length="1"/> <!-- extra edge -->
  <edge source="n7" target="n8" id="e7" length="1"/>
  <edge source="n7" target="n9" id="e8" length="1"/>
</network></trees></nex:nexml>
```

```Python
from Bio import Phylo
tree = Phylo.read("1.nexml", "nexml")
print(tree)
```

</details>

### Actual behaviour

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/Bio/Phylo/_io.py", line 62, in read
    tree = next(tree_gen)
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "1.py", line 2, in <module>
    tree = Phylo.read("1.nexml", "nexml")
  File "/usr/local/lib/python3.7/site-packages/Bio/Phylo/_io.py", line 64, in read
    raise ValueError("There are no trees in this file.")
ValueError: There are no trees in this file.
```

### Steps to reproduce
Create the NeXML file as `1.nexml` and the Python file as `1.py`. Run `python3 `1.py`.

**Comment by Artoria2e5** [comment]
A simple way to "just get it to work" is to have the tree-parsing code also accept `nex:network`. The connectivity works just fine, and clades do make some degree of sense despite the repetition:

```Python
from Bio import Phylo
import networkx as nx
import sys
tree = Phylo.read("1.nexml", "nexml")
print(tree)
nx.nx_pydot.write_dot(Phylo.to_networkx(tree), sys.stdout)
```
