### ISSUE TITLE
Make Seq translate method compatible with string method?

### ISSUE THREAD

**Issue by peterjc** [biopython/biopython#2968]
We have discussed making the ``Seq`` object subclass the Python string. Additional methods are fine (e.g. ``.reverse_complete(...)``) but changes in meaning are more tricky. Currently the ``.translate(...)`` method is very different, and does not attempt to match the Python string behaviour went it might be inferred (rather it raises a specific exception):

https://github.com/biopython/biopython/blob/biopython-177/Bio/Seq.py#L1162

This issue is to explore making ``Seq(....).translate(table)`` work like the string translate method as needed by distinguishing our valid table arguments (which include integer NCBI genetic codes, and their various string alias) versus a general string mapping.

This is now harder than I expected due to Python 2/3 changes:

```
$ python2 -c "print('ACGTNX'.translate('wibble'))"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ValueError: translation table must be 256 characters long
```

Under Python 2 it was easy, if ``table`` was a 256 character then we could assume it was the string mapping, not a biological translation.

However, Python 3 changed things - it accepts string which are not 256 long (plus dictionaries of unicode ordinals). Shorter strings (like our table names) are apparently treated as partial mappings, with the missing mapping entries treated as no change.

```
$ python3 -c "print('ACGTNX'.translate('wibble'))"
ACGTNX
python3 -c "print('ACGTNX'.translate('?'*9999))"
??????
$ python3 -c "print('ACGTNX'.translate('?'*256))"
??????
$ python3 -c "print('ACGTNX'.translate('?'*80))"
???T?X
python3 -c "print('ACGTNX'.translate(''))"
ACGTNX
```

I've not worked out yet if that is a Python bug, or something missing in the docstring. Part of this stems from the more complicated use cases with unicode.

On the bright side, there is no optional second argument ``deletechars`` anymore.

**Comment by chris-rands** [comment]
Apparently, i read that python 2 `unicode.translate()` is like python 3 `str.translate()`. And python 2 `str.translate()` is like python 3 `bytes.translate()`

```
$ python3 -c "print(b'ACGTNX'.translate(b'wibble'))"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ValueError: translation table must be 256 characters long
```

**Comment by peterjc** [comment]
Yes, that was the impression I got trying to find a pre-existing Python issue - along with a lot of work behind the scenes to get the unicode translate method faster for ASCII examples.

(This kind of thing has made me wonder if the ``Seq`` ought to use an internal bytes string rather than an internal unicode string on Python 3)
