### ISSUE TITLE
Align.IO fails to parse a stockholm alignment file. /Bio/AlignIO/StockholmIO.py ValueError

### ISSUE THREAD

**Issue by JamesABaker** [biopython/biopython#2982]
### Setup

I am reporting a problem with Biopython version, Python version, and operating
system as follows:

```
$ python
Python 3.8.1 (default, Jan  8 2020, 22:29:32) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys; print(sys.version)
3.8.1 (default, Jan  8 2020, 22:29:32) 
[GCC 7.3.0]
>>> import platform; print(platform.python_implementation()); print(platform.platform())
CPython
Linux-5.4.0-37-generic-x86_64-with-glibc2.10
>>> import Bio; print(Bio.__version__)
1.76

```

### Expected behaviour

`align = AlignIO.read(stockholm_file_location, "stockholm")` should parse a Stockholm alignment file to an object called align that can be iterated through for records within the object.

### Actual behaviour

`align = AlignIO.read(stockholm_file_location, "stockholm")` in some Stockholm alignments yields:

```
Traceback (most recent call last):
  File "manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/home/james/miniconda3/envs/vartmh/lib/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/home/james/miniconda3/envs/vartmh/lib/python3.8/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/james/miniconda3/envs/vartmh/lib/python3.8/site-packages/django_extensions/management/email_notifications.py", line 63, in run_from_argv
    super(EmailNotificationCommand, self).run_from_argv(argv)
  File "/home/james/miniconda3/envs/vartmh/lib/python3.8/site-packages/django/core/management/base.py", line 328, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/james/miniconda3/envs/vartmh/lib/python3.8/site-packages/django_extensions/management/email_notifications.py", line 75, in execute
    super(EmailNotificationCommand, self).execute(*args, **options)
  File "/home/james/miniconda3/envs/vartmh/lib/python3.8/site-packages/django/core/management/base.py", line 369, in execute
    output = self.handle(*args, **options)
  File "/home/james/miniconda3/envs/vartmh/lib/python3.8/site-packages/django_extensions/management/utils.py", line 59, in inner
    ret = func(self, *args, **kwargs)
  File "/home/james/miniconda3/envs/vartmh/lib/python3.8/site-packages/django_extensions/management/commands/runscript.py", line 238, in handle
    run_script(mod, *script_args)
  File "/home/james/miniconda3/envs/vartmh/lib/python3.8/site-packages/django_extensions/management/commands/runscript.py", line 148, in run_script
    mod.run(*script_args)
  File "/mnt/brain/VarTMH/scripts/populate_funfams.py", line 147, in run
    stockholm_to_database(a_query, superfamily_id, funfam_id, stockholm_file)
  File "/mnt/brain/VarTMH/scripts/populate_funfams.py", line 90, in stockholm_to_database
    align = AlignIO.read(stockholm_file_location, "stockholm")
  File "/home/james/miniconda3/envs/vartmh/lib/python3.8/site-packages/Bio/AlignIO/__init__.py", line 447, in read
    first = next(iterator)
  File "/home/james/miniconda3/envs/vartmh/lib/python3.8/site-packages/Bio/AlignIO/__init__.py", line 394, in parse
    for a in i:
  File "/home/james/miniconda3/envs/vartmh/lib/python3.8/site-packages/Bio/AlignIO/StockholmIO.py", line 460, in __next__
    seq_id, feature, text = line[5:].strip().split(None, 2)
ValueError: not enough values to unpack (expected 3, got 2)
```

### Steps to reproduce

Save the Stockholm alignment attached here: [634591.sth.zip](https://github.com/biopython/biopython/files/4794175/634591.sth.zip)

This is an example of an alignment that causes the error, but nothing seems amiss to me. 

Run:

```
from Bio import AlignIO
align = AlignIO.read(stockholm_file_location, "stockholm")`
```

**Comment by peterjc** [comment]
Helllo.

I can reproduce this. The exception is while handling the ``#=GS <seqname>
<feature> <free text>`` lines, and appears to be a line without any value.
It turns out to be this line:

```text
#=GS G4YF51/316-544              OS
```

Using any value there fixes it:

```text
#=GS G4YF51/316-544              OS .
```

I'd have to dig into the specifications to check if this is officially
valid or not, but it ought not to be too complicated to tolerate this
variation.

Where did this file come from?

Peter

>

**Comment by JamesABaker** [comment]
This is from CATH at UCL as part of their [FunFam](https://github.com/UCLOrengoGroup/cath-funfam-docs) project. 
You can directly view the at the [CATH database here](http://www.cathdb.info/version/v4_2_0/superfamily/3.40.50.300/funfam/634591/files/stockholm)

**Comment by peterjc** [comment]
Thanks for quoting the specification reference, "free text" was my recollection - so arguably if the free text was empty, the line should end with a trailing space - but the current parser would break anyway with ``"#=GS G4YF51/316-544              OS "`` so we need to make a small change anyway.

Being pragmatic, I think we should cope with the missing value, and assign an empty string as the annotation value.

Is this something you would be interested in working on, and submitting a pull request for?

**Comment by JamesABaker** [comment]
> Being pragmatic, I think we should cope with the missing value, and assign an empty string as the annotation value.

This sounds like a good solution.

> Is this something you would be interested in working on, and submitting a pull request for?

I'll give it a go!

**Comment by peterjc** [comment]
Excellent. Thanks!
