### ISSUE TITLE
Windows / AppVeyor psycopg2.OperationalError

### ISSUE THREAD

**Issue by peterjc** [biopython/biopython#3070]
Multiple pull requests in the last week or so have occasionally failed on App Veyor (32bit or 64bit) as noted on #3068 and #3069, but work on a re-run. Here on 32bit,

```
======================================================================
ERROR: test_duplicate_load (common_BioSQL.DupLoadTest)
Make sure can't import a single record twice (in one go).
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\projects\biopython\Tests\common_BioSQL.py", line 722, in setUp
    driver=DBDRIVER, user=DBUSER, passwd=DBPASSWD, host=DBHOST, db=TESTDB
  File "C:\projects\biopython\build\lib.win32-3.7\BioSQL\BioSeqDatabase.py", line 110, in open_database
    conn = connect(**kw)
  File "C:\Py\lib\site-packages\psycopg2\__init__.py", line 127, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
```

Or, 64bit:

```
======================================================================
ERROR: test_seq_features (common_BioSQL.SeqInterfaceTest)
Check SeqFeatures of a sequence.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\projects\biopython\Tests\common_BioSQL.py", line 440, in setUp
    load_database("GenBank/cor6_6.gb")
  File "C:\projects\biopython\Tests\common_BioSQL.py", line 246, in load_database
    TESTDB = create_database()
  File "C:\projects\biopython\Tests\common_BioSQL.py", line 216, in create_database
    _do_db_cleanup()
  File "C:\projects\biopython\Tests\common_BioSQL.py", line 145, in _do_db_cleanup
    driver=DBDRIVER, host=DBHOST, user=DBUSER, passwd=DBPASSWD, db=TESTDB
  File "C:\projects\biopython\build\lib.win-amd64-3.7\BioSQL\BioSeqDatabase.py", line 110, in open_database
    conn = connect(**kw)
  File "C:\Py\lib\site-packages\psycopg2\__init__.py", line 127, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
----------------------------------------------------------------------
```

This is most likely due to a change in the dependencies, e.g. a recent update to ``psycopg2``

**Comment by peterjc** [comment]
Current latest release of psycopg2 is 2.8.5 from April 2020, https://pypi.org/project/psycopg2/#history - so unlikely to be that directly.

**Comment by peterjc** [comment]
Looks like AppVeyor is running PostgreSQL 9.6 and has been for some time (our logs do not have the minor version).

Looking at https://www.postgresql.org/ the current version is 9.6.18  from 2020-05-14, so *might* be important if AppVeyor only recently started using that?

**Comment by peterjc** [comment]
https://www.appveyor.com/updates/ mentions *Visual Studio 2019 image update on July 3, 2020* which is a possibility time wise. This updated to Python 3.7.8 according to https://www.appveyor.com/updates/2020/07/03/ but we're ignoring the system python in favour of one via conda. They changed a few other things but nothing that catches my eye.

Here's a recent failing build https://ci.appveyor.com/project/biopython/biopython/builds/34201027/job/yvd9m22qvsna4705 which says:

```
python -c "import sys; print(sys.version)"
3.7.7 (default, May  6 2020, 11:43:10) [MSC v.1916 32 bit (Intel)]
```
