### ISSUE TITLE
NeXML output broken (bytes vs text)

### ISSUE THREAD

**Issue by peterjc** [biopython/biopython#3206]
Example based on issue reported on #334 by @yogeshhk (his was PhyloXML to Newick to NeXML):

```
$ python -c 'from Bio import Phylo; Phylo.convert("PhyloXML/phyloxml_examples.xml", "phyloxml", "other_trees.xml", "nexml")'
INFO:rdflib:RDFLib Version: 4.2.2
Traceback (most recent call last):
  File "/Users/xxx/miniconda3/lib/python3.7/site-packages/Bio/File.py", line 72, in as_handle
    yield fp
  File "/Users/xxx/miniconda3/lib/python3.7/site-packages/Bio/Phylo/_io.py", line 77, in write
    n = getattr(supported_formats[format], "write")(trees, fp, **kwargs)
  File "/Users/xxx/miniconda3/lib/python3.7/site-packages/Bio/Phylo/NeXMLIO.py", line 96, in write
    return Writer(trees).write(handle, plain=plain, **kwargs)
  File "/Users/xxx/miniconda3/lib/python3.7/site-packages/Bio/Phylo/NeXMLIO.py", line 287, in write
    handle.write(reparsed.toprettyxml(indent="  ").encode("utf8"))
TypeError: write() argument must be str, not bytes

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/xxx/miniconda3/lib/python3.7/site-packages/Bio/Phylo/_io.py", line 86, in convert
    return write(trees, out_file, out_format, **kwargs)
  File "/Users/xxx/miniconda3/lib/python3.7/site-packages/Bio/Phylo/_io.py", line 77, in write
    n = getattr(supported_formats[format], "write")(trees, fp, **kwargs)
  File "/Users/xxx/miniconda3/lib/python3.7/contextlib.py", line 161, in __exit__
    raise RuntimeError("generator didn't stop after throw()")
RuntimeError: generator didn't stop after throw()
```

@bendmorris can you take a look? The code seems to deliberately try to write bytes (since it uses ``.encode("utf8")``) but make no attempt to open the file in binary mode (which may be sensible for XML output).

**Comment by mdehoon** [comment]
> but make no attempt to open the file in binary mode (which may be sensible for XML output).

XML is a binary format, with the encoding written in the XML file itself.

**Comment by peterjc** [comment]
Also have a look at SeqIO, which used to have a private list of formats to be opened in binary mode, but now handles this in the writer for each format (note the test of writing zero length bytes or zero length string to verify the file mode).

**Comment by peterjc** [comment]
We want to get Biopython 1.78 out soon, so #3249 is a pragmatic fix to restore the behaviour from Biopython 1.76 (accidentally broken in Biopython 1.77 in a44d1fcd46aaf1a0836dd7f802d63360e3cc670b due to insufficient test coverage).

After that we should review ``Bio.Phylo`` to ensure XML files are opened in binary mode (probably following the style now used in ``Bio.SeqIO``). Is that something you could take on @etal, or would you rather just review such changes?
