### ISSUE TITLE
test_pcr_primers test fails with unexpected results

### ISSUE THREAD

**Issue by chebizarro** [biopython/biopython#3225]
### Setup

I am reporting a problem with Biopython version, Python version, and operating
system as follows:

```python
>>> import sys; print(sys.version)
3.6.9 (default, Apr 18 2020, 01:56:04) 
[GCC 8.4.0]
>>> import platform; print(platform.python_implementation()); print(platform.platform())
CPython
Linux-5.4.0-42-generic-x86_64-with-Ubuntu-18.04-bionic
>>> import Bio; print(Bio.__version__)
1.78.dev0
```

### Expected behaviour

Running the full test suite with online tests is expected to complete without failure

### Actual behaviour
```bash
======================================================================
FAIL: test_pcr_primers (test_NCBI_qblast.TestQblast)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/biopython/Tests/test_NCBI_qblast.py", line 142, in test_pcr_primers
    "XM_016930484.2",
  File "/biopython/Tests/test_NCBI_qblast.py", line 312, in run_qblast
    ", ".join(a.hit_id for a in record.alignments),
AssertionError: False is not true : Missing all expected hits (XM_009432096.3, XM_009432102.3, XM_009432101.3, XM_016930487.2, XM_009432104.3, XM_009432099.3, XR_001710553.2, XM_016930485.2, XM_009432089.3, XM_016930484.2), instead have: gi|1849034496|ref|XM_034941187.1|, gi|1849034494|ref|XM_034941186.1|, gi|1849034492|ref|XM_034941185.1|, gi|1849034490|ref|XM_034941184.1|, gi|1849034488|ref|XM_034941183.1|, gi|1849034486|ref|XM_034941182.1|, gi|1849034482|ref|XM_034941180.1|, gi|1849034480|ref|XM_034941179.1|, gi|1849034478|ref|XM_034941178.1|, gi|1849034476|ref|XM_034941177.1|

----------------------------------------------------------------------
```

### Steps to reproduce

Running the test suite online i.e.
```python3.6 setup.py test```

**Comment by peterjc** [comment]
Without checking the details, it looks none of the previously expected hits made the short list anymore. We probably just need to update the expected list to one of these (new?) transcript variants.
