### ISSUE TITLE
Bio.Sequencing.Applications.BwaMemCommandline Error

### ISSUE THREAD

**Issue by limbo1996** [biopython/biopython#3310]
### Setup
Using
```
Biopython version: 1.78
Python version: 3.8.6 | packaged by conda-forge | (default, Oct  7 2020, 19:08:05) 
[GCC 7.5.0]
Platform: CPython
operating system: Linux-5.4.50-amd64-desktop-x86_64-with-glibc2.10
```
If you run
```
from Bio.Sequencing.Applications import BwaMemCommandline


ref = '~/reference/Homo_sapiens.GRCh38.dna.primary_assembly.fa.gz'
fastq_1 = '../test_file/clean_fastq/SRR5134747_1_clean.fastq.gz'
fastq_2 = '../test_file/clean_fastq/SRR5134747_2_clean.fastq.gz'

out = '/home/limbo/Desktop/test.sam'

R = '"@RG\\tID:SRR5134747\\tLM:SRR5134747\\tSM:SRR5134747\\tPL:illuminat\\tPU:SRR5134747\\t"'

test_cmd = BwaMemCommandline(t = 1, R = R, reference=ref, read_file1=fastq_1, read_file2 = fastq_2)

test_cmd(stdout=out)
```

### Expected behaviour
it should run bwa mem using 1 threads,
by executinng:
```
bwa mem ~/reference/Homo_sapiens.GRCh38.dna.primary_assembly.fa.gz ../test_file/clean_fastq/SRR5134747_1_clean.fastq.gz ../test_file/clean_fastq/SRR5134747_2_clean.fastq.gz -t 1 -R "@RG\tID:SRR5134747\tLM:SRR5134747\tSM:SRR5134747\tPL:illuminat\tPU:SRR5134747\t"
```
and catch the standard out to the given filepath.

### Actual behaviour

```
>>> test_cmd(stdout=out)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/limbo/miniconda3/envs/muneo/lib/python3.8/site-packages/Bio/Application/__init__.py", line 569, in __call__
    raise ApplicationError(return_code, str(self), stdout_str, stderr_str)
Bio.Application.ApplicationError: Non-zero return code 1 from 'bwa mem ~/reference/Homo_sapiens.GRCh38.dna.primary_assembly.fa.gz ../test_file/clean_fastq/SRR5134747_1_clean.fastq.gz ../test_file/clean_fastq/SRR5134747_2_clean.fastq.gz -t 1 -R "@RG\\tID:SRR5134747\\tLM:SRR5134747\\tSM:SRR5134747\\tPL:illuminat\\tPU:SRR5134747\\t"', message '[M::bwa_idx_load_from_disk] read 0 ALT contigs'
```
But I can run it correctly using terminal, and if I save it as a python file and then 
> python test.py

It can get ouptput correctly.

**Comment by peterjc** [comment]
Trying ``print(test_cmd)`` gives:

```
bwa mem ~/reference/Homo_sapiens.GRCh38.dna.primary_assembly.fa.gz ../test_file/clean_fastq/SRR5134747_1_clean.fastq.gz ../test_file/clean_fastq/SRR5134747_2_clean.fastq.gz -t 1 -R "@RG\tID:SRR5134747\tLM:SRR5134747\tSM:SRR5134747\tPL:illuminat\tPU:SRR5134747\t"
```

That matches what you want to be used at the command line, good. Are you definitely running this from the same directory as when you tested the command at the terminal?

(As an aside, we are considering deprecating all the command line wrappers in favour of encourgaing use of ``subprocess`` directly - comments on #2877 welcome)

At this point I would try catching the exception to look at the stderr (and stdout should be empty as sent to a file) in case it is more than just ``[M::bwa_idx_load_from_disk] read 0 ALT contigs``:

```python
from Bio.Application import ApplicationError

try:
    stdout, stderr = test_cmd(stdout=out)
except ApplicationError as err:
    print(err.cmd)
    print(err.returncode)
    print(err.stderr)
    print(err.stdout)
    raise
```

**Comment by limbo1996** [comment]
Thanks!!!!!!!!!!
I ran the following code
```
try:
    stdout, stderr = test_cmd(stdout = out)
except ApplicationError as err:
    print(err.cmd)
    print(err.returncode)
    print(err.stderr)
    print(err.stdout)
    raise
```
And I got 
```
bwa mem ~/reference/Homo_sapiens.GRCh38.dna.primary_assembly.fa.gz ../test_file/clean_fastq/SRR5134747_1_clean.fastq.gz ../test_file/clean_fastq/SRR5134747_2_clean.fastq.gz -t 1 -R "@RG\tID:SRR5134747\tLM:SRR5134747\tSM:SRR5134747\tPL:illuminat\tPU:SRR5134747\t"
1
[M::bwa_idx_load_from_disk] read 0 ALT contigs
[E::main_mem] fail to open file `../test_file/clean_fastq/SRR5134747_1_clean.fastq.gz'.

None
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/home/limbo/miniconda3/envs/muneo/lib/python3.8/site-packages/Bio/Application/__init__.py", line 569, in __call__
    raise ApplicationError(return_code, str(self), stdout_str, stderr_str)
Bio.Application.ApplicationError: Non-zero return code 1 from 'bwa mem ~/reference/Homo_sapiens.GRCh38.dna.primary_assembly.fa.gz ../test_file/clean_fastq/SRR5134747_1_clean.fastq.gz ../test_file/clean_fastq/SRR5134747_2_clean.fastq.gz -t 1 -R "@RG\\tID:SRR5134747\\tLM:SRR5134747\\tSM:SRR5134747\\tPL:illuminat\\tPU:SRR5134747\\t"', message '[M::bwa_idx_load_from_disk] read 0 ALT contigs'
```
It can not find fastq files, after I corrected the file path it wored niced.
Thanks

**Comment by peterjc** [comment]
Glad we could solve it. The confusion stemmed from the ``ApplicationError`` exception only showing the first line of stderr for brevity; sometimes that is enough but in this case the last line was more important.

Maybe when stderr is multiline, it should show the first and last line - e.g.

``Bio.Application.ApplicationError: Non-zero return code 1 from 'bwa mem ~/reference/Homo_sapiens.GRCh38.dna.primary_assembly.fa.gz ../test_file/clean_fastq/SRR5134747_1_clean.fastq.gz ../test_file/clean_fastq/SRR5134747_2_clean.fastq.gz -t 1 -R "@RG\\tID:SRR5134747\\tLM:SRR5134747\\tSM:SRR5134747\\tPL:illuminat\\tPU:SRR5134747\\t"', message '[M::bwa_idx_load_from_disk] read 0 ALT contigs\n...\n[E::main_mem] fail to open file `../test_file/clean_fastq/SRR5134747_1_clean.fastq.gz'.\n'``
