### ISSUE TITLE
SearchIO: ValueError: Hit '' already present in this QueryResult.

### ISSUE THREAD

**Issue by mmokrejs** [biopython/biopython#333]
I am parsing some XML from blastn+ and it seems if there are two matches using same query, it chokes on the latter. Not always, mostly there are many resulting HSP, wonder what is so specific to this pair.

Maybe Bow is faster in finding out what is it doing internally.

<pre>
Debug: convert_blastn_XML_to_csv(): HYEES0401DFWIA:  Considering blastn hit to sctg_0001_0018, alignment # 1, HSP # 1, align_length=317, _hsp_identity_percentage=0.92, bits=433.236, score=234.0, sbjct:[2030-2339], query:[5-307], sbjct_length=200341
Debug: convert_blastn_XML_to_csv(): HYEES0401DFWIA:  Considering blastn hit to sctg_0001_0006, alignment # 2, HSP # 1, align_length=317, _hsp_identity_percentage=0.92, bits=433.236, score=234.0, sbjct:[199312-199621], query:[5-307], sbjct_length=778355

Traceback (most recent call last):
  File "mycode.py", line 20307, in convert_blastn_XML_to_csv
    for _record in _blastn_iterator:
  File "/usr/lib64/python2.7/site-packages/Bio/SearchIO/__init__.py", line 316, in parse
    for qresult in generator:
  File "/usr/lib64/python2.7/site-packages/Bio/SearchIO/BlastIO/blast_xml.py", line 193, in __iter__
    for qresult in self._parse_qresult():
  File "/usr/lib64/python2.7/site-packages/Bio/SearchIO/BlastIO/blast_xml.py", line 306, in _parse_qresult
    qresult = QueryResult(hit_list, query_id)
  File "/usr/lib64/python2.7/site-packages/Bio/SearchIO/_model/query.py", line 211, in __init__
    self.append(hit)
  File "/usr/lib64/python2.7/site-packages/Bio/SearchIO/_model/query.py", line 465, in append
    hit_key)
ValueError: Hit '' already present in this QueryResult.
</pre>

I have biopython-1.63.

**Comment by msarrias** [comment]
Hi,

I'm experiencing something similar:

### Setup

I am reporting a problem with Biopython 1.78, Python 3.8.7, and operating system CentOS 7 as follows:
3.8.7 (default, Feb  1 2021, 11:54:01) 
[GCC 8.3.0]
CPython
Linux-3.10.0-1160.76.1.el7.x86_64-x86_64-with-glibc2.2.5
1.78

### Expected behaviour

I am trying to parse two exonerate output files (attached) using the Bio.SearchIO parser. My problem is that I get an error (see below) while trying to parse one of the two files. Both output files result from identical calls to exonerate.  I would appreciate any guidance in dealing with this issue. 

### Actual behaviour

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
/sw/bioinfo/biopython/1.78/rackham/lib/python3.8/site-packages/Bio/SearchIO/_model/query.py in absorb(self, hit)
    443         try:
--> 444             self.append(hit)
    445         except ValueError:

/sw/bioinfo/biopython/1.78/rackham/lib/python3.8/site-packages/Bio/SearchIO/_model/query.py in append(self, hit)
    469         else:
--> 470             raise ValueError(
    471                 "The ID or alternative IDs of Hit %r exists in this QueryResult."

ValueError: The ID or alternative IDs of Hit 'P_napi_105.2-exon6' exists in this QueryResult.

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
<ipython-input-60-4f7f60df3cef> in <module>
     24     subprocess.run(exonerate_command, stdout=out)
     25 
---> 26 temp = parse_exonerate_output_only_higher_score_hits_(output_file)
     27 all_results = list(SearchIO.parse(f'output{exon_id}.txt', 'exonerate-text'))

<ipython-input-8-2affbe84548e> in parse_exonerate_output_only_higher_score_hits_(ex_out_fname)
     32     """
     33     #we take the first element of the list since there's only one query
---> 34     all_results = list(SearchIO.parse(ex_out_fname, 'exonerate-text'))
     35     print(all_results)
     36     if all_results:

/sw/bioinfo/biopython/1.78/rackham/lib/python3.8/site-packages/Bio/SearchIO/__init__.py in parse(handle, format, **kwargs)
    304     with as_handle(handle, **handle_kwargs) as source_file:
    305         generator = iterator(source_file, **kwargs)
--> 306         yield from generator
    307 
    308 

/sw/bioinfo/biopython/1.78/rackham/lib/python3.8/site-packages/Bio/SearchIO/ExonerateIO/_base.py in __iter__(self)
    337                 return
    338 
--> 339         for qresult in self._parse_qresult():
    340             qresult.program = "exonerate"
    341             # HACK: so that all descriptions are set

/sw/bioinfo/biopython/1.78/rackham/lib/python3.8/site-packages/Bio/SearchIO/ExonerateIO/_base.py in _parse_qresult(self)
    479                         # not using append since Exonerate may separate the
    480                         # same hit if it has different strands
--> 481                         qresult.absorb(hit)
    482                     for attr, value in prev["qresult"].items():
    483                         setattr(qresult, attr, value)

/sw/bioinfo/biopython/1.78/rackham/lib/python3.8/site-packages/Bio/SearchIO/_model/query.py in absorb(self, hit)
    446             assert hit.id in self
    447             for hsp in hit:
--> 448                 self[hit.id].append(hsp)
    449 
    450     def append(self, hit):

/sw/bioinfo/biopython/1.78/rackham/lib/python3.8/site-packages/Bio/SearchIO/_model/hit.py in append(self, hsp)
    356 
    357         """
--> 358         self._validate_hsp(hsp)
    359         self._items.append(hsp)
    360 

/sw/bioinfo/biopython/1.78/rackham/lib/python3.8/site-packages/Bio/SearchIO/_model/hit.py in _validate_hsp(self, hsp)
    288             if self.description is not None:
    289                 if hsp.hit_description != self.description:
--> 290                     raise ValueError(
    291                         "Expected HSP with hit description %r, found %r instead."
    292                         % (self.description, hsp.hit_description)

ValueError: Expected HSP with hit description '[revcomp]', found '' instead.
```

### Steps to reproduce
```
from Bio import SearchIO
# This should work
all_results = list(SearchIO.parse('outputP_napi_105.1-exon6_works.txt', 'exonerate-text'))
# This should trigger the error
all_results = list(SearchIO.parse('outputP_napi_105.1-exon6_does_not_work.txt', 'exonerate-text'))
```


[outputP_napi_105.1-exon6_does_not_work.txt](https://github.com/biopython/biopython/files/10049796/outputP_napi_105.1-exon6_does_not_work.txt)
[outputP_napi_105.1-exon6_works.txt](https://github.com/biopython/biopython/files/10049797/outputP_napi_105.1-exon6_works.txt)

**Comment by msarrias** [comment]
Hi,

I'm experiencing something similar:

### Setup

I am reporting a problem with Biopython 1.78, Python 3.8.7, and operating system CentOS 7 as follows:
3.8.7 (default, Feb  1 2021, 11:54:01) 
[GCC 8.3.0]
CPython
Linux-3.10.0-1160.76.1.el7.x86_64-x86_64-with-glibc2.2.5
1.78

### Expected behaviour

I am trying to parse an exonerate output file using the Bio.SearchIO parser - exonerate-text format. Similar to the problem presented in this case, my exonerate output returns more than one hit for a given target sequence. However, by modifying the output file, I notice that this only happens for the  -`exonerate-text` format with alignments. If I remove the alignments in the file and only leave the vulgar lines (following the same order of appearance), then I have no problem parsing the file using the `exonerate-vulgar format`. I'd appreciate any input.  

### Actual behaviour

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
/sw/bioinfo/biopython/1.78/rackham/lib/python3.8/site-packages/Bio/SearchIO/_model/query.py in absorb(self, hit)
    443         try:
--> 444             self.append(hit)
    445         except ValueError:

/sw/bioinfo/biopython/1.78/rackham/lib/python3.8/site-packages/Bio/SearchIO/_model/query.py in append(self, hit)
    469         else:
--> 470             raise ValueError(
    471                 "The ID or alternative IDs of Hit %r exists in this QueryResult."

ValueError: The ID or alternative IDs of Hit 'P_napi_105.2-exon6' exists in this QueryResult.

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
<ipython-input-60-4f7f60df3cef> in <module>
     24     subprocess.run(exonerate_command, stdout=out)
     25 
---> 26 temp = parse_exonerate_output_only_higher_score_hits_(output_file)
     27 all_results = list(SearchIO.parse(f'output{exon_id}.txt', 'exonerate-text'))

<ipython-input-8-2affbe84548e> in parse_exonerate_output_only_higher_score_hits_(ex_out_fname)
     32     """
     33     #we take the first element of the list since there's only one query
---> 34     all_results = list(SearchIO.parse(ex_out_fname, 'exonerate-text'))
     35     print(all_results)
     36     if all_results:

/sw/bioinfo/biopython/1.78/rackham/lib/python3.8/site-packages/Bio/SearchIO/__init__.py in parse(handle, format, **kwargs)
    304     with as_handle(handle, **handle_kwargs) as source_file:
    305         generator = iterator(source_file, **kwargs)
--> 306         yield from generator
    307 
    308 

/sw/bioinfo/biopython/1.78/rackham/lib/python3.8/site-packages/Bio/SearchIO/ExonerateIO/_base.py in __iter__(self)
    337                 return
    338 
--> 339         for qresult in self._parse_qresult():
    340             qresult.program = "exonerate"
    341             # HACK: so that all descriptions are set

/sw/bioinfo/biopython/1.78/rackham/lib/python3.8/site-packages/Bio/SearchIO/ExonerateIO/_base.py in _parse_qresult(self)
    479                         # not using append since Exonerate may separate the
    480                         # same hit if it has different strands
--> 481                         qresult.absorb(hit)
    482                     for attr, value in prev["qresult"].items():
    483                         setattr(qresult, attr, value)

/sw/bioinfo/biopython/1.78/rackham/lib/python3.8/site-packages/Bio/SearchIO/_model/query.py in absorb(self, hit)
    446             assert hit.id in self
    447             for hsp in hit:
--> 448                 self[hit.id].append(hsp)
    449 
    450     def append(self, hit):

/sw/bioinfo/biopython/1.78/rackham/lib/python3.8/site-packages/Bio/SearchIO/_model/hit.py in append(self, hsp)
    356 
    357         """
--> 358         self._validate_hsp(hsp)
    359         self._items.append(hsp)
    360 

/sw/bioinfo/biopython/1.78/rackham/lib/python3.8/site-packages/Bio/SearchIO/_model/hit.py in _validate_hsp(self, hsp)
    288             if self.description is not None:
    289                 if hsp.hit_description != self.description:
--> 290                     raise ValueError(
    291                         "Expected HSP with hit description %r, found %r instead."
    292                         % (self.description, hsp.hit_description)

ValueError: Expected HSP with hit description '[revcomp]', found '' instead.
```

### Steps to reproduce
```
from Bio import SearchIO
# This should trigger the error
all_results = list(SearchIO.parse('outputP_napi_105.1-exon6.txt', 'exonerate-text'))
```
[outputP_napi_105.1-exon6.txt](https://github.com/biopython/biopython/files/10049796/outputP_napi_105.1-exon6_does_not_work.txt)

**Comment by bow** [comment]
Hi @msarrias

Thanks for reporting the issue and sending an example too. I believe you have spotted the issue reported in https://github.com/biopython/biopython/issues/3757 which we have subsequently fixed in https://github.com/biopython/biopython/pull/3761.

You were on 1.78, well before the PR was merged in. Version 1.80, which contained this fix, was actually [released a few days ago](https://pypi.org/project/biopython/#history), so I would recommend updating to it :slightly_smiling_face:.
