### ISSUE TITLE
Why Entrez.efech from byopython is outputing "internal server error 500"?

### ISSUE THREAD

**Issue by criscapdechoy** [biopython/biopython#3424]
### Setup

Hi I was using biopython yesterday night and everything was working and now (next morning) for every Entrez query I get "Internal Server Error 500". Any idea of which could be the problem? I've checked my version of biopython (1.77), now I see that the last release is 1.78 so the problem could be the version...However, yesterday I had the code working and therefore it makes no sense.

```python
from Bio import Entrez

handle = Entrez.esearch(db='pubmed', term="neoplasms")
data = Entrez.read(handle)

ids = data['IdList']
print(ids)

##Till here everything works

#But now, I try to get the info for each id and I get the error
output = Entrez.efetch(db='pubmed', id=','.join(ids), retmode='xml', rettype='abstract')
print(output)```


### Expected behaviour

output = [{publication1 info}, ...,{
#Get the info of the publications from Pubmed matching the ids I give as the input.

### Actual behaviour
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/home/cristina_capdevila/Documents/git/trend-seeker/trendseeker/lib/python3.7/site-packages/Bio/Entrez/__init__.py", line 205, in efetch
    return _open(cgi, variables, post=post)
  File "/home/cristina_capdevila/Documents/git/trend-seeker/trendseeker/lib/python3.7/site-packages/Bio/Entrez/__init__.py", line 604, in _open
    handle = urlopen(cgi)
  File "/usr/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 500: Internal Server Error

**Comment by mdehoon** [comment]
Looks like an internet or network problem. Most likely your script will work again tomorrow.

**Comment by peterjc** [comment]
Yes, this is a message from the NCBI Entrez servers. It will probably work again later, try to avoid USA working hours which tend to be most busy.

**Comment by drussellmrichie** [comment]
I have this problem with just a very specific PMID. It has a very long author and affiliation list. Could that be the problem?

```
handle = Entrez.efetch(db='pubmed', id=33766997, rettype="medline", retmode="text")
```

Other PMID's are fine. I am therefore not sure that it's about connectivity issues, per se?

**Comment by mdehoon** [comment]
Biopython tries to access `https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=pubmed&id=33766997&rettype=medline&retmode=text&tool=biopython`, which is correct and works for other ID numbers. Then the error seems unrelated to Biopython and it's better to contact NCBI to let them know about this error.
