### ISSUE TITLE
Pickling/unpickling `Bio.Align.substitution_matrices.Array` loses the `alphabet` attribute

### ISSUE THREAD

**Issue by althonos** [biopython/biopython#3441]
### Setup

I am reporting a problem with Biopython version, Python version, and operating
system as follows:

```python
>>> import sys; print(sys.version)
3.8.6 (default, Sep 30 2020, 04:00:38) 
[GCC 10.2.0]
>>> import platform; print(platform.python_implementation()); print(platform.platform())
CPython
Linux-5.9.9-arch1-1-x86_64-with-glibc2.2.5
>>> import Bio; print(Bio.__version__)
1.78
```

### Expected behaviour

Pickling a substitution matrix should also keep the `alphabet` attribute.

### Actual behaviour

It is not the case because `Array` does not implement `__getstate__` and `__setstate__`, so `Array` uses the default `numpy.ndarray` implementation. (issue found by @gamcil in gamcil/clinker#22).

### Steps to reproduce

```python
import pickle
from Bio.Align import substitution_matrices
matrix = substitution_matrices.load("BLOSUM62")
pickled = pickle.dumps(matrix)
loaded = pickle.loads(pickled)
print(loaded.alphabet)
```
This fails with:
```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/althonos/.local/lib/python3.8/site-packages/Bio/Align/substitution_matrices/__init__.py", line 245, in alphabet
    return self._alphabet
AttributeError: 'Array' object has no attribute '_alphabet'
```

**Comment by mdehoon** [comment]
Fixed in #3442, thanks
