### ISSUE TITLE
Bio.Phylo can't read nexus file with commented both node name and length

### ISSUE THREAD

**Issue by ante-turudic** [biopython/biopython#3456]
### Setup
[mr_bayes_result.zip](https://github.com/biopython/biopython/files/5750462/mr_bayes_result.zip)

I am reporting a problem with Biopython version, Python version, and operating
system as follows:
>>> import sys; print(sys.version)
3.8.5 (default, Jul 28 2020, 12:59:40) 
[GCC 9.3.0]
>>> import platform; print(platform.python_implementation()); print(platform.platform())
CPython
Linux-5.4.0-58-generic-x86_64-with-glibc2.29
>>> import Bio; print(Bio.__version__)
1.78

### Expected behaviour

Loaded tree from a nexus file.
Problem is in parsing node values when there are more than one comment in it. That is done in file Bio/Nexus/Trees.py, method _get_values(). 'If' block starting in line 181 removes comment, but only one comment.
Attached nexus file (MrBayes result) has two comments per a node, one after node name and one after edge length. 

### Actual behaviour

Exception raised.

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/Bio/Nexus/Trees.py", line 198, in _get_values
    values.append(float(part))
ValueError: could not convert string to float: '1.322576e-02[&length_mean=1.32336084e-02,length_median=1.32257600e-02,length_95%HPD={1.25875600e-02,1.38462600e-02}]'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/Bio/Phylo/_io.py", line 60, in read
    tree = next(tree_gen)
  File "/usr/local/lib/python3.8/dist-packages/Bio/Phylo/_io.py", line 49, in parse
    yield from getattr(supported_formats[format], "parse")(fp, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/Bio/Phylo/NexusIO.py", line 40, in parse
    nex = Nexus.Nexus(handle)
  File "/usr/local/lib/python3.8/dist-packages/Bio/Nexus/Nexus.py", line 668, in __init__
    self.read(input)
  File "/usr/local/lib/python3.8/dist-packages/Bio/Nexus/Nexus.py", line 718, in read
    self._parse_nexus_block(title, contents)
  File "/usr/local/lib/python3.8/dist-packages/Bio/Nexus/Nexus.py", line 759, in _parse_nexus_block
    getattr(self, "_" + line.command)(line.options)
  File "/usr/local/lib/python3.8/dist-packages/Bio/Nexus/Nexus.py", line 1183, in _tree
    tree = Tree(name=name, weight=weight, rooted=rooted, tree=opts.rest().strip())
  File "/usr/local/lib/python3.8/dist-packages/Bio/Nexus/Trees.py", line 82, in __init__
    subtree_info, base_info = self._parse(tree)
  File "/usr/local/lib/python3.8/dist-packages/Bio/Nexus/Trees.py", line 132, in _parse
    subclades = [self._parse(subtree) for subtree in subtrees]
  File "/usr/local/lib/python3.8/dist-packages/Bio/Nexus/Trees.py", line 132, in <listcomp>
    subclades = [self._parse(subtree) for subtree in subtrees]
  File "/usr/local/lib/python3.8/dist-packages/Bio/Nexus/Trees.py", line 111, in _parse
    val = self._get_values(tree[closing + 1 :])
  File "/usr/local/lib/python3.8/dist-packages/Bio/Nexus/Trees.py", line 200, in _get_values
    assert taxonomy is None, "Two string taxonomies?"
AssertionError: Two string taxonomies?

### Steps to reproduce

from Bio import Phylo
t = Phylo.read('result.con.tre', 'nexus')

**Comment by etal** [comment]
Hmm, are multiple comments supported in the Nexus spec? If MrBayes emits this under normal circumstances then I suppose we should support it as best we can. Does MrBayes do this in all of its outputs now, or only when given certain options?

In Bio.Phylo.NexusIO and Bio.Nexus.Trees, I see comments are stored for nodes, but I don't see any representation for comments associated with edges. 

If the Nexus/Newick spec allows separate comments for node name and length, then there's some work to be done here to support that in both the parser and the object model.

If not it's not in the spec, other tools don't do it, and MrBayes doesn't do it pervasively, then would it be OK to e.g. concatenate the two comments when parsing this file and store the combined string in the existing `comment` attribute? Then when the tree is serialized again, this string would appear as a single comment.

**Comment by ante-turudic** [comment]
I am not quite familiar with Nexus format. Original [documentation](https://academic.oup.com/sysbio/article/46/4/590/1629695) doesn't set limits on comments at all. It seems to me that there is no reason that documentation prevents comments in any place.
Documentation even allows nested comments, which are problematic to parse :-/ I suppose, there is no application that exports nested comments.

Saving edge length info is standard MrBayes parameter (savebrlens). From [documentation](http://mrbayes.sourceforge.net/Help/mcmc.html):
Savebrlens - This specifies whether branch length information is saved on the trees.

Default value is Yes, so I suppose it would be good to fix this issue.

I managed my output files, and set savebrlens to No, so I don't have problems anymore :-)
