### ISSUE TITLE
MEME parsing error for runs with >1000 seqs.

### ISSUE THREAD

**Issue by mwittep** [biopython/biopython#3532]
### Setup

I am reporting a problem with Biopython version, Python version, and operating system as follows:
Biopython: 1.78
python: 3.8.3 (default, May 19 2020, 18:47:26)
OS: CPython/Linux-5.4.72-microsoft-standard-WSL2-x86_64-with-glibc2.10

### Expected behaviour

I ran MEME with a fasta-file with more than 1000 sequences and tried to parse the XML file in python. MEME output is normal. Hence I expected a variable with the XML output of MEME within my python script. 

### Actual behaviour
None-type error. 
```
Traceback (most recent call last):
  File "memeParser.py", line 13, in <module>
    record = meme.read(f)
  File "/.../python3.8/site-packages/Bio/motifs/meme.py", line 53, in read
    __read_motifs(record, xml_tree, sequence_id_name_map)
  File "/.../python3.8/site-packages/Bio/motifs/meme.py", line 176, in __read_motifs
    motif = Motif(record.alphabet, instances)
  File "/.../python3.8/site-packages/Bio/motifs/meme.py", line 67, in __init__
    motifs.Motif.__init__(self, alphabet, instances)
  File "/.../python3.8/site-packages/Bio/motifs/__init__.py", line 263, in __init__
    counts = self.instances.count()
  File "/.../python3.8/site-packages/Bio/motifs/__init__.py", line 216, in count
    counts[letter] = [0] * self.length
TypeError: can't multiply sequence by non-int of type 'NoneType'
```
### Steps to reproduce

- Create a fasta with more than 1000 sequences. 
- Run meme e.g. (```meme -dna -nmotifs 5 -minw 5 -maxw 20 /test.fasta -o test_more_1000```) 
- Output of MEME looks normal
- Parsing in python fails with the error mentioned above. Code:
 
```
parser = argparse.ArgumentParser()
parser.add_argument("--meme")
args = parser.parse_args()
with open(args.meme) as f:
        record = meme.read(f)
```

Though MEME is not recommended for more than 50 seqs, it is still often used and the program does not return any error, since, for cases with more than 1000 seqs, MEME takes a random subset and runs the analysis only on this subset. The rest is ignored. I assume that for those ignored sequences, the XML file has a "NoneType" variable. Hence, the parser fails. 

It should still be possible to parse the output of MEME.

**Comment by peterjc** [comment]
Can you share an example (or a least a sample) of a problematic XML file?

**Comment by mwittep** [comment]
I've zipped the file since GitHub does not allow .xml files. 
[meme_xml_file.zip](https://github.com/biopython/biopython/files/6337562/meme_xml_file.zip)

**Comment by peterjc** [comment]
OK, I can reproduce this:

```
$ python -c "from Bio.motifs import meme; meme.read(open('meme.xml'))"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/xxx/miniconda3/lib/python3.7/site-packages/Bio/motifs/meme.py", line 53, in read
    __read_motifs(record, xml_tree, sequence_id_name_map)
  File "/Users/xxx/miniconda3/lib/python3.7/site-packages/Bio/motifs/meme.py", line 176, in __read_motifs
    motif = Motif(record.alphabet, instances)
  File "/Users/xxx/miniconda3/lib/python3.7/site-packages/Bio/motifs/meme.py", line 67, in __init__
    motifs.Motif.__init__(self, alphabet, instances)
  File "/Users/xxx/miniconda3/lib/python3.7/site-packages/Bio/motifs/__init__.py", line 264, in __init__
    counts = self.instances.count()
  File "/Users/xxx/miniconda3/lib/python3.7/site-packages/Bio/motifs/__init__.py", line 217, in count
    counts[letter] = [0] * self.length
TypeError: can't multiply sequence by non-int of type 'NoneType'
```

**Comment by peterjc** [comment]
In this example, there are only 5 ``<motif>`` elements - is this the random subset you mentioned?

```
$ grep -c "<motif " meme.xml 
5
```

**Comment by mwittep** [comment]
No, I chose to get at most 5 motifs from MEME. The subset I meant refers to the sequences used for the analyses from the given input. The file I uploaded was generated with a FASTA file with >1000 sequences, but only 1000 sequences are used by meme. I produced many subsets of the same file with a different number of sequences (950, 1000, 1001, 1100), and the BioPython parser failed for all those >1000. In my research for the error, I came across a page stating that MEME uses only a subset of the input sequences, if the number is larger than 1000. Sadly, I don't remember where exactly I found this information.

The problem might be that for the files produced by FASTA files with >1000 seqs that the ```<contributing_sites>``` tags are just empty.

**Comment by mwittep** [comment]
Since no contributing_sites are given (sorry, I did not see that they were missing before opening the issue), then I won't be able to do what I expected. Still, thanks!
