### ISSUE TITLE
Do not use assert outside testing

### ISSUE THREAD

**Issue by fabianegli** [biopython/biopython#3600]
There are multiple uses of assert inside the production code. This is bad practice because assert is removed when python is run with optimization, e.g. `python -0 some_script_using_biopython.py`. The problem with assert is that it is not a reliable flow control and input check for code that is run outside the programmers control.

Use the following command to find assert throughout the biopython codebase:

```shell
git grep "^[^.>#]*assert" | egrep -v "^Tests/"
```

Some uses in doctests (remove the `>` from the above regex to reveal them) are probably fine but not all the others.

**Comment by fabianegli** [comment]
There are different use cases in the code AFACT:

1. Control Program flow: this includes input checks
    * These cases need to be replaced with proper if statements.
2. Tests: Testing assumptions about the codebase
    * These cases should be moved from `Bio` production code to the `Tests`

**Comment by peterjc** [comment]
There is probably a flake8 plugin for this, not https://pypi.org/project/flake8-assertive/ which does something different.

**Comment by fabianegli** [comment]
I have no idea if there is a tool that helps with this - but that would be cool :-)

Help wanted is fine with me. I am not territorial on this issue. Good first might be true for the part of the issue where program flow is the intended effect, the testing might be a bit more involved in some cases. There might be multiple PRs to solve this issue. Anyone who's new could go through one, few or multiple of the affected files. So yes, both flags are fine with me.

**Comment by JoaoRodrigues** [comment]
I'm a little late to the party with the asserts but I see them as very
valuable checks, particularly in a library like ours. Sometimes we *do*
want to enforce a specific type or size or something and asserts are very
valid for this.

Do we ever build with -O? Asserts should anyway not be used for important
checks but for developer usage they can be useful.

A quarta, 9/06/2021, 10:17, Fabian Egli ***@***.***> escreveu:

**Comment by mdehoon** [comment]
I agree with @JoaoRodrigues  . Also, for bug reports it's very useful to catch errors early.

**Comment by fabianegli** [comment]
I might have been to vague about my intention by putting the focus on the functionality. I do not argue against the checks but merely point out that they are lost if python is invoked with optimization. In fact I opened the issue in the hope the checks would be changed from assert to if statements to ensure they are not removed by the optimization and always run and show up in bug reports, logs and error messages.

**Comment by fabianegli** [comment]
@JoaoRodrigues  It does not matter how biopython is "built", but how python is invoked.

```shell
$ cat assert-test.py 
from Bio.SeqFeature import BetweenPosition
BetweenPosition(1, 2, 3)
print("The assertion did not run.")

$ python -O assert-test.py 
/path/to/biopython/Bio/__init__.py:118: BiopythonWarning: You may be importing Biopython from inside the source tree. This is bad practice and might lead to downstream issues. In particular, you might encounter ImportErrors due to missing compiled C extensions. We recommend that you try running your code from outside the source tree. If you are outside the source tree then you have a setup.py file in an unexpected directory: /path/to/biopython
  warnings.warn(
The assertion did not run.
$ python assert-test.py 
/path/to/biopython/Bio/__init__.py:118: BiopythonWarning: You may be importing Biopython from inside the source tree. This is bad practice and might lead to downstream issues. In particular, you might encounter ImportErrors due to missing compiled C extensions. We recommend that you try running your code from outside the source tree. If you are outside the source tree then you have a setup.py file in an unexpected directory: /path/to/biopython
  warnings.warn(
Traceback (most recent call last):
  File "assert-test.py", line 2, in <module>
    BetweenPosition(1, 2, 3)
  File "/path/to/biopython/Bio/SeqFeature.py", line 1899, in __new__
    assert position == left or position == right
AssertionError
$
```

NB: In the case where the assertion did not run an invalid `BetweenPosition` object has been created. If the assert were an if statement, the test would not be removed by the optimization.

I think it would be great to be able to run biopython with optimization without loosing these checks. That's the goal I want to reach with this issue. Basically biopython should behave the same way with and without optimization.

**Comment by peterjc** [comment]
Yes, sorry - I should have clarified this earlier. We're talking about replacing things like this which may not actually be run depending on how Python is invoked:

```python
assert len(value) > 4, "Bad input"
```

with an if-statement and explicit error raising:

```python
if len(value) < 5:
    raise ValueError("Bad input")
```

**Comment by JulianMaurin** [comment]
> There is probably a flake8 plugin for this, not https://pypi.org/project/flake8-assertive/ which does something different.

> I might have been to vague about my intention by putting the focus on the functionality. I do not argue against the checks but merely point out that they are lost if python is invoked with optimization. In fact I opened the issue in the hope the checks would be changed from assert to if statements to ensure they are not removed by the optimization and always run and show up in bug reports, logs and error messages.


Hello @fabianegli, @peterjc
Even simpler, what do you think about: https://github.com/biopython/biopython/pull/4017

**Comment by peterjc** [comment]
Via a suggestion on #4017, an alternative to grep for finding these asserts is:

```
$ pip install bandit
$ bandit -t B101 -r BioSQL/ Bio/ 
...
```

It is rather verbose (even with ``-q`` or ``--quiet``), but currently reports 588 cases, suggesting the grep has a few false positives:

```
$ git grep "^[^.>#]*assert" | egrep -v "^Tests/" | wc -l
     607
```

The grep approach has the advantage of making it easy to see which files to prioritise. e.g.

```
$ git grep "^[^.>#]*assert" | egrep -v "^Tests/" | cut -f 1 -d ":" | uniq -c | sort -n | tail
  16 Bio/SeqIO/InsdcIO.py
  18 Bio/AlignIO/ClustalIO.py
  19 Bio/GenBank/Scanner.py
  21 Bio/SwissProt/__init__.py
  22 Bio/Entrez/Parser.py
  22 Bio/SeqIO/QualityIO.py
  22 Bio/SeqIO/SffIO.py
  30 Bio/AlignIO/FastaIO.py
  34 Bio/Align/exonerate.py
  67 Bio/GenBank/__init__.py
```

The "worst offender" ``Bio/GenBank/__init__.py`` is something of a special case. All the unindented asserts are in-situ testing of the regular expressions which doubles as regex documentation. i.e. I would leave those alone, and just fix the ~16 asserts in the actual code below that.

**Comment by fabianegli** [comment]
I think it would be nicer to have the tests of the regexes as part of the test suite. They don't need to run on every import.

**Comment by JulianMaurin** [comment]
Small remarks about the grep/regex strategy, you will met false positive on: 

```python
def func():
	"""
	assert x
	"""
	pass
```

**Comment by fabianegli** [comment]
@JulianMaurin Can you please elaborate a bit more on you last post? I don't understand what you are trying to tell us.

**Comment by JulianMaurin** [comment]
A small remark responding to: 

> It is rather verbose (even with -q or --quiet), but currently reports 588 cases, suggesting the grep has a few false positives

To promote the addition of `bandit` at #4017 :smile: 

Nothing related to `GenBank/__init__.py`. But if I can give my opinion on this topic, these asserts have nothing to do here and would find their place in the test suite. There are more elegant ways to document the regex.

**Comment by mdehoon** [comment]
> There are different use cases in the code AFACT:
> 
>     1. Control Program flow: this includes input checks
>        
>        * These cases need to be replaced with proper if statements.
> 
>     2. Tests: Testing assumptions about the codebase
>        
>        * These cases should be moved from `Bio` production code to the `Tests`

The `assert` statements on regular expressions in `Bio/GenBank/__init__.py` are a third use case - effectively code documentation and a sanity check of complex pieces of code. To me, `assert` statements make the most sense there.

**Comment by mdehoon** [comment]
> We can verbose the regexes to make them readable (

Yes we can do that.

> and we can move tests to the test suite to make them reliable.

But the assertion statements make the code much easier to understand, as they contain concrete examples of the patterns we are looking for. Regexes will still be difficult even if we make them more readable.

**Comment by ssarmin** [comment]
I have read the discussion above. I would like to work on replacing assert statements with explicit if/raise error handling in Bio/Align/hhr.py. Is this file still available?

**Comment by peterjc** [comment]
@ssarmin yes, I think so.

On a more general point, five years on there is a new valid use case for the `assert` statement - providing type hints to tools like `mypy`. Retrospectively adding typing is much harder to use in a legacy code base like Biopython (see #2236), but in other newer projects I have found that a very useful technique. So some of the newer asserts in Biopython may have been done for that reason.

**Comment by ssarmin** [comment]
@peterjc , I checked the Bio/Align/hhr.py file, and none of the assert statements are related to type checking, so I'll go ahead with this file. If I do find any type-checking-related assert statements in another file later on, should I leave them as-is?
