### ISSUE TITLE
"Unknown format" ValueError message could be more helpful

### ISSUE THREAD

**Issue by fabianegli** [biopython/biopython#3614]
### Setup

Biopython version 1.79

### Steps to reproduce

```
>>> from Bio import SeqIO
>>> handle = ExPASy.get_sprot_raw("O23729")
>>> entry = SeqIO.read(handle, "swiss")
>>> entry.format("txt")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/eglif/github/fabianegli/biopython/Bio/SeqRecord.py", line 724, in format
    return self.__format__(format)
  File "/Users/eglif/github/fabianegli/biopython/Bio/SeqRecord.py", line 762, in __format__
    SeqIO.write(self, handle, format_spec)
  File "/Users/eglif/github/fabianegli/biopython/Bio/SeqIO/__init__.py", line 548, in write
    raise ValueError("Unknown format '%s'" % format)
ValueError: Unknown format 'txt'
```

### Proposed changes

Give a list of available formats **or** a hit where/how to find this list. e.g.:

```
ValueError: Unknown format 'txt'. Available formats are <insert list of available formats>
```

How to find all the occurrences of such errors:
```shell
$ git grep -n 'Unknown format'
Bio/Align/__init__.py:1396:            raise ValueError("Unknown format %s" % fmt)
Bio/AlignIO/__init__.py:232:            raise ValueError("Unknown format '%s'" % format)
Bio/AlignIO/__init__.py:259:        raise ValueError("Unknown format '%s'" % format)
Bio/AlignIO/__init__.py:334:            raise ValueError("Unknown format '%s'" % format)
Bio/SearchIO/_utils.py:55:                "Unknown format %r. Supported formats are %r"
Bio/SeqIO/__init__.py:548:    raise ValueError("Unknown format '%s'" % format)
Bio/SeqIO/__init__.py:609:    raise ValueError("Unknown format '%s'" % format)
Bio/motifs/__init__.py:116:        raise ValueError("Unknown format %s" % fmt)
Bio/motifs/__init__.py:577:            raise ValueError("Unknown format type %s" % format_spec)
Bio/motifs/__init__.py:604:        raise ValueError("Unknown format type %s" % fmt)
Bio/phenotype/__init__.py:138:            raise ValueError("Unknown format '%s'" % format)
Bio/phenotype/__init__.py:186:            raise ValueError("Unknown format '%s'" % format)
```

**Comment by peterjc** [comment]
For SeqIO, AlignIO, and SearchIO we should have a dict or similar which can supply the valid formats trivially (and will always be up to date). That seems a good idea. Beware input vs output formats and other restrictions.

That may not be so easy for the other examples...
