### ISSUE TITLE
ValueError raised by MafIO.get_spliced

### ISSUE THREAD

**Issue by iminkin** [biopython/biopython#3626]
Hi,

I would like to report (what seems to be) a bug with with MafIO.get_spliced function. Here is the output of running system information script suggested in the issue template:

`3.8.5 (default, Sep  4 2020, 07:30:14) 
[GCC 7.3.0]
CPython
Linux-5.8.0-53-generic-x86_64-with-glibc2.10
1.79
`
Here is the python code:

`from Bio import AlignIO
from Bio.AlignIO import MafIO

idx = MafIO.MafIndex("chr4.idx", "chr4.maf", "hg19.chr4")
multiple_alignment = idx.get_spliced([75013150], [75033882], +1)
`

The "chr4.maf" file referenced in the script can be downloaded at [at](https://drive.google.com/file/d/1z-QMZaRnhLE2F09E2V2S49NCqQ_Jr4eE/view?usp=sharing.)

The output I get is the following:

`Traceback (most recent call last):
  File "reproduce.py", line 12, in <module>
    multiple_alignment = idx.get_spliced([75013150], [75033882], +1)
  File "/home/ilia/.local/lib/python3.8/site-packages/Bio/AlignIO/MafIO.py", line 747, in get_spliced
    raise ValueError(
ValueError: Target seqname (hg19.chr4) has 75345 records, expected 75387
`

**Comment by peterjc** [comment]
Boring but important question - where did ``chr4.maf`` come from, and are you sure it is valid?

Did you build the index ``chr4.idx`` on the same machine? (I want to rule out any oddities between Linux and Windows new line characters).

Thanks for sharing the test case. I have not opened it yet though...

**Comment by iminkin** [comment]
Yes, I built chr4.idx on the same machine. The file is a subset I extracted from another MAF https://bds.mpi-cbg.de/hillerlab/CESAR/realignedMaf_100way.maf, which was published as supplementary data for [this paper](https://academic.oup.com/nar/article/44/11/e103/2468292). I will probably try to make an index out of the whole file to see if the error persists.

**Comment by peterjc** [comment]
I get the same error as you. I'd have to dig much deeper into the code to understand what it means by record count. Note neither number matches this:

```
$ grep hg19.chr4 chr4.maf -c
14531
```

Looking at the file, I presume it should first be pulling out sequence from this line (shown truncated):

```
s hg19.chr4         74964857 58449 + 191154276 AGCGGCTGTGCGAGGAGGAGAGCTGGCAAGGAGCTGCCTGTGGCCCGGGCTCTGTGGCTCTCCGAGAACGGCGAACCCCTTTTATGCATGGTTGGGGCTGGAAAGCCCGGAGTCCCGGGCCAGGGAAATTCCCGGAGCTCCAGATCGATCCCGAGTTCGGAAGGAAGGCGATGGCCCCGCCTCTGGGGTGGAGGGGGGTCGGGGCACTCACGAGTGACGTCCGGGTCTGACTGTCTTGCGTAACTCCCGCCAACTGTGGGATGTTCTCTTTCTGCCCCGAATCCCTGGAGCGGGAGCGAGAGCCCGCCGCTCTCAGAGATACCGAGATAACCG...
```

That has a start of 74964857 and length 58449 taking it to 75023306 (all plus/minus one for conversion to Python counting), so it would need more:

```
s hg19.chr4              75023306 571 + 191154276 AAAGTCCAGACCTTCCTTGTTCAGCCAGGTTT---TGC------------TCC---TTC---------TCC------------ACA----CAC------------CTTTGTTCT---TTTCTC---------CAA------------CTT---------CCAAGG------AAT------CTC---------ACA---------AAG------------GAA---------------GTG-GGAAAC--AATGAACCT---ATT-ACTTCT-TTC------CTGCTTTAAATCCAATTCCACGTAGTCACGGAG-ACTGTT---GGG-CAGGATCTCTGG-CTT------GGTGGA---AAGTGG-GGCGTGCTGCCT---------AAAGTG-ATA-GTT-TGGAGGCCTTCTCTGTGC---CGTCGCTAT---GGGAATGCCAGCTAT---ATGTTG---GCT---GGGTGC---------GGG---------------GCC---CAGTCG------------CCA------GGC---CAC---------------ACT---------GCACGC------------TTC---------------------------CAC---ATC---------------------------------------------CTC------------AGA---------------------------------------------------------------------------------------------------------------------GGG---------------------CCC------------------------------GGG------------------ACT------------------TGG---------------------------------------------GTC---CTGGCC---CCG---------CCC---CCT------------------------GCGGAC------------CCGGCA---CTC---TGT---CAG------TTC---------------------CGT---------------------CCC------------CGG------------------------------------------------------TCC---------------TGG------GAA---------CCG------------------------------------CTC---TTT---------------ACC------CCA---------------------CTC---------TGC---------GTG---TCT---------GCC------------------GGA---ACC------------------TGG------CTGGGA---AGC---------------GCT---------------------ACTTGCTGC---CCT---GCC------AGC---CCGGGT------------------GAGGGCGGA---GCCAGG---CCTCCA---GCCGCG---AGGACTGGAGTC-GCG---GGAGGTGGAGCCCCAGTCCGGAAGCCGGGG------ATCCGCGGCCATGACGGTGCCGGTCCGCGGCT
```

Very messy, but that takes us to 75023306 + 571 = 75023877, so you still want more. Next would be:

```
s hg19.chr4              75023835 183 + 191154276 GAAGCCGGGGATCCGCGGCCATGACGGTGCCGGTCCGCGGCTTCTCGCTGCTCCGCGGCCGCCTT---GGCCGAGCG-CCG-GCGTTGGGCAGAAGCACAGCACCCTCCGTAAGGGCACCGGGAGAGCCCGGGAGTGCG-TTCCGGGGCTTTCGG---AGCAGCGGT---------GTGAGGTACGAGGGCTGCGGGCGCC
```

The start of your region of interest seems fine.

I think it is definitely worth trying indexing the full file and seeing if that works, hopefully it doesn't take too long to run.

**Comment by iminkin** [comment]
If I try to index the whole file, I get the following error:

> Traceback (most recent call last):
>  File "reproduce.py", line 4, in <module>
>    idx = MafIO.MafIndex("19way.idx", "realignedMaf_100way.maf", "hg19.chr4")
>  File "/home/ilia/.local/lib/python3.8/site-packages/Bio/AlignIO/MafIO.py", line 277, in __init__
>    self._record_count = self.__make_new_index()
>  File "/home/ilia/.local/lib/python3.8/site-packages/Bio/AlignIO/MafIO.py", line 406, in __make_new_index
>    batch = list(islice(mafindex_func, 100))
>  File "/home/ilia/.local/lib/python3.8/site-packages/Bio/AlignIO/MafIO.py", line 455, in __maf_indexer
>    raise ValueError(
> ValueError: Target for indexing (hg19.chr4) not found in this bundle

However, hg19.chr4 is present in some of the blocks in the alignment file (not in all of them, though). Indexing works only if all the blocks contain hg19.chr4. Is it the expected behavior.

**Comment by peterjc** [comment]
I don't know - any comments from our MAF experts @adamnovak , @blaiseli etc?

**Comment by blaiseli** [comment]
I don't remember precisely how the MAF format is supposed to work, but looking at the implementation, it seems that the `MafIndex` class heavily relies on its `_target_seqname` attribute.

If such an assymetry is not part of MAF format (not obvious when briefly looking at https://genome.ucsc.edu/FAQ/FAQformat.html#format5), then the whole implementation should be re-thought.

**Comment by blaiseli** [comment]
It seems that aligned blocks are stored in the index into bins determined on the basis of the genomic coordinates of this `_target_seqname` reference sequence. Without this sequence in a block, it will be impossible to compute this bin.

See `__maf_indexer` in particular.

**Comment by peterjc** [comment]
So if it is legitimate for a reference (here ``hg19.chr4``) not to be in a block, then perhaps the current code can continue to work with a tweak to the indexing to ignore such blocks?

**Comment by blaiseli** [comment]
I had a look at the maf file around the queried region, and I notice something fishy.

Here are the blocks in this region, in terms of hg19.chr4 (chrom, start, length, strand) coordinates, copied from the maf file:

```python
blocks = [
    "hg19.chr4         74964857 58449 +",
    "hg19.chr4              75023306 571 +",
    "hg19.chr4              75023835 183 +",
    "hg19.chr4              75024018 16184 +",
    "hg19.chr4                     75040202 225 +"]
````

And here is what I obtain when computing the start and stop coordinates (basically, the same thing @peterjc was doing):

```python
for line in blocks:
    chrom, start, length, strand = line.split()
    print(int(start), int(start) + int(length))
```

```
74964857 75023306
75023306 75023877
75023835 75024018
75024018 75040202
75040202 75040427
```

The end of the second block (75023877) falls within the third block (75023835-75024018).

I'm not sure this is supposed to happen.

**Comment by blaiseli** [comment]
The above might explain why the initial error was triggered:

```python
        # make sure the number of bp entries equals the sum of the record lengths
        if len(split_by_position[self._target_seqname]) != total_rec_length:
            raise ValueError(
                "Target seqname (%s) has %s records, expected %s"
                % (
                    self._target_seqname,
                    len(split_by_position[self._target_seqname]),
                    total_rec_length,
                )
            )
```

And here is how the split_by_position is described in the code:

```python
        # split every record by base position
        # key: sequence name
        # value: dictionary
        #        key: position in the reference sequence
        #        value: letter(s) (including letters
        #               aligned to the "-" preceding the letter
        #               at the position in the reference, if any)
        split_by_position = {seq_name: {} for seq_name in all_seqnames}

        # keep track of what the total number of (unspliced) letters should be
        total_rec_length = 0
```

Later, I see that `total_rec_length` is incremented by the lengths of the reference sequence in each retrieved block.

It seems that a number of "records" is actually a number of letters in the sequence. The error message could be improved.

**Comment by blaiseli** [comment]
The sequence of the second block ends with: `"GAAGCCGGGG------ATCCGCGGCCATGACGGTGCCGGTCCGCGGCT"`, while the sequence of the third block starts with `GAAGCCGGGGATCCGCGGCCATGACGGTGCCGGTCCGCGGCT`:

This piece of sequence has been aligned twice (and it seems to be the same for panTro4.chr4).

**Comment by iminkin** [comment]
Hi @blaiseli, thank you for checking this thoroughly. It seems that there is some issue with the MAF file.
