### ISSUE TITLE
test_MafIO_index.TestSpliceGoodMAF is failing on Windows 64bit

### ISSUE THREAD

**Issue by JoaoRodrigues** [biopython/biopython#3640]
The new CI workflow in GHA is not passing on Windows, because of a failing test in `MafIO`. Traceback below:

```
======================================================================
ERROR: test_correct_retrieval_1 (test_MafIO_index.TestSpliceGoodMAF)
Correct retrieval of Cnksr3 in mouse.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\a\biopython\biopython\Tests\test_MafIO_index.py", line 668, in test_correct_retrieval_1
    result = self.idx.get_spliced(
  File "D:\a\biopython\biopython\build\lib.win-amd64-3.8\Bio\AlignIO\MafIO.py", line 650, in get_spliced
    fetched = list(self.search(starts, ends))
  File "D:\a\biopython\biopython\build\lib.win-amd64-3.8\Bio\AlignIO\MafIO.py", line 622, in search
    raise ValueError(
ValueError: Expected 3185728-3185797 @ offset 1974167, found 3185634-3185640

----------------------------------------------------------------------
```

Since the test is passing on Linux and MacOS, I suspect a line end issue, but I don't have a Win machine here to debug it.

**Comment by peterjc** [comment]
Looks like #1149 strikes again.

**Comment by peterjc** [comment]
See https://github.com/biopython/biopython/issues/1149#issuecomment-727122114 specifically, can we close this as a duplicate?

**Comment by peterjc** [comment]
Cross reference #3580 which added GitHub action testing
