### ISSUE TITLE
Sequence multiplication tests failing (Linux pypy3)

### ISSUE THREAD

**Issue by peterjc** [biopython/biopython#3659]
Not sure if this is new, or dates back to #3580 adding GitHub actions for continuous integration, but Linux pypy3 is failing e.g. https://github.com/biopython/biopython/runs/2996703017 

```
======================================================================
ERROR: test_imul_method (test_seq.TestSeqMultiplication)
Test imul method; relies on addition and mull methods.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/biopython/biopython/Tests/test_seq.py", line 472, in test_imul_method
    seq *= factor
  File "/home/runner/work/biopython/biopython/build/lib.linux-x86_64-3.6/Bio/Seq.py", line 526, in __imul__
    return self.__class__(self._data * other)
  File "/home/runner/work/biopython/biopython/build/lib.linux-x86_64-3.6/Bio/Seq.py", line 2561, in __init__
    "data should be a string, bytearray object, Seq object, or a "
TypeError: data should be a string, bytearray object, Seq object, or a MutableSeq object

======================================================================
ERROR: test_mul_method (test_seq.TestSeqMultiplication)
Test mul method; relies on addition method.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/biopython/biopython/Tests/test_seq.py", line 435, in test_mul_method
    self.assertEqual(seq * factor, seq + seq + seq)
  File "/home/runner/work/biopython/biopython/build/lib.linux-x86_64-3.6/Bio/Seq.py", line 486, in __mul__
    return self.__class__(self._data * other)
  File "/home/runner/work/biopython/biopython/build/lib.linux-x86_64-3.6/Bio/Seq.py", line 2561, in __init__
    "data should be a string, bytearray object, Seq object, or a "
TypeError: data should be a string, bytearray object, Seq object, or a MutableSeq object

======================================================================
ERROR: test_rmul_method (test_seq.TestSeqMultiplication)
Test rmul method; relies on addition method.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/biopython/biopython/Tests/test_seq.py", line 452, in test_rmul_method
    self.assertEqual(factor * seq, seq + seq + seq)
  File "/home/runner/work/biopython/biopython/build/lib.linux-x86_64-3.6/Bio/Seq.py", line 497, in __rmul__
    return self.__class__(self._data * other)
  File "/home/runner/work/biopython/biopython/build/lib.linux-x86_64-3.6/Bio/Seq.py", line 2561, in __init__
    "data should be a string, bytearray object, Seq object, or a "
TypeError: data should be a string, bytearray object, Seq object, or a MutableSeq object

----------------------------------------------------------------------
```

**Comment by gouttegd** [comment]
It looks more like a NumPy and/or a PyPy issue.

Independently of BioPython, multiplying a `bytearray` with a NumPy integer gives a completely different result between CPython and PyPy:

With CPython 3.8.3 (GNU/Linux x86_64):
```
>>>> import numpy
>>>> bytearray('ACGT', 'ascii') * numpy.intc(3)
bytearray(b'ACGTACGTACGT')
```

With PyPy 3.7.10 (same system):
```
>>>> import numpy
>>>> bytearray('ACGT', 'ascii') * numpy.intc(3)
array([195, 201, 213, 252], dtype=uint8)
```

The `MutableSeq` constructor does not expect this `numpy.ndarray`, hence the failure reported.

**Comment by gouttegd** [comment]
Nevermind, I didn't notice that @mdehoon was [ahead of me](https://foss.heptapod.net/pypy/pypy/-/issues/3507)... ^^' Sorry for the noise.

**Comment by mdehoon** [comment]
PR #3648 includes a workaround for this bug.

**Comment by peterjc** [comment]
This is working now, presumably since #3648 was merged. Closing
