### ISSUE TITLE
substitution_matrices.load() returns README.txt

### ISSUE THREAD

**Issue by peterjc** [biopython/biopython#3707]
### Setup

I am reporting a problem with Biopython version, Python version, and operating
system as follows:

```python
>>> import sys; print(sys.version)
3.8.5 (default, Sep  4 2020, 02:22:02) 
[Clang 10.0.0 ]
>>> import platform; print(platform.python_implementation()); print(platform.platform())
CPython
macOS-10.15.7-x86_64-i386-64bit
>>> import Bio; print(Bio.__version__)
1.80.dev0
```

Note: Development install using ``pip install -e .`` which could mean a difference in the files present.

### Expected behaviour

Expect ``from Bio.Phylo.TreeConstruction import DistanceCalculator`` to work even on a development install, and the doctests to pass.

### Actual behaviour

```
$ python -c "from Bio.Phylo.TreeConstruction import DistanceCalculator"
RDFLib Version: 6.0.0
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/xxx/repositories/biopython/Bio/Phylo/TreeConstruction.py", line 360, in <module>
    class DistanceCalculator:
  File "/Users/xxx/repositories/biopython/Bio/Phylo/TreeConstruction.py", line 433, in DistanceCalculator
    matrix = substitution_matrices.load(name)
  File "/Users/xxx/repositories/biopython/Bio/Align/substitution_matrices/__init__.py", line 513, in load
    matrix = read(path)
  File "/Users/xxx/repositories/biopython/Bio/Align/substitution_matrices/__init__.py", line 493, in read
    assert letter1 == row.pop(0)
AssertionError
```

Debugging this,

```
$ python -c "from Bio.Align.substitution_matrices import load; print(load())"
['BENNER22', 'BENNER6', 'BENNER74', 'BLOSUM45', 'BLOSUM50', 'BLOSUM62', 'BLOSUM80', 'BLOSUM90', 'DAYHOFF', 'FENG', 'GENETIC', 'GONNET1992', 'HOXD70', 'JOHNSON', 'JONES', 'LEVIN', 'MCLACHLAN', 'MDM78', 'NUC.4.4', 'PAM250', 'PAM30', 'PAM70', 'RAO', 'README.txt', 'RISLER', 'SCHNEIDER', 'STR', 'TRANS']
```

The inclusion of ``README.txt`` is the root cause, attempting to parse this as a matrix fails:

https://github.com/biopython/biopython/blob/master/Bio/Align/substitution_matrices/data/README.txt

Possible fix is to explicit exclude that here:

https://github.com/biopython/biopython/blob/biopython-179/Bio/Align/substitution_matrices/__init__.py#L510

**Comment by mdehoon** [comment]
Fixed by #3712
