### ISSUE TITLE
ladderize fails in Bio.Nexus.Trees.Tree.to_string()

### ISSUE THREAD

**Issue by anders-was-here** [biopython/biopython#3780]
### Setup

I am reporting a problem with Biopython version, Python version, and operating
system as follows:

```python
3.7.9 (default, Aug 19 2020, 17:05:11) 
[GCC 9.3.1 20200408 (Red Hat 9.3.1-2)]
CPython
Linux-5.8.18-100.fc31.x86_64-x86_64-with-fedora-31-Thirty_One
1.79
```

### Actual behaviour

```
Traceback (most recent call last):
File "to_string.py", line 11, in <module>
    print(t.to_string(ladderize="LEFT"))
File "/home/andla/.local/lib/python3.7/site-packages/Bio/Nexus/Trees.py", line 732, in to_string
    subtrees = [newickize(sn, ladderize=ladderize) for sn in succnodes]
File "/home/andla/.local/lib/python3.7/site-packages/Bio/Nexus/Trees.py", line 732, in <listcomp>
    subtrees = [newickize(sn, ladderize=ladderize) for sn in succnodes]
File "/home/andla/.local/lib/python3.7/site-packages/Bio/Nexus/Trees.py", line 714, in newickize
    succnodes = ladderize_nodes(self.node(node).succ, ladderize=ladderize)
File "/home/andla/.local/lib/python3.7/site-packages/Bio/Nexus/Trees.py", line 700, in ladderize_nodes
    succnodes = zip(*succnode_terminals)[1]
TypeError: 'zip' object is not subscriptable
```

zip(...)[1] is not valid in Python 3. 

### Steps to reproduce

```python
from Bio.Nexus import Trees

t = Trees.Tree(
    "(((B 9:0.385832, (C 8:0.445135, C 4:0.41401)C:0.024032)B:0.041436,"
    "A 6:0.392496)A:0.0291131, t2:0.497673, ((E 0:0.301171,"
    "E 7:0.482152)E:0.0268148, ((G 5:0.0984167,G 3:0.488578)G:0.0349662,"
    "F 1:0.130208)F:0.0318288)D:0.0273876);"
)
print(t.to_string(ladderize="LEFT"))
```

**Comment by peterjc** [comment]
That's Python 2 to 3 oversight. Try changing that line to:

```python
succnodes = list(zip(*succnode_terminals))[1]
```

If that works, maybe you could submit it as a pull request along with turning your example into a test case?

**Comment by anders-was-here** [comment]
> That's Python 2 to 3 oversight. Try changing that line to:
> 
> ```python
> succnodes = list(zip(*succnode_terminals))[1]
> ```
> 
> If that works, maybe you could submit it as a pull request along with turning your example into a test case?

Yes, the traceback disappears and the result is this:

`tree a_tree = ((A 6,(B 9,(C 8,C 4))),t2,((E 0,E 7),(F 1,(G 5,G 3))));
`

I'll try to create a pull request.

**Comment by peterjc** [comment]
Great :)

**Comment by anders-was-here** [comment]
Pull request #3781
