### ISSUE TITLE
Adding str and int never works

### ISSUE THREAD

**Issue by anders-was-here** [biopython/biopython#3783]
> Can you actually trigger this type mismatch? Does it depend on a non-standard input file?

### Steps to reproduce

Yes, when I look at it I actually can reproduce it. Code example:

```
import io
from Bio import phenotype

f = io.StringIO('{"csv_data": {"Plate Type": "PM-999"}, "measurements": {"Hour": 9}}')

for x in phenotype.phen_micro.JsonIterator(f):
    print(x)

```

### Expected result (from naive fix of issue)
```
/home/user/.local/lib/python3.7/site-packages/Bio/phenotype/__init__.py:96: BiopythonExperimentalWarning: Bio.phenotype is an experimental submodule which may undergo significant changes prior to its future official release.
  BiopythonExperimentalWarning,
/home/user/.local/lib/python3.7/site-packages/Bio/phenotype/phen_micro.py:961: UserWarning: Non-standard plate ID found (PM-999), using PM999
  plateID, _platesPrefix, abs(int(pID)))
Plate ID: PM999
Well: 0
Rows: 0
Columns: 0
PlateRecord()
```

### Actual result
```
/home/user/.local/lib/python3.7/site-packages/Bio/phenotype/__init__.py:96: BiopythonExperimentalWarning: Bio.phenotype is an experimental submodule which may undergo significant changes prior to its future official release.
  BiopythonExperimentalWarning,
Traceback (most recent call last):
  File "./1.py", line 34, in <module>
    for x in phenotype.phen_micro.JsonIterator(f):
  File "/home/user/.local/lib/python3.7/site-packages/Bio/phenotype/phen_micro.py", line 961, in JsonIterator
    % (plateID, _platesPrefix + abs(int(pID)))
TypeError: can only concatenate str (not "int") to str
```

**Comment by peterjc** [comment]
What do you think @mgalardini?

**Comment by anders-was-here** [comment]
I mean it's probably easy to fix by replacing 4 instances of:

`abs(int(pID)))
`
with 
`
str(abs(int(pID)))`

But something like:

```
 warnings.warn("Non-standard plate ID found ({}), using {}{}".format(
               plateID, _platesPrefix, abs(int(pID))))
```
would probably feel cleaner. (I'm not gonna write any unit test for this).

**Comment by peterjc** [comment]
Can you actually trigger this type mismatch? Does it depend on a non-standard input file?

**Comment by anders-was-here** [comment]
> Can you actually trigger this type mismatch? Does it depend on a non-standard input file?

Yes, when I look closer I could actually do a reasonable reproduction. See unit test in pull request.

**Comment by mgalardini** [comment]
Really sorry for not seeing this earlier; many thanks for finding and fixing this @anders-was-here !
