### ISSUE TITLE
`Bio.PDB.internal_coords.AtomKey.__init__` fails during class construction of `Bio.PDB.internal_coords.IC_Chain`

### ISSUE THREAD

**Issue by bzoracler** [biopython/biopython#3793]
### Setup

I am reporting a problem with Biopython version, Python version, and operating
system as follows:

```python
3.8.10 (default, May 30 2021, 17:33:00) 
[GCC 9.3.0]
CPython
Linux-5.13.0-7620-generic-x86_64-with-glibc2.2.5
1.79
```

and with `NumPy` version `1.21.2`.

### Expected behaviour

No issues when making an `IC_Chain` object from a `Bio.PDB.Chain.Chain` object.

### Actual behaviour

Using a `Bio.PDB.Chain.Chain` object as the constructor argument to `IC_Chain` fails:

```python
Traceback (most recent call last):
  File ".../lib/python3.8/site-packages/Bio/PDB/internal_coords.py", line 1313, in rak
    ak = self.akc[atm]
KeyError: <Atom N>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../lib/python3.8/site-packages/Bio/PDB/internal_coords.py", line 211, in __init__
    self.set_residues(verbose)  # no effect if no residues loaded
  File ".../lib/python3.8/site-packages/Bio/PDB/internal_coords.py", line 363, in set_residues
    if self._add_residue(res, last_res, last_ord_res, verbose):
  File ".../lib/python3.8/site-packages/Bio/PDB/internal_coords.py", line 292, in _add_residue
    res.internal_coord = IC_Residue(res)
  File ".../lib/python3.8/site-packages/Bio/PDB/internal_coords.py", line 1303, in __init__
    self._add_atom(atom)
  File ".../lib/python3.8/site-packages/Bio/PDB/internal_coords.py", line 1492, in _add_atom
    ak = self.rak(atm)  # passing Atom here not string
  File ".../lib/python3.8/site-packages/Bio/PDB/internal_coords.py", line 1315, in rak
    ak = self.akc[atm] = AtomKey(self, atm)
  File ".../lib/python3.8/site-packages/Bio/PDB/internal_coords.py", line 3261, in __init__
    "".join(filter(None, akl[:2])),
TypeError: sequence item 0: expected str instance, numpy.int64 found

```

### Steps to reproduce

```python
from Bio.PDB import mmtf
from Bio.PDB.internal_coords import IC_Chain

structure = mmtf.MMTFParser.get_structure_from_url("7EJT")
chain = next(structure.get_chains())
ic_chain = IC_Chain(chain)
```

---

### Suggested resolution

The directly offending code is 

https://github.com/biopython/biopython/blob/8546c9622bf7ca7d257a60477f4b9b4e39492b02/Bio/PDB/internal_coords.py#L3227-L3250

where `3228: if isinstance(akl[0], int):` does not account for when `akl[0]` is a `NumPy`-type integer,

```python
>>> import numpy
>>> num = numpy.array([0])[0]
>>> isinstance(num, int)
False
>>> type(num)
<class 'numpy.int64'>
```

thereby skipping execution of `3229: akl[0] = str(akl[0])  # numeric residue position to string`, and causing `3246: "".join(filter(None, akl[:2])),` to fail as it tries to execute `str.join` on a list containing a non-`str` item.

The easiest fix, as per https://stackoverflow.com/a/37727662/9407941, is something like changing line 3228 to

 `3228: if isinstance(akl[0], (int, numpy.integer)):`

However, I'm not sure if it is intended that `akl[0]` is supposed to be a `numpy`-type integer rather than a `builtins.int`, so this could be a symptom of another problem.

**Comment by rob-miller** [comment]
Sorry for the delay, and thank you - that is indeed the correct fix, will implement.

**Comment by rob-miller** [comment]
Submitted #3816 to fix in main branch now without waiting for #3774.
