### ISSUE TITLE
SeqRecord not properly adding in annotations

### ISSUE THREAD

**Issue by LifeMine-swyka** [biopython/biopython#3867]
I am reporting a problem with Biopython version, Python version, and operating
system as follows:

```python
>>> import sys; print(sys.version)
3.7.9 (default, Aug 31 2020, 12:42:55)
[GCC 7.3.0]
>>> import platform; print(platform.python_implementation()); print(platform.platform())
CPython
Linux-4.4.0-19041-Microsoft-x86_64-with-debian-buster-sid
>>> import Bio; print(Bio.__version__)
1.78
```

### Expected behaviour
```
updated_dct = {}
fna_input = SeqIO.to_dict(SeqIO.parse(genome.fna, 'fasta'))

for id, rec in fna_input.items():
    print(rec)
    new_rec = SeqRecord.SeqRecord(seq=rec.seq, id=rec.id, name=rec.name, description=rec.description, features=rec.features, annotations={"molecule_type": "DNA"})
    updated_dct[id] = new_rec
    print(new_rec)
```

"rec"
```
ID: NODE_1_c29
Name: NODE_1_c29
Description: NODE_1_c29
Number of features: 0
Seq('ATACTTTAATAATAATAATATTTTAAAGAGATTTTATTAATCTTTAAAAAATAG...TTT')
```

"new_rec"
```
ID: NODE_1_c29
Name: NODE_1_c29
Description: NODE_1_c29
Number of features: 0
Annotations: molecule_type=DNA
Seq('ATACTTTAATAATAATAATATTTTAAAGAGATTTTATTAATCTTTAAAAAATAG...TTT')
```

### Actual behaviour

"new_rec"
```
ID: NODE_1_c29
Name: NODE_1_c29
Description: NODE_1_c29
Number of features: 0
/molecule_type=DNA
Seq('ATACTTTAATAATAATAATATTTTAAAGAGATTTTATTAATCTTTAAAAAATAG...TTT')
```

In the updated_dct I am able to do:

```
>> print(new_rec.annotations)
{'molecule_type': 'DNA'}
```

However, when I print the updated_dct, I do not see "annotations" in the SeqRecord and I cannot use SeqIO.write:

```
>>print(updated_dct)
{'NODE_1_c29': SeqRecord(seq=Seq('ATACTTTAATAATAATAATATTTTAAAGAGATTTTATTAATCTTTAAAAAATAG...TTT'), id='NODE_1_c29', name='NODE_1_c29', description='NODE_1_c29', dbxrefs=[])}
```

```
  File "/home/swyka/miniconda3/envs/mconda/lib/python3.7/site-packages/Bio/SeqIO/Interfaces.py", line 218, in write_records
    self.write_record(record)
  File "/home/swyka/miniconda3/envs/mconda/lib/python3.7/site-packages/Bio/SeqIO/InsdcIO.py", line 981, in write_record
    self._write_the_first_line(record)
  File "/home/swyka/miniconda3/envs/mconda/lib/python3.7/site-packages/Bio/SeqIO/InsdcIO.py", line 744, in _write_the_first_line
    raise ValueError("missing molecule_type in annotations")
ValueError: missing molecule_type in annotations
```

**Comment by peterjc** [comment]
Could you share a self-contained example please?

To partly answer your question, the SeqRecord ``__repr__`` output is only a summary, quoting the help text:

>        Note that long sequences are shown truncated. Also note that any
>        annotations, letter_annotations and features are not shown (as they
>        would lead to a very long string).

I'm unclear why you make a new very similar ``SeqRecord`` rather than editing the existing one - have you tried something like this?:

```python
for rec in fna_input.values():
    rec.annotations["molecule_type"] = "DNA"
```

e.g. this shows where you need the molecule type for GenBank output:

```pycon
>>> from Bio.Seq import Seq
>>> from Bio.SeqRecord import SeqRecord
>>> rec = SeqRecord(Seq("ACGT"), id="Alpha", name="Alpha")
>>> print(rec.format("genbank"))
Traceback (most recent call last):
...
ValueError: missing molecule_type in annotations
```

Updating the record after it has been created:

```pycon
>>> rec.annotations["molecule_type"] = "DNA"
>>> print(rec.format("genbank"))
LOCUS       Alpha                      4 bp    DNA              UNK 01-JAN-1980
DEFINITION  .
ACCESSION   Alpha
VERSION     Alpha
KEYWORDS    .
SOURCE      .
  ORGANISM  .
            .
FEATURES             Location/Qualifiers
ORIGIN
        1 acgt
//
```

Or, creating the record with the DNA label from the start:

```pycon
>>> from Bio.Seq import Seq
>>> from Bio.SeqRecord import SeqRecord
>>> rec = SeqRecord(Seq("ACGT"), id="Alpha", name="Alpha", annotations={"molecule_type":"DNA"})
>>> print(rec.format("genbank"))
LOCUS       Alpha                      4 bp    DNA              UNK 01-JAN-1980
DEFINITION  .
ACCESSION   Alpha
VERSION     Alpha
KEYWORDS    .
SOURCE      .
  ORGANISM  .
            .
FEATURES             Location/Qualifiers
ORIGIN
        1 acgt
//
```

**Comment by LifeMine-swyka** [comment]
Hello,

Sorry, but I just figured it out. I was also writing the genbank from a gff and needed to add the annotations of {"molecule_type":"DNA"} to the GFF recs as well.
