### ISSUE TITLE
SnapGene files with line breaks in feature qualifiers result in corrupted genbank files

### ISSUE THREAD

**Issue by biostu24** [biopython/biopython#3885]
### Setup
python: 3.10.0 (default, Nov 10 2021, 11:24:47) [Clang 12.0.0 ]
implementation: CPython
platform: macOS-10.16-x86_64-i386-64bit
BioPython version: 1.78 (bug also appears in 1.79)

### Expected behaviour
In rare cases, line break characters can appear in SnapGene features. In the binary SnapGene format, this appears as "\&#10;". During parsing by BioPython (to SeqRecord), these characters result in line breaks in the strings. Saving the SeqRecord as genbank should gracefully deal with these line break characters.

### Actual behaviour
Reading a SnapGene file containing line breaks returns a SeqRecord. Saving this SeqRecord in Genbank format results in a corrupted genbank formatted file. For example:
```
FEATURES             Location/Qualifiers
     source          1..9692
                     /label="source"
     promoter        1..229
                     /label="RSV  promoter"
                     /note="/application_notes=Strong promoter; drives
                     transcription
of viral RNA in packaging cells."
```
Notice how the final line of text is not correctly indented. This incorrect indenting will cause all genbank parsers to fail to read the file. 

The source of this issue is due line break characters in the source SnapGene file ("\&#10;"). This results in qualifier value strings with line breaks. Biopython is not dealing with these line breaks correctly

After saving a SeqRecord with line breaks as a Genbank file, then reloading using Seq.IO.read, the following error is produced:
```
Traceback (most recent call last):
  File "/Users/my_user_name/Desktop/plasmid_bug/test_bug.py", line 30, in <module>
    _ = SeqIO.read('bugged_plasmid.gb', 'genbank')
  File "/Users/my_user_name/miniconda3/envs/utility/lib/python3.10/site-packages/Bio/SeqIO/__init__.py", line 656, in read
    record = next(iterator)
  File "/Users/my_user_name/miniconda3/envs/utility/lib/python3.10/site-packages/Bio/SeqIO/Interfaces.py", line 73, in __next__
    return next(self.records)
  File "/Users/my_user_name/miniconda3/envs/utility/lib/python3.10/site-packages/Bio/GenBank/Scanner.py", line 516, in parse_records
    record = self.parse(handle, do_features)
  File "/Users/my_user_name/miniconda3/envs/utility/lib/python3.10/site-packages/Bio/GenBank/Scanner.py", line 499, in parse
    if self.feed(handle, consumer, do_features):
  File "/Users/my_user_name/miniconda3/envs/utility/lib/python3.10/site-packages/Bio/GenBank/Scanner.py", line 470, in feed
    self._feed_feature_table(consumer, self.parse_features(skip=False))
  File "/Users/my_user_name/miniconda3/envs/utility/lib/python3.10/site-packages/Bio/GenBank/Scanner.py", line 230, in parse_features
    features.append(self.parse_feature(feature_key, feature_lines))
  File "/Users/my_user_name/miniconda3/envs/utility/lib/python3.10/site-packages/Bio/GenBank/Scanner.py", line 366, in parse_feature
    raise ValueError(
ValueError: Problem with 'promoter' feature:
1..229
/label="RSV  promoter"
/note="/application_notes=Strong promoter; drives
transcription
```

### Steps to reproduce
Unfortunately I cannot provide the original SnapGene file that caused this bug and I have not been able to introduce a line break character. The version of SnapGene that I have cleans these characters. However, the following code will recreate the bug:

```
from Bio import SeqIO
from Bio.Seq import Seq
from Bio.SeqRecord import SeqRecord
from Bio.SeqFeature import SeqFeature, FeatureLocation


# The line break in this feature qualifier label will cause an error
bugged_feature = SeqFeature(
    FeatureLocation(1, 2),
    type='misc_feature',
    qualifiers={'label': 'buggy\nlabel'} 
    )

record = SeqRecord(
    Seq('AAAA'),
    annotations = {'molecule_type': 'DNA'},
    features=[bugged_feature]
    )

SeqIO.write(record, 'test_file.gb', 'genbank')
_ = SeqIO.read('test_file.gb', 'genbank')
```

**Comment by peterjc** [comment]
It looks like there are several things we might want to do here.

* Change the SnapGene parser to replace literal newlines (perhaps with spaces, or slash escape them), and perhaps give a warning

* Change the GenBank writer to do either:
  -  replace literal newlines with a slash escaped one, or a space. Perhaps with a warning
  -  raise an exception.

CC @gouttegd for comment.

**Comment by biostu24** [comment]
@peterjc those sound like good solutions. I'd suggest a warning in the GenBank writer rather than raising an error, as line breaks can be easily solved.

**Comment by gouttegd** [comment]
@peterjc Replacing literal newlines with a single space seems when parsing from SnapGene seems good to me (with a warning that a data transformation occurred).

Having the GenBank writer do the same thing when writing would also be good, in case some newlines creep in through another way (as in the example given) – kind of a “belt and suspenders” approach.

Shall we extend that to other characters that may cause troubles? E.g. carriage returns (0x0D), form feeds (0x0C)? Or possibly even the entire range of control characters?

**Comment by erik-whiting** [comment]
Hello everyone. I've been hacking away at this problem for a few days and have come up with a fix for the parser side of the problem, I will start working on the generator side now. Do you mind assigning this to me @peterjc ?

**Comment by peterjc** [comment]
It looks like @gouttegd (who wrote the SnapGene parser) isn't working on this right now, so sure Erik - a PR for our GenBank parser is welcome. Thanks.

We're also suggesting a change to the SnapGene parser when parsing unusual SnapGene files with literal newlines (is that clearer now?).

**Comment by gouttegd** [comment]
I can take care of the SnapGene parser's side of things. Happy to let @erik-whiting take care of the GenBank side.

**Comment by erik-whiting** [comment]
Here are the changes I made so far: https://github.com/biopython/biopython/pull/3907
Do either of you mind taking a look at it and telling me if it's a good approach or not? I know next to nothing about the "bio" side of bioinformatics so it's totally possible my approach is wrong.

**Comment by peterjc** [comment]
Sorry, I miss read the recent post. On the GenBank side, isn't it the _writer_ we want focus on?

i.e. If given a SeqRecord with SeqFeatures with annotations containing ``\n``, what should it output?

**Comment by erik-whiting** [comment]
> Sorry, I miss read the recent post. On the GenBank side, isn't it the _writer_ we want focus on?
> 
> i.e. If given a SeqRecord with SeqFeatures with annotations containing `\n`, what should it output?

Sure, I can address that in my PR too. Originally I found that in the issue description, the test file provided ends up using the GenBank scanner so I thought to put some fixes there too. I can throw them out and just address the writer, I think that would be easier anyway.

**Comment by erik-whiting** [comment]
Howdy everyone, just pinging the subscribers of this issue to remind them I have a PR for it ready to review: https://github.com/biopython/biopython/pull/3911

**Comment by erik-whiting** [comment]
Hello again everyone, just wanted to ping the reviewers once again to let them know that PR #3911 has been updated with the latest suggestions and is ready for a second review. Hope I'm not annoying anyone with this nudge!
