### ISSUE TITLE
cannot import name '_unicodefun' from 'click'

### ISSUE THREAD

**Issue by rob-miller** [biopython/biopython#3893]
I am reporting a problem with Biopython version, Python version, and operating
system as follows:

Python 3.9.12 (main, Mar 26 2022, 15:51:15) 
[Clang 13.1.6 (clang-1316.0.21.2)] on darwin
>>> import sys; print(sys.version)
3.9.12 (main, Mar 26 2022, 15:51:15) 
>>> import platform; print(platform.python_implementation()); print(platform.platform())
CPython
macOS-12.3.1-x86_64-i386-64bit
>>> import Bio; print(Bio.__version__)
1.80.dev0

I'm struggling again with a commit; the pre-commit environment re-initialized and now I have this issue running black:

```
black....................................................................Failed
- hook id: black
- exit code: 1

Traceback (most recent call last):
  File "/Users/rob/.cache/pre-commit/repof1qgx4jh/py_env-python3.9/bin/black", line 8, in <module>
    sys.exit(patched_main())
  File "/Users/rob/.cache/pre-commit/repof1qgx4jh/py_env-python3.9/lib/python3.9/site-packages/black/__init__.py", line 1423, in patched_main
    patch_click()
  File "/Users/rob/.cache/pre-commit/repof1qgx4jh/py_env-python3.9/lib/python3.9/site-packages/black/__init__.py", line 1409, in patch_click
    from click import _unicodefun
ImportError: cannot import name '_unicodefun' from 'click' (/Users/rob/.cache/pre-commit/repof1qgx4jh/py_env-python3.9/lib/python3.9/site-packages/click/__init__.py)

```

I've installed click from PyPI as the error seems to indicate, and have black version 22.3.0.  The same issue has appeared in [data-utils](https://github.com/owid/data-utils-py/issues/10) but the work there does not seem to help me.  I've cleared my ~/.cache/, updated packages, and `pre-commit install`'d repeatedly but to no avail.

Happy if anyone can highlight what I'm missing?

**Comment by rob-miller** [comment]
OK, the relevant error report/discussion is [black 2964](https://github.com/psf/black/issues/2964).

Just upgrading to black 22.3.0 didn't work for me as noted above, this [comment](https://github.com/psf/black/issues/2964#issuecomment-1083591334) had the answer which is to do:

    pre-commit clean
    pre-commit autoupdate
    pre-commit run --all

When I did this however, I got:

    Bio/SwissProt/__init__.py:699:9: B020 Found for loop that reassigns the iterable it is iterating with each iterable value.
    Bio/Affy/CelFile.py:177:9: B020 Found for loop that reassigns the iterable it is iterating with each iterable value.
    Bio/SCOP/__init__.py:333:13: B020 Found for loop that reassigns the iterable it is iterating with each iterable value.
    Bio/SCOP/__init__.py:339:13: B020 Found for loop that reassigns the iterable it is iterating with each iterable value.
    Bio/SCOP/__init__.py:346:13: B020 Found for loop that reassigns the iterable it is iterating with each iterable value.

Nonetheless at this point I was able to do my own commit without triggering the above issues.
