### ISSUE TITLE
please consider support of muscle 5

### ISSUE THREAD

**Issue by emollier** [biopython/biopython#3902]
Good day,

I am forwarding a problem with Biopython version 1.79, initially reported as [Debian Bug#1009118] by Andrius Merkys.  Python version and operating system are as follows:
```
>>> import sys; print(sys.version)
3.10.4 (main, Apr  2 2022, 09:04:19) [GCC 11.2.0]
>>> import platform; print(platform.python_implementation()); print(platform.platform())
CPython
Linux-5.16.0-6-amd64-x86_64-with-glibc2.33
>>> import Bio; print(Bio.__version__)
1.79
```

The upcoming Debian 12 bookworm will be released with [Muscle 5] instead of the legacy [Muscle 3].  However, Muscle 5 is an extensive reimplementation of _muscle_ with rather different options which are not compatible with the wrapper currently available in Biopython 1.79.  As a side note, in its current form, the test suite does not catch the _muscle_ 5 command and just skips the test item in the test suite.

When the test suite is adjusted to capture _muscle_ 5 and run its corresponding test items, errors reported at the end of the suite are:
```
======================================================================
ERROR: test_Muscle_profile_simple (test_Muscle_tool.MuscleApplication)
Simple round-trip through app doing a profile alignment.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/<<PKGBUILDDIR>>/.pybuild/cpython3_3.10/build/Tests/test_Muscle_tool.py", line 133, in test_Muscle_profile_simple
    output, error = cmdline()
  File "/<<PKGBUILDDIR>>/.pybuild/cpython3_3.10/build/Bio/Application/__init__.py", line 574, in __call__
    raise ApplicationError(return_code, str(self), stdout_str, stderr_str)
Bio.Application.ApplicationError: Non-zero return code 1 from 'muscle -out Fasta/temp_align_out3.fa -profile -in1 Fasta/fa01 -in2 Fasta/f001', message 'Invalid command line'

======================================================================
ERROR: test_Muscle_simple (test_Muscle_tool.MuscleApplication)
Simple round-trip through app just infile and outfile.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/<<PKGBUILDDIR>>/.pybuild/cpython3_3.10/build/Tests/test_Muscle_tool.py", line 97, in test_Muscle_simple
    output, error = cmdline()
  File "/<<PKGBUILDDIR>>/.pybuild/cpython3_3.10/build/Bio/Application/__init__.py", line 574, in __call__
    raise ApplicationError(return_code, str(self), stdout_str, stderr_str)
Bio.Application.ApplicationError: Non-zero return code 1 from 'muscle -in Fasta/f002 -out "Fasta/temp align out1.fa"', message 'Invalid command line'

======================================================================
ERROR: test_Muscle_with_options (test_Muscle_tool.MuscleApplication)
Round-trip through app with a switch and valued option.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/<<PKGBUILDDIR>>/.pybuild/cpython3_3.10/build/Tests/test_Muscle_tool.py", line 115, in test_Muscle_with_options
    output, error = cmdline()
  File "/<<PKGBUILDDIR>>/.pybuild/cpython3_3.10/build/Bio/Application/__init__.py", line 574, in __call__
    raise ApplicationError(return_code, str(self), stdout_str, stderr_str)
Bio.Application.ApplicationError: Non-zero return code 1 from 'muscle -in Fasta/f002 -out Fasta/temp_align_out2.fa -objscore sp -noanchors', message 'Invalid command line'

======================================================================
ERROR: test_long (test_Muscle_tool.SimpleAlignTest)
Simple muscle call using long file.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/<<PKGBUILDDIR>>/.pybuild/cpython3_3.10/build/Tests/test_Muscle_tool.py", line 331, in test_long
    align = AlignIO.read(child.stdout, "clustal")
  File "/<<PKGBUILDDIR>>/.pybuild/cpython3_3.10/build/Bio/AlignIO/__init__.py", line 388, in read
    raise ValueError("No records found in handle") from None
ValueError: No records found in handle

======================================================================
ERROR: test_simple_clustal (test_Muscle_tool.SimpleAlignTest)
Simple muscle call using Clustal output with a MUSCLE header.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/<<PKGBUILDDIR>>/.pybuild/cpython3_3.10/build/Tests/test_Muscle_tool.py", line 249, in test_simple_clustal
    align = AlignIO.read(child.stdout, "clustal")
  File "/<<PKGBUILDDIR>>/.pybuild/cpython3_3.10/build/Bio/AlignIO/__init__.py", line 388, in read
    raise ValueError("No records found in handle") from None
ValueError: No records found in handle

======================================================================
ERROR: test_simple_clustal_strict (test_Muscle_tool.SimpleAlignTest)
Simple muscle call using strict Clustal output.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/<<PKGBUILDDIR>>/.pybuild/cpython3_3.10/build/Tests/test_Muscle_tool.py", line 286, in test_simple_clustal_strict
    align = AlignIO.read(child.stdout, "clustal")
  File "/<<PKGBUILDDIR>>/.pybuild/cpython3_3.10/build/Bio/AlignIO/__init__.py", line 388, in read
    raise ValueError("No records found in handle") from None
ValueError: No records found in handle

======================================================================
ERROR: test_simple_msf (test_Muscle_tool.SimpleAlignTest)
Simple muscle call using MSF output.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/<<PKGBUILDDIR>>/.pybuild/cpython3_3.10/build/Tests/test_Muscle_tool.py", line 216, in test_simple_msf
    align = AlignIO.read(child.stdout, "msf")
  File "/<<PKGBUILDDIR>>/.pybuild/cpython3_3.10/build/Bio/AlignIO/__init__.py", line 388, in read
    raise ValueError("No records found in handle") from None
ValueError: No records found in handle

======================================================================
ERROR: test_using_stdin (test_Muscle_tool.SimpleAlignTest)
Simple alignment using stdin.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/<<PKGBUILDDIR>>/.pybuild/cpython3_3.10/build/Tests/test_Muscle_tool.py", line 367, in test_using_stdin
    align = AlignIO.read(child.stdout, "clustal")
  File "/<<PKGBUILDDIR>>/.pybuild/cpython3_3.10/build/Bio/AlignIO/__init__.py", line 388, in read
    raise ValueError("No records found in handle") from None
ValueError: No records found in handle

======================================================================
ERROR: test_with_multiple_output_formats (test_Muscle_tool.SimpleAlignTest)
Simple muscle call with multiple output formats.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/<<PKGBUILDDIR>>/.pybuild/cpython3_3.10/build/Tests/test_Muscle_tool.py", line 410, in test_with_multiple_output_formats
    align = AlignIO.read(child.stdout, "clustal")
  File "/<<PKGBUILDDIR>>/.pybuild/cpython3_3.10/build/Bio/AlignIO/__init__.py", line 388, in read
    raise ValueError("No records found in handle") from None
ValueError: No records found in handle

----------------------------------------------------------------------
```

To reproduce the issue, one has to apply Andrius' patch below and run the test suite.

```patch
--- a/Tests/test_Muscle_tool.py
+++ b/Tests/test_Muscle_tool.py
@@ -49,14 +49,13 @@
         if muscle_exe:
             break
 else:
-    from subprocess import getoutput
+    from subprocess import getstatusoutput
 
-    output = getoutput("muscle -version")
+    exitcode, _ = getstatusoutput("muscle -version")
     # Since "not found" may be in another language, try and be sure this is
     # really the MUSCLE tool's output
-    if "not found" not in output and "not recognized" not in output:
-        if "MUSCLE" in output and "Edgar" in output:
-            muscle_exe = "muscle"
+    if exitcode == 0:
+        muscle_exe = "muscle"
 
 if not muscle_exe:
     raise MissingExternalDependencyError(
```

Please consider this a wishlist item: I was hoping those would be mere adjustments in option names, but having a more detailed reading of _muscle_ documentation, there is no such thing as a 1:1 mapping between old and new command line options, probably following radical changes in the internal algorithms in use in the newer version of the tool.  Thus I would tend to expect big changes in the _muscle_ wrapper, or even a separation between _muscle_ 3 and _muscle_ 5 wrappers; not sure how you would like to implement it yet.

Thanks for your work on Biopython development!

Have a nice day,  :)
Étienne.

[Debian Bug#1009118]: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1009118
[Muscle 5]: https://drive5.com/muscle/
[Muscle 3]: https://drive5.com/muscle/downloads_v3.htm

**Comment by peterjc** [comment]
What does Muscle v5 return at the command line for ``muscle -version``? I'd feel a bit happier checking both the return code (a good idea) and the text.

We've decide to deprecate our simple command line tool wrappers, so that problem will go away (see discussion on #2877 for background).

**Comment by emollier** [comment]
Hi Peter,

_muscle -version_ returns the below in standard output; the name of the author is not part of the output anymore:
```
muscle 5.1.linux64 []
Built Jan 17 2022 14:13:06

```

Thanks also for mentionning the deprecation of wrappers in favor of generic launchers such as _subprocess_.  I can understand wrappers may represent an excessive maintenance burden compared to their added value.  If necessary, I can forward the word about _subproces_ usage to the Debian bug entry.

Have a nice day,  :)
Étienne.

**Comment by merkys** [comment]
Thanks for prompt response @peterjc. Is there a roadmap for wrapper discontinuation? I.e., how soon they are expected to be dropped from Biopython codebase?

**Comment by peterjc** [comment]
See https://biopython.org/wiki/Deprecation_policy

Quoting https://github.com/biopython/biopython/blob/master/DEPRECATED.rst

> **Bio.Application and the command line wrappers using it**
> Declared obsolete in release 1.79. Please use the standard library subprocess module directly instead.

So that means it will be present with a warning in Biopython 1.79 (June 2021), the next release Biopython 1.80. We'd not drop the wrappers until June 2022, so they could be gone in Biopython 1.81. However, we would also need make some more progress updating our documentation...

**Comment by merkys** [comment]
Thanks for the reply @peterjc. Next Debian release is in early/mid 2023, thus if wrappers are gone by then there is no need to work on [Debian bug #1009118](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1009118).
