### ISSUE TITLE
 SearchIO.parse(handle, 'hmmer3-tab'): ID or alternative IDs of Hit 'XX' exists in this QueryResult.

### ISSUE THREAD

**Issue by diegohernansanchez** [biopython/biopython#3906]
Hi,
Im using python 2.7.12 on Ubuntu 16.04, and I just had this problem with  SearchIO.parse when handling a 'hmmer3-tab':

### Script (portion)
with open ("%s%s" %(path_hmmFile,hmmFile),'rU') as handle: 
    for hmmrecord in SearchIO.parse(handle, 'hmmer3-tab'):
        hits = hmmrecord.hits 
        print hits

### Behaviour
~/10_LTRs_Solanum/2_LTR_HARVEST$ /usr/lib/python2.7/dist-packages/Bio/SearchIO/__init__.py:211: BiopythonExperimentalWarning: Bio.SearchIO is an experimental submodule which may undergo significant changes prior to its future official release.
  BiopythonExperimentalWarning)
Traceback (most recent call last):
  File "8tris_92_parse_HMMER_TEST2.py", line 52, in <module>
    for hmmrecord in SearchIO.parse(handle, 'hmmer3-tab'):
  File "/usr/lib/python2.7/dist-packages/Bio/SearchIO/__init__.py", line 316, in parse
    for qresult in generator:
  File "/usr/lib/python2.7/dist-packages/Bio/SearchIO/HmmerIO/hmmer3_tab.py", line 36, in __iter__
    for qresult in self._parse_qresult():
  File "/usr/lib/python2.7/dist-packages/Bio/SearchIO/HmmerIO/hmmer3_tab.py", line 139, in _parse_qresult
    qresult = QueryResult(hit_list, prev_qid)
  File "/usr/lib/python2.7/dist-packages/Bio/SearchIO/_model/query.py", line 216, in __init__
    self.append(hit)
  File "/usr/lib/python2.7/dist-packages/Bio/SearchIO/_model/query.py", line 504, in append
    "this QueryResult." % hit_key)
ValueError: The ID or alternative IDs of Hit 'RVT_2' exists in this QueryResult.

This block of code was working before, but yesterday I did an update on the system and now thats the outcome. Since the hhmscan was run on a .fasta with multiple sequences, I believe it is reasonable that they will be repeated ...
Any suggestion? Thanks
d!!!

**Comment by diegohernansanchez** [comment]
Hi,
I came to realize that it was unrelated to the update: deleting the few duplications did enable the parser to go forward, it seems that before I had been always parsing non-duplicated data.
Sorry for the inconvenience
