### ISSUE TITLE
http.client.IncompleteRead: IncompleteRead(0 bytes read)

### ISSUE THREAD

**Issue by phage-GP** [biopython/biopython#3940]
### Setup

My goal is to obtain abstracts of miRNA related literature for further application.

It seems that errors often occur when there are a large number of queried records.

Of course I understand the access rate limits for this database, and I follow that principle.

I don't know if the problem is that the request for PUBMED is unreasonable (such as too many request entries) or the parsing of the request information.

````python
  handle = Entrez.efetch(db='pubmed',rettype="medline", retmode="text",webenv=webenv,query_key=query_key)

  # handle = Entrez.efetch(db="pubmed", id=pmid_list, rettype="medline", retmode="text")
  
  res = Medline.parse(handle)
  
  abstract_list = []

  for res_ in res:
      if 'AB' in res_: 
          abstract_ = res_['AB']
      else:
          abstract_ = ' '

      abstract_list.append(abstract_)

  df_pmid_abs = pd.DataFrame({'PMID':pmid_list,'Abstract':abstract_list})
````

```
Traceback (most recent call last):
  File "C:\Users\dell\anaconda3\Anaconda\envs\Web\lib\http\client.py", line 556, in _get_chunk_left
    chunk_left = self._read_next_chunk_size()
  File "C:\Users\dell\anaconda3\Anaconda\envs\Web\lib\http\client.py", line 523, in _read_next_chunk_size
    return int(line, 16)
ValueError: invalid literal for int() with base 16: b''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:/Hotgen/KnowladgeDatabase/code/Gene_miR_artical.py", line 49, in <module>
    df = pmids2abs(pmid_list)
  File "d:\Hotgen\KnowladgeDatabase\code\pmid_abstract.py", line 42, in pmids2abs
    for res_ in res:
  File "C:\Users\dell\anaconda3\Anaconda\envs\Web\lib\site-packages\Bio\Medline\__init__.py", line 168, in parse
    for line in handle:
  File "C:\Users\dell\anaconda3\Anaconda\envs\Web\lib\http\client.py", line 633, in read1
    return self._read1_chunked(n)
  File "C:\Users\dell\anaconda3\Anaconda\envs\Web\lib\http\client.py", line 670, in _read1_chunked
    chunk_left = self._get_chunk_left()
  File "C:\Users\dell\anaconda3\Anaconda\envs\Web\lib\http\client.py", line 558, in _get_chunk_left
    raise IncompleteRead(b'')
http.client.IncompleteRead: IncompleteRead(0 bytes read)
```

### Help!
Thanks.

**Comment by peterjc** [comment]
Both the initial ``ValueError`` exception in ``_read_next_chunk_size`` (getting an empty bytes string) and the raised ``http.client.IncompleteRead`` are consistent with a network/server glitch (e.g. high load).

I would expect this to work if retried.

I was going to suggest something like increasing ``Bio.Entrez.max_tries`` from 3 to 5 and/or increasing ``Bio.Entrez.sleep_between_tries`` from 15 to maybe 30 seconds? However, I think the failure is later - the network connection is working but at some point pulling data from it breaks prematurely.

You may have to add a retry in your script for the ``Medline.parse(Entrez.efetch(...))`` instead?
