### ISSUE TITLE
CI issues  @github-actions CI / test_windows (3.9) (pull_request) Failing after 5m — test_windows (3.9) 

### ISSUE THREAD

**Issue by rob-miller** [biopython/biopython#3944]
CI testing is failing on Windows builds for python 3.9, causing 3.7 and 3.8 to be skipped so maybe issue there too.  
The specific error is:

```
Traceback (most recent call last):
  File "D:\a\biopython\biopython\Tests\test_PhyloXML.py", line 574, in test_phylo
    self._rewrite_and_call(
  File "D:\a\biopython\biopython\Tests\test_PhyloXML.py", line 512, in _rewrite_and_call
    getattr(inst, test)()
  File "D:\a\biopython\biopython\Tests\test_PhyloXML.py", line 287, in test_Distribution
    self.assertEqual(dist.desc, desc)
AssertionError: 'ETH Zürich' != 'ETH Z�rich'
- ETH Zürich
?      ^^
+ ETH Z�rich
?      ^
```

As noted in #3898

**Comment by peterjc** [comment]
I suspect this is a change in a dependency or even the underling CI machine image - I would start with narrowing down _when_ this broke, and then look for dependency changes (we typically use the latest version of things) or any major GitHub Actions update around then.

**Comment by MarkusPiotrowski** [comment]
We have it at least since May 30, where you started a new CI run for PR #3934 
The same problem 14 days ago (May 27) when @mdehoon merged #3942, also in #3943
In fact, every commit since May 27 has this failure during committing: https://github.com/biopython/biopython/commits/master

**Comment by MarkusPiotrowski** [comment]
It's strange. In some CI runs, `test_windows (3.10)` passes or fails with the same error as 3.9:
fail: https://github.com/biopython/biopython/actions/runs/2359515702
pass: https://github.com/biopython/biopython/actions/runs/2442081003

So 5 days ago, `test_windows (3.10)` was still running.

One hint, which fits loosely with this results:
- latest Python 3.9 release for Windows (3.9.13) was May, 17
- latest Python 3.10 release for Windows (3.10.5) was June, 6

**Comment by MarkusPiotrowski** [comment]
Yes, another hint, which makes it clearer:
The last working/passing Windows tests used 3.9.12 and 3.10.4. 3.9.13 and 3.10.5 always failed.

**Comment by MarkusPiotrowski** [comment]
Possible reason?

> [gh-91810](https://github.com/python/cpython/issues/91810): [ElementTree](https://docs.python.org/release/3.9.13/library/xml.etree.elementtree.html#xml.etree.ElementTree.ElementTree) method [write()](https://docs.python.org/release/3.9.13/library/xml.etree.elementtree.html#xml.etree.ElementTree.ElementTree.write) and function [tostring()](https://docs.python.org/release/3.9.13/library/xml.etree.elementtree.html#xml.etree.ElementTree.tostring) now use the text file’s encoding (“UTF-8” if not available) instead of locale encoding in XML declaration when encoding="unicode" is specified.

This change was introduced in Python 3.9.13 and 3.10.5. `ElementTree` is at least used somewhere in `PhyloXMLIO`

**Comment by rob-miller** [comment]
Nice sleuthing.

For info the test is specifically testing for Unicode handling, though with a '(?)' so not very confidently:

```
def test_Distribution(self):
... Also checks Point type and safe Unicode handling (?).
...
dist ->  tree = list(PhyloXMLIO.parse(EX_PHYLO))[10]
...
desc ->        "ETH Zürich",
...
self.assertEqual(dist.desc, desc)
```
 
Assuming the assertion error is reported in the same order as the input, `AssertionError: 'ETH Zürich' != 'ETH Z�rich'` suggests the ElementTree value is correct and the local python string is not - something to do with [unsupported unicode characters on Windows](https://stackoverflow.com/questions/35863825/how-to-print-unsupported-unicode-characters-on-windows-cmd-as-e-g-instead-o)?

This is well outside my skillset, reverting out #2442 in this one spot (#3947) did nothing but I guess that's not surprising.

**Comment by MarkusPiotrowski** [comment]
So, my Windows notepad.exe says that the `test_PhyloXML.py` file (within my Git `biopython` folder) is encoded in 'Unicode BigEndian' and Notepad++ says it's 'UCS-2 BE BOM', so something like UTF-16 BE. The test file is reported as UTF-8.
This is also well outside my skillset, but as I'm working on Windows I can try to do some more local testing.

**Comment by MarkusPiotrowski** [comment]
When I run the test on my Windows 10, the `AssertationError` looks different, indicating that the ElementTree value is incorrect. You can also see from the traceback above that there are 2 carets below the `ü` in "Zürich" and only one caret below the 'strange symbol', which means that the `ü` (in this output) is encoded by two 'codes'. (Yes, it's strange that it shows the correct symbol here...)  

When using `encode` on both values, one gets the following result:
`b'ETH Z\xc3\x83\xc2\xbcrich' != b'ETH Z\xc3\xbcrich'`  

`\xc3\cbc` is the correct utf-8 encoding for `ü` while `\xc3\x83\xc2\xbc` seems to be the result of what is called "double encoding": a utf-8 encoded text is wrongly decoded, e.g., as ANSI (cp1251) and then re-encoded as utf-8. 
```python
>>> 'ü'.encode()
b'\xc3\xbc'
>>> b"\xc3\xbc".decode('ansi').encode()
b'\xc3\x83\xc2\xbc'
``` 

I wonder if someone can help to set up a minimal 'ElementTree' example for testing on Windows?

**Comment by fabianegli** [comment]
This might be related: #1320

**Comment by peterjc** [comment]
In the short term, how about we add a hack to skip this test under Windows (so that we can continue to use CI for the rest of Biopython)?

**Comment by MarkusPiotrowski** [comment]
Actually, the test `test_Distribution` itself runs fine, what is failing is the 'round-trip' test where the data files are rewritten by `Bio.PhyloXMLIO` and then all other tests are run with the newly written temporary files.

What happens on Windows: When using `ElementTree.write()` with the parameter `encoding='unicode'` the xml file in question is encoded to CP1252 (a typical Windows encoding). The header line is also changed:
`<?xml version="1.0" encoding="UTF-8"?>` changes to `<?xml version='1.0' encoding='cp1252'?>`
As far as I can tell, `ElementTree` does nothing wrong here. However, something in `Bio.PhyloXML...`  does write the data in utf-8 encoding. So the resulting file has a header saying 'CP1252' while the file is in fact utf-8 encoded. This explains the error. While this seems to be a Windows specific problem, I wonder what happens on computers that use an 'unusual' encoding. I guess the unusual encoding would also end up in the xml header while the file would be utf-8 encoded.

As for `Bio.PhyloXML...` I'd be happy if someone could take over.

Regarding a hack, the simplest hack would be just to out-comment this specific test (`test_Distribution`) in the round-trip testing:
https://github.com/biopython/biopython/blob/2d70f8d9c8f916de0c1436d4e2df4ef7a3f08394/Tests/test_PhyloXML.py#L568-L603

**Comment by mdehoon** [comment]
I can have a look once I get access to a Windows machine in a couple of weeks. Please leave this issue open.

**Comment by MarkusPiotrowski** [comment]
We can still apply the patch? I can re-open the issue afterwards. 
I'm happy to assist with testing on Windows. My problem is that I don't find an obvious place where to start (e.g. byte vs. string conversion, explicit declaration of encodings or similar). Once someone points me to a possible entry point, I can have a look. Round-tripping with pure `ElementTree` works fine for me (on Windows using Python 3.10.5).

**Comment by fabianegli** [comment]
There are two possible places I would start. One is to allow passing along encoding to the `parse` function in `Bio/Phylo/_io.py` (here's an experiment in: https://github.com/biopython/biopython/pull/3948/commits/3b024309ff23effe80448b987a61c3c0ea5ddec2) and then there is this line that might be the culprit:

https://github.com/biopython/biopython/blob/d704d1892df77c77acca5a5fb627690464794b9e/Bio/Phylo/PhyloXMLIO.py#L48-L49

**Comment by peterjc** [comment]
I do have access to a Windows VM, but it seems to be a clean slate each time I use it so its a hassle to reinstall Python, MSCV, etc in order to start debugging and testing. So good to know several of you are in a position to investigate this :)

**Comment by MarkusPiotrowski** [comment]
Found some interesting discussion [here](https://github.com/python/cpython/pull/91903#issuecomment-1144166476) which is probably related to our problem. It describes a behavior for `ElementTree.write()` that I have also seen during testing (but I was not aware that this could be the problem). This change has been fixed [here](https://github.com/python/cpython/pull/93426) and they are currently porting this to the various Python versions.

**Comment by fabianegli** [comment]
maybe skipping the test specifically on platforms that don't have an acceptable locale would be prudent. Or even raise an exception in the code if the architecture-locale combination will lead to invalid files being created.

useful for such an endeavor will be `import locale; locale.getlocale()` which gives a tuple with the language and the encoding locale.

**Comment by MarkusPiotrowski** [comment]
I think I found the problem. It is indeed different if you open the file using a file handle or directly:
```python
import xml.etree.ElementTree as ET

roots = []
print('Opening an xml file containing umlauts with ElementTree\n')

# Case 1: with container
with open ('test_file_wo_namespace.xml', 'r') as infile:
    tree = ET.parse(infile)
    root = tree.getroot()
    roots.append(root)

# Case 2: file handle
file_ = open('test_file_wo_namespace.xml', 'r')
tree = ET.parse(file_)
root = tree.getroot()
roots.append(root)

# Case 3 direct parsing
tree = ET.parse('test_file_wo_namespace.xml')
root = tree.getroot()
roots.append(root)

for root, handle in zip(
    roots, ['with container', 'file handle', 'direct parsing']
):
    print(f'Using {handle}:')
    for clade in root.iter('clade'):
        print(clade.tag, clade[0].tag, clade[0].text)
    print()
```
results in:
```python
Opening an xml file containing umlauts with ElementTree

Using with container:
clade name Ã„
clade name Ã–
clade name Ãœ

Using file handle:
clade name Ã„
clade name Ã–
clade name Ãœ

Using direct parsing:
clade name Ä
clade name Ö
clade name Ü
```
While the 'normal' `test_distribution` test uses direct parsing (and therefore passes), the 'round-trip' procedure in `_rewrite_and_call` uses a with container resulting in the wrong encoding. So we can fix the problem either by using the direct parsing in `rewrite_and_call` or by declaring a encoding for the with container.

I wonder if I should report this as a possible bug to Python? Because it did work before the change in `ElementTree` occured (will still need to test this on an 'older' Python version).

**Comment by peterjc** [comment]
It does "smell" like a subtle regression bug in Python, although it could be cleaning up of some undefined behaviour.

If you're suggesting explicit use of UTF-8 on output, that _sounds_ safe... but I'm wary with unicode and the fact locales and defaults differ widely. At least we have a reproducible test case :)

**Comment by MarkusPiotrowski** [comment]
No sorry, I didn't make this clear enough: I talk about opening the (Phylo)xml file for _reading/parsing_.
If you use `PhyloXMLIO.read(filename`) everything works fine, but if you use a file handle like `file_handle = open(filename, 'r'); PhyloXMLIO.read(file_handle)` it reads the utf-8 encoded file as Windows CP1252. And this is not due to an error in `PhyloXML...` but already happening in `ElementTree`. This is what my example should show, which does not contain any _writing_ step. Interestingly enough, for _writing_ is doesn't matter if you use a file handle or file name (not shown here).

So my suggestion for the test suite is to use `PhyloXMLIO.read(filename)`, since `ElementTree` seems to be capable of converting everything correctly when you do it this way.
Explicitely using `encoding='utf-8'` in a _file handle_ would be risky if the xml file is not utf-8 encoded.

**Comment by mdehoon** [comment]
Can you open the file in binary mode? As in
```python
>>> file_handle = open(filename, 'rb')
>>> PhyloXMLIO.read(file_handle)
```
XML files are binary, after all.

**Comment by peterjc** [comment]
As I recall in other parts of Biopython we try to open XML files in binary mode and let the XML parser itself interpret the declared encoding if any.

**Comment by MarkusPiotrowski** [comment]
@mdehoon Yes, you can open the file in binary mode. I was just very surprised about the different behavior depending on how you open the file for parsing.

But this doesn't help with the test suite (also, my suggestion would not help). For the moment we can only decide if we want to skip the test on Windows for Python 3.7/3.8 or 3.9/10 or wait for the 'bugfix' described here: https://github.com/python/cpython/pull/93426. The problem, as described in this link, is that with the current settings that `PhyloXMLIO` is using, an  xml declaration is added to the output file (which, under Windows, declares CP1252 as encoding, although the file is utf-8 encoded).

(Another alternative would be to open `PhyloXML` to allow for passing more arguments to it. E.g. passing `ElementTree`'s `xml_declaration=False` should help to make the test pass for (current) Python 3.9/3.10.)
