### ISSUE TITLE
PDBParser get_structure fails on 1B2U.pdb

### ISSUE THREAD

**Issue by 011235813** [biopython/biopython#3970]
### Setup

I am reporting a problem with Biopython version, Python version, and operating
system as follows:

```python
import sys; print(sys.version)
import platform; print(platform.python_implementation()); print(platform.platform())
import Bio; print(Bio.__version__)
```

>>> import sys; print(sys.version)
3.8.13 (default, Jun  2 2022, 14:09:02) 
[GCC 6.1.0]
>>> import platform; print(platform.python_implementation()); print(platform.platform())
CPython
Linux-3.10.0-1160.62.1.1chaos.ch6.x86_64-x86_64-with-glibc2.17
>>> import Bio; print(Bio.__version__)
1.79

### Expected behaviour

I expected `PDBParser.get_structure` to return without error when given a valid .pdb file.

### Actual behaviour

It fails on [1B2U.pdb](https://www.rcsb.org/structure/1b2u) with the following error message

```
Traceback (most recent call last):
  File "pdb.py", line 9, in <module>
    structure = parser.get_structure(name, f)
  File "/usr/.../venvs/anti/lib/python3.8/site-packages/Bio/PDB/PDBParser.py", line 100, in get_structure
    self._parse(lines)
  File "/usr/.../venvs/anti/lib/python3.8/site-packages/Bio/PDB/PDBParser.py", line 123, in _parse
    self.trailer = self._parse_coordinates(coords_trailer)
  File "/usr/.../venvs/anti/lib/python3.8/site-packages/Bio/PDB/PDBParser.py", line 299, in _parse_coordinates
    structure_builder.init_atom(
  File "/usr/.../venvs/anti/lib/python3.8/site-packages/Bio/PDB/StructureBuilder.py", line 285, in init_atom
    disordered_atom.disordered_add(self.atom)
  File "/usr/.../venvs/anti/lib/python3.8/site-packages/Bio/PDB/Atom.py", line 534, in disordered_add
    if occupancy > self.last_occupancy:
TypeError: '>' not supported between instances of 'NoneType' and 'int'
```

### Steps to reproduce

```
from Bio.PDB import PDBParser

name = ''
pdb_path = '1B2U.pdb'

with open(pdb_path, 'r') as f:
    parser = PDBParser()
    structure = parser.get_structure(name, f)

print(structure)
```

**Comment by peterjc** [comment]
An official PDB file (good), with what I'm guessing is a mix of missing and present occupancy numbers. That sounds a bit odd...

**Comment by rob-miller** [comment]
Sorry I'm not configured with Python environments so can't check Biopython 1.79, but with my development tree of 1.80 this reads (and rebuilds all 6 chains from internal coordinates) without error:
```
/Volumes/data/pdb/b2/pdb1b2u.ent.gz 1 ('1b2u',):('1b2u',) ['A', 'B', 'C', 'D', 'E', 'F'] -- 999 of 999 residue IDs match; 587 residues 4698 atom coords, 4698 full IDs of 4698 atoms (10 disordered) match : ALL OK 
```

Maybe it would be nice to get to a new release ?  :-) :-) :-) :-)

**Comment by 011235813** [comment]
>  with my development tree of 1.80 this reads (and rebuilds all 6 chains from internal coordinates) without error:

Is the development branch 1.80 available? I wasn't able to find it. I've also tried previous version 1.78-1.76 and all produce the same error.

**Comment by peterjc** [comment]
We mean the (default) master branch which will soon be Release 1.80

**Comment by peterjc** [comment]
We mean the (default) master branch which will soon be Release 1.80

**Comment by JoaoRodrigues** [comment]
Hi @011235813 , I can't reproduce your error on my machine (see below). Could you try running your code with the PDB file as downloaded from RCSB?

```
In [2]: %paste
import sys; print(sys.version)
import platform; print(platform.python_implementation()); print(platform.platform())
import Bio; print(Bio.__version__)

## -- End pasted text --
3.8.13 (default, Mar 28 2022, 06:16:26)
[Clang 12.0.0 ]
CPython
macOS-10.16-x86_64-i386-64bit
1.79

In [4]: from Bio.PDB import PDBParser
   ...:
   ...: name = ''
   ...: pdb_path = '1B2U.pdb'
   ...:
   ...: with open(pdb_path, 'r') as f:
   ...:     parser = PDBParser()
   ...:     structure = parser.get_structure(name, f)
   ...:
/Users/xxx/miniconda3/envs/biopy_38/lib/python3.8/site-packages/Bio/PDB/StructureBuilder.py:89: PDBConstructionWarning: WARNING: Chain A is discontinuous at line 5324.
  warnings.warn(
/Users/xxx/miniconda3/envs/biopy_38/lib/python3.8/site-packages/Bio/PDB/StructureBuilder.py:89: PDBConstructionWarning: WARNING: Chain B is discontinuous at line 5436.
  warnings.warn(
/Users/xxx/miniconda3/envs/biopy_38/lib/python3.8/site-packages/Bio/PDB/StructureBuilder.py:89: PDBConstructionWarning: WARNING: Chain C is discontinuous at line 5544.
  warnings.warn(
/Users/xxx/miniconda3/envs/biopy_38/lib/python3.8/site-packages/Bio/PDB/StructureBuilder.py:89: PDBConstructionWarning: WARNING: Chain D is discontinuous at line 5600.
  warnings.warn(
/Users/xxx/miniconda3/envs/biopy_38/lib/python3.8/site-packages/Bio/PDB/StructureBuilder.py:89: PDBConstructionWarning: WARNING: Chain E is discontinuous at line 5654.
  warnings.warn(
/Users/xxx/miniconda3/envs/biopy_38/lib/python3.8/site-packages/Bio/PDB/StructureBuilder.py:89: PDBConstructionWarning: WARNING: Chain F is discontinuous at line 5700.
  warnings.warn(
```

**Comment by JoaoRodrigues** [comment]
Closed since we cannot reproduce the problem. Feel free to re-open if the problem does persist on your installation.
