### ISSUE TITLE
PairwiseAligner behavior mismatch versus documentation for 1.79

### ISSUE THREAD

**Issue by ressy** [biopython/biopython#3991]
### Setup

I am reporting a problem with Biopython version, Python version, and operating
system as follows:

```python
>>> import sys; print(sys.version)
3.10.5 | packaged by conda-forge | (main, Jun 14 2022, 07:06:46) [GCC 10.3.0]
>>> import platform; print(platform.python_implementation()); print(platform.platform())
CPython
Linux-4.4.0-210-generic-x86_64-with-glibc2.23
>>> import Bio; print(Bio.__version__)
1.79
```

### Expected behaviour

Following along with the [Bio.Align.PairwiseAlignment docs for 1.79](https://biopython.org/docs/1.79/api/Bio.Align.html), I should get this:

```python
>>> from Bio.Align import PairwiseAligner
>>> aligner = PairwiseAligner()
>>> alignments = aligner.align("ACCGGTTT", "ACGGGTT")
>>> alignment = alignments[0]
>>> print(alignment)
ACCGG-TTT
||-||-||-
AC-GGGTT-

>>> alignment[0, :]
'ACCGG-TTT'
```

### Actual behaviour

But slicing the alignment like that gives `NotImplementedError` under version 1.79:

```python
>>> alignment[0, :]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jesse/miniconda3/envs/biopython-debug/lib/python3.10/site-packages/Bio/Align/__init__.py", line 1031, in __getitem__
    raise NotImplementedError
NotImplementedError
```

(It does work as documented on the 1.80 dev version straight from github, so apparently that wasn't yet actually implemented in 1.79?  But if not, is there an equivalent way to slice alignment objects?)

### Steps to reproduce

Run the lines in **Expected Behavior** above with BioPython version 1.79.

**Comment by mdehoon** [comment]
You can use
```python
>>> lines = str(alignment).split("\n")
>>> lines[0]
'ACCGG-TTT'
>>> lines[1]
'||-||-||-'
>>> lines[2]
'AC-GGGTT-'
```
until release 1.80 comes out.

**Comment by ressy** [comment]
Yep, just what I ended up doing.  Thanks!

As far as the documentation goes I realized what's in the [docstring for 1.79](https://github.com/biopython/biopython/blob/biopython-179/Bio/Align/__init__.py#L968) in the code itself actually *is* correct for that version's behavior, it's just that what's rendered on biopython.org for 1.79 doesn't match that docstring for that version.  I think the dev version's documentation ended up under 1.79 on the website.  You updated the docstring for the new behavior in 8b0951a1739c751713889160f3c8f8780f78e79d but I saw that @JoaoRodrigues bumped `__version__` from 1.79 to 1.80.dev0 just after that in 613a4fc08cd6e1806cfc6a5fdd6141753616d966, and then there are there two corresponding updates to the docs repo, first for the new behavior and then for the version bump:

https://github.com/biopython/docs/commit/58592330bdc18a3aaae4ec79953f8f8283ba8b1b
https://github.com/biopython/docs/commit/393e79b1ef9fcc0c1380cac42e7e6759926f50fe

**Comment by mdehoon** [comment]
Fixed in release 1.80.
