### ISSUE TITLE
Bio.PDB.PSEA should use a temporary directory to run the third-party tool

### ISSUE THREAD

**Issue by JoaoRodrigues** [biopython/biopython#4031]
Spun-off from #3999. `psea` should run in a temporary directory to avoid leaving unnecessary output files. For example:

```
def run_psea(...):
    curdir = os.path.abspath(os.curdir)
    with tempfile.TemporaryDirectory() as tmpdir:
        os.chdir(tmpdir)
        .... # run psea
        os.chdir(curdir)  # go back to where we started
```

**Comment by sean-workman** [comment]
```
def run_psea(...):
	...
    last = fname.split("/")[-1]
    base = last.split(".")[0]
    cmd = ["psea", fname]

    curdir = os.getcwd()
    with tempfile.TemporaryDirectory() as tmpdir:
        os.chdir(tmpdir)
        p = subprocess.run(cmd, capture_output=True, universal_newlines=True)
        if verbose:
            print(p.stdout)
        if not p.stderr.strip() and os.path.exists(base + ".sea"):
            os.chdir(curdir)
            return base + ".sea"
        else:
            raise RuntimeError(f"Error running p-sea: {p.stderr}")
```

This is what I currently have. I initially used `os.path.abspath(os.curdir)` and it worked fine, but the tests were failing, so I tried `os.getcwd()` since the traceback shows it's using that anyway. This fails as well.

I see the following stack trace, so it's failing at getting the current working drive inside the test script whether I use `os.path.abspath(os.curdir)` or `os.getcwd()`.

Any thoughts? If I run subprocess.run(["pwd"]) outside of unittest it correctly shows the absolute path of the file, but inside unittest it just shows "."
```
======================================================================
ERROR: test_run_psea_verbose (__main__.TestPDBPSEA)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/sean/python/biopython/Tests/test_PDB_PSEA.py", line 44, in test_run_psea_verbose
    psae_run = run_psea("PDB/1A8O.pdb", verbose=True)
  File "/Users/sean/python/biopython/Bio/PDB/PSEA.py", line 41, in run_psea
    curdir = os.getcwd()
FileNotFoundError: [Errno 2] No such file or directory
```

**Comment by JoaoRodrigues** [comment]
Do you have a branch I can checkout locally and play with?

**Comment by sean-workman** [comment]
Oops, just pushed to my branch [issue_4031](https://github.com/sean-workman/biopython/tree/issue_4031).

**Comment by JoaoRodrigues** [comment]
Ah, my bad, I might have induced you in error with my snippet.

Once you `os.chdir` the original file path (`fname`) doesn't point to anywhere valid (unless it's an absolute path). You need to have `cmd = ["psea", os.path.abspath(fname)]`.

Also, the return value of the function doesn't make sense anymore, because the temporary directory is destroyed once you leave the context manager (`with ...` statement), so the path to the `.psea` file (which is required by the `psea` function) is invalid. My suggestion here is to go a bit deeper and return the contents of the output file (e.g. `file.read()`) and refactor `def psea()` to work on that string, something like this:

```python
  def psea(pname):
      """Parse PSEA output file."""
      psea_data = run_psea(pname)
      start = 0
      ss = ""
          for l in psea_data.splitlines():  # <-- biggest change
              if l[0:6] == ">p-sea":
                  start = 1
                  continue
              if not start:
                  continue
              if l[0] == "\n":
                  break
              ss = ss + l[0:-1]
      return ss

**Comment by sean-workman** [comment]
Gotcha, I should have caught some of this when I was having difficulties with getting the directories to work. I'll get this sorted out this evening probably and make a PR once all tests are passing.

**Comment by kirandharmar867-maker** [comment]
Hello maintainers 👋  
I’d like to work on this issue.  
Could you please confirm if it’s still open and if there are any specific guidelines or tests you’d like me to follow?

Thanks!

**Comment by peterjc** [comment]
Given the timing, you having a go should be fine - good luck @kirandharmar867-maker

**Comment by kirandharmar867-maker** [comment]
Thank You so Much @peterjc ,
for responding To my request.

**Comment by kirandharmar867-maker** [comment]
I’ll start working on this issue and share progress here.
 Thanks @peterjc.
