### ISSUE TITLE
Issues parsing current GAF file using Bio.UniProt.GOA

### ISSUE THREAD

**Issue by ggonzalezp** [biopython/biopython#4155]
### Setup

I am reporting a problem with Biopython version, Python version, and operating
system as follows:

```python
import sys; print(sys.version)
import platform; print(platform.python_implementation()); print(platform.platform())
import Bio; print(Bio.__version__)
```

>>> import sys; print(sys.version)
3.8.12 (default, Oct 12 2021, 13:49:34) 
[GCC 7.5.0]
>>> import platform; print(platform.python_implementation()); print(platform.platform())
CPython
Linux-5.4.0-97-generic-x86_64-with-glibc2.17
>>> import Bio; print(Bio.__version__)
1.79

I am having an issue with Bio.UniProt.GOA when I try to read a current GAF file:

```
Traceback (most recent call last):
  File "<stdin>", line 4, in <module>
  File "/data/ggg17/anaconda3_new/envs/env_38/lib/python3.8/site-packages/Bio/UniProt/GOA.py", line 441, in gafiterator
    raise ValueError(f"Unknown GAF version {inline}\n")
ValueError: Unknown GAF version !gaf-version: 2.2

```

### Steps to reproduce

```
import Bio
import inspect
import os
from ftplib import FTP
#download the reduced GAF file containing gene association data for Arabidopsis Thaliana
data_folder = os.getcwd() + '/data'
arab_uri = '/pub/databases/GO/goa/ARABIDOPSIS/goa_arabidopsis.gaf.gz'
arab_fn = arab_uri.split('/')[-1]

# Check if the file exists already
arab_gaf = os.path.join(data_folder, arab_fn)
if(not os.path.isfile(arab_gaf)):
    # Login to FTP server
    ebi_ftp = FTP('ftp.ebi.ac.uk')
    ebi_ftp.login() # Logs in anonymously
    # Download
    with open(arab_gaf,'wb') as arab_fp:
        ebi_ftp.retrbinary('RETR {}'.format(arab_uri), arab_fp.write)
    # Logout from FTP server
    ebi_ftp.quit()

#Load all annotations into a dictionary
import gzip

# File is a gunzip file, so we need to open it in this way
with gzip.open(arab_gaf, 'rt') as arab_gaf_fp:
    arab_funcs = {}  # Initialise the dictionary of functions
    # Iterate on each function using Bio.UniProt.GOA library.
    for entry in Bio.UniProt.GOA.gafiterator(arab_gaf_fp):
        uniprot_id = entry.pop('DB_Object_ID')
        arab_funcs[uniprot_id] = entry
```

The format I am trying to read is `!gaf-version: 2.2`. I checked the source code here, and it should indeed be able to read it (lines 436-454 here https://github.com/biopython/biopython/blob/master/Bio/UniProt/GOA.py):

```
inline = handle.readline()
    if inline.strip() == "!gaf-version: 2.0":
        # sys.stderr.write("gaf 2.0\n")
        return _gaf20iterator(handle)
    elif inline.strip() == "!gaf-version: 2.1":
        # sys.stderr.write("gaf 2.1\n")
        # Handle GAF 2.1 as GAF 2.0 for now. TODO: fix
        return _gaf20iterator(handle)
    elif inline.strip() == "!gaf-version: 2.2":
        # Handle GAF 2.2 as GAF 2.0 for now. Change from
        # 2.1 to 2.2 is that Qualifier field is no longer optional.
        # As this type of checks has not been done before, we can
        # continue to use the gaf2.0 parser
        return _gaf20iterator(handle)
    elif inline.strip() == "!gaf-version: 1.0":
        # sys.stderr.write("gaf 1.0\n")
        return _gaf10iterator(handle)
    else:
        raise ValueError(f"Unknown GAF version {inline}\n")
```

But when I read the source code from within python (with `print(inspect.getsource(Bio.UniProt.GOA.gafiterator))`, it outputs:

```
>>> print(inspect.getsource(Bio.UniProt.GOA.gafiterator))
def gafiterator(handle):
    """Iterate over a GAF 1.0 or 2.0 file.

    This function should be called to read a
    gene_association.goa_uniprot file. Reads the first record and
    returns a gaf 2.0 or a gaf 1.0 iterator as needed

    Example: open, read, interat and filter results.

    Original data file has been trimed to ~600 rows.

    Original source ftp://ftp.ebi.ac.uk/pub/databases/GO/goa/YEAST/goa_yeast.gaf.gz

    >>> from Bio.UniProt.GOA import gafiterator, record_has
    >>> Evidence = {'Evidence': set(['ND'])}
    >>> Synonym = {'Synonym': set(['YA19A_YEAST', 'YAL019W-A'])}
    >>> Taxon_ID = {'Taxon_ID': set(['taxon:559292'])}
    >>> with open('UniProt/goa_yeast.gaf', 'r') as handle:
    ...     for rec in gafiterator(handle):
    ...         if record_has(rec, Taxon_ID) and record_has(rec, Evidence) and record_has(rec, Synonym):
    ...             for key in ('DB_Object_Name', 'Evidence', 'Synonym', 'Taxon_ID'):
    ...                 print(rec[key])
    ...
    Putative uncharacterized protein YAL019W-A
    ND
    ['YA19A_YEAST', 'YAL019W-A']
    ['taxon:559292']
    Putative uncharacterized protein YAL019W-A
    ND
    ['YA19A_YEAST', 'YAL019W-A']
    ['taxon:559292']
    Putative uncharacterized protein YAL019W-A
    ND
    ['YA19A_YEAST', 'YAL019W-A']
    ['taxon:559292']

    """
    inline = handle.readline()
    if inline.strip() == "!gaf-version: 2.0":
        # sys.stderr.write("gaf 2.0\n")
        return _gaf20iterator(handle)
    elif inline.strip() == "!gaf-version: 2.1":
        # sys.stderr.write("gaf 2.1\n")
        # Handle GAF 2.1 as GAF 2.0 for now. TODO: fix
        return _gaf20iterator(handle)
    elif inline.strip() == "!gaf-version: 1.0":
        # sys.stderr.write("gaf 1.0\n")
        return _gaf10iterator(handle)
    else:
        raise ValueError(f"Unknown GAF version {inline}\n")
```

The `elif` option `elif inline.strip() == "!gaf-version: 2.2":` is missing when I inspect the code from within python. This is what is causing the issue. Why are these lines of code missing even when I have the latest version of biopython?

**Comment by peterjc** [comment]
You probably need the changes from #3650 which will be in the next release, Biopython 1.80

Can you try installing from source?

**Comment by ggonzalezp** [comment]
@peterjc worked, thank you!
