### ISSUE TITLE
Entrez.read of PMC record throws: Failed to access mathml2-qname-1.mod

### ISSUE THREAD

**Issue by yarikoptic** [biopython/biopython#4168]
### Setup

I am reporting a problem with Biopython version, Python version, and operating
system as follows:

```python
(Pdb) import sys; print(sys.version)
3.10.7 (main, Sep  8 2022, 14:34:29) [GCC 12.2.0]
(Pdb) import platform; print(platform.python_implementation()); print(platform.platform())
CPython
Linux-5.19.0-2-amd64-x86_64-with-glibc2.35
(Pdb) import Bio; print(Bio.__version__)
1.79
```

### Expected behaviour

return usable record from parsed xml

### Actual behaviour

```
*(Pdb) pmc_records_xml = Entrez.efetch(db="pmc", id='8494634').read()
*(Pdb) pmc_records = Entrez.read(BytesIO(pmc_records_xml))
*** RuntimeError: Failed to access mathml2-qname-1.mod at https://dtd.nlm.nih.gov/ncbi/pmc/articleset/../2.0/mathml2-qname-1.mod
```

### Steps to reproduce

above

**Comment by mdehoon** [comment]
```python
>>> from Bio import Entrez
>>> handle = Entrez.efetch(db="pmc", id='8494634')
>>> records = Entrez.read(handle)
```

**Comment by yarikoptic** [comment]
Thank you for the super quick answer @mdehoon -- much appreciated.

<details>
<summary>I get /usr/lib/python3/dist-packages/Bio/Entrez/DTDs </summary> 

```shell
❯ ipython3
cpasPython 3.10.7 (main, Sep  8 2022, 14:34:29) [GCC 12.2.0]
Type 'copyright', 'credits' or 'license' for more information
IPython 8.4.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: cpaste
Pasting code; enter '--' alone on the line to stop or use Ctrl-D.
:>>> from Bio.Entrez import Parser
>>> Parser.DataHandler.global_dtd_dir:
:--
ERROR! Session/line number was not unique in database. History logging moved to new session 4560
Out[1]: '/usr/lib/python3/dist-packages/Bio/Entrez/DTDs'

```
</details>

There is no such file there and it is not provided by the debian package of python3-biopython 1.79+dfsg-3+b1 

```
❯ ls -l /usr/lib/python3/dist-packages/Bio/Entrez/DTDs/mathml2-qname-1.mod
ls: cannot access '/usr/lib/python3/dist-packages/Bio/Entrez/DTDs/mathml2-qname-1.mod': No such file or directory
❯ dpkg -L python3-biopython | grep mathml2-qname-1.mod
❯ apt-cache policy python3-biopython
python3-biopython:
  Installed: 1.79+dfsg-3+b1
  Candidate: 1.79+dfsg-3+b1
  Version table:
 *** 1.79+dfsg-3+b1 900
        900 http://deb.debian.org/debian bookworm/main amd64 Packages
        600 http://http.debian.net/debian sid/main amd64 Packages
        100 /var/lib/dpkg/status
     1.78+dfsg-4 100
        100 http://deb.debian.org/debian bullseye/main amd64 Packages
```

I have mentioned DFSG (debian free software quidelines) in the version, which means some materials were removed since "not free"

<details>
<summary>indeed this file marked to be removed and was excluded from distribution since 2014</summary> 

```shell
❯ debcheckout python3-biopython
declared git repository at https://salsa.debian.org/med-team/python-biopython.git
git clone https://salsa.debian.org/med-team/python-biopython.git python3-biopython ...
Cloning into 'python3-biopython'...
remote: Enumerating objects: 9421, done.
remote: Counting objects: 100% (789/789), done.
remote: Compressing objects: 100% (522/522), done.
remote: Total 9421 (delta 288), reused 471 (delta 263), pack-reused 8632
Receiving objects: 100% (9421/9421), 23.08 MiB | 16.77 MiB/s, done.
Resolving deltas: 100% (5678/5678), done.
❯ cd python3-biopython
Bio/     CONTRIB.rst       DEPRECATED.rst  LICENSE@     MANIFEST.in  README.rst  Tests/   setup.py
BioSQL/  CONTRIBUTING.rst  Doc/            LICENSE.rst  NEWS.rst     Scripts/    debian/
❯ less debian/copyright
❯ grep Exc debian/copyright
Files-Excluded: Bio/Entrez/DTDs/mathml2-qname-1.mod .gitattributes
❯ git log -SBio/Entrez/DTDs/mathml2-qname-1.mod debian/copyright
commit 0a0022acbdf00290011aedf88053edafa02d65ff (tag: debian/1.66+dfsg-1)
Author: Andreas Tille <tille@debian.org>
Date:   Wed Mar 9 12:50:43 2016 +0100

    Re-add debian/ dir

commit 80d5869d6dd4b4bd538e35eac3e183f65d23334a (tag: upstream/1.66+dfsg)
Author: Andreas Tille <tille@debian.org>
Date:   Wed Mar 9 12:45:55 2016 +0100

    Imported Upstream version 1.66+dfsg

commit a18a24138f4c066fc29ac3583984f7d861eff6bf
Author: Andreas Tille <tille@debian.org>
Date:   Wed Apr 30 21:50:32 2014 +0000

    Remove Bio\Entrez\DTDs\mathml2-qname-1.mod

```
</details>

debian changelog provides more info

```
python-biopython (1.63+dfsg-1) unstable; urgency=medium

  * Remove Bio\Entrez\DTDs\mathml2-qname-1.mod
    Closes: #746484

 -- Andreas Tille <tille@debian.org>  Wed, 30 Apr 2014 14:47:53 +0200
```
so the reason was https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=746484 which stated:

> according to: http://www.w3.org/Consortium/Legal/2002/copyright-documents-20021231
> the file biopython-1.63\Bio\Entrez\DTDs\mathml2-qname-1.mod may not be modified and such this file is not distributable in main.

I guess it is "ok" if the case is rare, otherwise I might suggest us gaining some python3-biopython-nonfree package in non-free suite of Debian or re-check with w3c on terms for this file and either they could be tuned up to allow for inclusion in debian. 

if I copy that file from this repository and run your slightly tuned code to request xml

```
from Bio import Entrez
handle = Entrez.efetch(db="pmc", id='8494634', format="xml")
records = Entrez.read(handle)
```

I do get a new error now:
```
❯ python3 test-entrez.py
/usr/lib/python3/dist-packages/Bio/Entrez/__init__.py:658: UserWarning: 
Email address is not specified.

To make use of NCBI's E-utilities, NCBI requires you to specify your
email address with each request.  As an example, if your email address
is A.N.Other@example.com, you can specify it as follows:
   from Bio import Entrez
   Entrez.email = 'A.N.Other@example.com'
In case of excessive usage of the E-utilities, NCBI will attempt to contact
a user at the email address provided before blocking access to the
E-utilities.
  warnings.warn(
Traceback (most recent call last):
  File "/home/yoh/doc/grants/nsf-coi/test-entrez.py", line 3, in <module>
    records = Entrez.read(handle)
  File "/usr/lib/python3/dist-packages/Bio/Entrez/__init__.py", line 508, in read
    record = handler.read(handle)
  File "/usr/lib/python3/dist-packages/Bio/Entrez/Parser.py", line 345, in read
    raise NotXMLError(e) from None
Bio.Entrez.Parser.NotXMLError: Failed to parse the XML data (syntax error: line 1850, column 57). Please make sure that the input data are in XML format.
```
although when I print that `.read()` data -- looks like some xml to me. Any clues?

**Comment by peterjc** [comment]
Debian (and other packager with strict rules) would not want to bundle the NCBI's DTD files. Maybe we shouldn't either.

However, the expected behaviour is Biopython would download missing ``*.mod.dtd`` or ``.dtd`` files on the fly (e.g. new ones the NCBI started using since the Biopython release).

In this case, can we even work out what the correct URL is for ``mathml2-qname-1.mod``?

**Comment by mdehoon** [comment]
> Bio.Entrez.Parser.NotXMLError: Failed to parse the XML data (syntax error: line 1850, column 57). Please make sure that the input data are in XML format.

The error message tells you in what line and column the data do not look as XML. Can you check there if there is something weird in the data?

**Comment by mdehoon** [comment]
> In this case, can we even work out what the correct URL is for `mathml2-qname-1.mod`?

When I try to parse the results, then `mathml2-qname-1.mod` is never needed.

> However, the expected behaviour is Biopython would download missing *.mod.dtd or .dtd files on the fly (e.g. new ones the NCBI started using since the Biopython release).

@yarikoptic  Can you check if you have files in the local directory given by `Parser.DataHandler.local_dtd_dir` ?
If so, remove all those files, and try again. My guess is that there is an out of date or otherwise corrupted file among them.

**Comment by yarikoptic** [comment]
sorry for the delay -- moved on from preparing my NSF COI and forgot about this issue ;)

```
❯ cat test-entrez.py
from Bio.Entrez import Parser
print(f'{Parser.DataHandler.local_dtd_dir!r}')

❯ python3 test-entrez.py
''
```
so it is just an empty string.  Should it have been `'.'` or alike?

**Comment by mdehoon** [comment]
If it is an empty string, then it means you have no local DTD files that could be causing a problem. Then something may be wrong in your global DTD files, i.e. in ` /usr/lib/python3/dist-packages/Bio/Entrez/DTDs`.

The local DTD directory takes precedence over the global one. If you set your local DTD directory to some path you have access to, and copy all DTD files from Biopython release 1.80 there (***not*** from your global directory), then your example should run.

**Comment by yarikoptic** [comment]
well, I worked around the issue by simply doing evil and copying needed file into system wide location. But I am with @peterjc [above](https://github.com/biopython/biopython/issues/4168#issuecomment-1320285804) that underlying issue is more within:

> However, the expected behaviour is Biopython would download missing *.mod.dtd or .dtd files on the fly (e.g. new ones the NCBI started using since the Biopython release).
> In this case, can we even work out what the correct URL is for mathml2-qname-1.mod?

**Comment by mdehoon** [comment]
> well, I worked around the issue by simply doing evil and copying needed file into system wide location. But I am with @peterjc [above](https://github.com/biopython/biopython/issues/4168#issuecomment-1320285804) that underlying issue is more within:
> 
> > However, the expected behaviour is Biopython would download missing *.mod.dtd or .dtd files on the fly (e.g. new ones the NCBI started using since the Biopython release).
> > In this case, can we even work out what the correct URL is for mathml2-qname-1.mod?

The question is why you need this file at all. I can delete that file and still run your example, and when I do, the file does not get downloaded either.
