### ISSUE TITLE
AttributeError when writing alignments

### ISSUE THREAD

**Issue by exs-bbutt** [biopython/biopython#4181]
### Setup

I am reporting a problem with Biopython version, Python version, and operating system as follows:
```
1.80
3.7.12 | packaged by conda-forge | (default, Oct 26 2021, 05:59:23) [Clang 11.1.0]
CPython Darwin-21.6.0-x86_64-i386-64bit
```

### Expected behaviour
Alignment instance generated by PairwiseAligner is written to file

### Actual behaviour
`AttributeError` is thrown:
```
Traceback (most recent call last):
  File "/Users/bbutt/tmp/test.py", line 7, in <module>
    Align.write(alns, "test.fasta", "fasta")
  File "/Users/bbutt/mambaforge/envs/tmp/lib/python3.7/site-packages/Bio/Align/__init__.py", line 3283, in write
    return writer(target, *args, **kwargs).write_file(alignments)
  File "/Users/bbutt/mambaforge/envs/tmp/lib/python3.7/site-packages/Bio/Align/interfaces.py", line 199, in write_file
    count = self.write_alignments(alignments)
  File "/Users/bbutt/mambaforge/envs/tmp/lib/python3.7/site-packages/Bio/Align/interfaces.py", line 187, in write_alignments
    line = self.format_alignment(alignment)
  File "/Users/bbutt/mambaforge/envs/tmp/lib/python3.7/site-packages/Bio/Align/fasta.py", line 37, in format_alignment
    if sequence.description:
AttributeError: 'str' object has no attribute 'description'
```

### Steps to reproduce
This error is thrown when writing alignments generated by `PairwiseAligner`:
```python
from Bio import Align

seq1 = "AAA"
seq2 = "AAA"
aligner = Align.PairwiseAligner()
alns = aligner.align(seq1, seq2)
Align.write(alns, "test.fasta", "fasta")
```
Notably, reading from file then re-writing works fine:
```python
from Bio import Align

aln = Align.read("in.fasta", "fasta")
count = Align.write(aln, "out.fasta", "fasta")
print(f"Wrote {count} alignment(s) to file")
```
Where `in.fasta` is:
```
>seq1
AAA
>seq2
AAA
```

**Comment by mdehoon** [comment]
Currently, the pairwise aligner accepts plain strings and `Seq` objects as input, where as `Align.write` expects `SeqRecord` objects (and `Align.read` creates `SeqRecord` objects). The pairwise aligner should be modified to accept `SeqRecord` objects also, and `Align.write` should also accept plain strings and `Seq` objects. For now, you can wrap the sequences in the alignments in `SeqRecord` objects, as in
```python
from Bio import Align
from Bio.Seq import Seq
from Bio.SeqRecord import SeqRecord

seq1 = Seq("AAA")
seq2 = Seq("AAA")
aligner = Align.PairwiseAligner()
alns = aligner.align(seq1, seq2)

for aln in alns:
    aln.sequences[0] = SeqRecord(aln.sequences[0])
    aln.sequences[1] = SeqRecord(aln.sequences[1])

count = Align.write(aln, "out.fasta", "fasta")
print(f"Wrote {count} alignment(s) to file")
```

**Comment by exs-bbutt** [comment]
Thanks for the working example!
