### ISSUE TITLE
Unable to parse a psl file produced by BLAT

### ISSUE THREAD

**Issue by mzdravkov** [biopython/biopython#4196]
Hello,

I'm working on a program that runs BLAT between two files with protein sequences and parses the output psl file using Bio.SearchIO.BlatIO. I stumbled an issue where parsing the psl produces an exception because of assertion errors. Here's my setup and how to reproduce the bug.

### Setup

I am reporting a problem with Biopython version, Python version, and operating
system as follows:

```python
>>> import sys; print(sys.version)
3.8.10 (default, Jun 22 2022, 20:18:18)
[GCC 9.4.0]
>>> import platform; print(platform.python_implementation()); print(platform.platform())
CPython
Linux-5.10.16.3-microsoft-standard-WSL2-x86_64-with-glibc2.29
>>> import Bio; print(Bio.__version__)
1.80
```

### Expected behaviour

Should be able to parse the psl file.

### Actual behaviour

The error message I get is:

```bash
Traceback (most recent call last):
  File "test.py", line 5, in <module>
    for hit in parser:
  File "/home/user/project/env/lib/python3.8/site-packages/Bio/SearchIO/BlatIO.py", line 428, in __iter__
    for qresult in self._parse_qresult():
  File "/home/user/project/env/lib/python3.8/site-packages/Bio/SearchIO/BlatIO.py", line 526, in _parse_qresult
    hsp = _create_hsp(prev_hid, prev_qid, prev)
  File "/home/user/project/env/lib/python3.8/site-packages/Bio/SearchIO/BlatIO.py", line 377, in _create_hsp
    assert hsp.query_end == psl["qend"]
AssertionError
```

### Steps to reproduce

I've narrowed down the hit that causes the issue and more specifically the exact line from the psl that seems to be responsible for the error.
Here's an example file that should cause the parsing to fail: [unparsable.psl](https://gist.github.com/mzdravkov/fbbc905419243ec9937896aeae547b94).
The line that causes the error is line 17 (the one indicated as match 829). If you remove this line, the parsing can complete successfully.

Here's a short snippet that reproduces the bug:

```python
from Bio.SearchIO.BlatIO import BlatPslParser

with open('unparsable.psl') as handle:
    parser = BlatPslParser(handle)
    for hit in parser:
        print(hit)
```

**Comment by peterjc** [comment]
I'll leave it to @bow to decide, but can we use your example as a test case to include with Biopython?

**Comment by mzdravkov** [comment]
Of course! I would be happy to help!

I was just playing a bit more with this. The `_is_protein` issue is weird, but doesn't seem related (it never detects that I work with proteins, but this is not a problem for all other lines in the file).

I think that maybe the problem is that in the HPS model [here](https://github.com/biopython/biopython/blob/master/Bio/SearchIO/_model/hsp.py#L467) instead of `max`, it should be just getting the last element. It currently makes the assumption that the last block would have the highest starting position, but this doesn't seem to be the case. Anyway, I'm really new to this and this is the first time I use a psl file, so it is also very likely that I'm wrong :)

**Comment by mdehoon** [comment]
@mzdravkov  Can you try with the new parser in `Bio.Align`? It is included in Biopython release 1.80.

```python
from Bio import Align

alignments = Align.parse('unparsable.psl', "psl")
for alignment in alignments:
    ...
```

**Comment by mzdravkov** [comment]
@mdehoon When using the `Bio.Align` as you suggested, I now get another error on the very first line of the same psl file:

```bash
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/project/env/lib/python3.8/site-packages/Bio/Align/interfaces.py", line 69, in __next__
    alignment = self._read_next_alignment(stream)
  File "/home/user/project/env/lib/python3.8/site-packages/Bio/Align/psl.py", line 425, in _read_next_alignment
    raise ValueError(
ValueError: Inconsistent tNumInsert found (23, expected 25)
```

**Comment by bow** [comment]
Hi @mzdravkov, @peterjc, @mdehoon 

Thanks for reporting the issue and sending the example file as well :+1:.

On the surface, it does seem  to be an off-by-one error. It is, however, caused by something else entirely. That is, an internal assumption I had (but was not 100% sure of) was broken.  @mzdravkov touched on this above: that the last block would have the highest starting position.

In particular, these columns (re-formatted into lines for readability):
```
blockSizes: 33,133,22,61,41,100,19,32,68,71,28,34,76,30,103,79,90,31,
qStarts: 188,221,354,314,378,419,519,538,570,652,723,751,785,861,891,994,951,1041,
tStarts: 188,231,374,463,524,575,680,704,746,814,900,952,991,1072,1131,1244,1349,1478,
```

The problematic fragment is third from last, that is the fragment with `blockSize=79` and `qStart=994`. More specifically:

* This fragment has an end coordinate of 1073 (994 + 79). This is where the assertion error came from.
* If you look at the `qStart` value of the fragment next to it, it's actually lower (goes to 951 from 994).

In this line alone, there are actually two fragments whose `qStart` value is higher than its neighbor.
```
>>> qstarts = [188,221,354,314,378,419,519,538,570,652,723,751,785,861,891,994,951,1041]
>>> list(filter(None, [idx if qstarts[idx] > qstarts[idx+1] else None for idx in range(len(qstarts)-1)]))
[2, 15]
```

Adding their respective block sizes, we also see that these fragments do overlap.
```
>>> qstarts = [188,221,354,314,378,419,519,538,570,652,723,751,785,861,891,994,951,1041]
>>> block_sizes = [33,133,22,61,41,100,19,32,68,71,28,34,76,30,103,79,90,31]
>>> def show(frag_idx):
...     print(f"Fragment start and end: {qstarts[frag_idx], qstarts[frag_idx] + block_sizes[frag_idx]}")
...     print(f"Next fragment start and end: {qstarts[frag_idx+1], qstarts[frag_idx+1] + block_sizes[frag_idx+1]}")
>>> show(2)
Fragment start and end: (354, 376)
Next fragment start and end: (314, 375)
>>> show(15)
Fragment start and end: (994, 1073)
Next fragment start and end: (951, 1041)
```

Now is where I'm not sure what the right behavior is.

Here we see that we have a fragment with a calculated end coordinate of 1073. This fragment is not the last in the HSP. However, looking at the `Q end` column, we see that it reports a value of 1072. My guess is that this is simply taking the last fragment start coordinate and adding the block size to it (1041 + 31):

```
>>> qstarts[-1] + block_sizes[-1]
1072
```

What is the right behavior? Strictly speaking, the query end coordinate is demonstrably 1073 and not 1072. However, this is just a parser after all (i.e. it did not perform the actual calculations).

Should we turn the `assert`s into warnings? Or remove them altogether?

**Comment by mdehoon** [comment]
@mzdravkov 

> @mdehoon When using the Bio.Align as you suggested, I now get another error on the very first line of the same psl file:

That is very strange; it works for me with Biopython release 1.80:
```python
>>> import Bio
>>> Bio.__version__
'1.80'
>>> from Bio import Align
>>> alignments = Align.parse('unparsable.psl', "psl")
>>> for alignment in alignments:
...     print(alignment.sequences[0].id, alignment.sequences[1].id)
... 
XP_035914594.1 XP_049281413.1
XP_035914594.1 XP_049281413.1
XP_035914594.1 XP_049281413.1
XP_035914594.1 XP_049281413.1
XP_035914594.1 XP_049281413.1
XP_035914594.1 XP_049281413.1
XP_035914594.1 XP_049281413.1
XP_035914594.1 XP_049281413.1
XP_035914594.1 XP_049281413.1
XP_035914594.1 XP_049281413.1
XP_035914594.1 XP_049281413.1
XP_035914594.1 XP_049281413.1
XP_035914594.1 XP_049281413.1
XP_035914594.1 XP_049281413.1
XP_035914594.1 XP_049281413.1
XP_035914594.1 XP_049281413.1
XP_035914595.1 XP_049281413.1
XP_035914595.1 XP_049281413.1
XP_035914595.1 XP_049281413.1
XP_035914595.1 XP_049281413.1
XP_035914595.1 XP_049281413.1
XP_035914595.1 XP_049281413.1
XP_035914595.1 XP_049281413.1
XP_035914595.1 XP_049281413.1
XP_035914595.1 XP_049281413.1
XP_035914595.1 XP_049281413.1
XP_035914595.1 XP_049281413.1
XP_035914595.1 XP_049281413.1
XP_035914595.1 XP_049281413.1
XP_035914595.1 XP_049281413.1
XP_035914595.1 XP_049281413.1
XP_035914595.1 XP_049281413.1
XP_035914596.1 XP_049281413.1
XP_035914596.1 XP_049281413.1
XP_035914596.1 XP_049281413.1
XP_035914596.1 XP_049281413.1
XP_035914596.1 XP_049281413.1
XP_035914596.1 XP_049281413.1
XP_035914596.1 XP_049281413.1
XP_035914596.1 XP_049281413.1
XP_035914596.1 XP_049281413.1
XP_035914596.1 XP_049281413.1
XP_035914596.1 XP_049281413.1
XP_035914596.1 XP_049281413.1
XP_035914596.1 XP_049281413.1
XP_035914596.1 XP_049281413.1
XP_035914596.1 XP_049281413.1
XP_035914596.1 XP_049281413.1
>>> 
```
```

**Comment by mdehoon** [comment]
@mzdravkov 
When you print the alignment, it finds that it cannot show the sequence alignment because PSL files do not contain the sequence contents. If you do want to see the sequence alignment, you could supply a fake sequence:
```python
>>> from Bio.Seq import Seq
>>> from Bio import Align
>>> alignments = Align.parse("unparsable.psl", "psl")
>>> alignment = next(alignments)
>>> len(alignment.sequences[0])
1593
>>> alignment.sequences[0].seq = Seq("?" * 1593)
>>> len(alignment.sequences[1])
1152
>>> alignment.sequences[1].seq = Seq("?" * 1152)
>>> print(alignment)
XP_035914        29 ????????????????????????????????????????????????????------??
                  0 |||||||||||||||||||||||||||||||||||||||||||||||-----------||
XP_049281        31 ???????????????????????????????????????????????-----????????

XP_035914        83 ????????????????????????????????????????????????????????????
                 60 ||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||
XP_049281        86 ????????????????????????????????????????????????????????????

XP_035914       143 ?????????????????????????????????--?????????????????????????
                120 |||||||||||||||||||||||||||||||||--|||||||||||||||||||||----
XP_049281       146 ????????????????????????????????????????????????????????----

XP_035914       201 ????????????????????????????????????????????????????????????
                180 ------------------------------||||||||||||||||||||||||||||||
XP_049281       202 ------------------------------??????????????????????????????

XP_035914       261 ????????????????????????????????????????????????????????????
                240 ||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||
XP_049281       232 ????????????????????????????????????????????????????????????

XP_035914       321 ????????????????????????????????????????????????????????????
                300 |||||-----------------------------||||||||||||||||||||||||||
XP_049281       292 ?????-----------------------------??????????????????????????

XP_035914       381 ????????????????????????????????????????????????????????????
                360 ||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||
XP_049281       323 ????????????????????????????????????????????????????????????

XP_035914       441 ????????????????????????????????????????????????????????????
                420 ||||||||||||||||||||||||||----------------------------------
XP_049281       383 ??????????????????????????----------------------------------

XP_035914       501 ?????????????????????????????????????????????????--------???
                480 --------------|||-----|||||||||||||||||||||||||||--------|||
XP_049281       409 --------------???-----??????????????????????????????????????

XP_035914       553 ????????????????????????????????????????????????????????????
                540 |||||||||||||||||||||||||||||||||||||||||-------------------
XP_049281       450 ?????????????????????????????????????????-------------------

XP_035914       613 ????????????????????????????????????????????????????????????
                600 -----------------------------------------------------|||||||
XP_049281       491 -----------------------------------------------------???????

XP_035914       673 ????????????????????????????????????????????????????????????
                660 ||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||
XP_049281       498 ????????????????????????????????????????????????????????????

XP_035914       733 ????????????????????????????????????????????????????????????
                720 |||||||||----------|||||||||||||||||||||||||||||||||||-----|
XP_049281       558 ?????????----------???????????????????????????????????-----?

XP_035914       793 ????????????????????????????????????????????????????????????
                780 ||||||||||||||||||||||||||||||-----|||||||||||||||||||||||||
XP_049281       603 ??????????????????????????????-----?????????????????????????

XP_035914       853 ????????????????????????????????????????????????????????????
                840 ||||||||||||||||||||-----|||||||||||||||||||||||||||||||||||
XP_049281       658 ????????????????????-----???????????????????????????????????

XP_035914       913 ????????????????????????????????????????????????????????????
                900 ||||||----------||||||||||||||||||||||||-----|||||||||||||||
XP_049281       713 ??????----------????????????????????????-----???????????????

XP_035914       973 ????????????????????????????????????????????????????????????
                960 |||||||||||||||||||||||||||-----||||||||||||||||||||||||||||
XP_049281       758 ???????????????????????????-----????????????????????????????

XP_035914      1033 ????????????????????????????????????????????????????????????
               1020 ||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||
XP_049281       813 ????????????????????????????????????????????????????????????

XP_035914      1093 ????????????????????????????????????????????????????????????
               1080 |||||||||||||||||-------------------------------------------
XP_049281       873 ?????????????????-------------------------------------------

XP_035914      1153 ????????????????????????????????????????????????????????????
               1140 ------------------------------------------------------------
XP_049281       890 ------------------------------------------------------------

XP_035914      1213 ????????????????????????????????????????????????????????????
               1200 -------------------------------|||||||||||||||||||||||||||||
XP_049281       890 -------------------------------?????????????????????????????

XP_035914      1273 ????????????????????????????????????????????????????????????
               1260 ||||||||||||||||||||||||||||----------||||||||||||||||||||||
XP_049281       919 ????????????????????????????----------??????????????????????

XP_035914      1333 ????????????????????????????????????????????????????????????
               1320 ||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||
XP_049281       969 ????????????????????????????????????????????????????????????

XP_035914      1393 ????????????????????????????????????????????????????????????
               1380 ||||||||||||||-----|||||||||||||||||||||||||||||||||--------
XP_049281      1029 ??????????????-----?????????????????????????????????--------

XP_035914      1453 ????????????????????????????????????????????????????????????
               1440 --||||||||||||||||||||||||||||||||||||||||||||||||||||||||||
XP_049281      1076 --??????????????????????????????????????????????????????????

XP_035914      1513 ????????????????????????????????????????????????????????????
               1500 |||||||||||||----------||||||||||||||||||||||||-----||||||||
XP_049281      1134 ?????????????----------????????????????????????-----????????

XP_035914      1573 ????????????????????????????????????????????????????????????
               1560 ||||||||||||||||||||||||||||||||||||||||--------||||||||||||
XP_049281      1179 ????????????????????????????????????????--------????????????

XP_035914      1633 ????????????-???????????????????????????????????????????????
               1620 ||||||||||---|||||||||||||||||||||||||||||||||||||||||||||||
XP_049281      1231 ??????????--????????????????????????????????????????????????

XP_035914      1692 ??????? 1593
               1680 ||||||| 1687
XP_049281      1289 ??????? 1152

```
Perhaps by default we should show a fake sequence in the printed alignment if the sequence contents is not available.

**Comment by peterjc** [comment]
That seems reasonable to me. It would be  more like how the old ``UnknownSeq`` worked, but there are drawbacks to doing that all the time via ``__str__`` of course. You're instead suggesting only filling in the missing characters on demand when printing the alignment?

**Comment by mdehoon** [comment]
@peterjc 

> You're instead suggesting only filling in the missing characters on demand when printing the alignment?

Yes, only when printing the alignment.
