### ISSUE TITLE
Add support for SeqRecord objects in Bio.Align.PairwiseAligner.align

### ISSUE THREAD

**Issue by jrom99** [biopython/biopython#4208]
### Setup

I am reporting a problem with Biopython version, Python version, and operating
system as follows:

```python
>>> import sys; print(sys.version)
3.11.1 (main, Dec  7 2022, 00:00:00) [GCC 12.2.1 20221121 (Red Hat 12.2.1-4)]
>>> import platform; print(platform.python_implementation()); print(platform.platform())
CPython
Linux-6.0.16-300.fc37.x86_64-x86_64-with-glibc2.36
>>> import Bio; print(Bio.__version__)
1.80
```

### Expected behaviour

Given the following code, I think it'd be better if `Bio.Align.PairwiseAligner` were also able to accept `SeqRecord` objects, since it would then be able to retain `id` and `description` properties, which are necessary to some further calls of `Alignment.format`.

```python
>>> seq1 = SeqIO.read('unknown_sequence.fasta', 'fasta')
>>> seq2 = SeqIO.read('unknown_sequence.fasta', 'fasta')
>>> aligner = Bio.Align.PairwiseAligner(mode='local', scoring='blastp')
>>> aln = aligner.align(seq1, seq2)[0]
# no errors
```

### Actual behaviour

```python
>>> aln = aligner.align(seq1, seq2)[0]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/junior/Downloads/venv/lib64/python3.11/site-packages/Bio/Align/__init__.py", line 3121, in align
    score, paths = _aligners.PairwiseAligner.align(self, sA, sB, strand)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: sequence has unexpected format

>>> aln = aligner.align(seq1.seq, seq2.seq)[0]
>>> aln.format('fasta')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/junior/Downloads/venv/lib64/python3.11/site-packages/Bio/Align/__init__.py", line 1825, in format
    return writer.format_alignment(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/junior/Downloads/venv/lib64/python3.11/site-packages/Bio/Align/fasta.py", line 37, in format_alignment
    if sequence.description:
       ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Seq' object has no attribute 'description'
```

### Steps to reproduce

1. Have a fasta file with a single sequence available
2. Launch python
3. Paste the following code:
```python
>>> seq1 = SeqIO.read('unknown_sequence.fasta', 'fasta')
>>> seq2 = SeqIO.read('unknown_sequence.fasta', 'fasta')
>>> aligner = Bio.Align.PairwiseAligner(mode='local', scoring='blastp')
>>> aln = aligner.align(seq1, seq2)[0]
```

**Comment by mdehoon** [comment]
Fixed in #4188
