### ISSUE TITLE
Cannot seek with bgzf on files written by bgzf

### ISSUE THREAD

**Issue by kmoad** [biopython/biopython#4271]
### Setup

I am reporting a problem with Biopython version, Python version, and operating
system as follows:

Biopython=1.81

Python=3.11.2

OS=Linux-6.2.8

### Expected behaviour

Bgzipped vcf files should be seekable.

### Actual behaviour

There is a magic number failure. It appears to be off by one.
```
Traceback (most recent call last):
  File "/home/kyle/a/jobs/kg/dx/head/bgzf-fail.py", line 11, in <module>
    zf.seek(100000)
  File "/home/kyle/.local/lib/python3.11/site-packages/Bio/bgzf.py", line 682, in seek
    self._load_block(start_offset)
  File "/home/kyle/.local/lib/python3.11/site-packages/Bio/bgzf.py", line 643, in _load_block
    block_size, self._buffer = _load_bgzf_block(handle, self._text)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kyle/.local/lib/python3.11/site-packages/Bio/bgzf.py", line 444, in _load_bgzf_block
    raise ValueError(
ValueError: A BGZF (e.g. a BAM file) block should start with b'\x1f\x8b\x08\x04', not b'\x8b\x08\x04\x00'; handle.tell() now says 5

```

### Steps to reproduce

Bgzip a vcf file, then seek to a large virtual offset.

```python
from Bio import bgzf

vcf_path = 'any.vcf'
zip_path = vcf_path+'.gz'

with open(vcf_path,'rb') as f, bgzf.open(zip_path,'wb') as zf:
    zf.write(f.read())

zf = bgzf.open(zip_path, 'rb')

zf.seek(100000)
print(zf.read(100))

```

The error also happens when seeking in vcfs zipped using the `bgzip` binary.

The error does not happen if the seek position is small (e.g. 100).

**Comment by kmoad** [comment]
I misunderstood how to make the virtual offset.
