### ISSUE TITLE
PDBParser fails with error "AttributeError: 'NoneType' object has no attribute 'get_fullname'"

### ISSUE THREAD

**Issue by ostrokach** [biopython/biopython#441]
When I try to use PDBParesr to read the pdb for 3nh3 I get an error:

```
AttributeError: 'NoneType' object has no attribute 'get_fullname'".
```

To reproduce the error:
1) download "3NH3.pdb" from http://www.rcsb.org/pdb/explore/explore.do?structureId=3NH3
2) run the following code

```
from Bio.PDB import PDBParser
parser = PDBParser()
structure = parser.get_structure('3nh3', open('3NH3.pdb', 'r'))
```

Here is the full traceback:

```
Traceback (most recent call last):

  File "<ipython-input-64-c2358d7c6b4e>", line 1, in <module>
    structure = parser.get_structure('3nh3', open('3NH3.pdb', 'r'))

  File "/home/xx/anaconda/lib/python2.7/site-packages/Bio/PDB/PDBParser.py", line 86, in get_structure
    self._parse(handle.readlines())

  File "/home/xx/anaconda/lib/python2.7/site-packages/Bio/PDB/PDBParser.py", line 109, in _parse
    self.trailer = self._parse_coordinates(coords_trailer)

  File "/home/xx/anaconda/lib/python2.7/site-packages/Bio/PDB/PDBParser.py", line 225, in _parse_coordinates
    fullname, serial_number, element)

  File "/home/xx/anaconda/lib/python2.7/site-packages/Bio/PDB/StructureBuilder.py", line 187, in init_atom
    duplicate_fullname=duplicate_atom.get_fullname()

  File "/home/xx/anaconda/lib/python2.7/site-packages/Bio/PDB/Entity.py", line 210, in __getattr__
    return getattr(self.selected_child, method)

AttributeError: 'NoneType' object has no attribute 'get_fullname'
```

**Comment by peterjc** [comment]
It turns out this had been reported earlier by @JoaoRodrigues on the old RedMine issue tracker as https://redmine.open-bio.org/issues/3229

>PDBParser fails when occupancy of atom is -1.0
>
> PDBID 3NH3 has occupancy values of -1.0 (seems to be an unique case in the PDB).
