### ISSUE TITLE
UndefinedSequenceData

### ISSUE THREAD

**Issue by Tim-Kirkwood** [biopython/biopython#4465]
### Setup

I am reporting a problem with Biopython version, Python version, and operating
system as follows:

```python
3.10.9 | packaged by Anaconda, Inc. | (main, Mar  8 2023, 10:42:25) [MSC v.1916 64 bit (AMD64)]
CPython
Windows-10-10.0.19044-SP0
1.80
```

### Expected behaviour
Scrape/parse/write intact genbank files from NCBI.

### Actual behaviour

I am scraping genbank files from NCBI, and using them in a second application (https://github.com/gamcil/clinker/tree/master).  Some files are breaking the second application, with the traceback:
```
Traceback (most recent call last):
  File "C:\Users\u03132tk\AppData\Local\anaconda3\envs\pip_env\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\u03132tk\AppData\Local\anaconda3\envs\pip_env\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\u03132tk\AppData\Local\anaconda3\envs\pip_env\Scripts\clinker.exe\__main__.py", line 7, in <module>
  File "C:\Users\u03132tk\AppData\Local\anaconda3\envs\pip_env\lib\site-packages\clinker\main.py", line 353, in main
    clinker(
  File "C:\Users\u03132tk\AppData\Local\anaconda3\envs\pip_env\lib\site-packages\clinker\main.py", line 167, in clinker
    clusters = parse_files(paths, ranges=ranges, set_origin=set_origin)
  File "C:\Users\u03132tk\AppData\Local\anaconda3\envs\pip_env\lib\site-packages\clinker\classes.py", line 329, in parse_files
    cluster = cluster_from_genbank(path, ranges=ranges, set_origin=set_origin)
  File "C:\Users\u03132tk\AppData\Local\anaconda3\envs\pip_env\lib\site-packages\clinker\classes.py", line 304, in cluster_from_genbank
    locus = Locus.from_seqrecord(record, set_origin=set_origin)
  File "C:\Users\u03132tk\AppData\Local\anaconda3\envs\pip_env\lib\site-packages\clinker\classes.py", line 527, in from_seqrecord
    gene = Gene.from_seqfeature(
  File "C:\Users\u03132tk\AppData\Local\anaconda3\envs\pip_env\lib\site-packages\clinker\classes.py", line 619, in from_seqfeature
    sequence=str(sequence),
  File "C:\Users\u03132tk\AppData\Local\anaconda3\envs\pip_env\lib\site-packages\Bio\Seq.py", line 382, in __str__
    return self._data.decode("ASCII")
  File "C:\Users\u03132tk\AppData\Local\anaconda3\envs\pip_env\lib\site-packages\Bio\Seq.py", line 156, in decode
    return bytes(self).decode(encoding)
  File "C:\Users\u03132tk\AppData\Local\anaconda3\envs\pip_env\lib\site-packages\Bio\Seq.py", line 3000, in __bytes__
    raise UndefinedSequenceError("Sequence content is undefined")
Bio.Seq.UndefinedSequenceError: Sequence content is undefined
```

When I look at the seq records I get from Entrez (please see "actual behaviour") I see some of the seq data attributes are set to undefined sequence, which is what I believe is the issue.  I have tested 3 accessions, 1 has this issue (https://www.ncbi.nlm.nih.gov/nuccore/NZ_JAPFQR010000015.1).

Why is this (and more importantly, is there a way to fix it)?

### Steps to reproduce

```
from Bio import Entrez, SeqIO
Entrez.email = my_email

#Undefined sequence
accession = 'NZ_JAPFQR010000015.1'
handle = Entrez.efetch(db="nucleotide", id=accession, rettype="gb", retmode="gb_with_parts")   
record = SeqIO.read(handle, "genbank")
print (record.seq._data[0:10]) #<Bio.Seq._UndefinedSequenceData object at 0x000002A3F2D94CD0>

#normal sequence 
accession = 'BMVQ01000009.1'
handle = Entrez.efetch(db="nucleotide", id=accession, rettype="gb", retmode="gb_with_parts")   
record = SeqIO.read(handle, "genbank")
print (record.seq._data[0:10]) #b'CCCGCAAGAA' 

```

Many thanks for the help!

**Comment by peterjc** [comment]
This appears to be as expected, https://www.ncbi.nlm.nih.gov/nuccore/NZ_JAPFQR010000015.1 has no sequence - it ends:

```
...
CONTIG      join(JAPFQR010000015.1:1..153948)
//
```

Therefore you cannot slice it, thus you get an exception.

You could handle the CONTIG information yourself in code, but the simpler solution is change the Entrez return type from ``gb`` to ``gbwithparts`` (or "Genbank (full)" in the web interface), and then the NCBI will expand that ``CONTIG`` reference and give you actual sequence:

https://www.ncbi.nlm.nih.gov/nuccore/NZ_JAPFQR010000015.1?report=gbwithparts&log$=seqview

Beware that the ``gbwithparts`` output is generated by the NCBI (on demand I think), and is not the official record.

**Comment by Tim-Kirkwood** [comment]
Ah that's interesting, I'm always finding stuff I didn't know about NCBI - I thought the only sequence free entries were WGS master records.  Thanks you for your help, it all seems to be working!
