### ISSUE TITLE
When using NCBIWWW.qblast for online query, an exception occurred when setting service=psi.

### ISSUE THREAD

**Issue by 9527567** [biopython/biopython#4519]
### Setup

I am reporting a problem with Biopython version, Python version, and operating
system as follows:

```python
import sys; print(sys.version)
import platform; print(platform.python_implementation()); print(platform.platform())
import Bio; print(Bio.__version__)
```

(*Please copy and run the above in your Python, and copy-and-paste the output*)

3.9.18 (main, Sep 11 2023, 13:41:44)
[GCC 11.2.0]
CPython
Linux-5.15.133.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
1.81
### Expected behaviour
I use the following code to search for templates online.
```python
from Bio.Blast import NCBIWWW
NCBIWWW.qblast("blastp", "pdbaa", "MPIPNNPGAGENAFDPVFVKDDDGYDLDSFMIPAHYKKYLTKVLVPNGVIKNRIEKLARDVMKEMGGHHIVALCVLKGGYKFFADLLDYIKALNRNSDRSIPMTVDFIRLKSYCNDQSTGDIKVIGGDDLSTLTGKNVLIVEDIIDTGKTMQTLLSLVRQYNPKMVKVACLFIKRTPLWNGFKADFVGFSIPDHFVVGYSLDYNEIFRDLDHCCLVNDEGKKKYKATSL", expect=0.001, entrez_query='Homo sapiens[Organism]', service="psi")
```
When using other services, no more errors will be reported, and `service=psi` will not be reported before a certain point in time.
### Actual behaviour

```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/z/miniconda3/envs/atm/lib/python3.9/site-packages/Bio/Blast/NCBIWWW.py", line 230, in qblast
    rid, rtoe = _parse_qblast_ref_page(handle)
  File "/home/z/miniconda3/envs/atm/lib/python3.9/site-packages/Bio/Blast/NCBIWWW.py", line 341, in _parse_qblast_ref_page
    raise ValueError(f"Error message from NCBI: {msg}")
ValueError: Error message from NCBI: Message ID#36 Error: Cannot validate the Blast options:  Word-size must be less than 5 for psiblast
```

### Steps to reproduce

Only execute the above code.

**Comment by peterjc** [comment]
Did you try the suggestion from the NCBI's error message and add something like ``word_size=4``? e.g.

```python
from Bio.Blast import NCBIWWW
handle = NCBIWWW.qblast(
    "blastp", "pdbaa",
    "MPIPNNPGAGENAFDPVFVKDDDGYDLDSFMIPAHYKKYLTKVLVPNGVIKNRIEKLARDVMKEMGGHHIVALCVLKGGYKFFADLLDYIKALNRNSDRSIPMTVDFIRLKSYCNDQSTGDIKVIGGDDLSTLTGKNVLIVEDIIDTGKTMQTLLSLVRQYNPKMVKVACLFIKRTPLWNGFKADFVGFSIPDHFVVGYSLDYNEIFRDLDHCCLVNDEGKKKYKATSL",
    expect=0.001, entrez_query='Homo sapiens[Organism]', service="psi", word_size=4
)
```

That seems to work for me, hopefully useful output.

**Comment by peterjc** [comment]
That would explain it, but I don't think we should be setting our own default word size (that could easily get out of sync with whatever the NCBI does in future).

So, do any of our examples or docs need updating?

**Comment by michaelfm1211** [comment]
@peterjc  I don't know too much about BLAST beyond the basics, but it looks like [the tutorial/cookbook](https://biopython.org/DIST/docs/tutorial/Tutorial.html#sec180) currently says PSI-BLAST isn't even supported on the NCBI servers. Does this need to be rewritten?

I haven't done a particularly in-depth search of the docs, but this is the only reference to PSI-BLAST that I could find. AFAIK, the `word_size` thing is only an issue for PSI-BLAST.

**Comment by peterjc** [comment]
See also #875, perhaps "psi" should be removed from the docstring as a possible value for "service".
