### ISSUE TITLE
XML Schema 'None' found not consistent with reported seqXML version 0.2

### ISSUE THREAD

**Issue by brucejwittmann** [biopython/biopython#4578]
### Setup

I am reporting a problem with Biopython version, Python version, and operating
system as follows:

```python
import sys; print(sys.version)
import platform; print(platform.python_implementation()); print(platform.platform())
import Bio; print(Bio.__version__)
```

3.11.7 (main, Dec 15 2023, 18:12:31) [GCC 11.2.0]
CPython
Linux-6.2.0-39-generic-x86_64-with-glibc2.35
1.83

### Expected behaviour

Running the below code should load in the attached seqXML file. Instead, it errors. Note that I had to change the file extension to ".txt" to get GitHub to accept the file. It is originally a seq.xml file, however, downloaded from [OMA](https://omabrowser.org/oma/home/).

```
for seq in SeqIO.parse("ACAM1.seq.xml", "seqxml"):
    pass
```
[ACAM1.seq.txt](https://github.com/biopython/biopython/files/13891282/ACAM1.seq.txt)

### Actual behaviour

The following traceback results:

```
ValueError                                Traceback (most recent call last)
Cell In[13], [line 10](vscode-notebook-cell:?execution_count=13&line=10)
      [7](vscode-notebook-cell:?execution_count=13&line=7)     continue
      [9](vscode-notebook-cell:?execution_count=13&line=9) # Process sequences
---> [10](vscode-notebook-cell:?execution_count=13&line=10) for seq in SeqIO.parse(filename, "seqxml"):
     [11](vscode-notebook-cell:?execution_count=13&line=11)     pass
     [13](vscode-notebook-cell:?execution_count=13&line=13) break

File [~/anaconda3/envs/pst/lib/python3.11/site-packages/Bio/SeqIO/__init__.py:613](https://vscode-remote+ssh-002dremote-002bbruce-002dubuntu.vscode-resource.vscode-cdn.net/home/bwittmann/GitRepos/pst/data_organization/~/anaconda3/envs/pst/lib/python3.11/site-packages/Bio/SeqIO/__init__.py:613), in parse(handle, format, alphabet)
    [611](https://vscode-remote+ssh-002dremote-002bbruce-002dubuntu.vscode-resource.vscode-cdn.net/home/bwittmann/GitRepos/pst/data_organization/~/anaconda3/envs/pst/lib/python3.11/site-packages/Bio/SeqIO/__init__.py:611) iterator_generator = _FormatToIterator.get(format)
    [612](https://vscode-remote+ssh-002dremote-002bbruce-002dubuntu.vscode-resource.vscode-cdn.net/home/bwittmann/GitRepos/pst/data_organization/~/anaconda3/envs/pst/lib/python3.11/site-packages/Bio/SeqIO/__init__.py:612) if iterator_generator:
--> [613](https://vscode-remote+ssh-002dremote-002bbruce-002dubuntu.vscode-resource.vscode-cdn.net/home/bwittmann/GitRepos/pst/data_organization/~/anaconda3/envs/pst/lib/python3.11/site-packages/Bio/SeqIO/__init__.py:613)     return iterator_generator(handle)
    [614](https://vscode-remote+ssh-002dremote-002bbruce-002dubuntu.vscode-resource.vscode-cdn.net/home/bwittmann/GitRepos/pst/data_organization/~/anaconda3/envs/pst/lib/python3.11/site-packages/Bio/SeqIO/__init__.py:614) if format in AlignIO._FormatToIterator:
    [615](https://vscode-remote+ssh-002dremote-002bbruce-002dubuntu.vscode-resource.vscode-cdn.net/home/bwittmann/GitRepos/pst/data_organization/~/anaconda3/envs/pst/lib/python3.11/site-packages/Bio/SeqIO/__init__.py:615)     # Use Bio.AlignIO to read in the alignments
    [616](https://vscode-remote+ssh-002dremote-002bbruce-002dubuntu.vscode-resource.vscode-cdn.net/home/bwittmann/GitRepos/pst/data_organization/~/anaconda3/envs/pst/lib/python3.11/site-packages/Bio/SeqIO/__init__.py:616)     return (r for alignment in AlignIO.parse(handle, format) for r in alignment)

File [~/anaconda3/envs/pst/lib/python3.11/site-packages/Bio/SeqIO/SeqXmlIO.py:400](https://vscode-remote+ssh-002dremote-002bbruce-002dubuntu.vscode-resource.vscode-cdn.net/home/bwittmann/GitRepos/pst/data_organization/~/anaconda3/envs/pst/lib/python3.11/site-packages/Bio/SeqIO/SeqXmlIO.py:400), in SeqXmlIterator.__init__(self, stream_or_path, namespace)
    [398](https://vscode-remote+ssh-002dremote-002bbruce-002dubuntu.vscode-resource.vscode-cdn.net/home/bwittmann/GitRepos/pst/data_organization/~/anaconda3/envs/pst/lib/python3.11/site-packages/Bio/SeqIO/SeqXmlIO.py:398) self.parser.setContentHandler(content_handler)
    [399](https://vscode-remote+ssh-002dremote-002bbruce-002dubuntu.vscode-resource.vscode-cdn.net/home/bwittmann/GitRepos/pst/data_organization/~/anaconda3/envs/pst/lib/python3.11/site-packages/Bio/SeqIO/SeqXmlIO.py:399) self.parser.setFeature(handler.feature_namespaces, True)
--> [400](https://vscode-remote+ssh-002dremote-002bbruce-002dubuntu.vscode-resource.vscode-cdn.net/home/bwittmann/GitRepos/pst/data_organization/~/anaconda3/envs/pst/lib/python3.11/site-packages/Bio/SeqIO/SeqXmlIO.py:400) super().__init__(stream_or_path, mode="b", fmt="SeqXML")

File [~/anaconda3/envs/pst/lib/python3.11/site-packages/Bio/SeqIO/Interfaces.py:76](https://vscode-remote+ssh-002dremote-002bbruce-002dubuntu.vscode-resource.vscode-cdn.net/home/bwittmann/GitRepos/pst/data_organization/~/anaconda3/envs/pst/lib/python3.11/site-packages/Bio/SeqIO/Interfaces.py:76), in SequenceIterator.__init__(self, source, alphabet, mode, fmt)
     [74](https://vscode-remote+ssh-002dremote-002bbruce-002dubuntu.vscode-resource.vscode-cdn.net/home/bwittmann/GitRepos/pst/data_organization/~/anaconda3/envs/pst/lib/python3.11/site-packages/Bio/SeqIO/Interfaces.py:74)     self.should_close_stream = False
     [75](https://vscode-remote+ssh-002dremote-002bbruce-002dubuntu.vscode-resource.vscode-cdn.net/home/bwittmann/GitRepos/pst/data_organization/~/anaconda3/envs/pst/lib/python3.11/site-packages/Bio/SeqIO/Interfaces.py:75) try:
---> [76](https://vscode-remote+ssh-002dremote-002bbruce-002dubuntu.vscode-resource.vscode-cdn.net/home/bwittmann/GitRepos/pst/data_organization/~/anaconda3/envs/pst/lib/python3.11/site-packages/Bio/SeqIO/Interfaces.py:76)     self.records = self.parse(self.stream)
     [77](https://vscode-remote+ssh-002dremote-002bbruce-002dubuntu.vscode-resource.vscode-cdn.net/home/bwittmann/GitRepos/pst/data_organization/~/anaconda3/envs/pst/lib/python3.11/site-packages/Bio/SeqIO/Interfaces.py:77) except Exception:
     [78](https://vscode-remote+ssh-002dremote-002bbruce-002dubuntu.vscode-resource.vscode-cdn.net/home/bwittmann/GitRepos/pst/data_organization/~/anaconda3/envs/pst/lib/python3.11/site-packages/Bio/SeqIO/Interfaces.py:78)     if self.should_close_stream:

File [~/anaconda3/envs/pst/lib/python3.11/site-packages/Bio/SeqIO/SeqXmlIO.py:415](https://vscode-remote+ssh-002dremote-002bbruce-002dubuntu.vscode-resource.vscode-cdn.net/home/bwittmann/GitRepos/pst/data_organization/~/anaconda3/envs/pst/lib/python3.11/site-packages/Bio/SeqIO/SeqXmlIO.py:415), in SeqXmlIterator.parse(self, handle)
    [413](https://vscode-remote+ssh-002dremote-002bbruce-002dubuntu.vscode-resource.vscode-cdn.net/home/bwittmann/GitRepos/pst/data_organization/~/anaconda3/envs/pst/lib/python3.11/site-packages/Bio/SeqIO/SeqXmlIO.py:413)     else:
    [414](https://vscode-remote+ssh-002dremote-002bbruce-002dubuntu.vscode-resource.vscode-cdn.net/home/bwittmann/GitRepos/pst/data_organization/~/anaconda3/envs/pst/lib/python3.11/site-packages/Bio/SeqIO/SeqXmlIO.py:414)         raise ValueError("XML file contains no data.")
--> [415](https://vscode-remote+ssh-002dremote-002bbruce-002dubuntu.vscode-resource.vscode-cdn.net/home/bwittmann/GitRepos/pst/data_organization/~/anaconda3/envs/pst/lib/python3.11/site-packages/Bio/SeqIO/SeqXmlIO.py:415) parser.feed(text)
    [416](https://vscode-remote+ssh-002dremote-002bbruce-002dubuntu.vscode-resource.vscode-cdn.net/home/bwittmann/GitRepos/pst/data_organization/~/anaconda3/envs/pst/lib/python3.11/site-packages/Bio/SeqIO/SeqXmlIO.py:416) seqXMLversion = content_handler.seqXMLversion
    [417](https://vscode-remote+ssh-002dremote-002bbruce-002dubuntu.vscode-resource.vscode-cdn.net/home/bwittmann/GitRepos/pst/data_organization/~/anaconda3/envs/pst/lib/python3.11/site-packages/Bio/SeqIO/SeqXmlIO.py:417) if seqXMLversion is not None:

File [~/anaconda3/envs/pst/lib/python3.11/xml/sax/expatreader.py:217](https://vscode-remote+ssh-002dremote-002bbruce-002dubuntu.vscode-resource.vscode-cdn.net/home/bwittmann/GitRepos/pst/data_organization/~/anaconda3/envs/pst/lib/python3.11/xml/sax/expatreader.py:217), in ExpatParser.feed(self, data, isFinal)
    [210](https://vscode-remote+ssh-002dremote-002bbruce-002dubuntu.vscode-resource.vscode-cdn.net/home/bwittmann/GitRepos/pst/data_organization/~/anaconda3/envs/pst/lib/python3.11/xml/sax/expatreader.py:210)     self._cont_handler.startDocument()
    [212](https://vscode-remote+ssh-002dremote-002bbruce-002dubuntu.vscode-resource.vscode-cdn.net/home/bwittmann/GitRepos/pst/data_organization/~/anaconda3/envs/pst/lib/python3.11/xml/sax/expatreader.py:212) try:
    [213](https://vscode-remote+ssh-002dremote-002bbruce-002dubuntu.vscode-resource.vscode-cdn.net/home/bwittmann/GitRepos/pst/data_organization/~/anaconda3/envs/pst/lib/python3.11/xml/sax/expatreader.py:213)     # The isFinal parameter is internal to the expat reader.
    [214](https://vscode-remote+ssh-002dremote-002bbruce-002dubuntu.vscode-resource.vscode-cdn.net/home/bwittmann/GitRepos/pst/data_organization/~/anaconda3/envs/pst/lib/python3.11/xml/sax/expatreader.py:214)     # If it is set to true, expat will check validity of the entire
    [215](https://vscode-remote+ssh-002dremote-002bbruce-002dubuntu.vscode-resource.vscode-cdn.net/home/bwittmann/GitRepos/pst/data_organization/~/anaconda3/envs/pst/lib/python3.11/xml/sax/expatreader.py:215)     # document. When feeding chunks, they are not normally final -
    [216](https://vscode-remote+ssh-002dremote-002bbruce-002dubuntu.vscode-resource.vscode-cdn.net/home/bwittmann/GitRepos/pst/data_organization/~/anaconda3/envs/pst/lib/python3.11/xml/sax/expatreader.py:216)     # except when invoked from close.
--> [217](https://vscode-remote+ssh-002dremote-002bbruce-002dubuntu.vscode-resource.vscode-cdn.net/home/bwittmann/GitRepos/pst/data_organization/~/anaconda3/envs/pst/lib/python3.11/xml/sax/expatreader.py:217)     self._parser.Parse(data, isFinal)
    [218](https://vscode-remote+ssh-002dremote-002bbruce-002dubuntu.vscode-resource.vscode-cdn.net/home/bwittmann/GitRepos/pst/data_organization/~/anaconda3/envs/pst/lib/python3.11/xml/sax/expatreader.py:218) except expat.error as e:
    [219](https://vscode-remote+ssh-002dremote-002bbruce-002dubuntu.vscode-resource.vscode-cdn.net/home/bwittmann/GitRepos/pst/data_organization/~/anaconda3/envs/pst/lib/python3.11/xml/sax/expatreader.py:219)     exc = SAXParseException(expat.ErrorString(e.code), e, self)

File /croot/python-split_1702663341049/work/Modules/pyexpat.c:416, in StartElement()

File [~/anaconda3/envs/pst/lib/python3.11/xml/sax/expatreader.py:369](https://vscode-remote+ssh-002dremote-002bbruce-002dubuntu.vscode-resource.vscode-cdn.net/home/bwittmann/GitRepos/pst/data_organization/~/anaconda3/envs/pst/lib/python3.11/xml/sax/expatreader.py:369), in ExpatParser.start_element_ns(self, name, attrs)
    [366](https://vscode-remote+ssh-002dremote-002bbruce-002dubuntu.vscode-resource.vscode-cdn.net/home/bwittmann/GitRepos/pst/data_organization/~/anaconda3/envs/pst/lib/python3.11/xml/sax/expatreader.py:366)     newattrs[apair] = value
    [367](https://vscode-remote+ssh-002dremote-002bbruce-002dubuntu.vscode-resource.vscode-cdn.net/home/bwittmann/GitRepos/pst/data_organization/~/anaconda3/envs/pst/lib/python3.11/xml/sax/expatreader.py:367)     qnames[apair] = qname
--> [369](https://vscode-remote+ssh-002dremote-002bbruce-002dubuntu.vscode-resource.vscode-cdn.net/home/bwittmann/GitRepos/pst/data_organization/~/anaconda3/envs/pst/lib/python3.11/xml/sax/expatreader.py:369) self._cont_handler.startElementNS(pair, None,
    [370](https://vscode-remote+ssh-002dremote-002bbruce-002dubuntu.vscode-resource.vscode-cdn.net/home/bwittmann/GitRepos/pst/data_organization/~/anaconda3/envs/pst/lib/python3.11/xml/sax/expatreader.py:370)                                   AttributesNSImpl(newattrs, qnames))

File [~/anaconda3/envs/pst/lib/python3.11/site-packages/Bio/SeqIO/SeqXmlIO.py:84](https://vscode-remote+ssh-002dremote-002bbruce-002dubuntu.vscode-resource.vscode-cdn.net/home/bwittmann/GitRepos/pst/data_organization/~/anaconda3/envs/pst/lib/python3.11/site-packages/Bio/SeqIO/SeqXmlIO.py:84), in ContentHandler.startSeqXMLElement(self, name, qname, attrs)
     [82](https://vscode-remote+ssh-002dremote-002bbruce-002dubuntu.vscode-resource.vscode-cdn.net/home/bwittmann/GitRepos/pst/data_organization/~/anaconda3/envs/pst/lib/python3.11/site-packages/Bio/SeqIO/SeqXmlIO.py:82) url = f"http://www.seqxml.org/{self.seqXMLversion}/seqxml.xsd"
     [83](https://vscode-remote+ssh-002dremote-002bbruce-002dubuntu.vscode-resource.vscode-cdn.net/home/bwittmann/GitRepos/pst/data_organization/~/anaconda3/envs/pst/lib/python3.11/site-packages/Bio/SeqIO/SeqXmlIO.py:83) if schema != url:
---> [84](https://vscode-remote+ssh-002dremote-002bbruce-002dubuntu.vscode-resource.vscode-cdn.net/home/bwittmann/GitRepos/pst/data_organization/~/anaconda3/envs/pst/lib/python3.11/site-packages/Bio/SeqIO/SeqXmlIO.py:84)     raise ValueError(
     [85](https://vscode-remote+ssh-002dremote-002bbruce-002dubuntu.vscode-resource.vscode-cdn.net/home/bwittmann/GitRepos/pst/data_organization/~/anaconda3/envs/pst/lib/python3.11/site-packages/Bio/SeqIO/SeqXmlIO.py:85)         "XML Schema '%s' found not consistent with reported seqXML version %s"
     [86](https://vscode-remote+ssh-002dremote-002bbruce-002dubuntu.vscode-resource.vscode-cdn.net/home/bwittmann/GitRepos/pst/data_organization/~/anaconda3/envs/pst/lib/python3.11/site-packages/Bio/SeqIO/SeqXmlIO.py:86)         % (schema, self.seqXMLversion)
     [87](https://vscode-remote+ssh-002dremote-002bbruce-002dubuntu.vscode-resource.vscode-cdn.net/home/bwittmann/GitRepos/pst/data_organization/~/anaconda3/envs/pst/lib/python3.11/site-packages/Bio/SeqIO/SeqXmlIO.py:87)     )
     [88](https://vscode-remote+ssh-002dremote-002bbruce-002dubuntu.vscode-resource.vscode-cdn.net/home/bwittmann/GitRepos/pst/data_organization/~/anaconda3/envs/pst/lib/python3.11/site-packages/Bio/SeqIO/SeqXmlIO.py:88) self.endElementNS = self.endSeqXMLElement
     [89](https://vscode-remote+ssh-002dremote-002bbruce-002dubuntu.vscode-resource.vscode-cdn.net/home/bwittmann/GitRepos/pst/data_organization/~/anaconda3/envs/pst/lib/python3.11/site-packages/Bio/SeqIO/SeqXmlIO.py:89) self.startElementNS = self.startEntryElement

ValueError: XML Schema 'None' found not consistent with reported seqXML version 0.2
```

### Steps to reproduce

Just run the provided code with the provided seq.xml file.

**Comment by peterjc** [comment]
Confirming behaviour:

```
$ python -c 'from Bio import SeqIO; print(len(list(SeqIO.parse("ACAM1.seq.xml", "seqxml"))))'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/xxx/mambaforge/lib/python3.10/site-packages/Bio/SeqIO/__init__.py", line 613, in parse
    return iterator_generator(handle)
  File "/Users/xxx/mambaforge/lib/python3.10/site-packages/Bio/SeqIO/SeqXmlIO.py", line 400, in __init__
    super().__init__(stream_or_path, mode="b", fmt="SeqXML")
  File "/Users/xxx/mambaforge/lib/python3.10/site-packages/Bio/SeqIO/Interfaces.py", line 76, in __init__
    self.records = self.parse(self.stream)
  File "/Users/xxx/mambaforge/lib/python3.10/site-packages/Bio/SeqIO/SeqXmlIO.py", line 415, in parse
    parser.feed(text)
  File "/Users/xxx/mambaforge/lib/python3.10/xml/sax/expatreader.py", line 217, in feed
    self._parser.Parse(data, isFinal)
  File "/Users/runner/miniforge3/conda-bld/python-split_1687559261959/work/Modules/pyexpat.c", line 416, in StartElement
  File "/Users/xxx/mambaforge/lib/python3.10/xml/sax/expatreader.py", line 369, in start_element_ns
    self._cont_handler.startElementNS(pair, None,
  File "/Users/xxx/mambaforge/lib/python3.10/site-packages/Bio/SeqIO/SeqXmlIO.py", line 84, in startSeqXMLElement
    raise ValueError(
ValueError: XML Schema 'None' found not consistent with reported seqXML version 0.2
```

However,

```
$ head -n 4 ACAM1.seq.xml 
<?xml version="1.0"?>
<seqXML source="Genome Reviews" sourceVersion="18-MAR-2008 (Rel. 88, Last updated, Version 2)" seqXMLversion="0.2">
 <entry id="ACAM100001">
  <species name="Acaryochloris marina (strain MBIC 11017)" ncbiTaxID="-644103924"/>
(base) Peters-iMac:Downloads pc40583$ head -n 3 ACAM1.seq.xml 
<?xml version="1.0"?>
<seqXML source="Genome Reviews" sourceVersion="18-MAR-2008 (Rel. 88, Last updated, Version 2)" seqXMLversion="0.2">
 <entry id="ACAM100001">
```

Note the minimal ``<seqXML ...>`` tag, lacking ``xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://www.seqxml.org/0.4/seqxml.xsd"`` seen in our test cases.

I am surprised to see v0.2 still in use, v0.4 was released June 28, 2011 -- see https://seqxml.org/0.4/seqxml_doc_v0.4.html#changes

I tried adding that snippet (adjusted to v0.2), and then the parser fails with ``ValueError: Unexpected attribute '(None, 'type')' found for DBRef element`` which seems somewhat related to the changes from v0.2 to v0.4. I suspect the parser simply doesn't work with v0.2 (which was current for less than a year in the early days of the file format).

Can you ask OMA to update their export code, or is this a static file they are hosting?

**Comment by brucejwittmann** [comment]
Unfortunately it's a static file. It wasn't much work for me to just use Python's inbuilt XML library instead. I get the sense that I'm probably the only person to have issues with this in a long time, seeing as v0.2 is so old. So maybe not worth fixing given how easy other options are to use. If it is worth fixing, perhaps adding an additional version flag for seqxml would work? For instance, the second argument to `SeqIO.parse` could be `seqxmlv0.2`.

**Comment by peterjc** [comment]
I agree it is probably not worth fixing, but the XML says which version it
is, so the user ought not to need to say. So no API change or new format
name required.

**Comment by mdehoon** [comment]
> I agree it is probably not worth fixing, but the XML says which version it is, so the user ought not to need to say. So no API change or new format name required.

The parser could look at the value of seqXMLversion and adjust its behavior accordingly. It may be a simple change, depending on how much the two versions differ from each other. If it is a more extensive change, I agree that it is not worth fixing.

**Comment by michaelfm1211** [comment]
> I tried adding that snippet (adjusted to v0.2), and then the parser fails with ValueError: Unexpected attribute '(None, 'type')' found for DBRef element which seems somewhat related to the changes from v0.2 to v0.4. I suspect the parser simply doesn't work with v0.2 (which was current for less than a year in the early days of the file format).

@peterjc According to the [documentation](https://seqxml.org/0.4/seqxml_doc_v0.4.html#DBRef), the `type` attribute on DBRef elements is still supported and encouraged after 0.4, but only optional. Even if the SeqXML parser doesn't support versions before 0.4, the `type` attribute should still be supported.

But it looks like there are only a few differences between the versions 0.1, 0.2, 0.3, and 0.4 anyway, so IMO we might as well add support. I can work on a PR for this.

**Comment by peterjc** [comment]
Thank you all, this should be fixed now on the master branch.
