### ISSUE TITLE
Conversion FASTA file to FASTQ format - error

### ISSUE THREAD

**Issue by silvia1234567890** [biopython/biopython#4580]
### Setup

Hello,

I am reporting a problem with Biopython 1.81, Python 3.12.1, and operating system MAC.
I would like to convert a fasta file to fastq format using Biopython. This is the command I used:

```
import Bio
from Bio import SeqIO

with open("/Users/Ana/19_S19_L001-C_collapse-unique_edit.fasta") as input_handle:
     with open("/Users/Ana/19_S19_L001-C_collapse-unique_edit.fastq", "w") as output_handle:
         records = SeqIO.parse(input_handle, "fasta")
         count = SeqIO.write(records, output_handle, "fastq")

print('Converted %i records' % count)
```

### Expected behaviour

`Converted 192299 records` and the fastq file

### Actual behaviour

```
Traceback (most recent call last):
  File "/Users/Ana/Desktop/Silvia(bioinfo)/scripts Python/FASTA_to_FASTQ.py", line 9, in <module>
    count = SeqIO.write(records, output_handle, "fastq")
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/Bio/SeqIO/__init__.py", line 518, in write
    fp.write(format_function(record))
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/Bio/SeqIO/QualityIO.py", line 1565, in as_fastq
    qualities_str = _get_sanger_quality_str(record)
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/Bio/SeqIO/QualityIO.py", line 648, in _get_sanger_quality_str
    raise ValueError(
ValueError: No suitable quality scores found in letter_annotations of SeqRecord (id=AGGTGGTGTCGTAGC_DUPCOUNT=1).
```
What's wrong with the code I used?

Thank you in advance!

**Comment by peterjc** [comment]
This is expected behavior - FASTQ files have quality scores for each base.
Are you expecting a default value to be assigned?

**Comment by MarkusPiotrowski** [comment]
Have a look here: https://biopython.org/docs/latest/api/Bio.SeqIO.QualityIO.html
