### ISSUE TITLE
Bio.SeqUtils can't load GC function

### ISSUE THREAD

**Issue by laczik-git** [biopython/biopython#4622]
Hi,

I have an issue loading the GC function of Bio.SeqUtils

Python version: 3.8.15 | packaged by conda-forge | (default, Nov 22 2022, 08:46:39) [GCC 10.4.0]
System: Linux-6.1.0-13-amd64-x86_64-with-glibc2.10
Bio version: 1.83
I'm running Python in an Anaconda environment:
mamba version 1.4.2
conda version 23.3.1

When I call for GC I get the following error: 

>>> from Bio.SeqUtils import GC
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'GC' from 'Bio.SeqUtils' (/anaconda3/miniforge-install/envs/funannotate/lib/python3.8/site-packages/Bio/SeqUtils/__init__.py)

although GC123 works fine:

>>> from Bio.SeqUtils import GC123
>>> GC123("ACTGTN")
(40.0, 50.0, 50.0, 0.0)

I have the same issue when running Funannotate so my .gbk file is not generated

Traceback (most recent call last):
  File "/anaconda3/miniforge-install/envs/funannotate/bin/funannotate", line 10, in <module>
    sys.exit(main())
  File "/anaconda3/miniforge-install/envs/funannotate/lib/python3.8/site-packages/funannotate/funannotate.py", line 716, in main
    mod.main(arguments)
  File "/anaconda3/miniforge-install/envs/funannotate/lib/python3.8/site-packages/funannotate/predict.py", line 2771, in main
    lib.annotation_summary(
  File "/anaconda3/miniforge-install/envs/funannotate/lib/python3.8/site-packages/funannotate/library.py", line 2880, in annotation_summary
    num, tot, gc, avg, n50, l50, n90, l90 = simpleFastaStats(fasta)
  File "/anaconda3/miniforge-install/envs/funannotate/lib/python3.8/site-packages/funannotate/library.py", line 2737, in simpleFastaStats
    from Bio.SeqUtils import GC
ImportError: cannot import name 'GC' from 'Bio.SeqUtils' (/anaconda3/miniforge-install/envs/funannotate/lib/python3.8/site-packages/Bio/SeqUtils/__init__.py)

Thank you in advance!

**Comment by laczik-git** [comment]
Thank you for the quick answer. It works now.
