### ISSUE TITLE
ImportError: dlopen after install using poetry on macM1

### ISSUE THREAD

**Issue by magisystem0408** [biopython/biopython#4636]
### Setup

I am reporting a problem with Biopython version, Python version, and operating
system as follows:

```python
import sys; print(sys.version)
import platform; print(platform.python_implementation()); print(platform.platform())
import Bio; print(Bio.__version__)
```

```
Python 3.11.5 (main, Aug 24 2023, 15:09:45) [Clang 14.0.3 (clang-1403.0.22.14.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys; print(sys.version)
3.11.5 (main, Aug 24 2023, 15:09:45) [Clang 14.0.3 (clang-1403.0.22.14.1)]
>>> import platform; print(platform.python_implementation()); print(platform.platform())
CPython
macOS-13.2.1-arm64-arm-64bit
>>> import Bio; print(Bio.__version__)
1.82
```

(*Please copy and run the above in your Python, and copy-and-paste the output*)

### Expected behaviour

I would like to run this module on poetry, but it doesn't work.
(*Please fill this in*)

### Actual behaviour
```
python main.py                                                    (base)  2024-02-26 04:26
Traceback (most recent call last):
  File "/Users/matsudomasato/Documents/GitHub/polar-template-match/main.py", line 1, in <module>
    from Bio import SeqIO
  File "/Users/matsudomasato/Documents/GitHub/polar-template-match/.venv/lib/python3.11/site-packages/Bio/SeqIO/__init__.py", line 377, in <module>
    from Bio.Align import MultipleSeqAlignment
  File "/Users/matsudomasato/Documents/GitHub/polar-template-match/.venv/lib/python3.11/site-packages/Bio/Align/__init__.py", line 38, in <module>
    from Bio.Align import _pairwisealigner  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ImportError: dlopen(/Users/matsudomasato/Documents/GitHub/polar-template-match/.venv/lib/python3.11/site-packages/Bio/Align/_pairwisealigner.cpython-311-darwin.so, 0x0002): tried: '/Users/matsudomasato/Documents/GitHub/polar-template-match/.venv/lib/python3.11/site-packages/Bio/Align/_pairwisealigner.cpython-311-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/matsudomasato/Documents/GitHub/polar-template-match/.venv/lib/python3.11/site-packages/Bio/Align/_pairwisealigner.cpython-311-darwin.so' (no such file), '/Users/matsudomasato/Documents/GitHub/polar-template-match/.venv/lib/python3.11/site-packages/Bio/Align/_pairwisealigner.cpython-311-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64'))
```

this is `poetry.lock` file

```

[[package]]
name = "biopython"
version = "1.82"
description = "Freely available tools for computational molecular biology."
optional = false
python-versions = ">=3.8"
files = [
    {file = "biopython-1.82-cp310-cp310-macosx_10_9_x86_64.whl", hash = "sha256:713be5e1e8571ea151864544dfcd2637eaf98c67a6e47b69781d325feb02f6b9"},
    {file = "biopython-1.82-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl", hash = "sha256:5bc908e84278bf61ac901a0c1b695c85ce49491957e0ab07e1e2afc216882525"},
    {file = "biopython-1.82-cp310-cp310-win32.whl", hash = "sha256:f53aff30f01ac9a8aa1fd42dab347a96ee5312945098dfa38f9a5125f6e913fd"},
    {file = "biopython-1.82-cp310-cp310-win_amd64.whl", hash = "sha256:0f3f685a2d85348b8c84c6eebe58a74cef7e1158ac52ae5aa91789436907f0e1"},
    {file = "biopython-1.82-cp311-cp311-macosx_10_9_x86_64.whl", hash = "sha256:c9bc080b7dc6cd6acbf2576766136e8e54acbcc6b7a29ad8075cb5a73f4cfb97"},
    {file = "biopython-1.82-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl", hash = "sha256:c7802b5033edaf34bd2fbd96b87f96999a6808caa0064c91087c7f1340624898"},
    {file = "biopython-1.82-cp311-cp311-win32.whl", hash = "sha256:ec35893b32458f6fa0c98d5f02d801a5fe76961ac66473455f51c0575562c594"},
    {file = "biopython-1.82-cp311-cp311-win_amd64.whl", hash = "sha256:40297d418bb142a7ea1a47faedc24bbe21b0ba455f3805373264470e5cb6ec5c"},
    {file = "biopython-1.82-cp312-cp312-macosx_10_9_x86_64.whl", hash = "sha256:96f77bd6540683c8958e4ebf55b58e8caa26d20db72891915d06670b783e9cdb"},
    {file = "biopython-1.82-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl", hash = "sha256:49b829c2276a0711106663af632c7e203695a5cf082d488d6e10b8aca5ec63e4"},
    {file = "biopython-1.82-cp312-cp312-win32.whl", hash = "sha256:54a9b200d4960ed2a4ec85faac2124ffa278afa58d22e07e2d15ca7509219ea1"},
    {file = "biopython-1.82-cp312-cp312-win_amd64.whl", hash = "sha256:762547037038d42c9ac98877fc32d4aeba798077129df7790cb178256171a4e5"},
    {file = "biopython-1.82-cp38-cp38-macosx_10_9_x86_64.whl", hash = "sha256:cb013256742d31e24fd5093d55511f58bc6a93b8ac723d2ca3b33c7904f1ca14"},
    {file = "biopython-1.82-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl", hash = "sha256:16829760fab60ba17141b7a81494fed837c6f29ea28cdcfb3070764c8e8f2ff1"},
    {file = "biopython-1.82-cp38-cp38-manylinux_2_5_i686.manylinux1_i686.manylinux_2_17_i686.manylinux2014_i686.whl", hash = "sha256:c6af82894dd4f736d737fdea62008a19966251ba39aef39a0ce8b41321305ad5"},
    {file = "biopython-1.82-cp38-cp38-win32.whl", hash = "sha256:a1ff583b2f8b314a4c2d612aad4f4b73827a5f741b391f3a834b0c192a4f1527"},
    {file = "biopython-1.82-cp38-cp38-win_amd64.whl", hash = "sha256:0198f23776d9cb9d514a797e81a024f486adac973b252a2f4696995a5a163745"},
    {file = "biopython-1.82-cp39-cp39-macosx_10_9_x86_64.whl", hash = "sha256:c88e9f87d1b07958e7e1e25ff20efced4796daf650e5290692b5c3ff9aebf9d3"},
    {file = "biopython-1.82-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl", hash = "sha256:8e2533db9275c3e1438151260844e7683f91308da320df02a4c28fb7053ea3a9"},
    {file = "biopython-1.82-cp39-cp39-win32.whl", hash = "sha256:80f48d220b92e747300281602f52e98ec6c537ddd4921b580d9a0368bae05ff5"},
    {file = "biopython-1.82-cp39-cp39-win_amd64.whl", hash = "sha256:73d619611bd7cf9d2ad8b3217b08d3796acfabb765b0771ad2ff7ee2e46a59b0"},
    {file = "biopython-1.82.tar.gz", hash = "sha256:a9b10d959ae88a9744a91c6ce3601f4c86e7ec41679bc93c29f679218f6167bb"},
]
```
### Steps to reproduce

(*Please fill this in *)

**Comment by peterjc** [comment]
I'm unclear how Biopython was installed - as you can see in that list of files, your system is not seeing any ARM specific wheels. You may have to compile from source...

We used to have have Linux ARM wheels, but not for recent releases which is odd - something seems to have stopped working there:

https://github.com/biopython/biopython-wheels/issues/13
https://pypi.org/project/biopython/1.78/#files - has aarch64
https://pypi.org/project/biopython/1.79/#files - has aarch64
