### ISSUE TITLE
bigbed test failures with Numpy 2.0.0b1

### ISSUE THREAD

**Issue by peterjc** [biopython/biopython#4675]
Testing on macOS, with numpy-1.26.4 these work, but break on numpy-2.0.0b1

```
$ pip uninstall scipy matplotlib
...
$ pip install numpy==2.0.0b1
...
$ python test_Align_bigmaf.py
test_reading (__main__.TestAlign_bundle_without_target)
Test parsing bundle_without_target.bb. ... ok
test_writing (__main__.TestAlign_bundle_without_target)
Test writing bundle_without_target.bb. ... ERROR
test_declaration (__main__.TestAlign_declaration) ... ok
test_search_chromosome (__main__.TestAlign_searching) ... ok
test_search_position (__main__.TestAlign_searching) ... ok
test_search_region (__main__.TestAlign_searching) ... ok
test_reading (__main__.TestAlign_ucsc_mm9_chr10)
Test parsing file ucsc_mm9_chr10.bb. ... ok
test_writing (__main__.TestAlign_ucsc_mm9_chr10)
Test writing file ucsc_mm9_chr10.bb. ... ERROR
test_reading (__main__.TestAlign_ucsc_test)
Test reading ucsc_test.bb. ... ok
test_writing (__main__.TestAlign_ucsc_test)
Test writing ucsc_test.bb. ... ERROR

======================================================================
ERROR: test_writing (__main__.TestAlign_bundle_without_target)
Test writing bundle_without_target.bb.
----------------------------------------------------------------------
Traceback (most recent call last):
...
  File "/Users/xxx/mambaforge/lib/python3.10/site-packages/Bio/Align/bigbed.py", line 453, in _write_zoom_levels
    if start + doubleReductionSize < summary.end:
OverflowError: Python integer -9223372036854775807 out of bounds for int32

======================================================================
ERROR: test_writing (__main__.TestAlign_ucsc_mm9_chr10)
Test writing file ucsc_mm9_chr10.bb.
----------------------------------------------------------------------
Traceback (most recent call last):
...
  File "/Users/xxx/mambaforge/lib/python3.10/site-packages/Bio/Align/bigbed.py", line 453, in _write_zoom_levels
    if start + doubleReductionSize < summary.end:
OverflowError: Python integer -9223372036854775807 out of bounds for int32

======================================================================
ERROR: test_writing (__main__.TestAlign_ucsc_test)
Test writing ucsc_test.bb.
----------------------------------------------------------------------
Traceback (most recent call last):
...
  File "/Users/xxx/mambaforge/lib/python3.10/site-packages/Bio/Align/bigbed.py", line 453, in _write_zoom_levels
    if start + doubleReductionSize < summary.end:
OverflowError: Python integer -9223372036854775807 out of bounds for int32

----------------------------------------------------------------------
Ran 10 tests in 0.285s

FAILED (errors=3)
```

(Separately there are also failures from scipy but we don't yet have a numpy 2.0.0 compatible scipy to test with)

There are also lots of doctest failures in Bio.Align and Bio.phenotype due to repr changes, e.g. 33 vs np.int64(33) but I think we can best tackle along side setting a minimum dependency on numpy 2.0.0?

**Comment by peterjc** [comment]
Filed #4676 for the doctest breakage due to NEP51

**Comment by peterjc** [comment]
Note to self, we can also test with SciPy 1.13.0rc1 which has numpy 2 support.

**Comment by peterjc** [comment]
```
$ python test_Tutorial.py
Running Tutorial doctests...
**********************************************************************
...
**********************************************************************
12 items had failures:
   7 of 235 in __main__.TutorialDocTestHolder.doctest_test_chapter_align_line_00045
   1 of  19 in __main__.TutorialDocTestHolder.doctest_test_chapter_align_line_02158
   1 of  19 in __main__.TutorialDocTestHolder.doctest_test_chapter_align_line_02296
   1 of  13 in __main__.TutorialDocTestHolder.doctest_test_chapter_align_line_02757
   7 of 145 in __main__.TutorialDocTestHolder.doctest_test_chapter_motifs_line_00035
   1 of  26 in __main__.TutorialDocTestHolder.doctest_test_chapter_msa_line_01438
   1 of  64 in __main__.TutorialDocTestHolder.doctest_test_chapter_pairwise_line_00023
   1 of  28 in __main__.TutorialDocTestHolder.doctest_test_chapter_pairwise_line_00379
   1 of  13 in __main__.TutorialDocTestHolder.doctest_test_chapter_pairwise_line_00928
   1 of  28 in __main__.TutorialDocTestHolder.doctest_test_chapter_pairwise_line_01243
   2 of  55 in __main__.TutorialDocTestHolder.doctest_test_chapter_pdb_line_01093
   3 of   9 in __main__.TutorialDocTestHolder.doctest_test_chapter_phenotype_line_00126
***Test Failed*** 27 failures.
Traceback (most recent call last):
  File "/Users/xxx/repositories/biopython/Tests/test_Tutorial.py", line 309, in <module>
    raise RuntimeError("%i/%i tests failed" % tests)
RuntimeError: 27/2544 tests failed
```

**Comment by peterjc** [comment]
Confirming this is fixed now.
