### ISSUE TITLE
Update doctests for numpy 2.0.0 scaler repr changes

### ISSUE THREAD

**Issue by peterjc** [biopython/biopython#4676]
See https://numpy.org/neps/nep-0051-scalar-representation.html - for example this:

```pycon
>>> np.float32(3.0)
3.0
```

becomes:

```pycon
>>> np.float32(3.0)
np.float32(3.0)
```

As per the NEP, this is expected to require documentation updates in libraries using numpy - like Biopython. Out of practicality we will probably do this alongside setting a minimum dependency of numpy 2.0.0

**Comment by peterjc** [comment]
```
$ python test_Tutorial.py
Running Tutorial doctests...
**********************************************************************
...
**********************************************************************
12 items had failures:
   7 of 235 in __main__.TutorialDocTestHolder.doctest_test_chapter_align_line_00045
   1 of  19 in __main__.TutorialDocTestHolder.doctest_test_chapter_align_line_02158
   1 of  19 in __main__.TutorialDocTestHolder.doctest_test_chapter_align_line_02296
   1 of  13 in __main__.TutorialDocTestHolder.doctest_test_chapter_align_line_02757
   7 of 145 in __main__.TutorialDocTestHolder.doctest_test_chapter_motifs_line_00035
   1 of  26 in __main__.TutorialDocTestHolder.doctest_test_chapter_msa_line_01438
   1 of  64 in __main__.TutorialDocTestHolder.doctest_test_chapter_pairwise_line_00023
   1 of  28 in __main__.TutorialDocTestHolder.doctest_test_chapter_pairwise_line_00379
   1 of  13 in __main__.TutorialDocTestHolder.doctest_test_chapter_pairwise_line_00928
   1 of  28 in __main__.TutorialDocTestHolder.doctest_test_chapter_pairwise_line_01243
   2 of  55 in __main__.TutorialDocTestHolder.doctest_test_chapter_pdb_line_01093
   3 of   9 in __main__.TutorialDocTestHolder.doctest_test_chapter_phenotype_line_00126
***Test Failed*** 27 failures.
Traceback (most recent call last):
  File "/Users/xxx/repositories/biopython/Tests/test_Tutorial.py", line 309, in <module>
    raise RuntimeError("%i/%i tests failed" % tests)
RuntimeError: 27/2544 tests failed
```

The seven MSA ones would be fixed by #4677.

Some of the others like the PDB angle function might be changed to return the Python float rather than a numpy float... but not sure this is the best idea.

**Comment by peterjc** [comment]
We're making good progress:

```
$ python test_Tutorial.py
Running Tutorial doctests...
**********************************************************************
...
**********************************************************************
5 items had failures:
   7 of 145 in __main__.TutorialDocTestHolder.doctest_test_chapter_motifs_line_00035
   1 of  26 in __main__.TutorialDocTestHolder.doctest_test_chapter_msa_line_01438
   1 of  28 in __main__.TutorialDocTestHolder.doctest_test_chapter_pairwise_line_01243
   2 of  55 in __main__.TutorialDocTestHolder.doctest_test_chapter_pdb_line_01093
   3 of   9 in __main__.TutorialDocTestHolder.doctest_test_chapter_phenotype_line_00126
***Test Failed*** 14 failures.
Traceback (most recent call last):
  File "/Users/pc40583/repositories/biopython/Tests/test_Tutorial.py", line 309, in <module>
    raise RuntimeError("%i/%i tests failed" % tests)
RuntimeError: 14/2544 tests failed
```

**Comment by peterjc** [comment]
@mgalardini do you have any views on how the Biopython phenotype module should handle the numpy scalar repr changes? e.g. Should we just update the doctests for numpy 2 onwards, or are you comfortable changing the code to cast to the Python float?

In addition to the tutorial test failures, running the doctests too there is currently only one file failing, ``Bio/phenotype/phen_micro.py``:

```
======================================================================
FAIL: WellRecord (Bio.phenotype.phen_micro)
Doctest: Bio.phenotype.phen_micro.WellRecord
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/pc40583/mambaforge/lib/python3.10/doctest.py", line 2221, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for Bio.phenotype.phen_micro.WellRecord
  File "/Users/pc40583/repositories/biopython/Bio/phenotype/phen_micro.py", line 580, in WellRecord

----------------------------------------------------------------------
File "/Users/pc40583/repositories/biopython/Bio/phenotype/phen_micro.py", line 597, in Bio.phenotype.phen_micro.WellRecord
Failed example:
    well[1]
Expected:
    16.0
Got:
    np.float64(16.0)
----------------------------------------------------------------------
File "/Users/pc40583/repositories/biopython/Bio/phenotype/phen_micro.py", line 599, in Bio.phenotype.phen_micro.WellRecord
Failed example:
    well[1:5]
Expected:
    [16.0, 20.0, 18.0, 15.0]
Got:
    [np.float64(16.0), np.float64(20.0), np.float64(18.0), np.float64(15.0)]
----------------------------------------------------------------------
File "/Users/pc40583/repositories/biopython/Bio/phenotype/phen_micro.py", line 601, in Bio.phenotype.phen_micro.WellRecord
Failed example:
    well[1:5:0.5]
Expected:
    [16.0, 19.0, 20.0, 18.0, 18.0, 18.0, 15.0, 18.0]
Got:
    [np.float64(16.0), np.float64(19.0), np.float64(20.0), np.float64(18.0), np.float64(18.0), np.float64(18.0), np.float64(15.0), np.float64(18.0)]
----------------------------------------------------------------------
File "/Users/pc40583/repositories/biopython/Bio/phenotype/phen_micro.py", line 608, in Bio.phenotype.phen_micro.WellRecord
Failed example:
    well[1.3]
Expected:
    19.0
Got:
    np.float64(19.0)
----------------------------------------------------------------------
File "/Users/pc40583/repositories/biopython/Bio/phenotype/phen_micro.py", line 610, in Bio.phenotype.phen_micro.WellRecord
Failed example:
    well[1250]
Expected:
    nan
Got:
    np.float64(nan)
```

**Comment by peterjc** [comment]
Numpy 2.0.0rc1 is out https://github.com/numpy/numpy/issues/24300#issuecomment-2030603395 with recommendations about dependency pinning

**Comment by peterjc** [comment]
PR #4691 adds some ``float(...)`` casting to fix the PDB and Phenotype doctests in the Tutorial under numpy 2.0.0rc1

**Comment by peterjc** [comment]
Progress:

```
$ python test_Tutorial.py
Running Tutorial doctests...
**********************************************************************
...
**********************************************************************
4 items had failures:
   2 of  10 in __main__.TutorialDocTestHolder.doctest_test_chapter_entrez_line_01810
   7 of 145 in __main__.TutorialDocTestHolder.doctest_test_chapter_motifs_line_00035
   1 of  26 in __main__.TutorialDocTestHolder.doctest_test_chapter_msa_line_01438
   1 of  28 in __main__.TutorialDocTestHolder.doctest_test_chapter_pairwise_line_01243
***Test Failed*** 11 failures.
Traceback (most recent call last):
  File "/Users/pc40583/repositories/biopython/Tests/test_Tutorial.py", line 309, in <module>
    raise RuntimeError("%i/%i tests failed" % tests)
RuntimeError: 11/2548 tests failed
```

**Comment by peterjc** [comment]
Assuming #4700 is merged too, there is just one class of errors left - the motifs class and ``m.counts[...]`` giving floats, lists of floats, or tuples of floats:

```
$ python test_Tutorial.py --offline
Skipping tests needing the following:
 - internet
Running Tutorial doctests...
**********************************************************************
File "/Users/pc40583/repositories/biopython/Tests/test_Tutorial.py", line 278, in __main__.TutorialDocTestHolder.doctest_test_chapter_motifs_line_00035
Failed example:
    m.counts["A"]
Expected:
    [3.0, 7.0, 0.0, 2.0, 1.0]
Got:
    [np.float64(3.0), np.float64(7.0), np.float64(0.0), np.float64(2.0), np.float64(1.0)]
**********************************************************************
File "/Users/pc40583/repositories/biopython/Tests/test_Tutorial.py", line 280, in __main__.TutorialDocTestHolder.doctest_test_chapter_motifs_line_00035
Failed example:
    m.counts["T", 0]
Expected:
    4.0
Got:
    np.float64(4.0)
**********************************************************************
File "/Users/pc40583/repositories/biopython/Tests/test_Tutorial.py", line 282, in __main__.TutorialDocTestHolder.doctest_test_chapter_motifs_line_00035
Failed example:
    m.counts["T", 2]
Expected:
    2.0
Got:
    np.float64(2.0)
**********************************************************************
File "/Users/pc40583/repositories/biopython/Tests/test_Tutorial.py", line 284, in __main__.TutorialDocTestHolder.doctest_test_chapter_motifs_line_00035
Failed example:
    m.counts["T", 3]
Expected:
    0.0
Got:
    np.float64(0.0)
**********************************************************************
File "/Users/pc40583/repositories/biopython/Tests/test_Tutorial.py", line 288, in __main__.TutorialDocTestHolder.doctest_test_chapter_motifs_line_00035
Failed example:
    m.counts["A", :]
Expected:
    (3.0, 7.0, 0.0, 2.0, 1.0)
Got:
    (np.float64(3.0), np.float64(7.0), np.float64(0.0), np.float64(2.0), np.float64(1.0))
**********************************************************************
File "/Users/pc40583/repositories/biopython/Tests/test_Tutorial.py", line 290, in __main__.TutorialDocTestHolder.doctest_test_chapter_motifs_line_00035
Failed example:
    m.counts[0, :]
Expected:
    (3.0, 7.0, 0.0, 2.0, 1.0)
Got:
    (np.float64(3.0), np.float64(7.0), np.float64(0.0), np.float64(2.0), np.float64(1.0))
**********************************************************************
1 items had failures:
   6 of 145 in __main__.TutorialDocTestHolder.doctest_test_chapter_motifs_line_00035
***Test Failed*** 6 failures.
Traceback (most recent call last):
  File "/Users/pc40583/repositories/biopython/Tests/test_Tutorial.py", line 309, in <module>
    raise RuntimeError("%i/%i tests failed" % tests)
RuntimeError: 6/2378 tests failed
```

We can probably "fix" this explicit casting, e.g. this solves most of them:

```
$ git diff
diff --git a/Bio/motifs/matrix.py b/Bio/motifs/matrix.py
index c04ecfb66..d14188517 100644
--- a/Bio/motifs/matrix.py
+++ b/Bio/motifs/matrix.py
@@ -81,10 +81,10 @@ class GenericPositionMatrix(dict):
                 else:
                     raise KeyError("Cannot understand key %s" % key2)
                 if dim1 == 1 and dim2 == 1:
-                    return dict.__getitem__(self, letter1)[index2]
+                    return float(dict.__getitem__(self, letter1)[index2])
                 elif dim1 == 1 and dim2 == 2:
                     values = dict.__getitem__(self, letter1)
-                    return tuple(values[index2] for index2 in indices2)
+                    return tuple(float(values[index2]) for index2 in indices2)
                 elif dim1 == 2 and dim2 == 1:
                     d = {}
                     for letter1 in letters1:
```

Or this solves all the tutorial doctest failures by casting when saving the (numpy) float into a Python float when stored within the position matrix class:

```
$ git diff
diff --git a/Bio/motifs/matrix.py b/Bio/motifs/matrix.py
index c04ecfb66..d28c98203 100644
--- a/Bio/motifs/matrix.py
+++ b/Bio/motifs/matrix.py
@@ -32,7 +32,7 @@ class GenericPositionMatrix(dict):
                 self.length = len(values[letter])
             elif self.length != len(values[letter]):
                 raise Exception("data has inconsistent lengths")
-            self[letter] = list(values[letter])
+            self[letter] = [float(_) for _ in values[letter]]
         self.alphabet = alphabet
 
     def __str__(self):
```

I'll leave this to you @mdehoon - there may be a neater solution?

**Comment by peterjc** [comment]
I have been testing locally on macOS with Biopython built under numpy 1.26, and again after updating to numpy 2.0.0rc2 *without* rebuilding Biopython.

This seems to work - presumably as we're not using the NumPy C API directly (only the buffer protocol), we're only affected by any NumPy Python API changes.

i.e. I believe we can leave our build system https://github.com/biopython/biopython-wheels as it is, and our wheels should work with any recent NumPy v1 or the new NumPy v2. And further more the pinning in https://github.com/biopython/biopython-wheels/blob/master/requirements.txt is over the top and any recent NumPy ought to be fine?

Does that make sense @mdehoon?

**Comment by seberg** [comment]
> i.e. I believe we can leave our build system https://github.com/biopython/biopython-wheels as it is

That seems right, if things import on NumPy 2 after building with NumPy 1.x, then you are not be using any NumPy C-API.

>  over the top and any recent NumPy ought to be fine?

Seems a bit like you should be able to just delete that file and also make the `install_requires` rather a NumPy dependency in the setup.py?

**Comment by peterjc** [comment]
Thanks - I can try that, probably legacy setup from when we did use the NumPy C-API explicitly.
