### ISSUE TITLE
The process for specifying Entrez.cache is unclear

### ISSUE THREAD

**Issue by meridiajane** [biopython/biopython#4732]
### Setup

I am reporting a problem with Biopython version, Python version, and operating
system as follows:

3.8.18 (default, Feb  1 2024, 06:08:46) \n[GCC 12.2.0]

CPython
Linux-5.15.146.1-microsoft-standard-WSL2-x86_64-with-glibc2.34

1.83

### Expected behaviour

I'm running Bio's etools as part of a Nextflow pipeline I'm writing on a university's cluster. The system information above may be inaccurate? I'm running Bio as part of a container, and had to check its versions as an interactive session in the container locally rather than in the cluster (was failing to recognize sys.version when using the provided version checking code). 

Etools are trying to write a cache to files that are not my own and are read only, which is causing it to fail. The files its trying to write to are also files that are outside of Nextflow's work directory, which is causing issues as well. I am expecting to be able to direct the Entrez tools cache to a file I specify (as implied by the conversations had in issues 1517 and 918).

I would like to know where I need to look to find how Entrez.cache was exposed, that way I can direct it to a writable directory instead of crashing the pipeline by automatically trying to write to read only directories. Neither of the issues I read prior to this were clear on the issue.

### Actual behaviour

When trying to run before specifying the cache:

```
  Traceback (most recent call last):
    File "/core/globus/cgi/raven/nf-core-raven/bin/focal_filter.py", line 10, in <module>
      from Bio.Entrez import Parser
    File "/usr/local/lib/python3.8/site-packages/Bio/Entrez/Parser.py", line 351, in <module>
      class DataHandler(metaclass=DataHandlerMeta):
    File "/usr/local/lib/python3.8/site-packages/Bio/Entrez/Parser.py", line 320, in __init__
      cls.directory = None  # use default directory for local cache
    File "/usr/local/lib/python3.8/site-packages/Bio/Entrez/Parser.py", line 342, in directory
      os.makedirs(cls.local_dtd_dir, exist_ok=True)
    File "/usr/local/lib/python3.8/os.py", line 213, in makedirs
      makedirs(head, exist_ok=exist_ok)
    File "/usr/local/lib/python3.8/os.py", line 213, in makedirs
      makedirs(head, exist_ok=exist_ok)
    File "/usr/local/lib/python3.8/os.py", line 213, in makedirs
      makedirs(head, exist_ok=exist_ok)
    [Previous line repeated 3 more times]
    File "/usr/local/lib/python3.8/os.py", line 223, in makedirs
      mkdir(name, mode)
  OSError: [Errno 30] Read-only file system: '/home/FCAM'
```

After trying to correct for the error using:

```
from Bio import Entrez
Entrez.Parser.Datahandler.cache = 'entrez_cache'
```
I recieved the error:
```
Traceback (most recent call last):
    File "/core/globus/cgi/raven/nf-core-raven/bin/focal_filter.py", line 9, in <module>
      Entrez.Parser.Datahandler.cache = 'entrez_cache'
  AttributeError: module 'Bio.Entrez' has no attribute 'Parser'
```
When correcting using:

```
from Bio import Entrez
Entrez.cache = 'entrez_cache'
from Bio.Entrez import Parser
```
I received the same error as though I hadn't used any fix (that is, the same read only directory error).

### Steps to reproduce

Can be reproduced by attempting to use entrez on a cluster with limited write access.

**Comment by peterjc** [comment]
Duplicate of #918

**Comment by meridiajane** [comment]
Hey, I have tried the solution you give at the end there 

```
from Bio.Entrez.Parser import DataHandler
DataHandler.local_dtd_dir = "/tmp"
```
And I believe it just tried to make the dir as soon as DataHandler was imported, so when removing that and instead trying

```
from Bio import Entrez
Entrez.Parser.DataHandler.local_dtd_dir = "/tmp"
from Bio.Entrez.Parser import DataHandler
```
It returned the error:
```
Command error:
  Traceback (most recent call last):
    File "/core/globus/cgi/raven/nf-core-raven/bin/focal_filter.py", line 9, in <module>
      Entrez.Parser.DataHandler.local_dtd_dir = "/tmp"
  AttributeError: module 'Bio.Entrez' has no attribute 'Parser'
```

I really appreciate your quick response! But I don't think this is a closed issue/the answer provided there doesn't seem to be satisfactory.

**Comment by peterjc** [comment]
I marked this as a duplicate, not as fixed.

Having your comment on #918 would have been more helpful.
