### ISSUE TITLE
Conversion from  MMCIF to PDB and back to MMCIF give an error

### ISSUE THREAD

**Issue by mms29** [biopython/biopython#4744]
### Setup

I am reporting a problem with Biopython 1.83, Python 3.12.3, and Ubuntu 22.04 as follows:

```python
from Bio import PDB
parser = PDB.MMCIFParser()
struct = parser.get_structure("", "5a00.cif")

io = PDB.PDBIO()
io.set_structure(struct)
io.save("5a00.pdb")

parser = PDB.PDBParser()
struct = parser.get_structure("", "5a00.pdb")


io = PDB.MMCIFIO()
io.set_structure(struct)
io.save("5a00_frompdb.cif")

parser = PDB.MMCIFParser()
struct = parser.get_structure("", "5a00_frompdb.cif")

```

(*Please copy and run the above in your Python, and copy-and-paste the output*)

### Expected behaviour

Going from MMCIF to PDB and back to MMCIF without problems

### Actual behaviour

The last line give the following error :
```
Traceback (most recent call last):
  File "/home/AD/vuillemr/miniconda/envs/imp/lib/python3.12/site-packages/IPython/core/interactiveshell.py", line 3577, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-35-a0128731b6f4>", line 2, in <module>
    full_structure = parser.get_structure("", "5a00_frompdb.cif")
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/AD/vuillemr/miniconda/envs/imp/lib/python3.12/site-packages/Bio/PDB/MMCIFParser.py", line 74, in get_structure
    self._build_structure(structure_id)
  File "/home/AD/vuillemr/miniconda/envs/imp/lib/python3.12/site-packages/Bio/PDB/MMCIFParser.py", line 145, in _build_structure
    atom_serial_list = mmcif_dict["_atom_site.id"]
                       ~~~~~~~~~~^^^^^^^^^^^^^^^^^
KeyError: '_atom_site.id'
```

**Comment by JoaoRodrigues** [comment]
Thanks for reporting this. I can tell what the problem is. Because you parse the structure with `struct = parser.get_structure("", "5a00.pdb")`, `structure.id` is set to an empty string (the first argument there). Then in `mmcifio.py` we check if the that field is empty to populate the initial `data_` line on the mmcif file and if so, we don't write it. We should always write it, even if it's empty, otherwise we trip the `MMCIF2Dict` parsing of the file.

So, for the short term, just provide an id to your structure `struct = parser.get_structure("5a00", "5a00.pdb")` and this should work.

**Comment by JoaoRodrigues** [comment]
@mms29 , could you try pulling the newest version of biopython (git) and retrying your example? #4747 should have fixed this issue.
