### ISSUE TITLE
scipy 1.14.0 breaks Bio.phenotype

### ISSUE THREAD

**Issue by peterjc** [biopython/biopython#4758]
Spotted via a regression on the master branch. See https://docs.scipy.org/doc/scipy/release/1.14.0-notes.html which says scipy 1.14.0 (released 15 June 2024) removed deprecated function ``scipy.integrate.trapz`` in favour of ``trapezoid``.

This requires updating ``Bio.phenotype`` but also I would have expected the test to have been skipped rather than failed:

```
======================================================================
ERROR: test_WellRecord (test_phenotype_fit.TestPhenoMicro.test_WellRecord)
Test basic functionalities of WellRecord objects.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/Bio/phenotype/pm_fitting.py", line 27, in <module>
    from scipy.integrate import trapz
Skipping any tests requiring internet access
Python version: 3.11.9 (main, Jun 20 2024, 16:02:53) [GCC 11.4.0]
Operating system: posix linux
ImportError: cannot import name 'trapz' from 'scipy.integrate' (/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/scipy/integrate/__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/biopython/biopython/Tests/test_phenotype_fit.py", line 63, in test_WellRecord
    w.fit()
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/Bio/phenotype/phen_micro.py", line 882, in fit
    from .pm_fitting import fit, get_area
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/Bio/phenotype/pm_fitting.py", line 31, in <module>
    raise MissingPythonDependencyError("Install scipy to extract curve parameters.")
Bio.MissingPythonDependencyError: Install scipy to extract curve parameters.

----------------------------------------------------------------------
```

**Comment by peterjc** [comment]
New function name looks to have been added in scipy 1.12.0 https://docs.scipy.org/doc/scipy/release/1.12.0-notes.html and is just a name change, so an easy fix.
