### ISSUE TITLE
`assert` statements performed non-idempotent operations

### ISSUE THREAD

**Issue by CNSeniorious000** [biopython/biopython#4796]
### Setup

I am reporting a problem with Biopython version, Python version, and operating
system as follows:

```python
import sys; print(sys.version)
import platform; print(platform.python_implementation()); print(platform.platform())
import Bio; print(Bio.__version__)
```

(*Please copy and run the above in your Python, and copy-and-paste the output*)

```
3.12.1 (main, Aug  8 2024, 18:45:38) [GCC 9.4.0]
CPython
Linux-6.5.0-1022-azure-x86_64-with-glibc2.31
1.84
```

### Expected behaviour

No output

### Actual behaviour

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "./.venv/lib/python3.12/site-packages/pymsaviz/__init__.py", line 6, in <module>
    from pymsaviz.msaviz import MsaViz
  File "./.venv/lib/python3.12/site-packages/pymsaviz/msaviz.py", line 16, in <module>
    from Bio.Phylo.TreeConstruction import DistanceCalculator, DistanceTreeConstructor
  File "./.venv/lib/python3.12/site-packages/Bio/Phylo/TreeConstruction.py", line 364, in <module>
    class DistanceCalculator:
  File "./.venv/lib/python3.12/site-packages/Bio/Phylo/TreeConstruction.py", line 465, in DistanceCalculator
    matrix = substitution_matrices.load(name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "./.venv/lib/python3.12/site-packages/Bio/Align/substitution_matrices/__init__.py", line 518, in load
    matrix = read(path)
             ^^^^^^^^^^
  File "./.venv/lib/python3.12/site-packages/Bio/Align/substitution_matrices/__init__.py", line 494, in read
    matrix[letter1, letter2] = float(word)
                               ^^^^^^^^^^^
ValueError: could not convert string to float: 'A'
```

### Steps to reproduce

python -O -c "import pymsaviz"

**Comment by CNSeniorious000** [comment]
The problem locate here.

https://github.com/biopython/biopython/blob/42e9dfdb02d9e6e85e191a9d68710aa1c4ed55aa/Bio/Align/substitution_matrices/__init__.py#L492

I am happy to raise a PR because this bug is very annoying.

**Comment by mdehoon** [comment]
Thank you. Yes, a PR is welcome.
