### ISSUE TITLE
Entrez returns unhelpful error messages.

### ISSUE THREAD

**Issue by erasche** [biopython/biopython#524]
BioPython responds with a traceback and the eventual error:

```
Traceback (most recent call last):
  File "efetch.py", line 37, in <module>
    c.fetch(args.db, whole=args.whole, **payload)
   ...
  File "/usr/local/lib/python2.7/dist-packages/Bio/Entrez/__init__.py", line 153, in efetch
    return _open(cgi, variables, post)
  File "/usr/local/lib/python2.7/dist-packages/Bio/Entrez/__init__.py", line 470, in _open
    raise exception
urllib2.HTTPError: HTTP Error 400: Bad Request
```

whereas BioPerl responds with the entire HTTP response (ugly) including the HTTP response's body (useful!)

```
------------- EXCEPTION: Bio::Root::Exception -------------
MSG: WebDBSeqI Request Error:
HTTP/1.1 400 Bad Request
Cache-Control: private
Connection: close
Date: Mon, 20 Apr 2015 17:18:26 GMT
Server: Apache
Content-Type: text/plain; charset=UTF-8
Access-Control-Allow-Origin: *
Client-Date: Mon, 20 Apr 2015 17:18:27 GMT
Client-Peer: 130.14.29.110:80
Client-Response-Num: 1
Client-Transfer-Encoding: chunked
NCBI-SID: 08DD311753534E21_0133SID
Set-Cookie: ncbi_sid=08DD311753534E21_0133SID; domain=.nih.gov; path=/; expires=Wed, 20 Apr 2016 17:18:26 GMT
X-UA-Compatible: IE=Edge

ID list is empty! In it there are neither IDs nor accessions.

STACK: Error::throw
STACK: Bio::Root::Root::throw /usr/local/share/perl/5.18.2/Bio/Root/Root.pm:486
STACK: Bio::DB::WebDBSeqI::_request /usr/local/share/perl/5.18.2/Bio/DB/WebDBSeqI.pm:698
STACK: Bio::DB::WebDBSeqI::get_seq_stream /usr/local/share/perl/5.18.2/Bio/DB/WebDBSeqI.pm:485
STACK: Bio::DB::NCBIHelper::get_Stream_by_acc /usr/local/share/perl/5.18.2/Bio/DB/NCBIHelper.pm:502
STACK: /usr/local/bin/cpt_batch_genbank_loader.pl:99
-----------------------------------------------------------
```

**Comment by peterjc** [comment]
This is core Python library behaviour - you should be able to access the response text from the exception, see e.g. http://stackoverflow.com/questions/2233687/overriding-urllib2-httperror-and-reading-response-html-anyway

(I'd make this into an example but you left out the Entrez call triggering the exception)

**Comment by erasche** [comment]
Great, thanks, you're right of course, please close this.
20. apr. 2015 14.07 skrev "Peter Cock" <notifications@github.com>:

**Comment by peterjc** [comment]
No problem. Maybe we need to add an example of this to the documentation...
