### ISSUE TITLE
max_o not always defined in Bio.motifs.matrix.dist_pearson

### ISSUE THREAD

**Issue by ghuls** [biopython/biopython#555]
```python
print motif.pwm.log_odds()
print repr(motif.pwm.log_odds())
print motif.pwm.log_odds().dist_pearson(motif.pwm.log_odds())
```

```python
        0      1      2      3      4      5      6      7      8      9     10     11
A:   -inf   -inf   -inf   -inf   -inf   -inf   -inf   -inf   -inf   -inf   -inf   0.42
C:   -inf   2.00   -inf   1.00   2.00   1.00   -inf   2.00   1.00   -inf   1.00   0.42
G:   2.00   -inf   -inf   1.00   -inf   -inf   1.00   -inf   -inf   2.00   -inf   -inf
T:   -inf   -inf   2.00   -inf   -inf   1.00   1.00   -inf   1.00   -inf   1.00   0.42

{'A': [-inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, 0.4150374992788437], 'C': [-inf, 2.0, -inf, 1.0, 2.0, 1.0, -inf, 2.0, 1.0, -inf, 1.0, 0.4150374992788437], 'T': [-inf, -inf, 2.0, -inf, -inf, 1.0, 1.0, -inf, 1.0, -inf, 1.0, 0.4150374992788437], 'G': [2.0, -inf, -inf, 1.0, -inf, -inf, 1.0, -inf, -inf, 2.0, -inf, -inf]}

Traceback (most recent call last):
  File "get_redundant_motifs.py", line 50, in <module>
    read_motifs()
  File "get_redundant_motifs.py", line 43, in read_motifs
    print motif.pwm.log_odds().dist_pearson(motif.pwm.log_odds())
  File "/home/ghuls/virtualenv/biopython/local/lib/python2.7/site-packages/Bio/motifs/matrix.py", line 516, in dist_pearson
    return 1 - max_p, max_o
UnboundLocalError: local variable 'max_o' referenced before assignment
```

max_o is not always defined in dist_pearson:
```python
def dist_pearson(self, other):
        """Return the similarity score based on pearson correlation for the given motif against self.

        We use the Pearson's correlation of the respective probabilities.
        """
        if self.alphabet != other.alphabet:
            raise ValueError("Cannot compare motifs with different alphabets")

        max_p = -2
        for offset in range(-self.length + 1, other.length):
            if offset < 0:
                p = self.dist_pearson_at(other, -offset)
            else:  # offset>=0
                p = other.dist_pearson_at(self, offset)
            if max_p < p:
                max_p = p
                max_o = -offset
        return 1 - max_p, max_o
```

**Comment by peterjc** [comment]
Can you say what ``max_o`` should be in this situation? e.g. Should we default to ``max_o = 0``?

**Comment by ghuls** [comment]
I have no clue about what the default value should be.

Do you know what the method is supposed to do?

I expected that I could use this method would allow me to compare 2 matrices to see if they are similar.

I tried it by giving the same matrix for self and other, but did not get the expected result.

Here is the output of another matrix than the one above.
```python
        0      1      2      3      4      5      6      7      8      9     10     11     12     13
A:   0.40  -1.31   0.07   -inf  -1.31  -0.04   1.68  -0.94  -2.34  -0.07  -3.07  -0.18   0.49  -0.40
C:  -0.25   0.73   0.07  -3.06  -2.31  -2.63  -2.64  -0.64  -2.34  -1.34   1.66   0.16   0.06   0.40
G:   0.40   0.62   0.07  -0.40  -1.31  -0.46   -inf  -3.64   1.47   1.17  -0.75   0.31   0.06   0.06
T:  -0.94  -1.31  -0.24   1.64   1.58   1.10  -0.64   1.46  -0.27  -1.34  -3.07  -0.40  -0.94  -0.18

{'A': [0.40053792958372886, -1.3074285251922473, 0.07108309806148269, -inf, -1.3074285251922473, -0.044394119358453395, 1.6780719051126378, -0.9434164716336324, -2.3362833878644325, -0.07324898203063845, -3.073248982030639, -0.18442457113742744, 0.4854268271702417, -0.3959286763311392], 'C': [-0.2515387669959645, 0.7281953845384741, 0.07108309806148269, -3.0588936890535687, -2.3074285251922473, -2.6293566200796095, -2.643856189774725, -0.6438561897747247, -2.3362833878644325, -1.3362833878644322, 1.6637166121355675, 0.16349873228287956, 0.056583528366367514, 0.40053792958372886], 'T': [-0.9434164716336324, -1.3074285251922473, -0.2370391973008493, 1.641546029087524, 1.5800967455493404, 1.0985638344835895, -0.6438561897747247, 1.464668267003444, -0.2658940599730345, -1.3362833878644322, -3.073248982030639, -0.3959286763311392, -0.9434164716336324, -0.18442457113742744], 'G': [0.40053792958372886, 0.6185708933639757, 0.07108309806148269, -0.3959286763311392, -1.3074285251922473, -0.45943161863729726, -inf, -3.6438561897747253, 1.4710715341931715, 1.174678531412947, -0.7513208871432763, 0.3103401206121505, 0.056583528366367514, 0.056583528366367514]}

(0.24565151474678715, 12)
```
I expected some nice round numbers as output as both matrices are the same.

**Comment by peterjc** [comment]
@mdehoon, @barwil - can you look at this please?

**Comment by mdehoon** [comment]
I guess the problem is that the log-odds matrix contains infinities, and that therefore the pearson correlation is nonsensical. @ghuls Have a look at what is happening in dist_pearson_at for your example, and then think about what the right answer should be if the log-odds matrix contains infinities. It may just be that there is no reasonable answer in that case, and that you should use the spearman correlation instead.
