### ISSUE TITLE
Genepop parsing error

### ISSUE THREAD

**Issue by StuntsPT** [biopython/biopython#582]
Currently, when using the example stated in the [wiki](http://biopython.org/wiki/PopGen_Genepop) for controlling Genpop, at least one of the example fails:

`loci_map = ctrl.test_hw_pop(1, "excess")`

The error is the following:

``` python
Traceback (most recent call last):
  File "BioGenepop.py", line 50, in <module>
    get_exp_obs_het(filehandle, argv[2])
  File "BioGenepop.py", line 34, in get_exp_obs_het
    loci_map = filehandle.test_hw_pop(pop, "excess")
  File "/usr/lib/python3.4/site-packages/Bio/PopGen/GenePop/EasyController.py", line 45, in test_hw_pop
    return next(hw_res)
  File "/usr/lib/python3.4/site-packages/Bio/PopGen/GenePop/Controller.py", line 164, in __next__
    return self.func(self)
  File "/usr/lib/python3.4/site-packages/Bio/PopGen/GenePop/Controller.py", line 266, in hw_func
    return _hw_func(self.stream, False)
  File "/usr/lib/python3.4/site-packages/Bio/PopGen/GenePop/Controller.py", line 130, in _hw_func
    locus, p, se, fis_wc, fis_rh, steps = entry[:-1]
ValueError: need more than 2 values to unpack
```

This is due to a problem in the table parsing, which has a wrong value.
I have patched the issue and will submit a pull request shortly.

**Comment by StuntsPT** [comment]
Just a ping.
It's been almost 1 year now (and I needed the GenPop module again, which reminded me about this issue).
I'm willing do make more changes to the module if necessary. Not sure if this will impact something else.

**Comment by peterjc** [comment]
This is all @tiagoantao's code - if it helps I'm happy to take care of the actual merge if he OKs it.
