### ISSUE TITLE
SearchIO parsing ggsearch36 (from fasta36 suite) output

### ISSUE THREAD

**Issue by krishnaroskin** [biopython/biopython#599]
I found a parser issue when parsing the output of ggsearch36, part of the fasta36 suite of tools. The FastaIO.py seems to work very well with ggsearch36 output but I think it's getting confused by the leading gap characters in the alignment. You wouldn't expect these in a local alignment but ggsearch uses a global alignment, that's what the gg stands for.

I'm using the following invocation (input files are listed below):

```
ggsearch36 -s BL80 -m 10 -p -b =1 query.fasta library.fasta >results
```

I get the following error when parsing the results with SearchIO:

```
/usr/local/lib/python2.7/dist-packages/Bio/SearchIO/__init__.py:211: BiopythonExperimentalWarning: Bio.SearchIO is an experimental submodule which may undergo significant changes prior to its future official release.
  BiopythonExperimentalWarning)
Traceback (most recent call last):
  File "./process_fasta_results.py", line 19, in <module>
    SearchIO.parse('results', 'fasta-m10')):
  File "/usr/local/lib/python2.7/dist-packages/Bio/SearchIO/__init__.py", line 316, in parse
    for qresult in generator:
  File "/usr/local/lib/python2.7/dist-packages/Bio/SearchIO/FastaIO.py", line 275, in __iter__
    for qresult in self._parse_qresult():
  File "/usr/local/lib/python2.7/dist-packages/Bio/SearchIO/FastaIO.py", line 369, in _parse_qresult
    for hit, strand in self._parse_hit(query_id):
  File "/usr/local/lib/python2.7/dist-packages/Bio/SearchIO/FastaIO.py", line 407, in _parse_hit
    _set_hsp_seqs(hsp, parsed_hsp, self._preamble['program'])
  File "/usr/local/lib/python2.7/dist-packages/Bio/SearchIO/FastaIO.py", line 200, in _set_hsp_seqs
    % (len(parsed['query']['seq']), len(parsed['hit']['seq']))
AssertionError: 14 13
```

I took a look at the \_set\_hsp\_seqs function where it sets the sequence in the parsed HSP and it seems like it does a lot of work with start and stop coordinates for reasons that I don't understand. What's the issue with using the alignment/HSP as given by program? Seems like when and/or how to further trim the alignment should be left to the library user.

For my purposes, I changed \_set\_hsp\_seqs to just take pseq['seq'] as is. This caused problems in sp.aln_annotation['similarity'] since ggsearch36 trims al_cons by the number of trailing gaps in the query but not by the number of trailing gaps in the hit. >_< But that was easy to fix.

I'll run some tests when I get home and if that looks good, I can submit a fix.

```
==> library.fasta <==
>Lib0001
ARDTWFGELLFR

==> query.fasta <==
>Query0001
CARCTWEFGDLLYR
```

**Comment by peterjc** [comment]
I don't have this version of the FASTA suite installed right now - could you paste the sample output here to look at?

**Comment by bow** [comment]
+1 ~ Also including the file (or a smaller test case that reproduces the bug) in the test suite would be appreciated :).

**Comment by krishnaroskin** [comment]
Peter, Bow,

I've put all the files at:

https://gist.github.com/krishnaroskin/d5d1bd6b1c1e4783bcef

Took me a second to duplicate the issue because, at first, I wasn't getting the error... because I had fixed it in my repo library. I can already see it's going to be one of those days. :)

-krish
