### ISSUE TITLE
MissingExternalDependencyError not working in run_tests.py on Python 3.5

### ISSUE THREAD

**Issue by peterjc** [biopython/biopython#612]
As noted on #601 (Python 3.5.0rc2 under Windows 8.1) and confirmed with Python 3.5.0 on Mac and Linux, our mechanism for skipping tests with missing dependencies is failing. e.g.

```
$ python3.5 run_tests.py test_KGML_graphics.py
Python version: 3.5.0 (default, Sep 14 2015, 09:37:32) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-11)]
Operating system: posix linux
test_KGML_graphics ... FAIL
======================================================================
ERROR: test_KGML_graphics (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_KGML_graphics
Traceback (most recent call last):
  File "/home_local/buildslave/repositories/biopython/build/lib.linux-x86_64-3.5/Bio/Graphics/__init__.py", line 11, in <module>
    import reportlab as r
ImportError: No module named 'reportlab'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home_local/buildslave/lib/python3.5/unittest/loader.py", line 153, in loadTestsFromName
    module = __import__(module_name)
  File "/home_local/buildslave/repositories/biopython/Tests/test_KGML_graphics.py", line 16, in <module>
    from Bio.Graphics.ColorSpiral import ColorSpiral
  File "/home_local/buildslave/repositories/biopython/build/lib.linux-x86_64-3.5/Bio/Graphics/__init__.py", line 16, in <module>
    "Please install ReportLab if you want "
Bio.MissingPythonDependencyError: Please install ReportLab if you want to use Bio.Graphics. You can find ReportLab at http://www.reportlab.com/software/opensource/


----------------------------------------------------------------------
Ran 1 test in 0.007 seconds

FAILED (failures = 1)
```

For some reason we are not able to catch ``MissingExternalDependencyError`` or its subclass ``MissingPythonDependencyError`` anymore.

**Comment by peterjc** [comment]
Looking over the https://docs.python.org/3.6/whatsnew/3.5.html my guess is this:

*Unittest discovery errors now are exposed in ``TestLoader.errors`` attribute of the TestLoader instance. (Contributed by Robert Collins in issue 19746.)*
https://bugs.python.org/issue19746
