### ISSUE TITLE
Jython 2.7 integer test failures not seen with Jython 2.7b2

### ISSUE THREAD

**Issue by peterjc** [biopython/biopython#632]
Example test output using Jython 2.7b2 under Windows XP http://testing.open-bio.org/biopython/builders/Windows%20XP%20-%20Jython%202.7/builds/457/steps/shell/logs/stdio

```
======================================================================
ERROR: test_NCBITextParser
----------------------------------------------------------------------
Traceback (most recent call last):
  File "run_tests.py", line 408, in runTest
    suite = loader.loadTestsFromName(name)
  File "C:\jython2.7\Lib\unittest\loader.py", line 91, in loadTestsFromName
    module = __import__('.'.join(parts_copy))
  File "C:\jython2.7\Lib\unittest\loader.py", line 91, in loadTestsFromName
    module = __import__('.'.join(parts_copy))
RuntimeException: java.lang.RuntimeException: Method code too large!
======================================================================
ERROR: test_format (test_motifs.MotifTestsBasic)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\repositories\BuildBotBiopython\jython27win\build\Tests\test_motifs.py", line 418, in test_format
    s1 = self.m.format('pfm')
  File "C:\repositories\BuildBotBiopython\jython27win\build\Bio\motifs\__init__.py", line 504, in format
    return jaspar.write(motifs, format)
  File "C:\repositories\BuildBotBiopython\jython27win\build\Bio\motifs\jaspar\__init__.py", line 165, in write
    terms = ["{0:6.2f}".format(value) for value in counts[letter]]
ValueError: Precision not allowed in integer format specifier

----------------------------------------------------------------------
```

The `RuntimeException: java.lang.RuntimeException: Method code too large!` problem is an occasional Jython pain point - in the past refactoring has been enough to side step this.

The format bug was fixed in Jython 2.7 (final) but that introduced some regressions. This is the test on the same commit of Biopython:

http://testing.open-bio.org/biopython/builders/Windows%20XP%20-%20Jython%202.7/builds/458/steps/shell/logs/stdio

```
======================================================================
ERROR: test_NCBITextParser
----------------------------------------------------------------------
Traceback (most recent call last):
  File "run_tests.py", line 408, in runTest
    suite = loader.loadTestsFromName(name)
  File "C:\Jython2.7\Lib\unittest\loader.py", line 91, in loadTestsFromName
    module = __import__('.'.join(parts_copy))
  File "C:\Jython2.7\Lib\unittest\loader.py", line 91, in loadTestsFromName
    module = __import__('.'.join(parts_copy))
RuntimeException: java.lang.RuntimeException: Method code too large!
======================================================================
FAIL: bgzf (Bio)
Doctest: Bio.bgzf
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Jython2.7\Lib\doctest.py", line 2205, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for Bio.bgzf
  File "C:\repositories\BuildBotBiopython\jython27win\build\Bio\bgzf.py", line 6, in bgzf

----------------------------------------------------------------------
File "C:\repositories\BuildBotBiopython\jython27win\build\Bio\bgzf.py", line 130, in Bio.bgzf
Failed example:
    line = handle.readline()
Exception raised:
    Traceback (most recent call last):
      File "C:\Jython2.7\Lib\doctest.py", line 1290, in _DocTestRunner__run
        exec compile(example.source, filename, "single",
      File "<doctest Bio.bgzf[10]>", line 1, in <module>
        line = handle.readline()
      File "C:\Jython2.7\Lib\gzip.py", line 469, in readline
        c = self.read(readsize)
      File "C:\Jython2.7\Lib\gzip.py", line 258, in read
        if not self._read(readsize):
      File "C:\Jython2.7\Lib\gzip.py", line 293, in _read
        self._read_gzip_header()
      File "C:\Jython2.7\Lib\gzip.py", line 205, in _read_gzip_header
        self._read_exact(struct.unpack("<H", self._read_exact(2)))
      File "C:\Jython2.7\Lib\gzip.py", line 185, in _read_exact
        data = self.fileobj.read(n)
    TypeError: integer required
----------------------------------------------------------------------
File "C:\repositories\BuildBotBiopython\jython27win\build\Bio\bgzf.py", line 131, in Bio.bgzf
Failed example:
    assert 80 == handle.tell()
Exception raised:
    Traceback (most recent call last):
      File "C:\Jython2.7\Lib\doctest.py", line 1290, in _DocTestRunner__run
        exec compile(example.source, filename, "single",
      File "<doctest Bio.bgzf[11]>", line 1, in <module>
        assert 80 == handle.tell()
    AssertionError
----------------------------------------------------------------------
File "C:\repositories\BuildBotBiopython\jython27win\build\Bio\bgzf.py", line 132, in Bio.bgzf
Failed example:
    line = handle.readline()
Exception raised:
    Traceback (most recent call last):
      File "C:\Jython2.7\Lib\doctest.py", line 1290, in _DocTestRunner__run
        exec compile(example.source, filename, "single",
      File "<doctest Bio.bgzf[12]>", line 1, in <module>
        line = handle.readline()
      File "C:\Jython2.7\Lib\gzip.py", line 469, in readline
        c = self.read(readsize)
      File "C:\Jython2.7\Lib\gzip.py", line 258, in read
        if not self._read(readsize):
      File "C:\Jython2.7\Lib\gzip.py", line 293, in _read
        self._read_gzip_header()
      File "C:\Jython2.7\Lib\gzip.py", line 197, in _read_gzip_header
        raise IOError, 'Not a gzipped file'
    IOError: Not a gzipped file
----------------------------------------------------------------------
File "C:\repositories\BuildBotBiopython\jython27win\build\Bio\bgzf.py", line 133, in Bio.bgzf
Failed example:
    assert 143 == handle.tell()
Exception raised:
    Traceback (most recent call last):
      File "C:\Jython2.7\Lib\doctest.py", line 1290, in _DocTestRunner__run
        exec compile(example.source, filename, "single",
      File "<doctest Bio.bgzf[13]>", line 1, in <module>
        assert 143 == handle.tell()
    AssertionError
----------------------------------------------------------------------
File "C:\repositories\BuildBotBiopython\jython27win\build\Bio\bgzf.py", line 134, in Bio.bgzf
Failed example:
    data = handle.read(70000)
Exception raised:
    Traceback (most recent call last):
      File "C:\Jython2.7\Lib\doctest.py", line 1290, in _DocTestRunner__run
        exec compile(example.source, filename, "single",
      File "<doctest Bio.bgzf[14]>", line 1, in <module>
        data = handle.read(70000)
      File "C:\Jython2.7\Lib\gzip.py", line 258, in read
        if not self._read(readsize):
      File "C:\Jython2.7\Lib\gzip.py", line 293, in _read
        self._read_gzip_header()
      File "C:\Jython2.7\Lib\gzip.py", line 197, in _read_gzip_header
        raise IOError, 'Not a gzipped file'
    IOError: Not a gzipped file
----------------------------------------------------------------------
File "C:\repositories\BuildBotBiopython\jython27win\build\Bio\bgzf.py", line 135, in Bio.bgzf
Failed example:
    assert 70143 == handle.tell()
Exception raised:
    Traceback (most recent call last):
      File "C:\Jython2.7\Lib\doctest.py", line 1290, in _DocTestRunner__run
        exec compile(example.source, filename, "single",
      File "<doctest Bio.bgzf[15]>", line 1, in <module>
        assert 70143 == handle.tell()
    AssertionError


======================================================================
FAIL: __init__ (Bio.SeqFeature.CompoundLocation)
Doctest: Bio.SeqFeature.CompoundLocation.__init__
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Jython2.7\Lib\doctest.py", line 2205, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for Bio.SeqFeature.CompoundLocation.__init__
  File "C:\repositories\BuildBotBiopython\jython27win\build\Bio\SeqFeature.py", line 967, in __init__

----------------------------------------------------------------------
File "C:\repositories\BuildBotBiopython\jython27win\build\Bio\SeqFeature.py", line 995, in Bio.SeqFeature.CompoundLocation.__init__
Failed example:
    list(f)
Expected:
    [3, 4, 5, 12, 11, 10]
Got:
    [ExactPosition(3), 4, 5, 12, 11, 10]
----------------------------------------------------------------------
File "C:\repositories\BuildBotBiopython\jython27win\build\Bio\SeqFeature.py", line 1002, in Bio.SeqFeature.CompoundLocation.__init__
Failed example:
    min(f)
Expected:
    3
Got:
    ExactPosition(3)
----------------------------------------------------------------------
File "C:\repositories\BuildBotBiopython\jython27win\build\Bio\SeqFeature.py", line 1026, in Bio.SeqFeature.CompoundLocation.__init__
Failed example:
    list(f)
Expected:
    [3, 4, 5, 12, 11, 10]
Got:
    [ExactPosition(3), 4, 5, 12, 11, 10]


======================================================================
FAIL: __iter__ (Bio.SeqFeature.FeatureLocation)
Doctest: Bio.SeqFeature.FeatureLocation.__iter__
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Jython2.7\Lib\doctest.py", line 2205, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for Bio.SeqFeature.FeatureLocation.__iter__
  File "C:\repositories\BuildBotBiopython\jython27win\build\Bio\SeqFeature.py", line 836, in __iter__

----------------------------------------------------------------------
File "C:\repositories\BuildBotBiopython\jython27win\build\Bio\SeqFeature.py", line 844, in Bio.SeqFeature.FeatureLocation.__iter__
Failed example:
    for i in loc: print(i)
Expected:
    5
    6
    7
    8
    9
Got:
    <5
    6
    7
    8
    9
----------------------------------------------------------------------
File "C:\repositories\BuildBotBiopython\jython27win\build\Bio\SeqFeature.py", line 850, in Bio.SeqFeature.FeatureLocation.__iter__
Failed example:
    list(loc)
Expected:
    [5, 6, 7, 8, 9]
Got:
    [BeforePosition(5), 6, 7, 8, 9]


----------------------------------------------------------------------
```

The `SeqFeature` problem appears related to our subclassing of Python's integers (Jython appears to be mixing up the plain integer `5` with an instance `BeforePosition(5)` etc?).

There could also be an integer issue in the bgzf test failures (note the `TypeError`).

This also happens on Mac OS X, and likely on Linux if I could find a machine with a recent enough version of Java to test this with...

**Comment by chris-rands** [comment]
Jython is no longer supported (for some time), I suggest to close this issue and also https://github.com/biopython/biopython/issues/1041

**Comment by peterjc** [comment]
Yes, we should. Thank you.
