### ISSUE TITLE
PyPy3 test failure with _sqlite3.InterfaceError

### ISSUE THREAD

**Issue by peterjc** [biopython/biopython#658]
Recently I've noticed this kind of error from PyPy3 under TravisCI, e.g.

https://travis-ci.org/biopython/biopython/jobs/87728288
https://travis-ci.org/biopython/biopython/jobs/87731411
https://travis-ci.org/biopython/biopython/jobs/88086877
https://travis-ci.org/biopython/biopython/jobs/88347907

```
======================================================================
ERROR: test_SeqIO_loading (common_BioSQL.AutoSeqIOTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/biopython/biopython/Tests/common_BioSQL.py", line 889, in test_SeqIO_loading
    self.check('fasta', 'Fasta/wisteria.nu')
  File "/home/travis/build/biopython/biopython/Tests/common_BioSQL.py", line 858, in check
    compare_record(record, db_rec)
  File "/home/travis/build/biopython/biopython/Tests/seq_tests_common.py", line 275, in compare_record
    compare_sequence(old.seq, new.seq)
  File "/home/travis/build/biopython/biopython/Tests/seq_tests_common.py", line 243, in compare_sequence
    assert expected == str(new[i:j:step])
  File "/home/travis/build/biopython/biopython/BioSQL/BioSeq.py", line 102, in __getitem__
    self.start + j)
  File "/home/travis/build/biopython/biopython/BioSQL/BioSeqDatabase.py", line 499, in get_subseq_as_string
    (start + 1, length, seqid))[0])
  File "/home/travis/build/biopython/biopython/BioSQL/BioSeqDatabase.py", line 473, in execute_one
    self.execute(sql, args or ())
  File "/home/travis/build/biopython/biopython/BioSQL/BioSeqDatabase.py", line 483, in execute
    self.dbutils.execute(self.cursor, sql, args)
  File "/home/travis/build/biopython/biopython/BioSQL/DBUtils.py", line 52, in execute
    cursor.execute(sql.replace("%s", "?"), args or ())
  File "/opt/python/pypy3-2.4.0/lib_pypy/_sqlite3.py", line 915, in wrapper
    return func(self, *args, **kwargs)
  File "/opt/python/pypy3-2.4.0/lib_pypy/_sqlite3.py", line 1084, in execute
    return self.__execute(False, sql, [params])
  File "/opt/python/pypy3-2.4.0/lib_pypy/_sqlite3.py", line 1042, in __execute
    self.__statement._set_params(params)
  File "/opt/python/pypy3-2.4.0/lib_pypy/_sqlite3.py", line 1340, in _set_params
    "probably unsupported type." % i)
_sqlite3.InterfaceError: Error binding parameter 0 - probably unsupported type.
----------------------------------------------------------------------
```

This does not seem to have been triggered by a Biopython change, perhaps the version of PyPy3 or SQLite was updated on TravisCI?

**Comment by peterjc** [comment]
This seems to be stochastic, in that requesting a rebuild for the failed PyPy3 job on TravisCI usually makes the problem go away.

**Comment by peterjc** [comment]
I'm going to close it - I've not seen error this for a long, and have updated PyPy3 several times since this was filed.
