### ISSUE TITLE
KEGG REST API conv limitations

### ISSUE THREAD

**Issue by peterjc** [biopython/biopython#729]
http://www.kegg.jp/kegg/rest/keggapi.html gives the following examples for the ``conv`` function,

* ``/conv/eco/ncbi-geneid`` - conversion from NCBI GeneID to KEGG ID for E. coli genes
* ``/conv/ncbi-geneid/eco`` - opposite direction
* ``/conv/ncbi-proteinid/hsa:10458+ece:Z5100`` - conversion from KEGG ID to NCBI GI
* ``/conv/genes/ncbi-geneid:3113320`` - conversion from NCBI GeneID to KEGG ID when the organism code is not known 

```
>>> from Bio.KEGG.REST import kegg_conv
>>> h = kegg_conv("eco", "ncbi-geneid")  # works, try h.read()
>>> h = kegg_conv("ncbi-geneid", "eco")  # works, try h.read()
```

Those worked, using the first form of the API:

```
http://rest.kegg.jp/conv/<target_db>/<source_db>[/<option>]

(<target_db> <source_db>) = (<kegg_db> <outside_db>) | (<outside_db> <kegg_db>)

For gene identifiers:
<kegg_db> = <org>
<org> = KEGG organism code or T number
<outside_db> = ncbi-proteinid | ncbi-geneid | uniprot

For chemical substance identifiers:
<kegg_db> = drug | compound | glycan
<outside_db> = pubchem | chebi

<option> = turtle | n-triple
```

However, the later two examples fail:

```
>>> h = kegg_conv("ncbi-proteinid", "hsa:10458+ece:Z5100")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/Bio/KEGG/REST.py", line 252, in kegg_conv
    raise Exception("Bad argument target_db or source_db for kegg conv request.")
Exception: Bad argument target_db or source_db for kegg conv request.
>>> h = kegg_conv("ncbi-proteinid", ["hsa:10458", "ece:Z5100"])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/Bio/KEGG/REST.py", line 252, in kegg_conv
    raise Exception("Bad argument target_db or source_db for kegg conv request.")
Exception: Bad argument target_db or source_db for kegg conv request.
>>> h = kegg_conv("genes", "ncbi-geneid:3113320")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/Bio/KEGG/REST.py", line 252, in kegg_conv
    raise Exception("Bad argument target_db or source_db for kegg conv request.")
Exception: Bad argument target_db or source_db for kegg conv request.
```

The Biopython wrapper does not seem to consider the second form of the ``conv`` function,

```
http://rest.kegg.jp/conv/<target_db>/<dbentries>[/<option>]

For gene identifiers:
<dbentries> = database entries involving the following <database>
<database> = <org> | genes | ncbi-proteinid | ncbi-geneid | uniprot
<org> = KEGG organism code or T number

For chemical substance identifiers:
<dbentries> = database entries involving the following <database>
<database> = drug | compound | glycan | pubchem | chebi

<option> = turtle | n-triple
```

**Comment by peterjc** [comment]
Reported on the mailing list by Felix Heeger, see http://lists.open-bio.org/pipermail/biopython/2015-December/015843.html
 
@kevinwuhoo could you look at this for us please?
