### ISSUE TITLE
bug while parsing mmCif files

### ISSUE THREAD

**Issue by ofajardo** [biopython/biopython#775]
Hi, 

I am getting an exception while parsing a bunch of mmcif files. I get the error when using 1.66, and actually I do not get the error when using 1.65.

the error appears when doing:

```
MMCIF_parser = MMCIFParser()
MMCIF_structure = MMCIF_parser.get_structure(pdbid, filename)
```

for example for structures: 4P9S, 4ZHL, 2IGM, 4ZHA, 3N0S

If it is a feature rather than a bug, would it be possible to get something like PERMISSIVE=1 like for the pdb parser, to ignore this?

os: linux and windows, both 64 bit
Python version : 2.7.10 (anaconda)
Biopython version: 1.66
Traceback that occurs (the full error message): when trying to parse 4P9S

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Anaconda\lib\site-packages\Bio\PDB\MMCIFParser.py", line 61, in get_structure
    self._build_structure(structure_id)
  File "C:\Anaconda\lib\site-packages\Bio\PDB\MMCIFParser.py", line 179, in _build_structure
    name, element=element)
  File "C:\Anaconda\lib\site-packages\Bio\PDB\StructureBuilder.py", line 241, in init_atom
    residue.add(self.atom)
  File "C:\Anaconda\lib\site-packages\Bio\PDB\Residue.py", line 80, in add
    "Atom %s defined twice in residue %s" % (atom_id, self))
Bio.PDB.PDBExceptions.PDBConstructionException: Atom PA defined twice in residue <Residue FAD het=H_FAD resseq=901 icode= >
```

**Comment by JoaoRodrigues** [comment]
Thanks for reporting this. The MMCIFParser wasn't correctly initiating new residues when the chain was changing. I'll submit a pull request to fix this shortly.

**Comment by peterjc** [comment]
This is probably fixed now, but ideally we'd like you to confirm this @ofajardo. Are you able to try the changes fro @JoaoRodrigues on #776 which I just merged? i.e. Are you comfortable getting Biopython from GitHub and reinstalling from source? Thanks!

**Comment by ofajardo** [comment]
Hi,

Yes, I will do. I will run my programs first with 1.65 and then with the
new version to be sure. It will take a couple of days to get everything
done. Should I expect other changes compared to 1.65?

2016-02-28 13:51 GMT+01:00 Peter Cock <notifications@github.com>:

**Comment by JoaoRodrigues** [comment]
Thanks @peterjc ! @ofajardo I don't think there were major changes, although 1.65 is over a year old.

**Comment by ofajardo** [comment]
Hi, 

Thanks a lot Joao and Peter for the wornderful and extremely quick support!.

The situation has dramatically improved regarding 1.66 and it is even better than in 1.65! However, it is not 100 % perfect. I have a sample of ~4600 cif files which pdb counterpart are correctly processed by biopython. In 1.66 there were around 650 cif files not processed, as I reported in this ticket, in 1.65 it was 379. Now with the latest code it is only 2 which is excellent! However, I think that it should be 0 failures ... so here I put the two failures for your consideration. The error message is a bit different this time, so we can open a new ticket if you prefer. Do you think it is something fixable? If yes, I would be happy to test again.

**Structure: 4Q96**
 traceback: Traceback (most recent call last):
  File "/apps64/bidev/pdbw/python/PdbWorkflow/PDB_convert_embl.py", line 307, in get_atom_sequence_mmcif
    MMCIF_structure = MMCIF_parser.get_structure(protein_ID, pdb_file_path)
  File "/homebasel/biocomp/fajardoo/python_test_modules/biopython_repo/Bio/PDB/MMCIFParser.py", line 65, in get_structure
    self._build_structure(structure_id)
  File "/homebasel/biocomp/fajardoo/python_test_modules/biopython_repo/Bio/PDB/MMCIFParser.py", line 181, in _build_structure
    structure_builder.init_residue(resname, hetatm_flag, int_resseq, icode)
  File "/homebasel/biocomp/fajardoo/python_test_modules/biopython_repo/Bio/PDB/StructureBuilder.py", line 157, in init_residue
    % (resname, field, resseq, icode))
PDBConstructionException: Blank altlocs in duplicate residue ARG (' ', 55, ' ')

**Structure 4Q94**
 traceback: Traceback (most recent call last):
  File "/apps64/bidev/pdbw/python/PdbWorkflow/PDB_convert_embl.py", line 307, in get_atom_sequence_mmcif
    MMCIF_structure = MMCIF_parser.get_structure(protein_ID, pdb_file_path)
  File "/homebasel/biocomp/fajardoo/python_test_modules/biopython_repo/Bio/PDB/MMCIFParser.py", line 65, in get_structure
    self._build_structure(structure_id)
  File "/homebasel/biocomp/fajardoo/python_test_modules/biopython_repo/Bio/PDB/MMCIFParser.py", line 181, in _build_structure
    structure_builder.init_residue(resname, hetatm_flag, int_resseq, icode)
  File "/homebasel/biocomp/fajardoo/python_test_modules/biopython_repo/Bio/PDB/StructureBuilder.py", line 157, in init_residue
    % (resname, field, resseq, icode))
PDBConstructionException: Blank altlocs in duplicate residue SER (' ', 2, ' ')

**Comment by peterjc** [comment]
Thanks for verifying the fix. Could you file a new issue for the blank altlocs issue?
