### ISSUE TITLE
Bio.Entrez can't parse NCBI bioproject XML

### ISSUE THREAD

**Issue by peterjc** [biopython/biopython#805]
Noted in passing in an answer on http://stackoverflow.com/questions/36069879/how-to-use-bioproject-id-for-exemple-prjna12997-in-biopython/36482743#36482743

```
>>> from Bio import Entrez
>>> Entrez.email = "p.j.a.cock@googlemail.com"
>>> handle = Entrez.efetch(db="bioproject", id="PRJNA12997")
>>> Entrez.read(handle)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "Bio/Entrez/__init__.py", line 447, in read
    record = handler.read(handle)
  File "Bio/Entrez/Parser.py", line 226, in read
    self.parser.ParseFile(handle)
  File "Bio/Entrez/Parser.py", line 361, in startElementHandler
    raise ValidationError(name)
Bio.Entrez.Parser.ValidationError: Failed to find tag 'RecordSet' in the DTD. To skip all tags that are not represented in the DTD, please call Bio.Entrez.read or Bio.Entrez.parse with validate=False.
>>> handle = Entrez.efetch(db="bioproject", id="PRJNA12997")
>>> Entrez.read(handle, validate=False)
''
>>> handle = Entrez.efetch(db="bioproject", id="PRJNA12997")
>>> print(handle.read())
<?xml version="1.0"?>
<RecordSet><DocumentSummary uid="12997">
    <Project>
        <ProjectID>
            <ArchiveID accession="PRJNA12997" archive="NCBI" id="12997"/>
        </ProjectID>
        <ProjectDescr>
            <Name>Acaryochloris marina MBIC11017</Name>
            <Title>A photosynthetic organism with a unique low ratio of chlorophyll a to chlorophyll d</Title>
            <Description>&lt;b&gt;&lt;i&gt;Acaryochloris marina&lt;/i&gt; MBIC11017&lt;/b&gt;. &lt;i&gt;Acaryochloris marina&lt;/i&gt; MBIC11017 was isolated from algae from the coast of the Palau Islands in the western Pacific. This organism will be used for comparative analysis with other photosynthetic microorganisms.</Description>
            <ExternalLink category="Other Databases" label="GOLD">
                <URL>http://genomesonline.org/cgi-bin/GOLD/bin/GOLDCards.cgi?goldstamp=Gc00667</URL>
            </ExternalLink>
            <ExternalLink category="Other Databases" label="GOLD">
                <URL>http://genomesonline.org/cgi-bin/GOLD/bin/GOLDCards.cgi?goldstamp=Gc00667</URL>
            </ExternalLink>
            <ExternalLink category="Related Resources" label="Cyanosite">
                <URL>http://www-cyanosite.bio.purdue.edu/</URL>
            </ExternalLink>
            <ExternalLink category="Related Resources" label="CyanoBase">
                <URL>http://www.kazusa.or.jp/cyano/cyano.html</URL>
            </ExternalLink>
            <ExternalLink category="Related Resources" label="CYORF">
                <URL>http://cyano.genome.jp/</URL>
            </ExternalLink>
            <Publication date="2008-02-07T00:00:00Z" id="18252824" status="ePublished">
                <Reference/>
                <DbType>ePubmed</DbType>
            </Publication>
            <ProjectReleaseDate>2007-10-16T00:00:00Z</ProjectReleaseDate>
            <LocusTagPrefix assembly_id="GCF_000018105" biosample_id="SAMN02604308">AM1</LocusTagPrefix>
        </ProjectDescr>
        <ProjectType>
            <ProjectTypeSubmission>
                <Target capture="eWhole" material="eGenome" sample_scope="eMonoisolate">
                    <Organism species="155978" taxID="329726">
                        <OrganismName>Acaryochloris marina MBIC11017</OrganismName>
                        <Strain>MBIC 11017</Strain>
                        <Supergroup>eBacteria</Supergroup>
                        <BiologicalProperties>
                            <Morphology>
                                <Shape>eCocci</Shape>
                                <Shape>eCocci</Shape>
                            </Morphology>
                            <Environment>
                                <OxygenReq>eAerobic</OxygenReq>
                                <TemperatureRange>eMesophilic</TemperatureRange>
                                <Habitat>eAquatic</Habitat>
                            </Environment>
                            <Phenotype>
                                <Disease>None</Disease>
                            </Phenotype>
                        </BiologicalProperties>
                        <RepliconSet>
                            <Replicon order="1">
                                <Type location="eNuclearProkaryote">eChromosome</Type>
                                <Name/>
                                <Size units="Mb">6.500000</Size>
                            </Replicon>
                            <Replicon order="2">
                                <Type location="eNuclearProkaryote">ePlasmid</Type>
                                <Name>pREB1</Name>
                                <Size units="Mb">0.370000</Size>
                            </Replicon>
                            <Replicon order="11">
                                <Type location="eNuclearProkaryote">ePlasmid</Type>
                                <Name>pREB2</Name>
                                <Size units="Mb">0.360000</Size>
                            </Replicon>
                            <Replicon order="12">
                                <Type location="eNuclearProkaryote">ePlasmid</Type>
                                <Name>pREB3</Name>
                                <Size units="Mb">0.270000</Size>
                            </Replicon>
                            <Replicon order="13">
                                <Type location="eNuclearProkaryote">ePlasmid</Type>
                                <Name>pREB4</Name>
                                <Size units="Mb">0.230000</Size>
                            </Replicon>
                            <Replicon order="14">
                                <Type location="eNuclearProkaryote">ePlasmid</Type>
                                <Name>pREB5</Name>
                                <Size units="Mb">0.180000</Size>
                            </Replicon>
                            <Replicon order="15">
                                <Type location="eNuclearProkaryote">ePlasmid</Type>
                                <Name>pREB6</Name>
                                <Size units="Mb">0.170000</Size>
                            </Replicon>
                            <Replicon order="16">
                                <Type location="eNuclearProkaryote">ePlasmid</Type>
                                <Name>pREB7</Name>
                                <Size units="Mb">0.160000</Size>
                            </Replicon>
                            <Replicon order="17">
                                <Type location="eNuclearProkaryote">ePlasmid</Type>
                                <Name>pREB8</Name>
                                <Size units="Mb">0.120000</Size>
                            </Replicon>
                            <Replicon order="18">
                                <Type location="eNuclearProkaryote">ePlasmid</Type>
                                <Name>pREB9</Name>
                                <Size units="Mb">0.002100</Size>
                            </Replicon>
                            <Count repliconType="eOther">10</Count>
                        </RepliconSet>
                        <GenomeSize units="Kb">8362.100000</GenomeSize>
                    </Organism>
                </Target>
                <Method method_type="eSequencing"/>
                <Objectives>
                    <Data data_type="eAssembly"/>
                </Objectives>
                <ProjectDataTypeSet>
                    <DataType>Genome sequencing and assembly</DataType>
                </ProjectDataTypeSet>
            </ProjectTypeSubmission>
        </ProjectType>
    </Project>
    <Submission submitted="2004-09-07">
        <Description>
            <!-- Submitter information has been removed -->
            <Organization role="owner" type="center">
                <Name abbr="Washington University">Washington University</Name>
                <!-- Contact information has been removed -->
            </Organization>
            <Organization role="participant" type="center" url="http://genomes.tgen.org">
                <Name abbr="TGen Sequencing Center">TGen Sequencing Center</Name>
            </Organization>
            <Access>public</Access>
        </Description>
    </Submission>
</DocumentSummary>

</RecordSet>
```

This is valid XML, but has no reference to a DTD schema, which presumably is why the ``Entrez.read`` parser returns nothing?

There is an XSD schema at ftp://ftp.ncbi.nlm.nih.gov/bioproject/  - found via http://www.ncbi.nlm.nih.gov/books/NBK169438/

Presumably another XML parser would be more useful here, eg ``ElementTree`` from the standard library?

**Comment by mdehoon** [comment]
Bio.Entrez nowadays can use an XSD schema to parse the XML, but since there is no reference to the schema in the XML, the parser has no way to find out which XSD schema to use. Perhaps we should add an option to Entrez.read/parse to explicitly pass the location of the XSD schema if it's not referenced in the XML.

**Comment by peterjc** [comment]
Is this worth leaving this issue open as a potential enhancement, or should we just close it?

**Comment by mdehoon** [comment]
We can keep it open.
