### ISSUE TITLE
pypy3-2.4.0 unit tests failures with missing command line tools

### ISSUE THREAD

**Issue by peterjc** [biopython/biopython#845]
I filed https://bitbucket.org/pypy/pypy/issues/2317/pypy3-subprocesspopen-failing-with for these on-going failures under PyPy3-2.4.0:

```
======================================================================
ERROR: test_ClustalOmega_tool
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\PyPy3-2.4.0-win32\lib-python\3\subprocess.py", line 744, in __init__
    restore_signals, start_new_session)
  File "C:\PyPy3-2.4.0-win32\lib-python\3\subprocess.py", line 981, in _execute_child
    startupinfo)
  File "C:\PyPy3-2.4.0-win32\lib_pypy\_subprocess.py", line 166, in CreateProcess
    raise _WinError()
WindowsError: [Error 0] The operation completed successfully

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run_tests.py", line 420, in runTest
    suite = loader.loadTestsFromName(name)
  File "C:\PyPy3-2.4.0-win32\lib-python\3\unittest\loader.py", line 96, in loadTestsFromName
    module = __import__('.'.join(parts_copy))
  File "c:\repositories\BuildBotBiopython\winpypy3_24\build\Tests\test_ClustalOmega_tool.py", line 26, in <module>
    output = getoutput("clustalo --help")
  File "c:\repositories\BuildBotBiopython\winpypy3_24\build\Bio\_py3k\__init__.py", line 258, in getoutput
    shell=False)
  File "C:\PyPy3-2.4.0-win32\lib-python\3\subprocess.py", line 763, in __init__
    os.close(fd)
TypeError: __int__ returned non-int (type 'NoneType')
======================================================================
ERROR: test_MSAProbs_tool
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\PyPy3-2.4.0-win32\lib-python\3\subprocess.py", line 744, in __init__
    restore_signals, start_new_session)
  File "C:\PyPy3-2.4.0-win32\lib-python\3\subprocess.py", line 981, in _execute_child
    startupinfo)
  File "C:\PyPy3-2.4.0-win32\lib_pypy\_subprocess.py", line 166, in CreateProcess
    raise _WinError()
WindowsError: [Error 0] The operation completed successfully

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run_tests.py", line 420, in runTest
    suite = loader.loadTestsFromName(name)
  File "C:\PyPy3-2.4.0-win32\lib-python\3\unittest\loader.py", line 96, in loadTestsFromName
    module = __import__('.'.join(parts_copy))
  File "c:\repositories\BuildBotBiopython\winpypy3_24\build\Tests\test_MSAProbs_tool.py", line 24, in <module>
   output = getoutput("msaprobs -version")
  File "c:\repositories\BuildBotBiopython\winpypy3_24\build\Bio\_py3k\__init__.py", line 258, in getoutput
    shell=False)
  File "C:\PyPy3-2.4.0-win32\lib-python\3\subprocess.py", line 763, in __init__
    os.close(fd)
TypeError: __int__ returned non-int (type 'NoneType')
======================================================================
ERROR: test_phyml_tool
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\PyPy3-2.4.0-win32\lib-python\3\subprocess.py", line 744, in __init__
    restore_signals, start_new_session)
  File "C:\PyPy3-2.4.0-win32\lib-python\3\subprocess.py", line 981, in _execute_child
    startupinfo)
  File "C:\PyPy3-2.4.0-win32\lib_pypy\_subprocess.py", line 166, in CreateProcess
    raise _WinError()
WindowsError: [Error 0] The operation completed successfully

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run_tests.py", line 420, in runTest
    suite = loader.loadTestsFromName(name)
  File "C:\PyPy3-2.4.0-win32\lib-python\3\unittest\loader.py", line 96, in loadTestsFromName
    module = __import__('.'.join(parts_copy))
  File "c:\repositories\BuildBotBiopython\winpypy3_24\build\Tests\test_phyml_tool.py", line 23, in <module>
    output = getoutput(exe_name + " --version")
  File "c:\repositories\BuildBotBiopython\winpypy3_24\build\Bio\_py3k\__init__.py", line 258, in getoutput
    shell=False)
  File "C:\PyPy3-2.4.0-win32\lib-python\3\subprocess.py", line 763, in __init__
    os.close(fd)
TypeError: __int__ returned non-int (type 'NoneType')
----------------------------------------------------------------------
```

**Comment by peterjc** [comment]
I'm going to close this as it seems to have been fixed in a more recent version of PyPy3
