### ISSUE TITLE
Non-zero return code -11 from 'phyml -i Phylip/interlaced2.phy -d aa'

### ISSUE THREAD

**Issue by peterjc** [biopython/biopython#921]
I recently installed a version of phyml on the 64 bit Linux buildbot buildslave, and now ``test_phyml_tool.py`` is failing with:

```
======================================================================
ERROR: test_phyml (test_phyml_tool.AppTests)
Run PhyML using the wrapper.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home_local/buildslave/BuildBot_Biopython/lin3364/build/Tests/test_phyml_tool.py", line 51, in test_phyml
    out, err = cmd()
  File "/home_local/buildslave/BuildBot_Biopython/lin3364/build/build/lib.linux-x86_64-3.3/Bio/Application/__init__.py", line 516, in __call__
    stdout_str, stderr_str)
Bio.Application.ApplicationError: Non-zero return code -11 from 'phyml -i Phylip/interlaced2.phy -d aa'

----------------------------------------------------------------------
```

It looks like the phyml API could have changed...

P.S. See also #919 and discussion about where to find the latest version, i.e. https://github.com/stephaneguindon/phyml

**Comment by peterjc** [comment]
I installed PhyML on the 64 bit Linux buildslave which now fails, e.g. http://testing.open-bio.org/biopython/builders/Linux%2064%20-%20Python%203.5/builds/190/steps/shell/logs/stdio

```
======================================================================
ERROR: test_phyml (test_phyml_tool.AppTests)
Run PhyML using the wrapper.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home_local/buildslave/BuildBot_Biopython/lin3564/build/Tests/test_phyml_tool.py", line 51, in test_phyml
    out, err = cmd()
  File "/home_local/buildslave/BuildBot_Biopython/lin3564/build/build/lib.linux-x86_64-3.5/Bio/Application/__init__.py", line 516, in __call__
    stdout_str, stderr_str)
Bio.Application.ApplicationError: Non-zero return code -11 from 'phyml -i Phylip/interlaced2.phy -d aa'

----------------------------------------------------------------------
```

This is running PhyML 3.3.20160826

```
$ phyml --version


. Command line: phyml --version 

. This is PhyML version 3.3.20160826.

```

Running the command directly,

```
$ cd ~/repositories/biopython/Tests
$ $ phyml -i Phylip/interlaced2.phy -d aa


. Command line: phyml -i Phylip/interlaced2.phy -d aa 





                                 ..........................                                      
 ooooooooooooooooooooooooooooo        CURRENT SETTINGS        ooooooooooooooooooooooooooooooooooo
                                 ..........................                                      

                . Sequence filename:				 interlaced2.phy
                . Data type:					 aa
                . Alphabet size:				 20
                . Sequence format:				 interleaved
                . Number of data sets:				 1
                . Nb of bootstrapped data sets:			 0
                . Compute approximate likelihood ratio test:	 yes (aBayes branch supports)
                . Model name:					 LG
                . Proportion of invariable sites:		 0.000000
                . Number of subst. rate categs:			 4
                . Gamma distribution parameter:			 estimated
                . 'Middle' of each rate class:			 mean
                . Amino acid equilibrium frequencies:		 model
                . Optimise tree topology:			 yes
                . Tree topology search:				 NNIs
                . Starting tree:				 BioNJ
                . Add random input tree:			 no
                . Optimise branch lengths:			 yes
                . Optimise substitution model parameters:	 yes
                . Run ID:					 none
                . Random seed:					 1472460274
                . Subtree patterns aliasing:			 no
                . Version:					 3.3.20160826
                . Byte alignment:				 16
                . AVX enabled:					 no
                . SSE3 enabled:					 yes

 oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo



. 40 patterns found (out of a total of 131 sites). 

. 120 sites without polymorphism (91.60%).

. Computing pairwise distances...

. Building BioNJ tree...
. First round of optimization...

. Building a list of starting trees...
. Best tree found so far has lnL:      -476.67 (9 more trees to examine)
. Best tree found so far has lnL:      -476.67 (7 more trees to examine)
. Best tree found so far has lnL:      -476.67 (3 more trees to examine)

. Finished building the list of trees. Their scores are given below...
. Tree   1, lnL:         0.00
. Tree   2, lnL:         0.00
. Tree   3, lnL:         0.00
. Tree   4, lnL:         0.00
. Tree   5, lnL:         0.00
. Tree   6, lnL:         0.00Segmentation fault (core dumped)
```

**Comment by peterjc** [comment]
Running the same command on my Mac works (as does the test suite),

```
$ $ phyml -i Phylip/interlaced2.phy -d aa






                                 ..........................                                      
 ooooooooooooooooooooooooooooo        CURRENT SETTINGS        ooooooooooooooooooooooooooooooooooo
                                 ..........................                                      

                . Sequence filename : 				 interlaced2.phy
                . Data type :             			 aa
                . Sequence format : 				 interleaved
                . Number of data sets : 			 1
                . Nb of bootstrapped data sets : 		 0
                . Compute approximate likelihood ratio test : 	 yes (SH-like branch supports)
                . Model name : 					 LG
                . Proportion of invariable sites :		 0.000000
                . Number of subst. rate categs : 		 4
                . Gamma distribution parameter : 		 estimated
                . 'Middle' of each rate class  : 		 mean
                . Amino acid equilibrium frequencies : 		 model
                . Optimise tree topology : 			 yes
                . Tree topology search : 			 NNIs
                . Starting tree : 				 BioNJ
                . Add random input tree : 			 no
                . Optimise branch lengths : 			 yes
                . Optimise substitution model parameters : 	 yes
                . Run ID : 					 none

 oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo



. Compressing sequences...

. 40 patterns found. (out of a total of 131 sites) 

. 120 sites without polymorphism (91.60%).

. Computing pairwise distances...

. Building BioNJ tree...

. This analysis requires at least 0 Mo of memory space.

. Maximizing likelihood (using NNI moves)...

. (    0 sec) [      -478.8522] [Alpha              ][  0.500960]
. (    0 sec) [      -478.8522] [Topology           ]
. (    0 sec) [      -477.8997] [Topology           ]
. (    0 sec) [      -477.6771] [Topology           ]
. (    0 sec) [      -477.6222] [Topology           ]
. (    0 sec) [      -477.6086] [Topology           ]
. (    0 sec) [      -477.6052] [Topology           ]
. (    0 sec) [      -477.6044] [Topology           ]

. Checking for NNIs, optimizing five branches...

. (    0 sec) [      -477.2033] [Alpha              ][  0.250961]
. (    0 sec) [      -477.2033] [Topology           ]
. (    0 sec) [      -477.1823] [Topology           ]
. (    0 sec) [      -477.1804] [Topology           ]
. (    0 sec) [      -477.1802] [Topology           ]

. Checking for NNIs, optimizing five branches...

. (    0 sec) [      -476.8559] [Alpha              ][  0.125721]
. (    0 sec) [      -476.8559] [Topology           ]
. (    0 sec) [      -476.8343] [Topology           ]
. (    0 sec) [      -476.8321] [Topology           ]
. (    0 sec) [      -476.8318] [Topology           ]

. Checking for NNIs, optimizing five branches...

. (    0 sec) [      -476.6909] [Alpha              ][  0.062981]
. (    0 sec) [      -476.6909] [Topology           ]
. (    0 sec) [      -476.6852] [Topology           ]
. (    0 sec) [      -476.6846] [Topology           ]

. Checking for NNIs, optimizing five branches...

. (    0 sec) [      -476.6680] [Alpha              ][  0.031533]
. (    0 sec) [      -476.6680] [Topology           ]
. (    0 sec) [      -476.6676] [Topology           ]

. Checking for NNIs, optimizing five branches...

. (    0 sec) [      -476.6675] [Alpha              ][  0.015785]
. (    0 sec) [      -476.6675] [Topology           ]
. (    0 sec) [      -476.6674] [Topology           ]

. Checking for NNIs, optimizing five branches...


. Checking for NNIs, optimizing five branches...


. Log likelihood of the current tree: -476.667419.

. Compute aLRT branch supports on the most likely tree...

. Printing the most likely tree in file 'interlaced2.phy_phyml_tree.txt'...


. Time used 0h0m1s

oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo
```

This is slightly older (and doesn't have a concise ``--version`` option):

```
$ phyml --version

NAME
	- PhyML v3.0_360-500M - 

	''A simple, fast, and accurate algorithm to estimate
	large phylogenies by maximum likelihood''

	Stephane Guindon and Olivier Gascuel,
	Systematic Biology 52(5):696-704, 2003.

	Please cite this paper if you use this software in your publications.

SYNOPSIS:

...
```

**Comment by peterjc** [comment]
Updated to latest commit https://github.com/stephaneguindon/phyml/commit/212563afbe8aa55ff887270749a317c65bdc7131 and tested on CentOS 6, reported upstream as https://github.com/stephaneguindon/phyml/issues/38

**Comment by peterjc** [comment]
Fixed as of this fix, https://github.com/stephaneguindon/phyml/commit/03a2597eeeaf4877cb25cf76f2fc814c2ba8e2c7?w=1 aka PhyML 3.3.20160826

Hopefully there will be another official release of PhyML before too long.
